-- KGM 2026 seed part 2/4 v2 (idempotent, tip cast'li)
insert into bf_poz (source_id,poz_no,tanim,birim,fiyat,fiyat_formul,extra)
select '00a62b45-1fdb-4bd8-8325-160287c204f0'::uuid, v.poz_no, v.tanim, v.birim, v.fiyat::numeric, v.fiyat_formul, v.extra::jsonb
from (values
('KGM/3781/10-M','3N Otokorkuluk genleşme eki montajı (80-160 mm)','adet',347.43,null,null),
('KGM/3781/10-S','3N Otokorkuluk genleşme eki sökülmesi (80-1600 mm)','adet',347.43,null,null),
('KGM/3781/11','3N Otokorkuluk geçiş elemanı yapılması (Malzeme bedeli dahil)','adet',2244.66,null,null),
('KGM/3781/11-M','3N Otokorkuluk geçiş elemanı montajı','adet',496.33,null,null),
('KGM/3781/11-S','3N Otokorkuluk geçiş elemanı sökülmesi','adet',496.33,null,null),
('KGM/3781/12','3N Otokorkuluk U kirişi indirme elemanı yapılması (U 130 profilden) (Malzeme bedeli dahil)','adet',786.73,null,null),
('KGM/3781/12-M','3N Otokorkuluk U kirişi indirme elemanı montajı','adet',297.79,null,null),
('KGM/3781/12-S','3N Otokorkuluk U kirişi indirme elemanı sökülmesi','adet',297.79,null,null),
('KGM/3783','Profilli demirden kazık ve keson hazırlanması (Malzeme bedeli dahil) (Boyama hariç)','ton',99440.3,null,null),
('KGM/3792','Yüksek dayanımlı öngerme çeliği temini','ton',40812.5,null,null),
('KGM/3792/1','Yüksek dayanımlı öngerme çeliği temini (0,5 inç halat) ( Tip 270 K)','ton',46125.0,null,null),
('KGM/3792/2','Yüksek dayanımlı öngerme çeliği temini (0,6 inç halat) ( Tip 270 K)','ton',46125.0,null,null),
('KGM/3793','Kılıf borusu temini','m',42.5,null,null),
('KGM/3794','Ankraj konu temini','adet',212.5,null,null),
('KGM/3800','Pirinç boru','kg',453.75,null,null),
('KGM/3805','Neopren (Lastik) mesnet tertibatı (İçi çelik fretli)',null,513.75,null,null),
('KGM/3820','3 cm. kalınlıkta muhafaza betonu yapılması','m2',263.98,null,null),
('KGM/3821','4 cm. kalınlıkta muhafaza betonu yapılması','m2',278.83,null,null),
('KGM/3822','5 cm. kalınlıkta muhafaza betonu yapılması','m2',293.66,null,null),
('KGM/3950','1000 kg'' dan 3000 kg'' a kadar tahkimat beton bloklarının yerine yerleştirilmesi','m3',105.45,null,null),
('KGM/3955','3000 kg'' dan 6000 kg'' a kadar tahkimat beton bloklarının yerine yerleştirilmesi','m3',126.54,null,null),
('KGM/3960','6000 kg'' dan 12000 kg'' a kadar tahkimat beton bloklarının yerine yerleştirilmesi','m3',185.59,null,null),
('KGM/3965','Tahkimat için her boyutta beton blok yapılması','m3',2261.33,null,null),
('KGM/3980','Sınır taşı hazırlanması ve yerine konulması','adet',353.98,null,null),
('KGM/3985/2A','CTP Yol kenar dikmesinin temini ve yol boyuna dikilmesi','adet',148.33,null,null),
('KGM/4030','Bitümlü temel ve satıh tabakalarında kalıp','m',14.45,null,null),
('KGM/4100','Ocak taşından konkasörle kırılmış ve elenmiş 50 mm. (2") lik agrega hazırlanması','m3',518.36,null,null),
('KGM/4100','Ocak taşından konkasörle kırılmış ve elenmiş 50 mm. (2") lik agrega hazırlanması','ton',323.98,null,null),
('KGM/4100-K','Kazı taşından konkasörle kırılmış ve elenmiş 50 mm. (2") lik agrega hazırlanması','m3',272.21,null,null),
('KGM/4100-K','Kazı taşından konkasörle kırılmış ve elenmiş 50 mm. (2") lik agrega hazırlanması','ton',170.13,null,null),
('KGM/4100-E1','Elenmemiş çakıllı malzemeden konkasörle kırılmış ve elenmiş 50 mm. (2") lik agrega hazırlanması','m3',232.33,null,null),
('KGM/4100-E1','Elenmemiş çakıllı malzemeden konkasörle kırılmış ve elenmiş 50 mm. (2") lik agrega hazırlanması','ton',145.21,null,null),
('KGM/4100-E2','Elenmiş çakıllı malzemeden konkasörle kırılmış ve elenmiş 50 mm. (2") lik agrega hazırlanması','m3',284.01,null,null),
('KGM/4100-E2','Elenmiş çakıllı malzemeden konkasörle kırılmış ve elenmiş 50 mm. (2") lik agrega hazırlanması','ton',177.51,null,null),
('KGM/4101','Ocak taşından konkasörle kırılmış ve elenmiş 37,5 mm. (1 1/2") lik agrega hazırlanması','m3',560.49,null,null),
('KGM/4101','Ocak taşından konkasörle kırılmış ve elenmiş 37,5 mm. (1 1/2") lik agrega hazırlanması','ton',350.31,null,null),
('KGM/4101-S','Sert taştan konkasörle kırılmış ve elenmiş 37,5 mm. (1 1/2") lik agrega hazırlanması','m3',644.74,null,null),
('KGM/4101-S','Sert taştan konkasörle kırılmış ve elenmiş 37,5 mm. (1 1/2") lik agrega hazırlanması','ton',402.96,null,null),
('KGM/4101-K','Kazı taşından konkasörle kırılmış ve elenmiş 37,5 mm. (1 1/2") lik agrega hazırlanması','m3',314.34,null,null),
('KGM/4101-K','Kazı taşından konkasörle kırılmış ve elenmiş 37,5 mm. (1 1/2") lik agrega hazırlanması','ton',196.46,null,null),
('KGM/4101-E1','Elenmemiş çakıllı malzemeden konkasörle kırılmış ve elenmiş 37,5 mm. (1 1/2") lik agrega hazırlanması','m3',274.45,null,null),
('KGM/4101-E1','Elenmemiş çakıllı malzemeden konkasörle kırılmış ve elenmiş 37,5 mm. (1 1/2") lik agrega hazırlanması','ton',171.53,null,null),
('KGM/4101-E2','Elenmiş çakıldan konkasörle kırılmış ve elenmiş 37,5 mm. (1 1/2") lik agrega hazırlanması','m3',326.14,null,null),
('KGM/4101-E2','Elenmiş çakıldan konkasörle kırılmış ve elenmiş 37,5 mm. (1 1/2") lik agrega hazırlanması','ton',203.84,null,null),
('KGM/4102','Ocak taşından konkasörle kırılmış ve elenmiş 25 mm. (1") ve 19 mm. (3/4") lik agrega hazırlanması','m3',624.56,null,null),
('KGM/4102','Ocak taşından konkasörle kırılmış ve elenmiş 25 mm. (1") ve 19 mm. (3/4") lik agrega hazırlanması','ton',390.35,null,null),
('KGM/4102-S','Sert taştan konkasörle kırılmış ve elenmiş 25 mm. (1") ve 19 mm. (3/4") lik agrega hazırlanması','m3',729.89,null,null),
('KGM/4102-S','Sert taştan konkasörle kırılmış ve elenmiş 25 mm. (1") ve 19 mm. (3/4") lik agrega hazırlanması','ton',456.18,null,null),
('KGM/4102-K','Kazı taşından konkasörle kırılmış ve elenmiş 25 mm. (1") ve 19 mm. (3/4") lik agrega hazırlanması','m3',378.41,null,null),
('KGM/4102-K','Kazı taşından konkasörle kırılmış ve elenmiş 25 mm. (1") ve 19 mm. (3/4") lik agrega hazırlanması','ton',236.51,null,null),
('KGM/4102-T','Toplama taştan konkasörle kırılmış ve elenmiş 25 mm. (1") ve 19 mm. (3/4") lik agrega hazırlanması','m3',1099.69,null,null),
('KGM/4102-T','Toplama taştan konkasörle kırılmış ve elenmiş 25 mm. (1") ve 19 mm. (3/4") lik agrega hazırlanması','ton',687.31,null,null),
('KGM/4102-E1','Elenmemiş çakıllı malzemeden konkasörle kırılmış ve elenmiş 25 mm. (1") ve19 mm. (3/4") lik agrega hazırlanması','m3',338.53,null,null),
('KGM/4102-E1','Elenmemiş çakıllı malzemeden konkasörle kırılmış ve elenmiş 25 mm. (1") ve19 mm. (3/4") lik agrega hazırlanması','ton',211.58,null,null),
('KGM/4102-E2','Elenmiş çakıldan konkasörle kırılmış ve elenmiş 25 mm. (1") ve19 mm. (3/4") lik agrega hazırlanması','m3',390.21,null,null),
('KGM/4102-E2','Elenmiş çakıldan konkasörle kırılmış ve elenmiş 25 mm. (1") ve19 mm. (3/4") lik agrega hazırlanması','ton',243.88,null,null),
('KGM/4103','Ocak taşından konkasörle kırılmış ve elenmiş 25 mm. (1"), 19 mm. (3/4") ve 12,5 mm. (1/2") lik agrega hazırlanması','m3',656.46,null,null),
('KGM/4103','Ocak taşından konkasörle kırılmış ve elenmiş 25 mm. (1"), 19 mm. (3/4") ve 12,5 mm. (1/2") lik agrega hazırlanması','ton',410.29,null,null),
('KGM/4103-S','Sert taştan konkasörle kırılmış ve elenmiş 25 mm. (1"), 19 mm. (3/4") ve 12,5 mm. (1/2") lik agrega hazırlanması','m3',777.58,null,null),
('KGM/4103-S','Sert taştan konkasörle kırılmış ve elenmiş 25 mm. (1"), 19 mm. (3/4") ve 12,5 mm. (1/2") lik agrega hazırlanması','ton',485.99,null,null),
('KGM/4103-K','Kazı taşından konkasörle kırılmış ve elenmiş 25 mm. (1"), 19 mm. (3/4") ve 12,5 mm. (1/2") lik agrega hazırlanması','m3',410.31,null,null),
('KGM/4103-K','Kazı taşından konkasörle kırılmış ve elenmiş 25 mm. (1"), 19 mm. (3/4") ve 12,5 mm. (1/2") lik agrega hazırlanması','ton',256.44,null,null),
('KGM/4103-T','Toplama taştan konkasörle kırılmış ve elenmiş 25 mm. (1"), 19 mm. (3/4") ve 12,5 mm. (1/2") lik agrega hazırlanması','m3',1131.59,null,null),
('KGM/4103-T','Toplama taştan konkasörle kırılmış ve elenmiş 25 mm. (1"), 19 mm. (3/4") ve 12,5 mm. (1/2") lik agrega hazırlanması','ton',707.24,null,null),
('KGM/4103-E1','Elenmemiş çakıllı malzemeden konkasörle kırılmış ve elenmiş 25 mm. (1"), 19 mm. (3/4") ve 12,5 mm. (1/2") lik agrega hazırlanması','m3',370.43,null,null),
('KGM/4103-E1','Elenmemiş çakıllı malzemeden konkasörle kırılmış ve elenmiş 25 mm. (1"), 19 mm. (3/4") ve 12,5 mm. (1/2") lik agrega hazırlanması','ton',231.52,null,null),
('KGM/4103-E2','Elenmiş çakıldan konkasörle kırılmış ve elenmiş 25 mm. (1"), 19 mm. (3/4") ve 12,5 mm. (1/2") lik agrega hazırlanması','m3',422.11,null,null),
('KGM/4103-E2','Elenmiş çakıldan konkasörle kırılmış ve elenmiş 25 mm. (1"), 19 mm. (3/4") ve 12,5 mm. (1/2") lik agrega hazırlanması','ton',263.82,null,null),
('KGM/4104','Ocak taşından konkasörle kırılmış ve elenmiş 19 mm. (3/4") ve 12,5 mm. (1/2") lik agrega hazırlanması','m3',682.79,null,null),
('KGM/4104','Ocak taşından konkasörle kırılmış ve elenmiş 19 mm. (3/4") ve 12,5 mm. (1/2") lik agrega hazırlanması','ton',426.74,null,null),
('KGM/4104-S','Sert taştan konkasörle kırılmış ve elenmiş 19 mm. (3/4") ve 12,5 mm. (1/2") lik agrega hazırlanması','m3',814.44,null,null),
('KGM/4104-S','Sert taştan konkasörle kırılmış ve elenmiş 19 mm. (3/4") ve 12,5 mm. (1/2") lik agrega hazırlanması','ton',509.03,null,null),
('KGM/4104-K','Kazı taşından konkasörle kırılmış ve elenmiş 19 mm. (3/4") ve 12,5 mm. (1/2") lik agrega hazırlanması','m3',436.64,null,null),
('KGM/4104-K','Kazı taşından konkasörle kırılmış ve elenmiş 19 mm. (3/4") ve 12,5 mm. (1/2") lik agrega hazırlanması','ton',272.9,null,null),
('KGM/4104-T','Toplama taştan konkasörle kırılmış ve elenmiş 19 mm. (3/4") ve 12,5 mm. (1/2") lik agrega hazırlanması','m3',1157.91,null,null),
('KGM/4104-T','Toplama taştan konkasörle kırılmış ve elenmiş 19 mm. (3/4") ve 12,5 mm. (1/2") lik agrega hazırlanması','ton',723.69,null,null),
('KGM/4104-E1','Elenmemiş çakıllı malzemeden konkasörle kırılmış ve elenmiş 19 mm. (3/4") ve12,5 mm. (1/2") lik agrega hazırlanması','m3',396.75,null,null),
('KGM/4104-E1','Elenmemiş çakıllı malzemeden konkasörle kırılmış ve elenmiş 19 mm. (3/4") ve12,5 mm. (1/2") lik agrega hazırlanması','ton',247.97,null,null),
('KGM/4104-E2','Elenmiş çakıldan konkasörle kırılmış ve elenmiş 19 mm. (3/4") ve12,5 mm. (1/2") lik agrega hazırlanması','m3',448.44,null,null),
('KGM/4104-E2','Elenmiş çakıldan konkasörle kırılmış ve elenmiş 19 mm. (3/4") ve12,5 mm. (1/2") lik agrega hazırlanması','ton',280.28,null,null),
('KGM/4105','Ocak taşından konkasörle kırılmış ve elenmiş 12,5 mm. (1/2") ve 9,5 mm. (3/8") lik agrega hazırlanması','m3',709.11,null,null),
('KGM/4105','Ocak taşından konkasörle kırılmış ve elenmiş 12,5 mm. (1/2") ve 9,5 mm. (3/8") lik agrega hazırlanması','ton',443.19,null,null),
('KGM/4105-S','Sert taştan konkasörle kırılmış ve elenmiş 12,5 mm. (1/2") ve 9,5 mm. (3/8") lik agrega hazırlanması','m3',856.56,null,null),
('KGM/4105-S','Sert taştan konkasörle kırılmış ve elenmiş 12,5 mm. (1/2") ve 9,5 mm. (3/8") lik agrega hazırlanması','ton',535.35,null,null),
('KGM/4105-K','Kazı taşından konkasörle kırılmış ve elenmiş 12,5 mm. (1/2") ve 9,5 mm. (3/8") lik agrega hazırlanması','m3',462.96,null,null),
('KGM/4105-K','Kazı taşından konkasörle kırılmış ve elenmiş 12,5 mm. (1/2") ve 9,5 mm. (3/8") lik agrega hazırlanması','ton',289.35,null,null),
('KGM/4105-T','Toplama taştan konkasörle kırılmış ve elenmiş 12,5 mm. (1/2") ve 9,5 mm. (3/8") lik agrega hazırlanması','m3',1184.24,null,null),
('KGM/4105-T','Toplama taştan konkasörle kırılmış ve elenmiş 12,5 mm. (1/2") ve 9,5 mm. (3/8") lik agrega hazırlanması','ton',740.15,null,null),
('KGM/4105-E1','Elenmemiş çakıllı malzemeden konkasörle kırılmış ve elenmiş 12,5 mm. (1/2") ve 9,5 mm. (3/8") lik agrega hazırlanması','m3',423.08,null,null),
('KGM/4105-E1','Elenmemiş çakıllı malzemeden konkasörle kırılmış ve elenmiş 12,5 mm. (1/2") ve 9,5 mm. (3/8") lik agrega hazırlanması','ton',264.43,null,null),
('KGM/4105-E2','Elenmiş çakıldan konkasörle kırılmış ve elenmiş 12,5 mm. (1/2") ve 9,5 mm. (3/8") lik agrega hazırlanması','m3',474.76,null,null),
('KGM/4105-E2','Elenmiş çakıldan konkasörle kırılmış ve elenmiş 12,5 mm. (1/2") ve 9,5 mm. (3/8") lik agrega hazırlanması','ton',296.73,null,null),
('KGM/4106','Ocak taşından konkasörle kırılmış ve elenmiş 9,5 mm. (3/8") lik agrega hazırlanması','m3',724.91,null,null),
('KGM/4106','Ocak taşından konkasörle kırılmış ve elenmiş 9,5 mm. (3/8") lik agrega hazırlanması','ton',453.07,null,null),
('KGM/4106-S','Sert taştan konkasörle kırılmış ve elenmiş 9,5 mm. (3/8") lik agrega hazırlanması','m3',882.88,null,null),
('KGM/4106-S','Sert taştan konkasörle kırılmış ve elenmiş 9,5 mm. (3/8") lik agrega hazırlanması','ton',551.8,null,null),
('KGM/4106-K','Kazı taşından konkasörle kırılmış ve elenmiş 9,5 mm. (3/8") lik agrega hazırlanması','m3',478.76,null,null),
('KGM/4106-K','Kazı taşından konkasörle kırılmış ve elenmiş 9,5 mm. (3/8") lik agrega hazırlanması','ton',299.23,null,null),
('KGM/4106-T','Toplama taştan konkasörle kırılmış ve elenmiş 9,5 mm. (3/8") lik agrega hazırlanması','m3',1200.04,null,null),
('KGM/4106-T','Toplama taştan konkasörle kırılmış ve elenmiş 9,5 mm. (3/8") lik agrega hazırlanması','ton',750.03,null,null),
('KGM/4106-E1','Elenmemiş çakıllı malzemeden konkasörle kırılmış ve elenmiş 9,5 mm. (3/8") lik agrega hazırlanması','m3',438.88,null,null),
('KGM/4106-E1','Elenmemiş çakıllı malzemeden konkasörle kırılmış ve elenmiş 9,5 mm. (3/8") lik agrega hazırlanması','ton',274.3,null,null),
('KGM/4106-E2','Elenmiş çakıldan konkasörle kırılmış ve elenmiş 9,5 mm. (3/8") lik agrega hazırlanması','m3',490.56,null,null),
('KGM/4106-E2','Elenmiş çakıldan konkasörle kırılmış ve elenmiş 9,5 mm. (3/8") lik agrega hazırlanması','ton',306.6,null,null),
('KGM/4107','Ocak taşından konkasörle kırılmış ve elenmiş 4,75 mm. (No.4) ve daha küçük agrega hazırlanması','m3',751.24,null,null),
('KGM/4107','Ocak taşından konkasörle kırılmış ve elenmiş 4,75 mm. (No.4) ve daha küçük agrega hazırlanması','ton',469.53,null,null),
('KGM/4107-S','Sert taştan konkasörle kırılmış ve elenmiş 4,75 mm. (No.4) ve daha küçük agrega hazırlanması','m3',925.0,null,null),
('KGM/4107-S','Sert taştan konkasörle kırılmış ve elenmiş 4,75 mm. (No.4) ve daha küçük agrega hazırlanması','ton',578.13,null,null),
('KGM/4107-K','Kazı taşından konkasörle kırılmış ve elenmiş 4,75 mm. (No.4) ve daha küçük agrega hazırlanması','m3',505.09,null,null),
('KGM/4107-K','Kazı taşından konkasörle kırılmış ve elenmiş 4,75 mm. (No.4) ve daha küçük agrega hazırlanması','ton',315.68,null,null),
('KGM/4107-T','Toplama taştan konkasörle kırılmış ve elenmiş 4,75 mm. (No.4) ve daha küçük agrega hazırlanması','m3',1226.36,null,null),
('KGM/4107-T','Toplama taştan konkasörle kırılmış ve elenmiş 4,75 mm. (No.4) ve daha küçük agrega hazırlanması','ton',766.48,null,null),
('KGM/4107-E1','Elenmemiş çakıllı malzemeden konkasörle kırılmış ve elenmiş 4,75 mm. (No.4) ve daha küçük agrega hazırlanması','m3',465.2,null,null),
('KGM/4107-E1','Elenmemiş çakıllı malzemeden konkasörle kırılmış ve elenmiş 4,75 mm. (No.4) ve daha küçük agrega hazırlanması','ton',290.75,null,null),
('KGM/4107-E2','Elenmiş çakıldan konkasörle kırılmış ve elenmiş 4,75 mm. (No.4) ve daha küçük agrega hazırlanması','m3',516.89,null,null),
('KGM/4107-E2','Elenmiş çakıldan konkasörle kırılmış ve elenmiş 4,75 mm. (No.4) ve daha küçük agrega hazırlanması','ton',323.06,null,null),
('KGM/4269','Malzemenin kantar ile tartılması','ton',0.8,null,null),
('KGM/4270','Mineral filler hazırlanması','ton',442.5,null,null),
('KGM/4300/PMB','Özel plentte polimer modifiye bitüm (PMB) hazırlanması','ton',1963.05,null,null),
('KGM/4355','Yarı katı bitümlü malzemenin sarnıç veya tanklarda emiş derecesine kadar ısıtılması (Makine İle)','ton',502.49,null,null),
('KGM/4358','Katı bitümlü malzemenin sarnıç veya tanklarda emiş derecesine kadar ısıtılması (Makine ile)','ton',738.44,null,null),
('KGM/4358/1','Katı bitümlü malzemenin sarnıç veya tanklarda emiş derecesinden tatbik derecesine kadar ısıtılması (Makine İle)',null,null,null,null),
('KGM/4364','Varil veya bidonla taşınan bitümlü malzemenin tankdan geçirilmesi','ton',36.81,null,null),
('KGM/4365','Sarnıçlı vagon, tanker, kamyon ve roley tank gibi kaplarla taşınan bitümlü malzemenin depolanması','ton',55.23,null,null),
('KGM/4366','Bitümlü malzemenin asfalt pompası ile bir kaptan diğer bir kaba aktarılması','ton',30.6,null,null),
('KGM/4367','Yumuşatıcı (Gaz, benzin, motorin vs.) petrol ürünlerinin pompa veya el ile bir kaptan diğer bir kaba aktarılması','ton',30.6,null,null),
('KGM/4368','Yumuşatıcı (Gaz, benzin, motorin vs.) petrol ürünlerinin depolanması','ton',312.5,null,null),
('KGM/4371','Evvelce hazırlanmış stabilize bir yolun ince reglajı',null,4141.94,null,null),
('KGM/4375','Beton ve her nevi asfalt yollar dışındaki yolların el ile süpürülmesi',null,25000.0,null,null),
('KGM/4376','Beton ve her nevi asfalt yolların el ile süpürülmesi',null,12500.0,null,null),
('KGM/4377','Beton ve her nevi asfsalt yollar dışındaki yolların makine ile süpürülmesi',null,864.93,null,null),
('KGM/4378','Beton ve her nevi asfsalt yolların makine ile süpürülmesi',null,438.23,null,null),
('KGM/4380','Bitümlü kaplama ve karışımlar için mevcut agreganın elenmesi','m3',58.09,null,null),
('KGM/4381','Mevcut asfalt mıcırının tozunun giderilmesi','m3',94.05,null,null),
('KGM/4382','Bitümlü kaplama ve karışımlar için mevcut agreganın yıkama makinesi ile yıkanması','m3',124.54,null,null),
('KGM/4383','Bitümlü kaplama ve karışım agregasının Poz KGM/4380''e göre elenirken eleğe su verilerek yıkanması','m3',16.66,null,null),
('KGM/4393','Distribütör makinesi ile astar bitümlü malzemesinin püskürtülmesi (Boru İle)',null,1236.33,null,null),
('KGM/4394','Distribütör makinesi ile astar bitümlü malzemesinin püskürtülmesi (El ile) Not:Bu Poz İdarenin izni olmadan kullanılmaz.',null,2985.15,null,null),
('KGM/4398','Distribütör makinesi ile yapıştırıcı bitümlü malzemesinin püskürtülmesi (Boru ile)',null,874.48,null,null),
('KGM/4399','Distribütör makinesi ile yapıştırıcı bitümlü malzemesinin püskürtülmesi (El ile) Not:Bu Poz İdarenin izni olmadan kullanılmaz.',null,2121.91,null,null),
('KGM/4402','Distribütör makinesi ve 25 mm. (1") lik agrega (Mıcır) ile bir tabaka bitümlü sathi kaplama yapılması',null,6771.75,null,null),
('KGM/4407','Distribütör makinesi ve 19 mm. (3/4") lik agrega (Mıcır) ile bir tabaka bitümlü sathi kaplama yapılması',null,5543.73,null,null),
('KGM/4412','Distribütör makinesi ve 12.5 mm. (1/2") lik agrega (Mıcır) ile bir tabaka bitümlü sathi kaplama yapılması',null,4148.13,null,null),
('KGM/4417','Distribütör makinesi ve 9,5 mm. (3/8") lik agrega (Mıcır) ile bir tabaka bitümlü sathi kaplama veya silkot yapılması',null,2721.78,null,null),
('KGM/4422','Distribütör makinesi ile penetrasyon makadam satıh tabakası yapılması',null,45464.33,null,null),
('KGM/4427','Küçük plent ünitesi ile "Asfalt betonu kaplama", "Rolled asfalt kaplama", "Bitümlü makadam satıh tabakası", "Karışımı plent-miks metoduyla hazırlanan bitümlü kaplamalar (TİP A, B, C satıh tabakası)", "Rolled asfalt temel tabakası"; "Bitümlü makadam temel tabakası", "Sıcak bitümlü temel", "Karışımı plent-miks metoduyla hazırlanan bitümlü düzeltme tabakası", "Bitüm İle stabilize edilmiş temel ve alttemel" karışımlarının hazırlanması Not:Bu Poz, her bir yıllık süre için 60000 ton''dan büyük çıkacak işlerde kullanılmamalıdır.','ton',642.31,null,null),
('KGM/4428','Küçük plent ünitesi ile hazırlanmış "Asfalt betonu kaplama", "Rolled asfalt kaplama", "Bitümlü makadam satıh tabakası", "Karışımı plent-miks metoduyla hazırlanan bitümlü kaplamalar (TİP A, B, C satıh tabakası)", "Rolled asfalt temel tabakası"; "Bitümlü makadam temel tabakası", "Sıcak bitümlü temel", "Karışımı plent-miks metoduyla hazırlanan bitümlü düzeltme tabakası", "Bitüm İle stabilize edilmiş temel ve alttemel" karışımlarının küçük finişerle serilmesi ve silindirle sıkıştırılması Not:Poz KGM/4427 deki Not gibidir.','ton',390.63,null,null),
('KGM/4429','Küçük plent ünitesi ile hazırlanmış "Asfalt betonu kaplama", "Rolled asfalt kaplama", "Bitümlü makadam satıh tabakası", "Karışımı plent-miks metoduyla hazırlanan bitümlü kaplamalar (TİP A, B, C satıh tabakası)", "Rolled asfalt temel tabakası"; "Bitümlü makadam temel tabakası", "Sıcak bitümlü temel", "Karışımı plent-miks metoduyla hazırlanan bitümlü düzeltme tabakası", "Bitüm İle stabilize edilmiş temel ve alttemel" karışımlarının elektronik duyargalı finişer ile serilmesi ve silindirle sıkıştırılması Not:Poz KGM/4427 deki Not gibidir.','ton',370.4,null,null),
('KGM/4430','Plent ünitesi ile hazırlanmış "Asfalt betonu kaplama", "Rolled asfalt kaplama", "Bitümlü makadam satıh tabakası", "Karışımı plent-miks metoduyla hazırlanan bitümlü kaplamalar (TİP A, B, C satıh tabakası)", "Rolled asfalt temel tabakası"; "Bitümlü makadam temel tabakası", "Sıcak bitümlü temel", "Karışımı plent-miks metoduyla hazırlanan bitümlü düzeltme tabakası", "Bitüm İle stabilize edilmiş temel ve alttemel" karışımlarının greyderle serilmesi ve silindirle sıkıştırılması Not:Bu Poz, sermenin greyderle yapılmasının gerektiği yerler için uygulanır.','ton',380.71,null,null),
('KGM/4431','Plent ünitesi ile hazırlanmış "Asfalt betonu kaplama", "Rolled asfalt kaplama", "Bitümlü makadam satıh tabakası", "Karışımı plent-miks metoduyla hazırlanan bitümlü kaplamalar (TİP A, B, C satıh tabakası)", "Rolled asfalt temel tabakası"; "Bitümlü makadam temel tabakası", "Sıcak bitümlü temel", "Karışımı plent-miks metoduyla hazırlanan bitümlü düzeltme tabakası", "Bitüm İle stabilize edilmiş temel ve alttemel" karışımlarının el ile serilmesi ve silindirle sıkıştırılması Not:Bu Poz, sermenin el ile yapılmasının gerektiği yerler için uygulanır.','ton',1342.63,null,null),
('KGM/4432','Küçük plent ünitesi ile hazırlanmış "Asfalt betonu kaplama", "Rolled asfalt kaplama", "Bitümlü makadam satıh tabakası", "Karışımı plent-miks metoduyla hazırlanan bitümlü kaplamalar (TİP A, B, C satıh tabakası)", "Rolled asfalt temel tabakası"; "Bitümlü makadam temel tabakası", "Sıcak bitümlü temel", "Karışımı plent-miks metoduyla hazırlanan bitümlü düzeltme tabakası", "Bitüm İle stabilize edilmiş temel ve alttemel" karışımlarının hazırlanması, serilmesi ve sıkıştırılması (Serme küçük finişerle) Not:Poz KGM/4427 deki Not gibidir.','ton',1032.94,null,null),
('KGM/4433','Küçük plent ünitesi ile hazırlanmış "Asfalt betonu kaplama", "Rolled asfalt kaplama", "Bitümlü makadam satıh tabakası", "Karışımı plent-miks metoduyla hazırlanan bitümlü kaplamalar (TİP A, B, C satıh tabakası)", "Rolled asfalt temel tabakası"; "Bitümlü makadam temel tabakası", "Sıcak bitümlü temel", "Karışımı plent-miks metoduyla hazırlanan bitümlü düzeltme tabakası", "Bitüm İle stabilize edilmiş temel ve alttemel" karışımlarının hazırlanması, serilmesi ve sıkıştırılması (Serme elektronik duyargalı finişerle) Not:Poz KGM/4427 deki Not gibidir.','ton',1012.71,null,null),
('KGM/4434','Küçük plent ünitesi ile hazırlanmış "Asfalt betonu kaplama", "Rolled asfalt kaplama", "Bitümlü makadam satıh tabakası", "Karışımı plent-miks metoduyla hazırlanan bitümlü kaplamalar (TİP A, B, C satıh tabakası)", "Rolled asfalt temel tabakası"; "Bitümlü makadam temel tabakası", "Sıcak bitümlü temel", "Karışımı plent-miks metoduyla hazırlanan bitümlü düzeltme tabakası", "Bitüm İle stabilize edilmiş temel ve alttemel" karışımlarının hazırlanması, serilmesi ve sıkıştırılması (Serme greyderle) Not: 1- Poz KGM/4427 deki Not gibidir. Not: 2- Bu Poz, sermenin greyderle yapılmasının gerektiği yerler iç','ton',1023.02,null,null),
('KGM/4435','Küçük plent ünitesi ile hazırlanmış "Asfalt betonu kaplama", "Rolled asfalt kaplama", "Bitümlü makadam satıh tabakası", "Karışımı plent-miks metoduyla hazırlanan bitümlü kaplamalar (TİP A, B, C satıh tabakası)", "Rolled asfalt temel tabakası"; "Bitümlü makadam temel tabakası", "Sıcak bitümlü temel", "Karışımı plent-miks metoduyla hazırlanan bitümlü düzeltme tabakası", "Bitüm İle stabilize edilmiş temel ve alttemel" karışımlarının hazırlanması, serilmesi ve sıkıştırılması (Serme el ile) Not: 1- Poz KGM/4427 deki Not gibidir. Not: 2- Bu Poz, sermenin el ile yapılmasının gerektiği yerler için uyg','ton',1984.94,null,null),
('KGM/4436','Büyük plent ünitesi ile hazırlanmış "Asfalt betonu kaplama", "Rolled asfalt kaplama", "Bitümlü makadam satıh tabakası", "Karışımı plent-miks metoduyla hazırlanan bitümlü kaplamalar (TİP A, B, C satıh tabakası)", "Rolled asfalt temel tabakası"; "Bitümlü makadam temel tabakası", "Sıcak bitümlü temel", "Karışımı plent-miks metoduyla hazırlanan bitümlü düzeltme tabakası", "Bitüm İle stabilize edilmiş temel ve alttemel" karışımlarının hazırlanması','ton',470.65,null,null),
('KGM/4436/M','Büyük plent ünitesi ile hazırlanmış "Asfalt betonu kaplama", "Rolled asfalt kaplama", "Bitümlü makadam satıh tabakası", "Karışımı plent-miks metoduyla hazırlanan bitümlü kaplamalar (TİP A, B, C satıh tabakası)", "Rolled asfalt temel tabakası"; "Bitümlü makadam temel tabakası", "Sıcak bitümlü temel", "Karışımı plent-miks metoduyla hazırlanan bitümlü düzeltme tabakası", "Bitüm İle stabilize edilmiş temel ve alttemel" karışımlarının hazırlanması','ton',465.63,null,null),
('KGM/4436/S','Büyük plent ünitesi ile "Taş mastik asfalt (TMA)" karışımı hazırlanması','ton',538.66,null,null),
('KGM/4436/1','Büyük plent ünitesi ile hazırlanmış "Asfalt betonu kaplama", "Rolled asfalt kaplama", "Bitümlü makadam satıh tabakası", "Karışımı plent-miks metoduyla hazırlanan bitümlü kaplamalar (TİP A, B, C satıh tabakası)", "Rolled asfalt temel tabakası"; "Bitümlü makadam temel tabakası", "Sıcak bitümlü temel", "Karışımı plent-miks metoduyla hazırlanan bitümlü düzeltme tabakası", "Bitüm İle stabilize edilmiş temel ve alttemel" karışımlarının hazırlanması (Yama ve bakım için - İdarece taşınacaktır.)','ton',460.6,null,null),
('KGM/4436/2','Büyük plent ünitesinde polimer modifiye bitüm kullanılarak ''''Asfalt betonu kaplama'''' ve ''''Bitümlü sıcak temel'''' hazırlanması için gerekli ilave işler','ton',89.09,null,null),
('KGM/4437','Büyük plent ünitesi ile hazırlanmış "Asfalt betonu kaplama", "Rolled asfalt kaplama", "Bitümlü makadam satıh tabakası", "Karışımı plent-miks metoduyla hazırlanan bitümlü kaplamalar (TİP A, B, C satıh tabakası)", "Rolled asfalt temel tabakası"; "Bitümlü makadam temel tabakası", "Sıcak bitümlü temel", "Karışımı plent-miks metoduyla hazırlanan bitümlü düzeltme tabakası", "Bitüm İle stabilize edilmiş temel ve alttemel" karışımlarının büyük finişerle serilmesi ve silindirle sıkıştırılması','ton',246.81,null,null),
('KGM/4438','Büyük plent ünitesi ile hazırlanmış "Asfalt betonu kaplama", "Rolled asfalt kaplama", "Bitümlü makadam satıh tabakası", "Karışımı plent-miks metoduyla hazırlanan bitümlü kaplamalar (TİP A, B, C satıh tabakası)", "Rolled asfalt temel tabakası"; "Bitümlü makadam temel tabakası", "Sıcak bitümlü temel", "Karışımı plent-miks metoduyla hazırlanan bitümlü düzeltme tabakası", "Bitüm İle stabilize edilmiş temel ve alttemel" karışımlarının elektronik duyargalı finişerle serilmesi ve silindirle sıkıştırılması','ton',240.69,null,null),
('KGM/4439','Büyük plent ünitesi ile hazırlanmış "Asfalt betonu kaplama", "Rolled asfalt kaplama", "Bitümlü makadam satıh tabakası", "Karışımı plent-miks metoduyla hazırlanan bitümlü kaplamalar (TİP A, B, C satıh tabakası)", "Rolled asfalt temel tabakası"; "Bitümlü makadam temel tabakası", "Sıcak bitümlü temel", "Karışımı plent-miks metoduyla hazırlanan bitümlü düzeltme tabakası", "Bitüm İle stabilize edilmiş temel ve alttemel" karışımlarının hazırlanması, serilmesi ve silindirle sıkıştırılması (Serme büyük finişerle)','ton',717.46,null,null),
('KGM/4440','Büyük plent ünitesi ile "Asfalt betonu kaplama", "Rolled asfalt kaplama", "Bitümlü makadam satıh tabakası", "Karışımı plent-miks metoduyla hazırlanan bitümlü kaplamalar (TİP A, B, C satıh tabakası)", "Rolled asfalt temel tabakası"; "Bitümlü makadam temel tabakası", "Sıcak bitümlü temel", "Karışımı plent-miks metoduyla hazırlanan bitümlü düzeltme tabakası", "Bitüm İle stabilize edilmiş temel ve alttemel" karışımlarının hazırlanması, serilmesi ve silindirle sıkıştırılması (Serme elektronik duyargalı finişerle)','ton',711.34,null,null),
('KGM/4440/M','Büyük plent ünitesi ile "Asfalt betonu kaplama", "Rolled asfalt kaplama", "Bitümlü makadam satıh tabakası", "Karışımı plent-miks metoduyla hazırlanan bitümlü kaplamalar (TİP A, B, C satıh tabakası)", "Rolled asfalt temel tabakası"; "Bitümlü makadam temel tabakası", "Sıcak bitümlü temel", "Karışımı plent-miks metoduyla hazırlanan bitümlü düzeltme tabakası", "Bitüm İle stabilize edilmiş temel ve alttemel" karışımlarının hazırlanması, serilmesi ve silindirle sıkıştırılması (Serme elektronik duyargalı finişerle)','ton',706.32,null,null),
('KGM/4440/S','Büyük plent ünitesi ile "Taş mastik asfalt (TMA)" karışımının hazırlanması, serilmesi ve sıkıştırılması','ton',779.35,null,null),
('KGM/4441','Büyük plent ünitesi ile "Asfalt betonu kaplama", "Rolled asfalt kaplama", "Bitümlü makadam satıh tabakası", "Karışımı plent-miks metoduyla hazırlanan bitümlü kaplamalar (TİP A, B, C satıh tabakası)", "Rolled asfalt temel tabakası"; "Bitümlü makadam temel tabakası", "Sıcak bitümlü temel", "Karışımı plent-miks metoduyla hazırlanan bitümlü düzeltme tabakası", "Bitüm İle stabilize edilmiş temel ve alttemel" karışımlarının hazırlanması, serilmesi ve silindirle sıkıştırılması (Serme greyder ile)','ton',851.36,null,null),
('KGM/4442','Büyük plent ünitesi ile "Asfalt betonu kaplama", "Rolled asfalt kaplama", "Bitümlü makadam satıh tabakası", "Karışımı plent-miks metoduyla hazırlanan bitümlü kaplamalar (TİP A, B, C satıh tabakası)", "Rolled asfalt temel tabakası"; "Bitümlü makadam temel tabakası", "Sıcak bitümlü temel", "Karışımı plent-miks metoduyla hazırlanan bitümlü düzeltme tabakası", "Bitüm İle stabilize edilmiş temel ve alttemel" karışımlarının hazırlanması, serilmesi ve silindirle sıkıştırılması (Serme el ile)','ton',1813.28,null,null),
('KGM/4448','Distribütör makinesi ve greyder ile "karışımı rodmiks metoduyla hazırlanan bitümlü satıh tabakası" veya" Karışımı rodmiks metoduyla hazırlanan bitümlü düzeltme tabakası" yapılması Not:Bu poz, bir grupta 2000 m3 den büyük işlerde kullanılmamalıdır.','m3',757.5,null,null),
('KGM/4449','Distribütör, pulvimikser ve greyder ile "karışımı rodmiks metoduyla hazırlanan bitümlü satıh tabakası" veya" Karışımı rodmiks metoduyla hazırlanan bitümlü düzeltme tabakası" yapılması','m3',685.71,null,null),
('KGM/4450','Rodmikser ve greyder ile "karışımı rodmiks metoduyla hazırlanan bitümlü satıh tabakası" veya" Karışımı rodmiks metoduyla hazırlanan bitümlü düzeltme tabakası" yapılması','m3',742.4,null,null),
('KGM/4457','Küçük plent ünitesi ile "plent-miks metoduyla hazırlanan soğuk karışım satıh tabakası " veya "Karışımı plent-miks metoduyla hazırlanan bitümlü Düzeltme tabakası" yapılması Not:Bu poz, her bir yıllık süre için 60000 ton''dan büyük çıkacak işlerde kullanılmamalıdır.','ton',849.84,null,null),
('KGM/4458','Büyük plent ünitesi ile "plent-miks metoduyla hazırlanan soğuk karışım satıh tabakası " veya "Karışımı plent-miks metoduyla hazırlanan bitümlü Düzeltme tabakası" yapılması','ton',627.75,null,null),
('KGM/4462','Distribütör makinesi ile penetrasyon makadam temel yapılması',null,60061.35,null,null),
('KGM/4465','Büyük plent ünitesi ile çimento karışımı (Çimento stabilizasyonu) hazırlanması','ton',236.79,null,null),
('KGM/4465/3','Plent-miks alttemel ve temel karışımı hazırlanması','ton',86.68,null,null),
('KGM/4465/4','Plent-miks karışım plentinin beslenmesi','ton',38.39,null,null),
('KGM/4466','Büyük plent ünitesi ile hazırlanmış olan çimento karışımının (Çimento stabilizasyonu) büyük finişerle serilmesi ve silindirle sıkıştırılması','ton',347.5,null,null),
('KGM/4466/4','Plent-miks alttemel ve temel karışımlarının büyük finişerle serilmesi ve silindirle sıkıştırılması','ton',213.05,null,null),
('KGM/4466/5','Plent-miks alttemel ve temel karışımlarının elektronik duyargalı finişerle serilmesi ve silindirle sıkıştırılması','ton',206.93,null,null),
('KGM/4467','Büyük plent ünitesi ile çimento karışımının (Çimento stabilazyonu) hazırlanması, büyük finişerle serilmesi ve silindirle sıkıştırılması','ton',584.29,null,null),
('KGM/4468','Plent ünitesi ile hazırlanmış ve serilip sıkıştırılmış çimento karışımının (Çimento stabilizasyonu) kürü',null,2737.68,null,null),
('KGM/4470','Dökme çimentonun vasıta üzerinden çimento silosuna basılması','ton',53.44,null,null),
('KGM/4475','3 cm. kalınlıkta mastik asfalt kaplama yapılması ve üzerine bir tabaka sathi kaplama çekilmesi (Köprü döşemesi ve benzeri yerlerde )','m2',2064.16,null,null),
('KGM/4476','2 cm. kalınlıkta mastik asfalt kaplama yapılması ve üzerine bir tabaka sathi kaplama çekilmesi (Köprü döşemesi ve benzeri yerlerde )','m2',1422.86,null,null),
('KGM/4480','Parke taşı döşeme derzlerine mastik asfalt dolgu yapılması','m2',412.83,null,null),
('KGM/5001/K','Trafik standart 90 cm. üçgen kenarlı T ve Y levhası yapılması','adet',590.73,null,null),
('KGM/5002/K','Trafik standart yuvarlak 60 cm. çaplı B ve Y levhası yapılması','adet',656.39,null,null),
('KGM/5003/K','Trafik standart dikdörtgen 60 X 60 cm. B levhası yapılması','adet',328.11,null,null),
('KGM/5004/K','Trafik yol engel işareti levhası yapılması (20 x 200 cm.)','adet',402.7,null,null),
('KGM/5005/K','Trafik çavuş levhası yapılması (30 x 150 cm.)','adet',456.99,null,null),
('KGM/5006/K','Trafik standart işaret levha direği yapılması (Siyah sacdan)','m',847.55,null,null),
('KGM/5007/K','Trafik emniyet klavuzu ayağı yapılması','adet',436.36,null,null),
('KGM/5008/K','Trafik işaret levhası boyanması (Yasak, tahdit ve bilgi levhaları)','m2',565.45,null,null),
('KGM/5009/K','Standart trafik işaret levhalarına sembol, bordür ve yazı yapılması','m2',163.06,null,null),
('KGM/5010/K','Standart trafik levhaları (Üçgen, yuvarlak, dörtgen) engel işaretleri ve engel işaretlerinin ayaklarının bakımının yapılması','adet',98.48,null,null),
('KGM/5020/K','Trafik işaretlemesinin yapılması ve emniyet tedbirlerinin alınması','km',13550.0,null,null),
('KGM/5030/K','Trafik işaretlemesi için lüzumlu her türlü malzemenin temini','km',1229.06,null,null),
('KGM/5050/K','Trafik işaretleme malzemelerinin temini, işaretlemenin yapılması ve emniyet tedbirlerinin alınması','km',14779.06,null,null),
('KGM/5060/K','Trafik emniyetinin sinyalizasyon tertibatı ile sağlanması','km',14905.0,null,null),
('KGM/6000','Ocak taşından konkasörle kırılmış ve elenmiş 50 mm. (2") lik malzeme ile alttemel yapılması','m3',637.93,null,null),
('KGM/6010','Elenmiş çakıllı malzeme ile alttemel yapılması','m3',209.38,null,null),
('KGM/6020','Kırılmamış ve elenmemiş çakıllı (Tüvenan) malzeme ile alttemel yapılması','m3',170.59,null,null),
('KGM/6030','Elenmemiş çakıllı malzemeden konkasörle kırılmış ve elenmiş malzeme ile alttemel yapılması','m3',351.89,null,null),
('KGM/6040','Temel yapılması [Kırılmış ve elenmiş ocak taşı ile (1")]','m3',684.52,null,null),
('KGM/6050','Temel yapılması [Kırılmış ocak taşı ve elenmiş çakıllı malzeme ile (1")]','m3',427.99,null,null),
('KGM/6060','Temel yapılması [Elenmiş çakıllı malzeme ve çakıldan konkasörle kırılmış malzeme ile (1") (Kırılmış malzeme dereden)]','m3',345.97,null,null),
('KGM/6080','Temel yapılması (Elenmiş çakıllı malzeme ve ocak taşından konkasörle kırılmış malzeme ile)','m3',427.99,null,null),
('KGM/6100/2','Plent-miks temel yapılması (Kırılmış ve elenmiş ocak taşı ile - astarlı)','ton',694.73,null,null),
('KGM/6100/3','Plent-miks temel yapılması (Kırılmış ve elenmiş ocak taşı ile)','ton',691.72,null,null),
('KGM/6100/3-1','Plent-miks alttemel yapılması (Kırılmış ve elenmiş ocak taşı ile)','ton',606.15,null,null),
('KGM/6115','Plent-miks banket yapılması (Kırılmış ve elenmiş ocak taşı ile)','ton',552.79,null,null),
('KGM/6115/1','Plent-miks banket yapılması (Kırılmış ve elenmiş ocak taşı ile - serme finişerle)','ton',691.72,null,null),
('KGM/6125','Plent-miks temel yapılması (Kırılmış ve elenmiş çakıllı malzeme ile - astarlı)','ton',554.57,null,null),
('KGM/6126','Plent-miks temel yapılması (Kırılmış ve elenmiş çakıllı malzeme ile)','ton',551.56,null,null),
('KGM/6135','Plent-miks banket yapılması (Kırılmış ve elenmiş çakıllı malzeme ile)','ton',412.63,null,null),
('KGM/6200-A','Bitümlü sıcak temel karışım malzemelerinin temini (Kırılmış ve elenmiş ocak taşı ile) (Tip-A)','ton',446.86,null,null),
('KGM/6200-B','Bitümlü sıcak temel karışım malzemelerinin temini (Kırılmış ve elenmiş ocak taşı ile) (Tip-B)','ton',453.67,null,null),
('KGM/6201-A','Bitümlü sıcak temel karışım malzemelerinin temini (Kırılmış ve elenmiş sert taş ile) (Tip-A)','ton',533.17,null,null),
('KGM/6201-B','Bitümlü sıcak temel karışım malzemelerinin temini (Kırılmış ve elenmiş sert taş ile) (Tip-B)','ton',543.43,null,null),
('KGM/6202-A','Bitümlü sıcak temel karışım malzemelerinin temini (Kırılmış ve elenmiş çakıllı malzeme ile) (Tip-A)','ton',305.95,null,null),
('KGM/6202-B','Bitümlü sıcak temel karışım malzemelerinin temini (Kırılmış ve elenmiş çakıllı malzeme ile) (Tip-B)','ton',312.78,null,null),
('KGM/6208','8 cm. sıkışmış kalınlıkta 1 m2 asfalt betonu bitümlü sıcak temel tabakası yapılması (Kırılmış ve elenmiş ocak taşı ile) (Tip-A)','m2',216.69,null,null),
('KGM/6208-A','8 cm. sıkışmış kalınlıkta 1 m2 asfalt betonu bitümlü sıcak temel tabakası yapılması (Kırılmış ve elenmiş ocak taşı ile) (Astarsız temel üzerine) (Tip-A)','m2',213.04,null,null),
('KGM/6209','9 cm. sıkışmış kalınlıkta 1 m2 asfalt betonu bitümlü sıcak temel tabakası yapılması (Kırılmış ve elenmiş ocak taşı ile) (Tip-A)','m2',243.22,null,null),
('KGM/6209-A','9 cm. sıkışmış kalınlıkta 1 m2 asfalt betonu bitümlü sıcak temel tabakası yapılması (Kırılmış ve elenmiş ocak taşı ile) (Astarsız temel üzerine) (Tip-A)','m2',239.57,null,null),
('KGM/6210','10 cm. sıkışmış kalınlıkta 1 m2 asfalt betonu bitümlü sıcak temel tabakası yapılması (Kırılmış ve elenmiş ocak taşı ile) (Tip-A)','m2',269.74,null,null),
('KGM/6210-A','10 cm. sıkışmış kalınlıkta 1 m2 asfalt betonu bitümlü sıcak temel tabakası yapılması (Kırılmış ve elenmiş ocak taşı ile) (Astarsız temel üzerine) (Tip-A)','m2',266.09,null,null),
('KGM/6210/S','10 cm. sıkışmış kalınlıkta 1 m2 asfalt betonu bitümlü sıcak temel tabakası yapılması (Kırılmış ve elenmiş sert taş ile) (Tip-A)','m2',295.79,null,null),
('KGM/6210/S-A','10 cm. sıkışmış kalınlıkta 1 m2 asfalt betonu bitümlü sıcak temel tabakası yapılması (Kırılmış ve elenmiş sert taş ile) (Astarsız temel üzerine) (Tip-A)','m2',292.14,null,null),
('KGM/6211','11 cm. sıkışmış kalınlıkta 1 m2 asfalt betonu bitümlü sıcak temel tabakası yapılması (Kırılmış ve elenmiş ocak taşı ile) (Tip-A)','m2',296.27,null,null),
('KGM/6211-A','11 cm. sıkışmış kalınlıkta 1 m2 asfalt betonu bitümlü sıcak temel tabakası yapılması (Kırılmış ve elenmiş ocak taşı ile) (Astarsız temel üzerine) (Tip-A)','m2',292.62,null,null),
('KGM/6212','12 cm. sıkışmış kalınlıkta 1 m2 asfalt betonu bitümlü sıcak temel tabakası yapılması (Kırılmış ve elenmiş ocak taşı ile) (Tip-A)','m2',322.78,null,null),
('KGM/6212-A','12 cm. sıkışmış kalınlıkta 1 m2 asfalt betonu bitümlü sıcak temel tabakası yapılması (Kırılmış ve elenmiş ocak taşı ile) (Astarsız temel üzerine) (Tip-A)','m2',319.13,null,null),
('KGM/6212/S','12 cm. sıkışmış kalınlıkta 1 m2 asfalt betonu bitümlü sıcak temel tabakası yapılması (Kırılmış ve elenmiş sert taş ile) (Tip-A)','m2',354.04,null,null),
('KGM/6212/S-A','12 cm. sıkışmış kalınlıkta 1 m2 asfalt betonu bitümlü sıcak temel tabakası yapılması (Kırılmış ve elenmiş sert taş ile) (Astarsız temel üzerine) (Tip-A)','m2',350.39,null,null),
('KGM/6212/E','12 cm. sıkışmış kalınlıkta 1 m2 asfalt betonu bitümlü sıcak temel tabakası yapılması (Kırılmış ve elenmiş çakıllı malzeme ile) (Tip-A)','m2',283.89,null,null),
('KGM/6212/E-A','12 cm. sıkışmış kalınlıkta 1 m2 asfalt betonu bitümlü sıcak temel tabakası yapılması (Kırılmış ve elenmiş çakıllı malzeme ile) (Astarsız temel üzerine) (Tip-A)','m2',280.24,null,null),
('KGM/6213','13 cm. sıkışmış kalınlıkta 1 m2 asfalt betonu bitümlü sıcak temel tabakası yapılması (Kırılmış ve elenmiş ocak taşı ile) (Tip-A)','m2',349.31,null,null),
('KGM/6213-A','13 cm. sıkışmış kalınlıkta 1 m2 asfalt betonu bitümlü sıcak temel tabakası yapılması (Kırılmış ve elenmiş ocak taşı ile) (Astarsız temel üzerine) (Tip-A)','m2',345.66,null,null),
('KGM/6214','14 cm. sıkışmış kalınlıkta 1 m2 asfalt betonu bitümlü sıcak temel tabakası yapılması (Kırılmış ve elenmiş ocak taşı ile) (Tip-A)','m2',375.84,null,null),
('KGM/6214-A','14 cm. sıkışmış kalınlıkta 1 m2 asfalt betonu bitümlü sıcak temel tabakası yapılması (Kırılmış ve elenmiş ocak taşı ile) (Astarsız temel üzerine) (Tip-A)','m2',372.19,null,null),
('KGM/6214/E','14 cm. sıkışmış kalınlıkta 1 m2 asfalt betonu bitümlü sıcak temel tabakası yapılması (Kırılmış ve elenmiş çakıllı malzeme ile) (Tip-A)','m2',330.47,null,null),
('KGM/6214/E-A','14 cm. sıkışmış kalınlıkta 1 m2 asfalt betonu bitümlü sıcak temel tabakası yapılması (Kırılmış ve elenmiş çakıllı malzeme ile) (Astarsız temel üzerine) (Tip-A)','m2',326.82,null,null),
('KGM/6220','Bitümlü sıcak temel yapılması (Kırılmış ve elenmiş ocak taşı ile) (Tip-A)','ton',1178.63,null,null),
('KGM/6220-A','Bitümlü sıcak temel yapılması (Kırılmış ve elenmiş ocak taşı ile) (Astarsız temel üzerine) (Tip-A)','ton',1162.76,null,null),
('KGM/6220/S','Bitümlü sıcak temel yapılması (Kırılmış ve elenmiş sert taş ile) (Tip-A)','ton',1264.94,null,null),
('KGM/6220/S-A','Bitümlü sıcak temel yapılması (Kırılmış ve elenmiş sert taş ile) (Astarsız temel üzerine) (Tip-A)','ton',1249.07,null,null),
('KGM/6220/E','Bitümlü sıcak temel yapılması (Kırılmış ve elenmiş çakıllı malzeme ile) (Tip-A)','ton',1037.72,null,null),
('KGM/6220/E-A','Bitümlü sıcak temel yapılması (Kırılmış ve elenmiş çakıllı malzeme ile) (Astarsız temel üzerine) (Tip-A)','ton',1021.85,null,null),
('KGM/6300','Asfalt betonu binder tabakası malzemelerinin temini (Kırılmış ve elenmiş ocak taşı ile)','ton',455.05,null,null),
('KGM/6301','Asfalt betonu binder tabakası malzemelerinin temini (Kırılmış ve elenmiş sert taş ile)','ton',543.22,null,null),
('KGM/6302','Asfalt betonu binder tabakası malzemelerinin temini (Kırılmış ve elenmiş çakıllı malzeme ile)','ton',314.87,null,null),
('KGM/6305','5 cm. sıkışmış kalınlıkta 1 m2 asfalt betonu binder tabakası yapılması (Kırılmış ve elenmiş ocak taşı ile)','m2',143.88,null,null),
('KGM/6305/S','5 cm. sıkışmış kalınlıkta 1 m2 asfalt betonu binder tabakası yapılması (Kırılmış ve elenmiş sert taş ile)','m2',157.57,null,null),
('KGM/6306','6 cm. sıkışmış kalınlıkta 1 m2 asfalt betonu binder tabakası yapılması (Kırılmış ve elenmiş ocak taşı ile)','m2',171.75,null,null),
('KGM/6306/S','6 cm. sıkışmış kalınlıkta 1 m2 asfalt betonu binder tabakası yapılması (Kırılmış ve elenmiş sert taş ile)','m2',188.19,null,null),
('KGM/6307','7 cm. sıkışmış kalınlıkta 1 m² asfalt betonu binder tabakası yapılması (Kırılmış ve elenmiş ocak taşı ile)','m2',199.62,null,null),
('KGM/6307/S','7 cm. sıkışmış kalınlıkta 1 m2 asfalt betonu binder tabakası yapılması (Kırılmış ve elenmiş sert taş ile)','m2',218.8,null,null),
('KGM/6308','8 cm. sıkışmış kalınlıkta 1 m2 asfalt betonu binder tabakası yapılması (Kırılmış ve elenmiş ocak taşı ile)','m2',227.49,null,null),
('KGM/6308/S','8 cm. sıkışmış kalınlıkta 1 m2 asfalt betonu binder tabakası yapılması (Kırılmış ve elenmiş sert taş ile)','m2',249.42,null,null),
('KGM/6320','Asfalt betonu binder tabakası yapılması (Kırılmış ve elenmiş ocak taşı ile)','ton',1198.7,null,null),
('KGM/6320/S','Asfalt betonu binder tabakası yapılması (Kırılmış ve elenmiş sert taş ile)','ton',1286.87,null,null),
('KGM/6320/E','Asfalt betonu binder tabakası yapılması (Kırılmış ve elenmiş malzeme ile)','ton',1058.52,null,null),
('KGM/6330','Bakım için asfalt betonu binder karışımı temini (Kırılmış ve elenmiş ocak taşından) (Karışımın taşınması yüklenici kamyonları ile)','ton',926.5,null,null),
('KGM/6331','Bakım için asfalt betonu binder karışımı temini (Kırılmış ve elenmiş ocak taşından) (Karışımın taşınması idare kamyonları ile)','ton',916.45,null,null),
('KGM/6340','Bakım için asfalt betonu binder karışımı temini (Kırılmış ve elenmiş çakıllı malzeme ile) (Karışımın taşınması yüklenici kamyonları ile)','ton',786.32,null,null),
('KGM/6341','Bakım için asfalt betonu binder karışımı temini (Kırılmış ve elenmiş çakıllı malzeme ile) (Karışımın taşınması idare kamyonları ile)','ton',776.27,null,null),
('KGM/6400-1','Asfalt betonu aşınma tabakası malzemelerinin temini (Kırılmış ve elenmiş ocak taşı ile) (Tip-1)','ton',474.24,null,null),
('KGM/6400-2','Asfalt betonu aşınma tabakası malzemelerinin temini (Kırılmış ve elenmiş ocak taşı ile) (Tip-2)','ton',478.49,null,null),
('KGM/6401-1','Asfalt betonu aşınma tabakası malzemelerinin temini (Kırılmış ve elenmiş sert taş ile) (Tip-1)','ton',570.34,null,null),
('KGM/6401-2','Asfalt betonu aşınma tabakası malzemelerinin temini (Kırılmış ve elenmiş sert taş ile) (Tip-2)','ton',577.12,null,null),
('KGM/6402-1','Asfalt betonu aşınma tabakası malzemelerinin temini (Kırılmış ve elenmiş çakıllı malzeme ile) (Tip-1)','ton',334.8,null,null),
('KGM/6402-2','Asfalt betonu aşınma tabakası malzemelerinin temini (Kırılmış ve elenmiş çakıllı malzeme ile) (Tip-2)','ton',339.07,null,null),
('KGM/6404','4 cm. sıkışmış kalınlıkta 1 m2 asfalt betonu aşınma tabakası yapılması (Kırılmış ve elenmiş ocak taşı ile) (Tip-1)','m2',117.85,null,null),
('KGM/6404-M','4 cm. sıkışmış kalınlıkta 1 m2 asfalt betonu aşınma tabakası yapılması (Kırılmış ve elenmiş ocak taşı ve modifiye bitüm ile) (Tip-1)','m2',135.45,null,null),
('KGM/6404/S','4 cm. sıkışmış kalınlıkta 1 m2 asfalt betonu aşınma tabakası yapılması (Kırılmış ve elenmiş sert taş ile) (Tip-1)','m2',129.62,null,null),
('KGM/6404/S-M','4 cm. sıkışmış kalınlıkta 1 m2 asfalt betonu aşınma tabakası yapılması (Kırılmış ve elenmiş sert taş ve modifiye bitüm ile)','m2',148.36,null,null),
('KGM/6405','5 cm. sıkışmış kalınlıkta 1 m2 asfalt betonu aşınma tabakası yapılması (Kırılmış ve elenmiş ocak taşı ile) (Tip-1)','m2',146.18,null,null),
('KGM/6405-M','5 cm. sıkışmış kalınlıkta 1 m2 asfalt betonu aşınma tabakası yapılması (Kırılmış ve elenmiş ocak taşı ve modifiye bitüm ile) (Tip-1)','m2',168.18,null,null),
('KGM/6405/S','5 cm. sıkışmış kalınlıkta 1 m2 asfalt betonu aşınma tabakası yapılması (Kırılmış ve elenmiş sert taş ile) (Tip-1)','m2',160.9,null,null),
('KGM/6405/S-M','5 cm. sıkışmış kalınlıkta 1 m2 asfalt betonu aşınma tabakası yapılması (Kırılmış ve elenmiş sert taş ve modifiye bitüm ile)','m2',184.31,null,null),
('KGM/6410','Asfalt betonu aşınma tabakası yapılması (Kırılmış ve elenmiş ocak taşı ile) (Tip-1)','ton',1233.66,null,null),
('KGM/6450-1','Taş mastik asfalt (TMA) aşınma tabakası malzemesinin temini (Tip-1) (Kırılmış ve elenmiş ocak taşı ile)','ton',471.76,null,null),
('KGM/6450-2','Taş mastik asfalt (TMA) aşınma tabakası malzemesinin temini (Tip-2) (Kırılmış ve elenmiş ocak taşı ile)','ton',476.95,null,null),
('KGM/6451-1','Taş mastik asfalt (TMA) aşınma tabakası malzemesinin temini (Tip-1) (Kırılmış ve elenmiş sert taş ile)','ton',553.39,null,null),
('KGM/6451-2','Taş mastik asfalt (TMA) aşınma tabakası malzemesinin temini (Tip-2) (Kırılmış ve elenmiş sert taş ile)','ton',559.46,null,null),
('KGM/6454','4 cm. sıkışmış kalınlıkta taş mastik asfalt aşınma tabakası yapılması (Tip-1) (Kırılmış ve elenmiş ocak taşı ile)','m2',126.18,null,null),
('KGM/6454-M','4 cm. sıkışmış kalınlıkta taş mastik asfalt aşınma tabakası yapılması (Tip-1) (Kırılmış ve elenmiş ocak taşı ve modifiye bitüm ile)','m2',146.23,null,null),
('KGM/6454/S','4 cm. sıkışmış kalınlıkta taş mastik asfalt aşınma tabakası yapılması (Tip-1) (Kırılmış ve elenmiş sert taş ile)','m2',136.69,null,null),
('KGM/6454/S-M','4 cm. sıkışmış kalınlıkta taş mastik asfalt aşınma tabakası yapılması (Tip-1) (Kırılmış ve elenmiş sert taş ve modifiye bitüm ile)','m2',157.15,null,null),
('KGM/6540','Bir tabaka astarlı bitümlü sathi kaplama yapılması (Tip-1) (Kırılmış ve elenmiş ocak taşı ile) Not:Agreganın yıkanması halinde yıkama bedeli ayrıca ödenir.',null,20817.17,null,null),
('KGM/6550','Bir tabaka astarlı bitümlü sathi kaplama yapılması (Tip-1) (Kırılmış ve elenmiş çakıl ile)',null,18979.66,null,null),
('KGM/6560','İki tabaka astarlı bitümlü sathi kaplama yapılması (Tip-1 + Tip-3) (Kırılmış ve elenmiş ocak taşı ile) Not:Agreganın yıkanması halinde yıkama bedeli ayrıca ödenir.',null,38480.73,null,null),
('KGM/6570','İki tabaka astarlı bitümlü sathi kaplama yapılması (Tip-1 + Tip-3) (Kırılmış ve elenmiş çakıl ile)',null,34996.28,null,null),
('KGM/6580','Bir tabaka astarsız bitümlü sathi kaplama yapılması (Tip-2) (Kırılmış ve elenmiş ocak taşı ile) Not:Agreganın yıkanması halinde yıkama bedeli ayrıca ödenir.',null,18891.59,null,null),
('KGM/6590','Bir tabaka astarsız bitümlü sathi kaplama yapılması (Tip-2) (Kırılmış ve elenmiş çakıl ile)',null,17244.65,null,null),
('KGM/7500','Prefabrik beton parke imali ve yerine döşenmesi (10 cm. kalınlıkta)','m2',1118.16,null,null),
('KGM/7501','Prefabrik beton parke imali ve yerine döşenmesi (8 cm. kalınlıkta)','m2',1052.54,null,null),
('KGM/7502','Prefabrik beton parke imali ve yerine döşenmesi (6 cm. kalınlıkta)','m2',986.69,null,null),
('KGM/7503','Prefabrik beton plak imali ve yerine döşenmesi (5 cm. kalınlıkta)','m2',925.68,null,null),
('KGM/7504','Prefabrik beton bordür imali ve yerine döşenmesi (0,15x0,30)','m',540.98,null,null),
('KGM/7505/1','Prefabrik beton bordür yapılması ve yerine döşenmesi (Düz bordür)','m',402.94,null,null),
('KGM/7505/2','Prefabrik beton bordür yapılması ve yerine döşenmesi (Tam kesik çıkış bordürü)','m',475.4,null,null),
('KGM/7506','Prefabrik beton plaklarla şev kaplama yapılması','m2',1572.64,null,null),
('KGM/7507/1','Prekast küçük tip (Tip-1) düşüm oluğu yapılması','m',446.96,null,null),
('KGM/7507/2','Prekast büyük tip (Tip-2) düşüm oluğu yapılması','m',862.69,null,null),
('KGM/7508','Yağmur oluğu yapılması ve yerine konulması (30x12 cm.) (4 cm. oval derinlikte)','m',354.39,null,null),
('KGM/9000','Delgi makinesiyle her türlü zeminde/kayada, her uzunlukta, her çapta ve açıda ankraj, zemin çivisi, bulon ve barbakan deliği delinmesi','m',736.46,null,null),
('KGM/9001','Delik içine perfore boru ile Ø50mm barbakan tesis edilmesi','m',264.9,null,null),
('KGM/9001/1','Delik içine perfore boru ile Ø50mm barbakan tesis edilmesi (Geotekstil sarımlı)','m',332.85,null,null),
('KGM/9002','Zemin çivisi imali ve yerine yerleştirilmesi (Ø28 mm)','m',357.38,null,null),
('KGM/9002/1','Zemin çivisi imali ve yerine yerleştirilmesi (Ø32 mm)','m',417.88,null,null),
('KGM/9003/1','Her türlü zeminde/kayada her boy ve açıda bulon tesis edilmesi (Ø 28 mm)','m',503.43,null,null),
('KGM/9003/2','Her türlü zeminde/kayada her boy ve açıda bulon tesis edilmesi (Ø 32 mm)','m',552.74,null,null),
('KGM/9004','Çimento enjeksiyonu yapılması','m3',2521.55,null,null),
('KGM/08.002/1-K','Makine ile kil ve benzeri bağlayıcı malzemenin temini','m3',115.09,null,null),
('KGM/08.007/K-1','Makine ile kum ve çakıl yıkanması','m3',124.54,null,null),
('KGM/08.010/K','Profilli demirden "Kazık çarığı, mesnet ve teferruatı, bordür kenarı ve ayrım demiri ile ahşap menfez ve köprülerde madeni birleştirme unsurları" işçiliği (Boyama hariç)','ton',93575.0,null,null),
('KGM/14.001/K-A','El ile yumuşak toprak kazılması ve kullanılması (Yarmadan dolguya gidecek kazılarda)','m3',526.1,null,null),
('KGM/14.001/K-B','El ile yumuşak toprak kazılması ve kullanılması (Ariyet ocağından getirilecek veya depoya gidecek kazılarda)','m3',522.55,null,null),
('KGM/14.001/K-1','Yolların orta refüjlerindeki fazla toprakların elle kazılması ve kullanılması','m2',87.38,null,null),
('KGM/14.002/K-A','El ile sert toprak kazılması ve kullanılması (Yarmadan dolguya gidecek kazılarda)','m3',679.85,null,null),
('KGM/14.002/K-B','El ile sert toprak kazılması ve kullanılması (Ariyet ocağından getirilecek veya depoya gidecek kazılarda)','m3',676.3,null,null),
('KGM/14.003/K-A','El ile yumuşak küskülük kazılması ve kullanılması (Yarmadan dolguya gidecek kazılarda)','m3',846.41,null,null),
('KGM/14.003/K-B','El ile yumuşak küskülük kazılması ve kullanılması (Ariyet ocağından getirilecek veya depoya gidecek kazılarda)','m3',842.86,null,null),
('KGM/14.004/K-A','El ile sert küskülük kazılması ve kullanılması (Yarmadan dolguya gidecek kazılarda)','m3',974.54,null,null),
('KGM/14.004/K-B','El ile sert küskülük kazılması ve kullanılması (Ariyet ocağından getirilecek veya depoya gidecek kazılarda)','m3',970.99,null,null),
('KGM/14.005/K-A','Patlayıcı madde kullanılarak el veya kompresörle yumuşak kaya kazılması ve kullanılması (Yarmadan dolguya gidecek kazılarda)','m3',662.73,null,null),
('KGM/14.005/K-B','Patlayıcı madde kullanılarak el veya kompresörle yumuşak kaya kazılması ve kullanılması (Ariyet ocağından getirilecek veya depoya gidecek kazılarda)','m3',659.18,null,null),
('KGM/14.006/K-A','Patlayıcı madde kullanılarak el veya kompresörle sert kaya kazılması ve kullanılması (Yarmadan dolguya gidecek kazılarda)','m3',751.08,null,null),
('KGM/14.006/K-B','Patlayıcı madde kullanılarak el veya kompresörle sert kaya kazılması ve kullanılması (Ariyet ocağından getirilecek veya depoya gidecek kazılarda)','m3',747.53,null,null),
('KGM/14.007/K-A','Patlayıcı madde kullanılarak el veya kompresörle çok sert kaya kazılması ve kullanılması (Yarmadan dolguya gidecek kazılarda)','m3',902.06,null,null),
('KGM/14.007/K-B','Patlayıcı madde kullanılarak el veya kompresörle çok sert kaya kazılması ve kullanılması (Ariyet ocağından getirilecek veya depoya gidecek kazılarda)','m3',898.51,null,null),
('KGM/14.008/K-A','Patlayıcı madde kullanılmadan el veya kompresörle yumuşak kaya kazılması ve kullanılması (Yarmadan dolguya gidecek kazılarda)','m3',1063.44,null,null),
('KGM/14.008/K-B','Patlayıcı madde kullanılmadan el veya kompresörle yumuşak kaya kazılması ve kullanılması (Ariyet ocağından getirilecek veya depoya gidecek kazılarda)','m3',1059.89,null,null),
('KGM/14.009/K-A','Patlayıcı madde kullanılmadan el veya kompresörle sert kaya kazılması ve kullanılması (Yarmadan dolguya gidecek kazılarda)','m3',1533.7,null,null),
('KGM/14.009/K-B','Patlayıcı madde kullanılmadan el veya kompresörle sert kaya kazılması ve kullanılması (Ariyet ocağından getirilecek veya depoya gidecek kazılarda)','m3',1530.15,null,null),
('KGM/14.009/1','Saplama deliği açılması','m',678.28,null,null),
('KGM/14.010/K-A','Patlayıcı madde kullanılmadan el veya kompresörle çok sert kaya kazılması ve kullanılması (Yarmadan dolguya gidecek kazılarda)','m3',2343.1,null,null),
('KGM/14.010/K-B','Patlayıcı madde kullanılmadan el veya kompresörle çok sert kaya kazılması ve kullanılması (Ariyet ocağından getirilecek veya depoya gidecek kazılarda)','m3',2339.55,null,null)
) as v(poz_no,tanim,birim,fiyat,fiyat_formul,extra)
on conflict (source_id,poz_no,coalesce(birim,'')) do nothing;