-- KGM 2026 seed part 4/4 v2 (idempotent, tip cast'li)
insert into bf_poz (source_id,poz_no,tanim,birim,fiyat,fiyat_formul,extra)
select '00a62b45-1fdb-4bd8-8325-160287c204f0'::uuid, v.poz_no, v.tanim, v.birim, v.fiyat::numeric, v.fiyat_formul, v.extra::jsonb
from (values
('KGM/26.021/K-1','Yivli karo siman kaplama (Tesviye betonlu)','m2',1316.8,null,null),
('KGM/26.030/K','Renkli ve yivli karo siman kaplama (Tesviye betonsuz)','m2',1121.53,null,null),
('KGM/26.030/K-1','Renkli ve yivli karo siman kaplama (Tesviye betonlu)','m2',1316.8,null,null),
('KGM/26.041/K','Karo mozaik kaplama (Tesviye betonsuz)','m2',1195.03,null,null),
('KGM/26.041/K-1','Karo mozaik kaplama (Tesviye betonlu)','m2',1390.3,null,null),
('KGM/27.101/K','Moloz ve çaplanmış moloz taş inşaat yüzlerine gömme oluklu derz yapılması','m2',251.48,null,null),
('KGM/27.104/K','Yonma ve kesme taş inşaat yüzlerine derz yapılması','m2',336.24,null,null),
('KGM/27.501/K','2 cm. kalınlıkta beton yüzey sıvası','m2',384.13,null,null),
('KGM/27.583/K','2 cm kalınlıkta şap yapılması','m2',411.35,null,null),
('KGM/27.583/K-1','3 cm kalınlıkta şap yapılması','m2',432.0,null,null),
('KGM/27.586/K','4 cm kalınlıkta şap yapılması','m2',452.65,null,null),
('KGM/28.010/K','Köprülerde 0-80 mm. boyuna hareket kapasiteli, sabit ankrajlı, kauçuk contalı,sıcak haddelenmiş veya ekstrüde özel çelik profilli, su geçirmez tip genleşme derzi yapılması ve yerine konulması','m',19878.69,null,null),
('KGM/28.011/K','Köprülerde 0-160 mm. boyuna hareket kapasiteli, sabit ankrajlı, kauçuk contalı,sıcak haddelenmiş veya ekstrüde özel çelik profilli, su geçirmez tip genleşme derzi yapılması ve yerine konulması','m',55344.08,null,null),
('KGM/28.012/K','Köprülerde 0-240 mm. boyuna hareket kapasiteli, sabit ankrajlı, kauçuk contalı,sıcak haddelenmiş veya ekstrüde özel çelik profilli, su geçirmez tip genleşme derzi yapılması ve yerine konulması','m',75184.46,null,null),
('KGM/28.013/K','Köprülerde 0-320 mm. boyuna hareket kapasiteli, sabit ankrajlı, kauçuk contalı,sıcak haddelenmiş veya ekstrüde özel çelik profilli, su geçirmez tip genleşme derzi yapılması ve yerine konulması','m',115649.84,null,null),
('KGM/32.002/K','Her cins ve klastaki zeminde kesiti 6 m2 den az olan drenaj, kaptaj ve benzeri galeri kazısı','m3',9230.26,null,null),
('KGM/32.005/K','Galeri kazısı su zammı','m3',923.03,null,null),
('KGM/34.001','Ocak taşından (0 - 0,005 ton kategorideki) taşlar ile tahkimatın yapımı (Dalgakıran ve deniz tahkimatı gibi inşaatta)','m3',174.58,null,null),
('KGM/34.001','Ocak taşından (0 - 0,005 ton kategorideki) taşlar ile tahkimatın yapımı (Dalgakıran ve deniz tahkimatı gibi inşaatta)','ton',96.99,null,null),
('KGM/34.001/1-K','Kazı taşından (0 - 0,005 ton kategorideki) taşlar ile tahkimatın yapımı (Dalgakıran ve deniz tahkimatı gibi inşaatta)','m3',53.66,null,null),
('KGM/34.001/1-K','Kazı taşından (0 - 0,005 ton kategorideki) taşlar ile tahkimatın yapımı (Dalgakıran ve deniz tahkimatı gibi inşaatta)','ton',29.81,null,null),
('KGM/34.003','Ocak taşından ( 0,005 - 0,100 ton kategorideki) taşlar ile tahkimatın yapımı (Dalgakıran ve deniz tahkimatı gibi inşaatta)','m3',390.62,null,null),
('KGM/34.003','Ocak taşından ( 0,005 - 0,100 ton kategorideki) taşlar ile tahkimatın yapımı (Dalgakıran ve deniz tahkimatı gibi inşaatta)','ton',217.01,null,null),
('KGM/34.003/1-K','Kazı taşından ( 0,005 - 0,100 ton kategorideki) taşlar ile tahkimatın yapımı (Dalgakıran ve deniz tahkimatı gibi inşaatta)','m3',128.36,null,null),
('KGM/34.003/1-K','Kazı taşından ( 0,005 - 0,100 ton kategorideki) taşlar ile tahkimatın yapımı (Dalgakıran ve deniz tahkimatı gibi inşaatta)','ton',71.31,null,null),
('KGM/34.004/K','Ocak taşından (0 - 0,250 ton kategorideki) taşlar ile tahkimatın yapımı (Dalgakıran ve deniz tahkimatı gibi inşaatta)','m3',433.24,null,null),
('KGM/34.004/K','Ocak taşından (0 - 0,250 ton kategorideki) taşlar ile tahkimatın yapımı (Dalgakıran ve deniz tahkimatı gibi inşaatta)','ton',240.69,null,null),
('KGM/34.004/1-K','Kazı taşından (0 - 0,250 ton kategorideki) taşlar ile tahkimatın yapımı (Dalgakıran ve deniz tahkimatı gibi inşaatta)','m3',143.57,null,null),
('KGM/34.004/1-K','Kazı taşından (0 - 0,250 ton kategorideki) taşlar ile tahkimatın yapımı (Dalgakıran ve deniz tahkimatı gibi inşaatta)','ton',79.76,null,null),
('KGM/34.005','Ocak taşından (0,100 - 0,250 ton kategorideki) taşlar ile tahkimatın yapımı (Dalgakıran ve deniz tahkimatı gibi inşaatta)','m3',446.87,null,null),
('KGM/34.005','Ocak taşından (0,100 - 0,250 ton kategorideki) taşlar ile tahkimatın yapımı (Dalgakıran ve deniz tahkimatı gibi inşaatta)','ton',248.26,null,null),
('KGM/34.005/1-K','Kazık taşından (0,100 - 0,250 ton kategorideki) taşlar ile tahkimatın yapımı (Dalgakıran ve deniz tahkimatı gibi inşaatta)','m3',155.66,null,null),
('KGM/34.005/1-K','Kazık taşından (0,100 - 0,250 ton kategorideki) taşlar ile tahkimatın yapımı (Dalgakıran ve deniz tahkimatı gibi inşaatta)','ton',86.48,null,null),
('KGM/34.006/K','Ocak taşından (0 - 0,400 ton kategorideki) taşlar ile tahkimatın yapımı (Dalgakıran ve deniz tahkimatı gibi inşaatta)','m3',457.36,null,null),
('KGM/34.006/K','Ocak taşından (0 - 0,400 ton kategorideki) taşlar ile tahkimatın yapımı (Dalgakıran ve deniz tahkimatı gibi inşaatta)','ton',254.09,null,null),
('KGM/34.006/1-K','Kazı taşından (0 - 0,400 ton kategorideki) taşlar ile tahkimatın yapımı (Dalgakıran ve deniz tahkimatı gibi inşaatta)','m3',163.8,null,null),
('KGM/34.006/1-K','Kazı taşından (0 - 0,400 ton kategorideki) taşlar ile tahkimatın yapımı (Dalgakıran ve deniz tahkimatı gibi inşaatta)','ton',91.0,null,null),
('KGM/34.007','Ocak taşından (0,250 - 0,400 ton kategorideki) taşlar ile tahkimatın yapımı (Dalgakıran ve deniz tahkimatı gibi inşaatta)','m3',493.25,null,null),
('KGM/34.007','Ocak taşından (0,250 - 0,400 ton kategorideki) taşlar ile tahkimatın yapımı (Dalgakıran ve deniz tahkimatı gibi inşaatta)','ton',274.03,null,null),
('KGM/34.007/1-K','Kazı taşından (0,250 - 0,400 ton kategorideki) taşlar ile tahkimatın yapımı (Dalgakıran ve deniz tahkimatı gibi inşaatta)','m3',197.06,null,null),
('KGM/34.007/1-K','Kazı taşından (0,250 - 0,400 ton kategorideki) taşlar ile tahkimatın yapımı (Dalgakıran ve deniz tahkimatı gibi inşaatta)','ton',109.48,null,null),
('KGM/34.008/K','Ocak taşından (0,400 - 2 ton kategorideki) taşlar ile tahkimatın yapımı (Dalgakıran ve deniz tahkimatı gibi inşaatta)','m3',490.91,null,null),
('KGM/34.008/K','Ocak taşından (0,400 - 2 ton kategorideki) taşlar ile tahkimatın yapımı (Dalgakıran ve deniz tahkimatı gibi inşaatta)','ton',272.73,null,null),
('KGM/34.008/1-K','Kazı taşından (0,400 - 2 ton kategorideki) taşlar ile tahkimatın yapımı (Dalgakıran ve deniz tahkimatı gibi inşaatta)','m3',197.39,null,null),
('KGM/34.008/1-K','Kazı taşından (0,400 - 2 ton kategorideki) taşlar ile tahkimatın yapımı (Dalgakıran ve deniz tahkimatı gibi inşaatta)','ton',109.66,null,null),
('KGM/34.009/K','Ocak taşından (2 - 6 ton kategorideki) taşlar ile tahkimatın yapımı (Dalgakıran ve deniz tahkimatı gibi inşaatta)','m3',610.99,null,null),
('KGM/34.009/K','Ocak taşından (2 - 6 ton kategorideki) taşlar ile tahkimatın yapımı (Dalgakıran ve deniz tahkimatı gibi inşaatta)','ton',339.44,null,null),
('KGM/34.009/1-K','Kazı taşından (2 - 6 ton kategorideki) taşlar ile tahkimatın yapımı (Dalgakıran ve deniz tahkimatı gibi inşaatta)','m3',257.54,null,null),
('KGM/34.009/1-K','Kazı taşından (2 - 6 ton kategorideki) taşlar ile tahkimatın yapımı (Dalgakıran ve deniz tahkimatı gibi inşaatta)','ton',143.08,null,null),
('KGM/34.010/K','Ocak taşından (6 -15 ton kategorideki) taşlar ile tahkimatın yapımı (Dalgakıran ve deniz tahkimatı gibi inşaatta)','m3',807.95,null,null),
('KGM/34.010/K','Ocak taşından (6 -15 ton kategorideki) taşlar ile tahkimatın yapımı (Dalgakıran ve deniz tahkimatı gibi inşaatta)','ton',448.86,null,null),
('KGM/34.010/1-K','Kazı taşından (6 -15 ton kategorideki) taşlar ile tahkimatın yapımı (Dalgakıran ve deniz tahkimatı gibi inşaatta)','m3',358.99,null,null),
('KGM/34.010/1-K','Kazı taşından (6 -15 ton kategorideki) taşlar ile tahkimatın yapımı (Dalgakıran ve deniz tahkimatı gibi inşaatta)','ton',199.44,null,null),
('KGM/34.011/K','Ocak taşından (15 tondan yukarı kategorideki) taşlar ile tahkimatın yapımı (Dalgakıran ve deniz tahkimatı gibi inşaatta)','m3',1004.42,null,null),
('KGM/34.011/K','Ocak taşından (15 tondan yukarı kategorideki) taşlar ile tahkimatın yapımı (Dalgakıran ve deniz tahkimatı gibi inşaatta)','ton',558.01,null,null),
('KGM/34.011/1-K','Kazı taşından (15 tondan yukarı kategorideki) taşlar ile tahkimatın yapımı (Dalgakıran ve deniz tahkimatı gibi inşaatta)','m3',496.71,null,null),
('KGM/34.011/1-K','Kazı taşından (15 tondan yukarı kategorideki) taşlar ile tahkimatın yapımı (Dalgakıran ve deniz tahkimatı gibi inşaatta)','ton',275.95,null,null),
('KGM/34.012/K','Ocak artığı ile dolgu yapılması','m3',90.75,null,null),
('KGM/34.012/1-K','Ocak artığının ocakta depo edilmesi','m3',80.0,null,null),
('KGM/34.113/K','Ocakta kalan kategori fazlası taş','m3',174.3,null,null),
('KGM/34.113/K','Ocakta kalan kategori fazlası taş','ton',96.83,null,null),
('KGM/37.001/K','Traktörle toprağın 20 - 25 cm. derinlikte sürülmesi',null,679.8,null,null),
('KGM/37.006','Çim saha tanziminde toprağın el ile tırmıklanması',null,435.63,null,null),
('KGM/37.006/K','Yolların yarma ve dolgu şevleri ile orta refüjlerde yapılan çim saha tanziminde toprağın el ile tırmıklanması','m2',10.31,null,null),
('KGM/37.007','Yumuşak toprakların 20 - 25 cm. derinlikte bellenmesi',null,896.88,null,null),
('KGM/37.007/K','Yolların orta refüjlerinde çim saha hazırlamak için yumuşak toprakların 20 - 25 cm. derinlikte bellenmesi','m2',17.91,null,null),
('KGM/37.008','Sert toprakların 20 - 25 cm. derinlikte bellenmesi',null,1793.75,null,null),
('KGM/37.008/K','Yolların orta refüjlerinde çim saha hazırlamak için sert toprakların 20 - 25 cm. derinlikte bellenmesi','m2',33.25,null,null),
('KGM/37.009/K','Toprağın çapalanması ve satıhların el ile düzeltilmesi',null,768.75,null,null),
('KGM/37.009/K-1','Yolların yarma ve dolgu şevleri ile orta refüjlerde toprağın çapalanması ve satıhların el ile düzeltilmesi','m2',15.63,null,null),
('KGM/37.010/K-1','Fidan diplerinin 30 cm. çapında çapalanması','adet',15.38,null,null),
('KGM/37.010/K-2','Fidan diplerinin 80 cm. çapında çapalanması','adet',38.44,null,null),
('KGM/37.010/K-5','Yolların yarma ve dolgu şevleri ile orta refüjlerde fidan diplerinin 50 cm. çapında çapalanması','adet',31.25,null,null),
('KGM/37.010/K-6','Yolların yarma ve dolgu şevleri ile orta refüjlerde fidan diplerinin 80 cm. çapında çapalanması','adet',62.5,null,null),
('KGM/37.012/K','Yumuşak topraklarda 30 cm. çapında 30 cm. derinliğinde el ile fidan çukurunun açılması','adet',35.88,null,null),
('KGM/37.012/K-1','Yolların yarma ve dolgu şevleri ile orta refüjlerde yumuşak topraklarda 30 cm. çapında 30 cm. derinliğinde el ile fidan çukurunun açılması','adet',46.88,null,null),
('KGM/37.014/K','Yumuşak topraklarda 40 cm. çapında 50 cm. derinliğinde el ile fidan çukurunun açılması','adet',61.5,null,null),
('KGM/37.014/K-1','Yolların yarma ve dolgu şevleri ile orta refüjlerde yumuşak topraklarda 40 cm. çapında 50 cm. derinliğinde el ile fidan çukurunun açılması','adet',125.0,null,null),
('KGM/37.016/K','Yumuşak topraklarda 60 cm. çapında 80 cm. derinliğinde el ile fidan çukurunun açılması','adet',125.0,null,null),
('KGM/37.018/K','Sert ve çakıllı topraklarda 30 cm. çapında 30 cm. derinliğinde el ile fidan çukurunun açılması','adet',46.13,null,null),
('KGM/37.018/K-1','Yolların yarma ve dolgu şevleri ile orta refüjlerde sert ve çakıllı topraklarda 30 cm. çapında 30 cm. derinliğinde el ile fidan çukurunun açılması','adet',78.13,null,null),
('KGM/37.020/K','Sert ve çakıllı topraklarda 40 cm. çapında 50 cm. derinliğinde el ile fidan çukurunun açılması','adet',79.44,null,null),
('KGM/37.020/K-1','Yolların yarma ve dolgu şevleri ile orta refüjlerde sert ve çakıllı topraklarda 40 cm. çapında 50 cm. derinliğinde el ile fidan çukurunun açılması','adet',187.5,null,null),
('KGM/37.022','Sert ve çakıllı topraklarda 60 cm. çapında 80 cm. derinliğinde el ile fidan çukurunun açılması','adet',187.5,null,null),
('KGM/37.026','Yumuşak topraklarda teras açılması','m3',384.38,null,null),
('KGM/37.026/K','Yolların yarma ve dolgu şevlerinde yumuşak topraklarda teras açılması','m3',1442.19,null,null),
('KGM/37.027','Sert ve taşlı topraklarda teras açılması','m3',576.56,null,null),
('KGM/37.027/K','Yolların yarma ve dolgu şevlerinde sert ve taşlı topraklarda teras açılması','m3',2105.63,null,null),
('KGM/37.030','Çim ve çiçeklik sahaların tanzimi',null,4725.0,null,null),
('KGM/37.035/K','30 cm. çap ve 30 cm. derinlikteki çukurlara ibreli küçük fidanların topraksız dikimi','adet',5.14,null,null),
('KGM/37.035/K-1','Yolların yarma ve dolgu şevleri ile orta refüjlerde 30 cm. çap ve 30 cm. derinlikteki çukurlara ibreli küçük fidanların topraksız dikimi','adet',32.69,null,null),
('KGM/37.040/K','40 cm. çap ve 50 cm. derinlikteki çukurlara ibreli büyük fidanlarla yapraklı fidanların topraklı dikimi','adet',38.44,null,null),
('KGM/37.040/K-1','Yolların yarma ve dolgu şevleri ile orta refüjlerde 40 cm. çap ve 50 cm. derinlikteki çukurlara ibreli ve yapraklı fidanların topraklı dikimi','adet',120.31,null,null),
('KGM/37.040/K-2','60 cm. çap ve 80 cm. derinlikteki çukurlara ibreli ve yapraklı fidanların kaplı dikimi','adet',126.56,null,null),
('KGM/37.043/K','30 cm. çap ve 30 cm. derinlikteki çukurlara sarılıcı ve örtücü fidanların dikimi','adet',9.49,null,null),
('KGM/37.045/K','40 cm. çap ve 50 cm. derinlikteki çukurlara yapraklı fidanların ve çalıların topraksız dikimi','adet',30.75,null,null),
('KGM/37.045/K-1','Yolların yarma ve dolgu şevleri ile orta refüjlerde 40 cm. çap ve 50 cm. derinlikteki çukurlara yapraklı fidanların ve çalıların topraksız dikimi','adet',87.5,null,null),
('KGM/37.049','Çit nebatlarının topraksız dikimi',null,100717.5,null,null),
('KGM/37.072','Park sahalarının hortumla sulanması',null,102.5,null,null),
('KGM/37.081/K','Yapraklı ağaçların yan dallarının budanması ve tepe tacının yapılması','adet',283.44,null,null),
('KGM/37.088','Çim ve çiçeklik sahalarda yabani otların temizlenmesi',null,156.25,null,null),
('KGM/37.088/K','Yolların yarma ve dolgu şevleri ile orta refüjlerde yabani otların temizlenmesi',null,3125.0,null,null),
('KGM/37.089','Makasla çim ve çayır biçme','m2',15.63,null,null),
('KGM/37.089/K','Yolların otokorkuluk orta refüjlerinde makasla çim ve çayırların biçilmesi','m2',19.75,null,null),
('KGM/37.090','Tırpanla çim ve çayır biçme',null,156.25,null,null),
('KGM/37.090/K-1','Yolların yarma ve dolgu şevleri ile orta refüjlerde tırpanla çim ve çayır biçme',null,6693.75,null,null),
('KGM/37.091/K','Yolların yarma ve dolgu şevleri ile orta refüjlerde makine ile çim biçme',null,2571.73,null,null),
('KGM/37.092/1','Toprağın gübrelenmesi','ton',1153.13,null,null),
('KGM/37.092/1-K','Yolların yarma ve dolgu şevleri ile orta refüjlerinde toprağın gübrelenmesi','ton',2003.13,null,null),
('KGM/37.094/K','Çim veya çayır kesekleri ile kaplama','m2',512.5,null,null),
('KGM/37.094/K-1','Yolların yarma ve dolgu şevleri ile orta refüjlerde çim ve çayır kesekleri ile kaplama yapılması','m2',617.5,null,null),
('KGM/37.097','Erozyon önleme tahtası veya örgü çiti, canlı (Vejatatif) çitler ile şev tahkimatı','m',198.13,null,null),
('KGM/37.556/K','Çim tohumu ekme (İngiliz çimi)',null,12907.49,null,null),
('KGM/37.556/K-1','Yolların yarma ve dolgu şevleri ile orta refüjlerinde çim saha teşkili (İngiliz çimi)',null,48946.76,null,null),
('KGM/40.130','Asfalt kazıma makinesi ile her cins bitümlü karışım kaplamaların kazılması','m3',1369.09,null,null),
('KGM/50.127/A','Beton yol korkuluğu kalıbı yapılması (Çelik)','m2',4349.19,null,null),
('KGM/50.128','Beton yol korkuluğu yapılması (A Tipi)','m',3299.89,null,null),
('KGM/50.129','Beton yol korkuluğu yapılması (B Tipi)','m',3486.36,null,null),
('KGM/50.130','Beton yol korkuluğu son elemanı yapılması (A Tipi)','adet',6599.78,null,null),
('KGM/50.131','Beton yol korkuluğu son elemanı yapılması (B Tipi)','adet',6972.72,null,null),
('KGM/50.132','A tipi beton yol korkuluğu ve son elemanın yerine konulması','m',1016.61,null,null),
('KGM/50.133','B tipi beton yol korkuluğu ve son elemanın yerine konulması','m',1024.06,null,null),
('KGM/51.100/B-1','Prefabrik betonarme kar siperi imali (3 Boşluklu plak + 1 Dikme = 1 ANO)',null,2441.48,null,null),
('KGM/51.100/B-2','Prefabrik betonarme kar siperi imali (2 Boşluklu plak + 1 Dikme = 1 ANO)',null,1649.91,null,null),
('KGM/51.101/B-1','Prefabrik betonarme kar siperlerinin montajı (3 Boşluklu plak + 1 Dikme = 1 ANO)',null,858.5,null,null),
('KGM/51.101/B-2','Prefabrik betonarme kar siperlerinin montajı (2 Boşluklu plak + 1 Dikme = 1 ANO)',null,568.5,null,null),
('KGM/51.102/B','Prefabrik dik çit direği imali','adet',340.36,null,null),
('KGM/51.103/B','Prefabrik eğik çit direği imali','adet',422.46,null,null),
('KGM/51.104/B','Beton çit direğinin yerleştirilmesi','adet',575.68,null,null),
('KGM/51.105/B','Galvanizli borudan düz çit direği imali ve montajı','adet',1430.74,null,null),
('KGM/51.106/B','Galvanizli kafes telden çit yapılması','m2',347.31,null,null),
('KGM/51.107/B','1,5 X 2 m ebatlarında galvanizli kafes tel çit pano ve 2,5 m boyunda kare profilden düz çit direği imali (1 Pano + 1 Direk = 1 ANO)',null,2764.91,null,null),
('KGM/51.108/B','1,5 X 2 m ebatlarında galvanizli kafes tel çit pano ve 2,5 m boyunda kare profilden düz çit direği montajı(1 Pano + 1 Direk = 1 ANO)',null,329.53,null,null),
('KGM/52.001/K','Her kalınlıkta ve kesitte polikarbon levha ile konstrüksiyon üzeri kaplama yapılması','m2',307.23,null,null),
('KGM/52.011/K','Gabion tel kafes ile taş tahkimat yapılması (Her ebatta)','m3',1497.49,null,null),
('KGM/52.021/K','Çelik ağlarla şev koruma yapılması','m2',602.41,null,null),
('KGM/52.022/K','Çelik ağlarla yapılan şev koruması için tepe ankrajı tesis edilmesi','adet',664.53,null,null),
('KGM/52.023/K','Çelik ağlarla yapılan şev koruması için topuk ve yüzey ankrajı tesis edilmesi','adet',607.23,null,null),
('KGM/60.004','Standart trafik işaret levhası ve direğinin bakımının yapılması','adet',173.48,null,null),
('KGM/60.005','Trafik bilgi işaret levhası bakımının yapılması','adet',483.65,null,null),
('KGM/60.006','Yol bakım ve onarımlarında geçici trafik işaretlemesi için malzeme temini, işaretleme yapılması ve emniyet tedbirlerinin alınması','gün',11233.58,null,null),
('KGM/60.007','Yol bakım ve onarımlarının trafik emniyetinin sinyalizasyon tertibatı ile sağlanması','gün',8864.89,null,null),
('KGM/60.010','3 mm. kalınlığındaki alüminyum malzemeden 90 cm. kenarlı eşkenar üçgen levha yapılması','adet',3674.83,null,null),
('KGM/60.011','3 mm. kalınlığındaki alüminyum malzemeden 135 cm. kenarlı eşkenar üçgen levha yapılması','adet',6239.64,null,null),
('KGM/60.012','3 mm. kalınlığındaki alüminyum malzemeden 60 cm çaplı yuvarlak levha yapılması','adet',2835.66,null,null),
('KGM/60.013','3 mm. kalınlığındaki alüminyum malzemeden 90 cm çaplı yuvarlak levha yapılması',null,null,null,null),
('KGM/60.014','3 mm. kalınlığındaki alüminyum malzemeden 75 cm.lik sekizgen levha yapılması (Anahtar ağzı olan sekizgen)',null,null,null,null),
('KGM/60.015','3 mm. kalınlığındaki alüminyum malzemeden 90 cm.lik sekizgen levha yapılması (Anahtar ağzı olan sekizgen)',null,null,null,null),
('KGM/60.016','3 mm. kalınlığındaki alüminyum malzemeden muhtelif ebatlarda dörtgen levha yapılması','m2',5744.56,null,null),
('KGM/60.017','3 mm. kalınlığındaki alüminyum malzemeden tehlikeli viraj yön levhası yapılması T- 33 b (60 X 180 cm.) levhası','adet',9195.23,null,null),
('KGM/60.018','3 mm. kalınlığındaki alüminyum malzemeden tehlikeli viraj yön levhası yapılması T- 33 c (50 X 150 cm.) levhası','adet',7858.5,null,null),
('KGM/60.019','3 mm. kalınlığındaki alüminyum malzemeden engel levhası yapılması','adet',6453.59,null,null),
('KGM/60.020','Alüminyum profilden bilgi levhası yapılması (2,5 m2 ve 2,5 m2 den küçük)','m2',7783.63,null,null),
('KGM/60.021','Alüminyum profilden bilgi levhası yapılması (2,5 m2 den büyük)','m2',7511.04,null,null),
('KGM/60.022','2 mm. kalınlığındaki galvanizli sacdan 90 cm. kenarlı eşkenar üçgen levha yapılması','adet',1064.31,null,null),
('KGM/60.023','2 mm. kalınlığındaki galvanizli sacdan 135 cm. kenarlı eşkenar üçgen levha yapılması','adet',2374.65,null,null),
('KGM/60.024','1,5 mm. kalınlığındaki galvanizli sacdan 90 cm. kenarlı eşkenar üçgen levha yapılması','adet',943.69,null,null),
('KGM/60.025','2 mm. kalınlığındaki galvanizli sacdan 60 cm. çaplı yuvarlak levha yapılması','adet',1047.53,null,null),
('KGM/60.026','2 mm. kalınlığındaki galvanizli sacdan 90 cm. çaplı yuvarlak levha yapılması','adet',1808.7,null,null),
('KGM/60.027','1,5 mm. kalınlığındaki galvanizli sacdan 60 cm. çaplı yuvarlak levha yapılması','adet',957.48,null,null),
('KGM/60.028','2 mm. kalınlığındaki galvanizli sacdan 75 cm. lik sekizgen levha yapılması (Anahtar ağzı olan sekizgen)','adet',1302.73,null,null),
('KGM/60.029/A','2 mm. kalınlığındaki galvanizli sacdan 90 cm. lik sekizgen levha yapılması (Anahtar ağzı olan sekizgen)','adet',1787.45,null,null),
('KGM/60.030','1,5 mm. kalınlığındaki galvanizli sacdan 75 cm. lik sekizgen levha yapılması (Anahtar ağzı olan sekizgen)','adet',1170.95,null,null),
('KGM/60.031','2 mm. kalınlığındaki galvanizli sacdan muhtelif ebatlarda dörtgen levha yapılması','m2',2582.64,null,null),
('KGM/60.032','1,5 mm. kalınlığındaki galvanizli sacdan muhtelif ebatlarda dörtgen levha yapılması','m2',2315.35,null,null),
('KGM/60.033','2 mm. kalınlığındaki galvanizli sacdan tehlikeli viraj yön levhası yapılması T - 33 b (60 x 180 cm.) levhası','adet',3521.99,null,null),
('KGM/60.034','2 mm. kalınlığındaki galvanizli sacdan tehlikeli viraj yön levhası yapılması T - 33 c (50 x 150 cm.) levhası','adet',2622.35,null,null),
('KGM/60.035','2 mm. kalınlığındaki galvanizli sacdan engel levhası yapılması','adet',1638.76,null,null),
('KGM/60.036','Galvanizli sacdan trafik bilgi levhası yapılması (2,5 m2 ve 2,5 m2 den küçük)','m2',4754.66,null,null),
('KGM/60.037','Galvanizli sac profilden trafik bilgi levhası yapılması(1,5 mm. Kalınlığında)','m2',4610.26,null,null),
('KGM/60.038','Galvanizli sac profilden trafik bilgi levhası yapılması(2 mm. Kalınlığında)','m2',5127.65,null,null),
('KGM/60.039','1,5 mm. kalınlığındaki siyah sacdan (DKP) kaplama sınırlayıcı levha yapılması','adet',290.35,null,null),
('KGM/60.040','Kaplama sınırlayıcı levhanın boyanması ve sembol yapılması','adet',70.28,null,null),
('KGM/60.041','1,5 mm. kalınlığındaki siyah sacdan (DKP) kaplama sınırlayıcı levha yapılması ve galvaniz kaplanması','adet',489.85,null,null),
('KGM/60.042','Trafik işaret levhası direği yapılması ve galvanizlenmesi (5 mm. kalınlığında, 170 mm. açılımında)','m',1463.51,null,null),
('KGM/60.042/A','Trafik işaret levhası direği yapılması ve galvanizlenmesi (4 mm. kalınlığında, 149 mm. açılımında)','m',1090.89,null,null),
('KGM/60.043','Trafik bilgi ve yön levhaları için direk yapılması ve boyanması (Muhtelif ebat NPI profil demir)','kg',140.31,null,null),
('KGM/60.044','Trafik bilgi ve yön levhaları için direk yapılması ve galvaniz kaplanması (Muhtelif ebat NPI profilden)','kg',181.9,null,null),
('KGM/60.045','Trafik bilgi ve yön levhaları için direk yapılması ve galvaniz kaplanması (Muhtelif ebat NPI profilden ankrajlı tip)','kg',216.5,null,null),
('KGM/60.046','Kaplama üstü levha taşıyıcı konstrüksiyonu imali ve galvaniz kaplanması','kg',197.54,null,null),
('KGM/60.047','Trafik işaret levhalarına sembol, bordür ve yazı yazılması (Standart ve bilgi trafik işaret levhaları)','m2',306.31,null,null),
('KGM/60.048','Levhaya tam reflektif malzeme yapıştırılması (Standart ve bilgi işaret levhaları)','m2',1645.71,null,null),
('KGM/60.049','Levhaya standart hazır retroreflektif trafik işaretinin yapıştırılması','adet',319.55,null,null),
('KGM/60.050','Levhaya tek kat reflektif malzeme yapıştırılması (Standart ve bilgi işaret levhaları)','m2',882.33,null,null),
('KGM/60.051','Levhaya vinil (Folyo) malzeme ile yazı ve sembol yapılması (Standart ve bilgi işaret levhaları)','m2',675.0,null,null),
('KGM/60.052','Standart trafik işaret levha direğinin yerine konulması (Tehlike uyarı, trafik tanzim, bilgi, durma ve park levhaları)','adet',806.46,null,null),
('KGM/60.053','Kaplama sınırlayıcı levhasının yerine konulması','adet',32.53,null,null),
('KGM/60.054','Trafik bilgi levhalarına temel yapımı ve levha direği montajı','adet',5636.38,null,null),
('KGM/60.055','Trafik bilgi levhalarına ankrajlı temel yapılması ve levha direğinin montajı','adet',5999.23,null,null),
('KGM/60.056','Kaplama üstü levha taşıyıcı konstrüksiyonunun komple yerine konulması','adet',116713.69,null,null),
('KGM/60.057','Standart tafik işaret levhalarının yerine konulması (Tehlike uyarı, trafik tanzim, bilgi, durma ve park levhaları)','adet',458.39,null,null),
('KGM/60.058','Trafik bilgi levhalarının yerlerine konulması','m2',1048.96,null,null),
('KGM/60.059','Kaplama üstü bilgi levhalarının yerlerine konulması','m2',2298.44,null,null),
('KGM/60.060','Standart trafik işaret levhasının yerinden sökülmesi (Tehlike uyarı, trafik tanzim, bilgi, durma ve park levhaları)','adet',304.64,null,null),
('KGM/60.061','Trafik bilgi levhalarının yerlerinden sökülmesi','m2',810.53,null,null),
('KGM/60.062','Kaplama üstü bilgi levhalarının yerlerinden sökülmesi','m2',1130.18,null,null),
('KGM/60.063','Standart levha direğinin yerinden sökülmesi','adet',806.46,null,null),
('KGM/60.064','Trafik bilgi levha direğinin yerinden sökülmesi','adet',1599.23,null,null),
('KGM/60.065','Kaplama üstü levha taşıyıcı konstrüksiyonun komple yerinden sökülmesi','adet',42915.46,null,null),
('KGM/60.070','Beton yol korkuluğu yapılması (A Tipi) (Yerinde)','m',4272.86,null,null),
('KGM/60.071','Beton yol korkuluğu yapılması (B Tipi) (Yerinde)','m',4047.59,null,null),
('KGM/60.072','Beton yol korkuluğu son elemanı yapılması (A Tipi) (Yerinde)','adet',8545.72,null,null),
('KGM/60.073','Beton yol korkuluğu son elemanı yapılması (B Tipi) (Yerinde)','adet',8095.18,null,null),
('KGM/60.100','Standart sinyal verici direği yapılması ve galvanizlenmesi','adet',7326.41,null,null),
('KGM/60.101','Baş üstü sinyal verici direği yapılması ve galvanizlenmesi','adet',18637.96,null,null),
('KGM/60.104','Kamaşma panosu yapılması ve elektrostatik toz boya ile boyanması (200 mm. çaplı sinyal verici gruplar için)','adet',2885.69,null,null),
('KGM/60.105','Kamaşma panosu yapılması ve elektrostatik toz boya ile boyanması (300 mm. çaplı sinyal verici gruplar için)','adet',3605.74,null,null),
('KGM/60.109','Kamaşma panosunun oto sinyal verici grubuna montajı (200''lük ve 300''lük oto sinyal verici gruplarına)','adet',1212.14,null,null),
('KGM/60.110','Sinyal verici grubu veya sinyal vericinin standart veya baş üstü direğinden sökülmesi (200 mm. veya 300 mm. çaplı sinyal verici grubu veya sinyal verici için)','grup',3409.8,null,null),
('KGM/60.111','Standart sinyal verici direğin yerine konulması (Temel dahil)','adet',2137.68,null,null),
('KGM/60.112','Standart sinyal verici direğin yerinden sökülmesi','adet',1118.46,null,null),
('KGM/60.113','Baş üstü sinyal verici direğin yerine konulması (Temel dahil)','adet',3519.2,null,null),
('KGM/60.114','Baş üstü sinyal verici direğin yerinden sökülmesi','adet',1950.38,null,null),
('KGM/60.115','200 mm. çaplı sinyal verici ile 300 mm. çaplı sinyal vericinin standart direğine montajı','adet',1225.89,null,null),
('KGM/60.116','300 mm. çaplı sinyal vericinin baş üstü direğine montajı','adet',1654.5,null,null),
('KGM/60.117','200 mm. çaplı sinyal verici ile 300 mm. çaplı sinyal verici grubun standart direğine montajı','grup',1520.53,null,null),
('KGM/60.118','300 mm. çaplı sinyal verici grubun baş üstü direğine montajı','grup',1752.34,null,null),
('KGM/60.119','200 mm. veya 300 mm. çaplı sinyal verici grubu ile 200 mm. veya 300 mm. çaplı sinyal vericinin kaplama üstü konstrüksiyona montajı','grup',6796.18,null,null),
('KGM/60.120','Sinyal verici grubu veya sinyal vericinin kaplama üstü konstrüksiyonundan sökülmesi (200 mm. veya 300 mm. çaplı sinyal verici grubu veya sinyal verici için)','grup',6411.56,null,null),
('KGM/60.121','Kavşak kontrol cihazının yerine konulması (Temel dahil)','adet',3002.79,null,null),
('KGM/60.122','Yol altından kablo geçişi','m',481.0,null,null),
('KGM/60.123','Orta refüj ve kaldırım altından kablo geçişi','m',195.79,null,null),
('KGM/60.200','Soğuk yol çizgi boyası ile yol çizgilerinin çizilmesi (Makine ile)','m2',312.74,null,null),
('KGM/60.201','Yatay işaretlemenin silinmesi','m2',312.75,null,null),
('KGM/60.202','Termoplastik boya ile püskürtme (Sprey) yöntemiyle yol çizgilerinin çizilmesi (Makine ile) (1.5 mm. kalınlığında)','m2',376.91,null,null),
('KGM/60.203','Termoplastik boya ile püskürtme (Sprey) yöntemiyle yol çizgilerinin çizilmesi (Makine ile) (2 mm. kalınlığında)','m2',458.3,null,null),
('KGM/60.204','Termoplastik boya ile püskürtme (Sprey) yöntemiyle yol çizgilerinin çizilmesi (Makine ile) (1 mm. kalınlığında)','m2',246.36,null,null),
('KGM/60.205','Soğuk yol çizgi boyası ile yaya geçitleri ve yavaşlama uyarı çizgilerinin çizilmesi','m2',656.26,null,null),
('KGM/60.206','Çift kompenantlı boya ile yaya geçitleri, yavaşlama uyarı ve şerit çizgilerinin çizilmesi (2 mm. kalınlığında)','m2',1427.73,null,null),
('KGM/60.207','Çift kompenantlı boya ile yaya geçitleri, yavaşlama uyarı ve şerit çizgilerinin çizilmesi (3 mm. kalınlığında)','m2',1772.73,null,null),
('KGM/60.208','Termoplastik boya ile serme yöntemiyle yaya geçitleri, yavaşlama uyarı ve şerit çizgilerinin çizilmesi (3 mm. kalınlığında)','m2',1460.39,null,null),
('KGM/60.209','Termoplastik boya ile serme yöntemiyle yaya geçitleri, yavaşlama uyarı ve şerit çizgilerinin çizilmesi (2 mm. kalınlığında)','m2',1260.78,null,null),
('KGM/60.210','Soğuk yol çizgi boyası ile ofset taraması çizilmesi','m2',692.61,null,null),
('KGM/60.211','Çift kompenantlı boya ile ofset taraması çizilmesi (2 mm. kalınlığında)','m2',1071.5,null,null),
('KGM/60.212','Çift kompenantlı boya ile ofset taraması çizilmesi (3 mm. kalınlığında)','m2',1221.5,null,null),
('KGM/60.213','Termoplastik boya ile serme yöntemiyle ofset taraması çizilmesi (3 mm. kalınlığında)','m2',1146.09,null,null),
('KGM/60.214','Termoplastik boya ile serme yöntemiyle ofset taraması çizilmesi (2 mm. kalınlığında)','m2',1057.66,null,null),
('KGM/60.215','Soğuk yol çizgi boyası ile seyrek refüj taramaları çizilmesi','m2',434.96,null,null),
('KGM/60.216','Çift kompenantlı boya ile seyrek refüj taramaları çizilmesi (2 mm. kalınlığında)','m2',760.76,null,null),
('KGM/60.217','Çift kompenantlı boya ile seyrek refüj taramaları çizilmesi (3 mm. kalınlığında)','m2',873.26,null,null),
('KGM/60.218','Termoplastik boya ile serme yöntemiyle seyrek refüj taramaları çizilmesi (3 mm. kalınlığında)','m2',847.33,null,null),
('KGM/60.219','Termoplastik boya ile serme yöntemiyle seyrek refüj taramaları çizilmesi (2 mm. kalınlığında)','m2',784.3,null,null),
('KGM/60.220','Soğuk yol çizgi boyası ile standart ok ve yazıların çizilmesi','adet',1740.38,null,null),
('KGM/60.221','Çift kompenantlı boya ile standart ok ve yazıların çizilmesi (2 mm. kalınlığında)','adet',3292.85,null,null),
('KGM/60.222','Çift kompenantlı boya ile standart ok ve yazıların çizilmesi (3 mm. kalınlığında)','adet',4294.25,null,null),
('KGM/60.223','Termoplastik boya ile serme yöntemiyle standart ok ve yazıların çizilmesi (3 mm. kalınlığında)','adet',3479.46,null,null),
('KGM/60.224','Termoplastik boya ile serme yöntemiyle standart ok ve yazıların çizilmesi (2 mm. kalınlığında)','adet',3019.84,null,null),
('KGM/60.225','Soğuk yol çizgi boyası ile standart çift ok çizilmesi','adet',2253.44,null,null),
('KGM/60.226','Çift kompenantlı boya ile standart çift ok çizilmesi (2 mm. kalınlığında)','adet',3883.41,null,null),
('KGM/60.227','Çift kompenantlı boya ile standart çift ok çizilmesi (3 mm. kalınlığında)','adet',4941.44,null,null),
('KGM/60.228','Termoplastik boya ile serme yöntemiyle standart çift ok çizilmesi (3 mm. kalınlığında)','adet',4018.43,null,null),
('KGM/60.229','Termoplastik boya ile serme yöntemiyle standart çift ok çizilmesi (2 mm. kalınlığında)','adet',3547.43,null,null),
('KGM/60.230','Malzeme idareden soğuk yol çizgi boyası ile yol çizgilerinin çizilmesi (Makine','m2',56.94,null,null),
('KGM/60.231','Malzeme idareden soğuk yol çizgi boyası ile yaya geçitleri ve yavaşlama uyarı çizgilerinin çizilmesi','m2',526.85,null,null),
('KGM/60.232','Malzeme idareden soğuk yol çizgi boyası ile ofset taraması çizelmesi','m2',643.18,null,null),
('KGM/60.233','Malzeme idareden soğuk yol çizgi boyası ile seyrek refüj taramaları çizelmesi','m2',410.51,null,null),
('KGM/60.234','Malzeme idareden soğuk yol çizgi boyası ile standart ok ve yazıların çizelmesi','adet',1452.19,null,null),
('KGM/60.235','Malzeme idareden soğuk yol çizgi boyası ile standart çift ok çizilmesi','adet',1936.25,null,null),
('KGM/70.001','120 HP gücünde 7 tonluk damperli kamyon ile bakım işleri yapılması','gün',34336.13,null,null),
('KGM/70.002','45 HP gücünde lastik tekerlekli, damperli kasası olan traktör ile bakım işleri','gün',28785.26,null,null),
('KGM/70.003','Kış programında kar ve buzla mücadele amacıyla kamyon çalıştırılması (Ataşman ve malzeme idareden)','sa',1942.45,null,null),
('KGM/70.004','Makine ile her kesit ve genişlikte hidrolik yapıların giriş ve çıkışında dere yataklarının düzenlenmesi','m3',324.19,null,null),
('KGM/70.005','El ile her kesit ve genişlikte hidrolik yapıların giriş ve çıkışında dere yataklarının düzenlenmesi','m3',384.38,null,null),
('KGM/70.006','Stabilize yollarda reglaj, sulama ve sıkıştırma','km',28216.33,null,null),
('KGM/70.007','El ile kurada veya suda 3 m2 den daha büyük kesitteki kutu veya kemer menfez ile her türlü büz ve mecra kanallarının içindeki batak, balçık ve alüvyon vs. birikinti malzemesinin temizlenmesi','m3',3075.0,null,null),
('KGM/70.008','El ile kuruda veya suda 1 m2 ile 3 m2 arası kesitteki (1 m2 hariç, 3 m2 dahil) kutu veya kemer menfez ile her türlü büz ve mecra kanallarının içindeki batak, balçık ve alüvyon vs. birikinti malzemesinin temizlenmesi','m3',3715.63,null,null),
('KGM/70.009','El ile kuruda veya suda 1 m2 ve daha küçük kesitteki kutu veya kemer menfez ile her türlü büz ve mecra kanallarının içindeki batak, balçık ve alüvyon vs. birikinti malzemesinin temizlenmesi','m3',4740.63,null,null),
('KGM/70.010','El ile kuruda veya suda her türlü rogar içindeki batak, balçık ve alüvyon vs. birikinti malzemesinin temizlenmesi','m3',1153.13,null,null),
('KGM/70.011','Her kesit ve genişlikte beton kaplamalı kenar, refüj ve kafa hendeklerinin temizliği','m3',249.05,null,null),
('KGM/70.012','Her kesit ve genişlikte taş kaplamalı kenar, refüj ve kafa hendeklerinin temizliği','m3',313.11,null,null),
('KGM/70.013','Her kesit ve genişlikte kuruda veya suda kaplamasız kafa hendeklerinin temizliği','m3',313.11,null,null),
('KGM/70.014','El ile her kesit ve genişlikte kuruda veya suda kaplamasız kenar ve refüj hendeklerinin temizliği','km',29356.45,null,null),
('KGM/70.015','Makine ile her kesit ve genişlikte kuruda veya suda kaplamasız kenar ve refüj hendeklerinin temizliği','km',17791.33,null,null),
('KGM/70.016','Tretuvarsız bordür diplerinin temizliği','m',73.63,null,null),
('KGM/70.017','Tretuvarlı bordür diplerinin ve tretuvarların temizliği','km',86.71,null,null),
('KGM/70.018','Asfalt yol yüzeyine dökülen petrol türevi sıvı maddelerin temizlenmesi','m2',200.8,null,null),
('KGM/70.019','Asfalt yol yüzeyine dökülen petrol türevi olmayan sıvı maddelerin temizlenmesi','m2',103.1,null,null),
('KGM/70.020','Yol yüzeyindeki kayganlığın giderilmesi için kum serpilmesi ve süpürülmesi','m2',85.69,null,null),
('KGM/70.021','Park alanları ve yol boyu kamulaştırma alanlarının temizlenmesi',null,249.28,null,null),
('KGM/70.022','Tünellerde buz sarkıtlarının temizlenmesi','m2',84.8,null,null),
('KGM/70.023','Tünel iç yüzeyinin yıkanması','m2',82.21,null,null),
('KGM/70.024','Her cins ve ebattaki devrilmiş ağaçların kesilerek yoldan uzaklaştırılması','adet',297.94,null,null),
('KGM/70.025','Drenaj bacasının kontrolü ve temizliği','adet',89.64,null,null),
('KGM/70.026','Drenaj borularının temizliği','ton',230.35,null,null),
('KGM/70.027','CTP (Cam elyaf takviyeli polyester) yol kenar dikmesinin yıkanması','adet',97.21,null,null),
('KGM/70.028','CTP (Cam elyaf takviyeli polyester) yol kenar dikmesine reflektör yapıştırılması (Reflektör idareden)','adet',47.48,null,null),
('KGM/70.029','Yolun iki tarafındaki kaplamasız banketlerin bakımı Not:Yolun tek tarafındaki kaplamasız banketin bakımının yapılması halinde birim fiyatın yarısı ödenir.','km',24006.69,null,null),
('KGM/70.030','Sathi kaplamalı yollarda asfalt yaması yapılması işçiliği (Rodmiks malzemesi, astar bitümlü malzeme ve distribütör idareden)','m3',7064.34,null,null),
('KGM/70.031','Sıcak karışım kaplamalı yollarda asfalt yaması yapılması işçiliği (Sıcak karışım malzemesi, yapıştırıcı bitüm malzemesi ve distrübütör idareden)','m3',9430.69,null,null),
('KGM/70.032','Asfalt yaması üzerine sathi kaplama yaması yapılması işçiliği (Yapıştırıcı bitümlü malzeme, agrega, distribütör idareden)','m2',150.99,null,null),
('KGM/70.033','Beton asfalt kaplamalı yollarda bitümlü yama altlarına stabilize temel yapılması işçiliği (Stabilize temel malzemesi idareden)','m3',6149.64,null,null),
('KGM/70.034','Beton asfalt kaplamalı yollarda bitümlü yama altlarına alt temel yapılması işçiliği (Alttemel malzemesi idareden)','m3',6405.89,null,null),
('KGM/70.035','Sathi kaplamalı yollarda bitümlü yama altlarına stabilize temel yapılması işçiliği (Stabilize temel malzemesi idareden)','m3',5124.64,null,null),
('KGM/70.036','Sathi kaplamalı yollarda bitümlü yama altlarına alt temel yapılması işçiliği (Alt temel malzemesi idareden)','m3',5380.89,null,null),
('KGM/70.037','Prefabrik betonarme kar siperlerinin bakımı','m',106.88,null,null),
('KGM/70.038','Prefabrik betonarme kar siperlerinin sökülmesi','m',160.31,null,null),
('KGM/70.039','Taş kaplamalı kafa hendeklerinin onarımı','m2',1586.78,null,null),
('KGM/70.040','Beton kaplamalı kafa hendeklerinin onarımı','m2',1246.53,null,null),
('KGM/70.041','Taş kaplamalı kenar ve refüj hendeklerinin onarımı','m2',1464.74,null,null),
('KGM/70.042','Beton kaplamalı kenar ve refüj hendeklerinin onarımı','m2',1166.68,null,null),
('KGM/70.043','Ocak taşı ile İksa ve istinat duvarı onarımı','m3',3884.53,null,null),
('KGM/70.044','Kazı taşı ile iksa ve istinat duvarı onarımı','m3',3580.28,null,null),
('KGM/70.045','İksa duvarı temizliği','m2',94.19,null,null),
('KGM/70.046','İksa duvarı boyanması','m2',103.1,null,null),
('KGM/70.047','Sınır taşı boyanması','adet',113.16,null,null),
('KGM/70.048','İdare malı kar direklerinin dikilmesi','adet',264.64,null,null),
('KGM/70.049','2" çapında kar direklerinin boyanması ve idare malı reflektif malzemenin yapıştırılması','adet',294.38,null,null),
('KGM/70.050','2 1/2" çapında kar direklerinin boyanması ve idare malı reflektif malzemenin yapıştırılması','adet',364.1,null,null),
('KGM/70.051','Kar direklerinin sökülmesi','adet',51.25,null,null),
('KGM/70.052','Her çeşit kafes tipi tel çitin sökülmesi','m2',134.06,null,null),
('KGM/70.053','Her çeşit kafes tipi telçit direğinin sökülmesi','adet',108.44,null,null),
('KGM/70.054','Galvanizli dikenli tel temini ve beton çit direkleri arasına gerilerek bağlanması','m',62.69,null,null),
('KGM/2024-HR','Tünel nihai beton kaplamasının yapılması m3 (C 30/37 Hazır beton harcı ile)',null,6016.41,null,null),
('KGM/16.070/HR','Köprülerde veya heyelanlı bölgelerde Ø 60 cm. çapında her boyda yerinde dökme kazık yapılması (C 30/37 Hazır beton harcı ile) m',null,3930.46,null,null),
('KGM/16.070/H-1R','Ø 60 cm. çapında her boyda yerinde dökme kazık yapılması (Köprüler ve heyelanlı bölgeler hariç) (C 30/37 Hazır beton harcı ile) m',null,3389.35,null,null),
('KGM/16.071/HR','Köprülerde veya heyelanlı bölgelerde Ø 80 cm. çapında her boyda yerinde dökme kazık yapılması (C 30/37 Hazır beton harcı ile) m',null,6899.66,null,null),
('KGM/16.071/H-1R','Ø 80 cm. çapında her boyda yerinde dökme kazık yapılması m (Köprüler ve heyelanlı bölgeler hariç) (C 30/37 Hazır beton harcı ile)',null,5952.58,null,null),
('KGM/16.072/HR','Köprülerde veya heyelanlı bölgelerde Ø 100 cm. çapında her boyda yerinde dökme kazık yapılması (C 30/37 Hazır beton harcı ile) m',null,9682.93,null,null),
('KGM/16.072/H-1R','Ø 100 cm. çapında her boyda yerinde dökme kazık yapılması (Köprüler ve heyelanlı bölgeler hariç) (C 30/37 Hazır beton harcı ile) m',null,8395.68,null,null),
('KGM/16.073/HR','Köprülerde veya heyelanlı bölgelerde Ø 120 cm. çapında her boyda yerinde dökme kazık yapılması (C 30/37 hazır beton harcı ile) m',null,12627.83,null,null),
('KGM/16.073/H-1R','Ø 120 cm. çapında her boyda yerinde dökme kazık yapılması (Köprüler ve heyelanlı bölgeler hariç) (C 30/37 Hazır beton harcı ile) m',null,10999.71,null,null),
('KGM/16.074/HR','Köprülerde veya heyelanlı bölgelerde Ø 165 cm. çapında her boyda yerinde dökme kazık yapılması (C 30/37 Hazır beton harcı ile) m',null,18098.18,null,null),
('KGM/16.074/H-1R','Ø 165 cm. çapında her boyda yerinde dökme kazık yapılması (Köprüler ve heyelanlı bölgeler hariç) (C 30/37 Hazır beton harcı ile) m',null,16177.95,null,null),
('KGM/16.080/HR','Yerinde dökme kazıkların alt uçlarına soğanbaşı yapılması m2 (C 30/37 Hazır beton harcı ile)',null,7014.48,null,null),
('KGM/16.100/K-HR','Her türlü inşaat temellerinde (Köprü temelleri hariç) kuruda veya suda her m3 dozda demirsiz beton (C20/25 hazır beton harcı ile)',null,3491.74,null,null),
('KGM/16.101/K-HR','Köprü temellerinde kuruda veya suda her dozda demirsiz beton (C20/25 hazır beton harcı ile) m3',null,3926.39,null,null),
('KGM/16.120/K-HR','Her türlü inşaatta temel dışında kuruda veya suda her dozda demirsiz m3 beton (C 30/37 Hazır beton harcı ile)',null,4191.5,null,null),
('KGM/16.122/K-HR','Hendeklerin betonla kaplanması (Orta refüj ve yarma hendeği) (C 30/37 Hazır beton harcı ile) m3',null,4223.79,null,null),
('KGM/16.130/K-HR','Her türlü inşaatta (Kirişli ve kutu menfezler, köprüler ve betonarme kazık hariç, plak ve kompozit menfezler dahil) kuruda veya suda her dozda demirli beton (C 30/37 Hazır beton harcı ile) m3',null,5735.26,null,null),
('KGM/16.131/K-HR','Kirişli menfezlerde kuruda veya suda her dozda demirli beton m3 (C 30/37 Hazır beton harcı ile)',null,7024.79,null,null),
('KGM/16.132/K-HR','Kutu menfezlerde kuruda veya suda her dozda demirli beton (C 30/37 Hazır beton harcı ile) m3',null,7884.48,null,null),
('KGM/16.133/K-HR','Köprülerde kuruda veya suda her dozda demirli beton m3 (C 30/37 Hazır beton harcı ile)',null,8378.54,null,null),
('KGM/16.135/K-HR','Plak ve kompozit köprülerin tabliyelerinde, betonarme kazıkta, kuruda veya suda her dozda demirli beton (C 30/37 Hazır beton harcı ile) m3',null,8059.04,null,null),
('KGM/16.139/K-B-HR','Baca kapağı tipi prekast elemanların imali ve yerine konulması (C 30/37 hazır beton harcı ile) (Her ebat ve kalınlıkta) m3',null,9131.11,null,null),
('KGM/16.141/K-HR','Toprakarme için prekast cephe panelleri yapılması ve yerine konulması m3 (C 30/37 hazır beton harcı ile) (Her ebat ve kalınlıkta)',null,12053.35,null,null),
('KGM/16.142/K-HR','Prekast cephe panelleri yapılması ve yerine konulması (Toprakarme hariç) (C 30/37 hazır beton harcı ile) (Her ebat ve kalınlıkta) m3',null,11706.78,null,null)
) as v(poz_no,tanim,birim,fiyat,fiyat_formul,extra)
on conflict (source_id,poz_no,coalesce(birim,'')) do nothing;