-- OGM 2026 part 3/3 (idempotent)
insert into bf_poz (source_id,poz_no,tanim,birim,fiyat,extra)
select '448f0829-51d1-4202-9cec-3a4b7fbe391b'::uuid, v.poz_no, v.tanim, v.birim, v.fiyat::numeric, v.extra::jsonb
from (values
('4402.1','Çıplak köklü fidanların repikajı (Polietilen torba veya kabın doldurulması, repikaj yapılması, taşınması, yastıklara  dizilmesi  ve sulanması) — Hacmi 1,3 litreye kadar (çapı 8,9 cm dahil) olan kaplara  repikaj','1000 Adet',5244.55,'{"ihaleli_fiyat": 6136.12}'),
('4402.2','Çıplak köklü fidanların repikajı (Polietilen torba veya kabın doldurulması, repikaj yapılması, taşınması, yastıklara  dizilmesi  ve sulanması) — Hacmi 1,4 - 4 litre arasındaki (çapı 9 - 13 cm) olan kaplara repikaj','1000 Adet',10722.47,'{"ihaleli_fiyat": 12545.28}'),
('4402.3','Çıplak köklü fidanların repikajı (Polietilen torba veya kabın doldurulması, repikaj yapılması, taşınması, yastıklara  dizilmesi  ve sulanması) — Hacmi 4,1 - 7 litre arasınaki (Çapı 13,1 - 17 cm) kaplara repikaj','1000 Adet',13547.17,'{"ihaleli_fiyat": 15850.19}'),
('4402.4','Çıplak köklü fidanların repikajı (Polietilen torba veya kabın doldurulması, repikaj yapılması, taşınması, yastıklara  dizilmesi  ve sulanması) — Hacmi 11,1 - 22 litre arasındaki (Çapı 19,1 - 25 cm) kaplara repikaj','1000 Adet',29156.51,'{"ihaleli_fiyat": 34113.11}'),
('4402.5','Çıplak köklü fidanların repikajı (Polietilen torba veya kabın doldurulması, repikaj yapılması, taşınması, yastıklara  dizilmesi  ve sulanması) — Hacmi 23 - 35 litre arasındaki (Çapı 26 - 35 cm) kaplara repikaj','1000 Adet',39578.72,'{"ihaleli_fiyat": 46307.11}'),
('4402.6','Çıplak köklü fidanların repikajı (Polietilen torba veya kabın doldurulması, repikaj yapılması, taşınması, yastıklara  dizilmesi  ve sulanması) — 36 - 50 Litre hacmindeki kaplara repikaj','100 Adet',7249.2,'{"ihaleli_fiyat": 8481.56}'),
('4402.7','Çıplak köklü fidanların repikajı (Polietilen torba veya kabın doldurulması, repikaj yapılması, taşınması, yastıklara  dizilmesi  ve sulanması) — 51 - 80 litre hacmindeki kaplara repikaj','100 Adet',11785.21,'{"ihaleli_fiyat": 13788.7}'),
('4402.8','Çıplak köklü fidanların repikajı (Polietilen torba veya kabın doldurulması, repikaj yapılması, taşınması, yastıklara  dizilmesi  ve sulanması) — 81 litre ve üzerindeki hacimli kaplarda repikaj','100 Adet',17626.71,'{"ihaleli_fiyat": 20623.25}'),
('4402.9','Çıplak köklü fidanların repikajı (Polietilen torba veya kabın doldurulması, repikaj yapılması, taşınması, yastıklara  dizilmesi  ve sulanması) — Köklenmiş çeliklerin enso veya benzeri kaplara repikajı (çeliklerin sökümü dahil)','1000 Adet',1250.91,'{"ihaleli_fiyat": 1463.56}'),
('4402.10','Çıplak köklü fidanların repikajı (Polietilen torba veya kabın doldurulması, repikaj yapılması, taşınması, yastıklara  dizilmesi  ve sulanması) — Hacmi 7,1 -11 litre arasındaki (Çapı 17,1- 19 cm) kaplara repikaj','1000 Adet',19521.32,'{"ihaleli_fiyat": 22839.94}'),
('4403.1','Torbalı veya kaplı fidanların üst boya repikajı (Polietilen torba veya kabın doldurulması,repikaj yapılması, taşınması, yastıklara dizilmesi ve sulanması) — Hacmi 1,3 litreye kadar (Çapı 8,9 cm dahil) olan kaplara  repikaj','1000 Adet',5749.41,'{"ihaleli_fiyat": 6726.81}'),
('4403.2','Torbalı veya kaplı fidanların üst boya repikajı (Polietilen torba veya kabın doldurulması,repikaj yapılması, taşınması, yastıklara dizilmesi ve sulanması) — Hacmi 1,4 - 4 litre arasındaki (Çapı 9 - 13 cm) olan kaplara repikaj','1000 Adet',11449.74,'{"ihaleli_fiyat": 13396.19}'),
('4403.3','Torbalı veya kaplı fidanların üst boya repikajı (Polietilen torba veya kabın doldurulması,repikaj yapılması, taşınması, yastıklara dizilmesi ve sulanması) — Hacmi 4,1 - 7 litre arasınaki (Çapı 13,1 - 17 cm) kaplara repikaj','1000 Adet',19526.01,'{"ihaleli_fiyat": 22845.43}'),
('4403.4','Torbalı veya kaplı fidanların üst boya repikajı (Polietilen torba veya kabın doldurulması,repikaj yapılması, taşınması, yastıklara dizilmesi ve sulanması) — Hacmi 11,1 - 22 litre arasındaki (Çapı 19,1 - 25 cm) kaplara repikaj','1000 Adet',36339.62,'{"ihaleli_fiyat": 42517.35}'),
('4403.5','Torbalı veya kaplı fidanların üst boya repikajı (Polietilen torba veya kabın doldurulması,repikaj yapılması, taşınması, yastıklara dizilmesi ve sulanması) — Hacmi 23 - 35 litre arasındaki (Çapı 26 - 35 cm) kaplara repikaj','1000 Adet',40632.15,'{"ihaleli_fiyat": 47539.62}'),
('4403.6','Torbalı veya kaplı fidanların üst boya repikajı (Polietilen torba veya kabın doldurulması,repikaj yapılması, taşınması, yastıklara dizilmesi ve sulanması) — 36 - 50 litre hacimli kaplarda repikaj','100 Adet',6804.02,'{"ihaleli_fiyat": 7960.7}'),
('4403.7','Torbalı veya kaplı fidanların üst boya repikajı (Polietilen torba veya kabın doldurulması,repikaj yapılması, taşınması, yastıklara dizilmesi ve sulanması) — 51 - 80 litre hacimli kaplarda repikaj','100 Adet',11666.1,'{"ihaleli_fiyat": 13649.33}'),
('4403.8','Torbalı veya kaplı fidanların üst boya repikajı (Polietilen torba veya kabın doldurulması,repikaj yapılması, taşınması, yastıklara dizilmesi ve sulanması) — 81 litre ve üzerindeki hacimli kaplarda repikaj','100 Adet',18134.69,'{"ihaleli_fiyat": 21217.58}'),
('4403.9','Torbalı veya kaplı fidanların üst boya repikajı (Polietilen torba veya kabın doldurulması,repikaj yapılması, taşınması, yastıklara dizilmesi ve sulanması) — Hacmi 7,1 -11 litre arasındaki (Çapı 17,1 - 19 cm) kaplara repikaj','1000 Adet',27764.43,'{"ihaleli_fiyat": 32484.38}'),
('4404.1','Fidan aralarındaki boşlukların doldurulması — Yastıklara aralıklı yerleştirilen torbaların veya kapların arasının mil veya talaş vb. materyal ile doldurulması','1000 Adet',2727.27,'{"ihaleli_fiyat": 3190.91}'),
('4405.1','Kaplı  fidanlarda ot alma — Çapı 10- 25 cm arasında  olan kaplarda','1000 Adet',472.73,'{"ihaleli_fiyat": 553.09}'),
('4405.2','Kaplı  fidanlarda ot alma — Çapı 26 - 45 cm arasında olan kaplarda','1000 Adet',890.91,'{"ihaleli_fiyat": 1042.36}'),
('4405.3','Kaplı  fidanlarda ot alma — Çapı 45  cm'' den büyük olan kaplarda','1000 Adet',1000.0,'{"ihaleli_fiyat": 1170.0}'),
('4406.1','Kaplı fidanların taşıtlara yüklenmesi — Hacmi 1,3 litreye kadar olan kaplarda (Çapı 8,9 cm'' den küçük)','1000 Adet',1181.82,'{"ihaleli_fiyat": 1382.73}'),
('4406.2','Kaplı fidanların taşıtlara yüklenmesi — Hacmi 1,4 - 4 litre arası  olan kaplarda  (Çapı 9 - 13 cm)','1000 Adet',1745.45,'{"ihaleli_fiyat": 2042.18}'),
('4406.3','Kaplı fidanların taşıtlara yüklenmesi — Hacmi 7,1 -11 litre arası olan kaplarda (Çapı 13,1 -19 cm)','1000 Adet',2585.45,'{"ihaleli_fiyat": 3024.98}'),
('4406.4','Kaplı fidanların taşıtlara yüklenmesi — Hacmi 11,1-22 litre arası olan kaplarda (Çapı 19,1 - 25 cm)','1000 Adet',6027.27,'{"ihaleli_fiyat": 7051.9}'),
('4406.5','Kaplı fidanların taşıtlara yüklenmesi — Hacmi 23 - 35 litre arası  olan kaplarda  (Çapı 26 - 35 cm)','1000 Adet',9469.08,'{"ihaleli_fiyat": 11078.83}'),
('4406.6','Kaplı fidanların taşıtlara yüklenmesi — Hacmi 36 - 50 litre arası  olan kaplarda  (Çapı 36 - 45 cm)','100 Adet',1581.82,'{"ihaleli_fiyat": 1850.73}'),
('4406.7','Kaplı fidanların taşıtlara yüklenmesi — Hacmi 51 - 80 litre   olan kaplarda','100 Adet',3585.45,'{"ihaleli_fiyat": 4194.98}'),
('4406.8','Kaplı fidanların taşıtlara yüklenmesi — Hacmi 4.1 - 7 litre arasınaki kaplarda (Çapı 13,1- 17 cm)','1000 Adet',2154.54,'{"ihaleli_fiyat": 2520.82}'),
('4406.9','Kaplı fidanların taşıtlara yüklenmesi — Hacmi 81 litre ve üzeri olan kaplarda','100 Adet',5623.63,'{"ihaleli_fiyat": 6579.65}'),
('4407.1','Kaplı fidanların taşıtlardan indirilerek dizilmesi — Hacmi 1,3 litreye kadar olan kaplarda 
(Çapı 8,9 cm'' den küçük)','1000 Adet',718.18,'{"ihaleli_fiyat": 840.27}'),
('4407.2','Kaplı fidanların taşıtlardan indirilerek dizilmesi — Hacmi 1,4 - 4 litre arası  olan kaplarda  (Çapı 9 - 13 cm)','1000 Adet',1078.18,'{"ihaleli_fiyat": 1261.47}'),
('4407.3','Kaplı fidanların taşıtlardan indirilerek dizilmesi — Hacmi 7,1 - 11litre arası olan kaplarda (Çapı 13,1 -19 cm)','1000 Adet',2332.72,'{"ihaleli_fiyat": 2729.29}'),
('4407.4','Kaplı fidanların taşıtlardan indirilerek dizilmesi — Hacmi 11,1-22 litre arası olan kaplarda (Çapı 19,1-25 cm)','1000 Adet',3054.54,'{"ihaleli_fiyat": 3573.81}'),
('4407.5','Kaplı fidanların taşıtlardan indirilerek dizilmesi — Hacmi 23 - 35 litre arası olan kaplarda (Çapı 26 - 35 cm )','1000 Adet',3590.91,'{"ihaleli_fiyat": 4201.36}'),
('4407.6','Kaplı fidanların taşıtlardan indirilerek dizilmesi — Hacmi 36 - 50 litre arası olan kaplarda  (Çapı 36 - 45 cm )','100 Adet',885.45,'{"ihaleli_fiyat": 1035.98}'),
('4407.7','Kaplı fidanların taşıtlardan indirilerek dizilmesi — Hacmi 51 - 80 litre olan kaplarda','100 Adet',1541.82,'{"ihaleli_fiyat": 1803.93}'),
('4407.8','Kaplı fidanların taşıtlardan indirilerek dizilmesi — Hacmi 4,1 - 7 litre arasınaki kaplarda (çapı 13,1- 17 cm)','1000 Adet',1541.82,'{"ihaleli_fiyat": 1803.93}'),
('4407.9','Kaplı fidanların taşıtlardan indirilerek dizilmesi — Hacmi 81 litre ve üzeri   olan kaplarda','100 Adet',2227.27,'{"ihaleli_fiyat": 2605.91}'),
('4408.1','Kaplı fidan üretim parsellerinin hazırlanması — Kaplı fidan üretim parsellerinin hazırlanması','Da',16241.29,'{"ihaleli_fiyat": 19002.31}'),
('4409.1','Mevcut kaplı fidan üretim tavalarının yeniden düzenlenmesi (kullanılmış tavalarda biriken artıkların kazılarak çıkarılması 40 cm genişliğinde kanal açılması bu kanala taş döşenmesi alana örtü ve malzeme serilmesi) — Mevcut kaplı fidan üretim tavalarının yeniden düzenlenmesi (kullanılmış tavalarda biriken artıkların kazılarak çıkarılması 40 cm genişliğinde kanal açılması bu kanala taş döşenmesi alana örtü ve malzeme serilmesi)','Metre',174.55,'{"ihaleli_fiyat": 204.22}'),
('4411.1','Kaplı fidanların bulundukları yerde aralarının açılması — 4-11 lt arasındaki hacimli kapların arasının açılması','1000 Adet',2254.54,'{"ihaleli_fiyat": 2637.82}'),
('4411.2','Kaplı fidanların bulundukları yerde aralarının açılması — 11,1 - 22 lt arasındaki hacimli kapların arasının açılması','1000 Adet',4545.45,'{"ihaleli_fiyat": 5318.18}'),
('4501.1','Serada aşı yapılması — Kaplı altlık  fidanların seraya nakli','100 Adet',551.11,'{"ihaleli_fiyat": 644.8}'),
('4501.3','Serada aşı yapılması — Fidanın uygun yükseklikten budanması aşı yapılması bağlanması macunlanması yastıklara yerleştirilmesi (malzeme bedeli hariç)','100 Adet',2317.02,'{"ihaleli_fiyat": 2710.92}'),
('4501.4','Serada aşı yapılması — Aşı bağlarının çözülmesi ve tepe kesiminin yapılması','100 Adet',763.85,'{"ihaleli_fiyat": 893.71}'),
('4502.2','Fidanlık sahasında repikajlı orman ağacı ve repikajlı süs bitkilerine aşı yapılması — Fidanların   budanması, 175 cm yüksekliğe kadar bölümde aşı yapılması (Malzeme hariç)','100 Adet',1578.63,'{"ihaleli_fiyat": 1847.0}'),
('4502.3','Fidanlık sahasında repikajlı orman ağacı ve repikajlı süs bitkilerine aşı yapılması — Fidanların   budanması ve 175 cm ve yukarı yükseklikten  aşı yapılması (Malzeme hariç)','100 Adet',1986.02,'{"ihaleli_fiyat": 2323.64}'),
('4502.4','Fidanlık sahasında repikajlı orman ağacı ve repikajlı süs bitkilerine aşı yapılması — Aşı bağının çözülmesi ve tepe kesimi yapılması','100 Adet',1171.24,'{"ihaleli_fiyat": 1370.35}'),
('4503.2','Arazide ve Doğal Meşçerelerde bulunan münferit altlıkların Aşılanması — Altlıkların budanması,175 cm'' ye kadar yükseklikten aşı yapılması (Malzeme hariç)','100 Adet',6365.45,'{"ihaleli_fiyat": 7447.58}'),
('4503.3','Arazide ve Doğal Meşçerelerde bulunan münferit altlıkların Aşılanması — Altlıkların budanması, 175 cm ve yukarı yükseklikten aşı yapılması (Malzeme hariç)','100 Adet',7638.54,'{"ihaleli_fiyat": 8937.09}'),
('4503.4','Arazide ve Doğal Meşçerelerde bulunan münferit altlıkların Aşılanması — Aşı bağının çözülmesi ve tepe kesimi yapılması','100 Adet',738.39,'{"ihaleli_fiyat": 863.92}'),
('4503.5','Arazide ve Doğal Meşçerelerde bulunan münferit altlıkların Aşılanması — Aşı yapılacak fertlerin etrafında 2 m çapındaki alanda diri örtü temizliği yapılması','100 Adet',2199.9,'{"ihaleli_fiyat": 2573.88}'),
('4504.1','Tohum Bahçelerinde aşı kalemi alınması — Tohum Bahçesinden Aşı Kalemi Alma (Boyu 10 metre''ye kadar)','100 Adet',254.62,'{"ihaleli_fiyat": 297.9}'),
('4504.2','Tohum Bahçelerinde aşı kalemi alınması — Tohum Bahçesinden Aşı Kalemi Alma (Boyu 10 metre''den büyük ağaçlar için)','100 Adet',560.16,'{"ihaleli_fiyat": 655.39}'),
('4505.2','Ekim yastıklarında aşı yapılması — Ekim yastığında bulunan ceviz,badem,kestane vb.gibi orman ağacı fidanlarına göz aşısı yapılması','100 Adet',1509.88,'{"ihaleli_fiyat": 1766.57}'),
('4505.3','Ekim yastıklarında aşı yapılması — Ekim yastığında bulunan ceviz,badem,kestane vb.gibi orman ağacı fidanlarına göz aşısı dışında (yapılan tüm aşılar) aşı yapılması','100 Adet',1670.29,'{"ihaleli_fiyat": 1954.24}'),
('4601.1','Çelik materyalinin temini — Materyal temini (yapraklı)','1000 Adet',1500.0,'{"ihaleli_fiyat": 1755.0}'),
('4601.2','Çelik materyalinin temini — Materyal temini (ibreli)','1000 Adet',1660.0,'{"ihaleli_fiyat": 1942.2}'),
('4601.3','Çelik materyalinin temini — Materyal temini (çalı formlu)','1000 Adet',2000.0,'{"ihaleli_fiyat": 2340.0}'),
('4602.1','Çeliklerin hazırlanması — Yapraklı fidanlar','1000 Adet',1236.36,'{"ihaleli_fiyat": 1446.54}'),
('4602.2','Çeliklerin hazırlanması — İbreli Fidanlar','1000 Adet',1945.45,'{"ihaleli_fiyat": 2276.18}'),
('4603.1','Çeliklerin dikimi — Yapraklı fidanlardan elde edilen çeliklerin dikilmesi','1000 Adet',527.27,'{"ihaleli_fiyat": 616.91}'),
('4603.2','Çeliklerin dikimi — İbreli fidanlardan elde edilen çeliklerin dikilmesi','1000 Adet',709.09,'{"ihaleli_fiyat": 829.64}'),
('4701.1','Meşe tohumu üretimi (İdarece gösterilen alanlardan meşe tohumu üretimi ve idareye teslimi dahil) — Meşe Tohumu Üretimi (İdarece gösterilen alanlardan üretimi ve idareye teslimi)','Kg',21.82,'{"ihaleli_fiyat": 25.53}'),
('4701.2','Meşe tohumu üretimi (İdarece gösterilen alanlardan meşe tohumu üretimi ve idareye teslimi dahil) — Meşe Tohumu Üretimi küçük tohumlu saçlı meşe, mazı meşesi v.b.(İdarece gösterilen alanlardan üretimi ve idareye teslimi)','Kg',30.91,'{"ihaleli_fiyat": 36.16}'),
('4702.1','Sedir tohumu üretimi (Tohum meşcerelerinden sedir kozalaklarının toplanarak idareye teslimi dahil) — Sedir kozalağı üretimi (Tohum meşcerelerinden sedir kozalaklarının toplanarak idareye teslimi) Zayıf tohum yılında 1,5 kat sayısı uygulanır.','Kg',36.36,'{"ihaleli_fiyat": 42.55}'),
('4702.2','Sedir tohumu üretimi (Tohum meşcerelerinden sedir kozalaklarının toplanarak idareye teslimi dahil) — Sedir kozalaklarının karpellerinin ayrılması','Kg',45.45,'{"ihaleli_fiyat": 53.18}'),
('4702.3','Sedir tohumu üretimi (Tohum meşcerelerinden sedir kozalaklarının toplanarak idareye teslimi dahil) — Sedir karpellerinden tohumlarının elenmesi ve temiz tohum elde edilmesi','Kg',854.54,'{"ihaleli_fiyat": 999.82}'),
('4703.1','Kızılçam ve Halepçamı tohumu üretimi (tohum meşçerelerinden veya bahçelerinden kozalak  üretimi ve idareye teslimi) Bol tohum yılı dışında  1,5 kat sayısı uygulanır. — Tohum meşçeresinden kozalak üretimi','Kg',36.36,'{"ihaleli_fiyat": 42.55}'),
('4703.2','Kızılçam ve Halepçamı tohumu üretimi (tohum meşçerelerinden veya bahçelerinden kozalak  üretimi ve idareye teslimi) Bol tohum yılı dışında  1,5 kat sayısı uygulanır. — Kozalakların tohum pistine serilerek,  her gün karıştırılması 5 defa aktarılarak, tohumun ve boş kozalakların toplanması','Kg',43.64,'{"ihaleli_fiyat": 51.05}'),
('4703.3','Kızılçam ve Halepçamı tohumu üretimi (tohum meşçerelerinden veya bahçelerinden kozalak  üretimi ve idareye teslimi) Bol tohum yılı dışında  1,5 kat sayısı uygulanır. — Tohum bahçesinden kozalak üretimi','Kg',25.45,'{"ihaleli_fiyat": 29.78}'),
('4704.1','Karaçam tohum üretimi (Tohum meşçerelerinden veya bahçelerinden kozalak üretimi ve idareye teslimi dahil) Bol tohum yılı dışında  1,5 katsayısı uygulanır. — Tohum meşçeresinden kozalak üretimi','Kg',58.18,'{"ihaleli_fiyat": 68.07}'),
('4704.2','Karaçam tohum üretimi (Tohum meşçerelerinden veya bahçelerinden kozalak üretimi ve idareye teslimi dahil) Bol tohum yılı dışında  1,5 katsayısı uygulanır. — Tohum bahçesinden kozalak üretimi','Kg',40.0,'{"ihaleli_fiyat": 46.8}'),
('4705.1','Sarıçam tohum üretimi (tohum meşçerelerinden veya bahçesinden kozalak üretimi ve idareye teslimi dahil) Bol tohum yılı dışında  1,5 katsayısı uygulanır. — Tohum meşçeresinden kozalak üretimi','Kg',90.91,'{"ihaleli_fiyat": 106.36}'),
('4705.2','Sarıçam tohum üretimi (tohum meşçerelerinden veya bahçesinden kozalak üretimi ve idareye teslimi dahil) Bol tohum yılı dışında  1,5 katsayısı uygulanır. — Tohum bahçesinden kozalak üretimi','Kg',54.55,'{"ihaleli_fiyat": 63.82}'),
('4706.1','Fıstıkçamı tohum üretimi (Tohum meşçerelerinden veya bahçelerinden kozalak üretimi ve idareye teslimi) Bol tohum yılı dışında  1,5 kat sayısı uygulanır. — Tohum meşçeresinden kozalak üretimi','Kg',19.67,'{"ihaleli_fiyat": 23.02}'),
('4706.2','Fıstıkçamı tohum üretimi (Tohum meşçerelerinden veya bahçelerinden kozalak üretimi ve idareye teslimi) Bol tohum yılı dışında  1,5 kat sayısı uygulanır. — Fıstıkçamı  kozalağının tohum pistine serilerek 3 defa aktarılması,  tohumun ve boş kozalakların toplanması','Kg',19.67,'{"ihaleli_fiyat": 23.02}'),
('4706.3','Fıstıkçamı tohum üretimi (Tohum meşçerelerinden veya bahçelerinden kozalak üretimi ve idareye teslimi) Bol tohum yılı dışında  1,5 kat sayısı uygulanır. — Tohum bahçesinden kozalak üretimi','Kg',9.84,'{"ihaleli_fiyat": 11.51}'),
('4707.1','Yapraklı tür orman ağacı tohumu üretimi — Akasya, Yalancı akasya, Gladiçya, Erguvan ve benzeri türler','Kg',772.73,'{"ihaleli_fiyat": 904.09}'),
('4707.2','Yapraklı tür orman ağacı tohumu üretimi — Manolya tohumu üretimi (tohumun toplanması, kurutulması, ayıklanması)','Kg',4058.18,'{"ihaleli_fiyat": 2608.83}'),
('4707.3','Yapraklı tür orman ağacı tohumu üretimi — Sığla tohumu üretimi (tohumun toplanması , ayıklanması)','Kg',16579.98,'{"ihaleli_fiyat": 19398.58}'),
('4707.4','Yapraklı tür orman ağacı tohumu üretimi — Ihlamur Tohumu Üretimi (tohumun toplanması , ayıklanması)','Kg',1145.45,'{"ihaleli_fiyat": 1340.18}'),
('4708.1','Doğu ladini tohumu üretimi. (Tohum meşcerelerinden kozalak üretimi ve idareye teslimi) Bol tohum yılı dışında  1,5 katsayısı uygulanır. — Tohum meşçeresinde kozalak üretimi','Kg',80.0,'{"ihaleli_fiyat": 93.6}'),
('4708.2','Doğu ladini tohumu üretimi. (Tohum meşcerelerinden kozalak üretimi ve idareye teslimi) Bol tohum yılı dışında  1,5 katsayısı uygulanır. — Doğu ladini  kozalağının tohum pistine serilerek 3 defa aktarılması,  tohumun ve boş kozalakların toplanması','Kg',1.82,'{"ihaleli_fiyat": 2.13}'),
('4709.1','Kayın tohumu üretimi — Tohum Meşçerelerinden Kayın Tohumu Üretimi ve İdareye Teslimi (Zayıf Tohum Yılında 1,5 katsayısı uygulanır.)','Kg',165.45,'{"ihaleli_fiyat": 193.58}'),
('4710.1','Kızılağaç tohumu üretimi — Tohum Meşçerelerinden Kızılağaç Tohumu Üretimi ve İdareye Teslimi (Zayıf Tohum Yılında 1,5 katsayısı uygulanır)','Kg',872.73,'{"ihaleli_fiyat": 1021.09}'),
('4710.2','Kızılağaç tohumu üretimi — Kızılağaç Kozalaklarından Tohumun Çıkarılması ve Temizlenmesi','Kg',363.64,'{"ihaleli_fiyat": 425.45}'),
('4711.1','Kara servi ve mavi servi tohumu üretimi (Tohum meşcerelerinden  ve/ veya kaynaklarından kozalakların toplanarak idareye teslimi) — Kara Servi ve Mavi Servi Tohumu Üretimi (Tohum meşcerelerinden  ve/veya Kaynaklarından Kozalakların Toplanarak İdareye Teslimi)','Kg',81.82,'{"ihaleli_fiyat": 95.73}'),
('4720.1','Thermoblokta tohum çıkarılması (Tesis idarece temin edilecektir.) — Kozalağın ön kurutmaya serilmesi','Ton',1272.73,'{"ihaleli_fiyat": 1489.09}'),
('4720.2','Thermoblokta tohum çıkarılması (Tesis idarece temin edilecektir.) — Boş kozalakların thermobloktan alınması','Ton',1636.36,'{"ihaleli_fiyat": 1914.54}'),
('4722.1','Tohum bahçelerinde tepe budaması : 8 m. ve daha yüksek boylu ağaçların tepe budamasında işaretleme, kesme, macunlama ve budama artıklarının saha dışına çıkartılması işi. — Tepe budaması yapılacak ağaçlarda kesim yerinin işaretlenmesi','100 Adet',1743.63,'{"ihaleli_fiyat": 2040.05}'),
('4722.2','Tohum bahçelerinde tepe budaması : 8 m. ve daha yüksek boylu ağaçların tepe budamasında işaretleme, kesme, macunlama ve budama artıklarının saha dışına çıkartılması işi. — İşaretlenen yerden tepenin ve yan dalların budanması ve kesit yüzeylerinin macunlanması','100 Adet',2432.72,'{"ihaleli_fiyat": 2846.29}'),
('4722.3','Tohum bahçelerinde tepe budaması : 8 m. ve daha yüksek boylu ağaçların tepe budamasında işaretleme, kesme, macunlama ve budama artıklarının saha dışına çıkartılması işi. — Budama artıklarının sahadan çıkartılması','100 Adet',1241.82,'{"ihaleli_fiyat": 1452.93}'),
('4722.4','Tohum bahçelerinde tepe budaması : 8 m. ve daha yüksek boylu ağaçların tepe budamasında işaretleme, kesme, macunlama ve budama artıklarının saha dışına çıkartılması işi. — Tohum Bahçelerinde kuru dalların budanması','100 Adet',87.27,'{"ihaleli_fiyat": 102.11}'),
('4722.5','Tohum bahçelerinde tepe budaması : 8 m. ve daha yüksek boylu ağaçların tepe budamasında işaretleme, kesme, macunlama ve budama artıklarının saha dışına çıkartılması işi. — Tohum Bahçelerinde Çam Kese Böceği ile Mücadele (Çam Kese Böceklerinin bir yerde toplanarak imha edilmesi dahil)','100 Adet',2087.27,'{"ihaleli_fiyat": 2442.11}'),
('4740.1','Andız, boz ardıç, dikenli ardıç, servi ardıç ve kokulu ardıç tohumu üretimi (tohum meşcerelerinden veya idarece gösterilecek alanlardan kozalak üretimi ve idareye teslimi) Bol tohum yılı dışında  1,5 katsayısı uygulanır. — Boz Ardıç,Servi Ardıç ve Kokulu Ardıç Kozalak Toplanması','Kg',163.64,'{"ihaleli_fiyat": 191.45}'),
('4740.2','Andız, boz ardıç, dikenli ardıç, servi ardıç ve kokulu ardıç tohumu üretimi (tohum meşcerelerinden veya idarece gösterilecek alanlardan kozalak üretimi ve idareye teslimi) Bol tohum yılı dışında  1,5 katsayısı uygulanır. — Dikenli Ardıç Kozalağı Toplanması','Kg',110.91,'{"ihaleli_fiyat": 129.76}'),
('4740.3','Andız, boz ardıç, dikenli ardıç, servi ardıç ve kokulu ardıç tohumu üretimi (tohum meşcerelerinden veya idarece gösterilecek alanlardan kozalak üretimi ve idareye teslimi) Bol tohum yılı dışında  1,5 katsayısı uygulanır. — Andız Kozalağı Toplanması','Kg',100.0,'{"ihaleli_fiyat": 117.0}'),
('4740.4','Andız, boz ardıç, dikenli ardıç, servi ardıç ve kokulu ardıç tohumu üretimi (tohum meşcerelerinden veya idarece gösterilecek alanlardan kozalak üretimi ve idareye teslimi) Bol tohum yılı dışında  1,5 katsayısı uygulanır. — Boz Ardıç Kozalağından Tohum Çıkarılması','Kg',994.54,'{"ihaleli_fiyat": 1163.62}'),
('4740.5','Andız, boz ardıç, dikenli ardıç, servi ardıç ve kokulu ardıç tohumu üretimi (tohum meşcerelerinden veya idarece gösterilecek alanlardan kozalak üretimi ve idareye teslimi) Bol tohum yılı dışında  1,5 katsayısı uygulanır. — Dikenli Ardıç ve Servi Ardıç Kozalağından Tohum Çıkartılması','Kg',1243.64,'{"ihaleli_fiyat": 1455.05}'),
('4740.6','Andız, boz ardıç, dikenli ardıç, servi ardıç ve kokulu ardıç tohumu üretimi (tohum meşcerelerinden veya idarece gösterilecek alanlardan kozalak üretimi ve idareye teslimi) Bol tohum yılı dışında  1,5 katsayısı uygulanır. — Kokulu Ardıç Kozalağından Tohum Çıkartılması','Kg',641.82,'{"ihaleli_fiyat": 750.93}'),
('4740.7','Andız, boz ardıç, dikenli ardıç, servi ardıç ve kokulu ardıç tohumu üretimi (tohum meşcerelerinden veya idarece gösterilecek alanlardan kozalak üretimi ve idareye teslimi) Bol tohum yılı dışında  1,5 katsayısı uygulanır. — Andız Kozalağından Tohum Çıkartılması','Kg',372.73,'{"ihaleli_fiyat": 436.09}'),
('4800.1','Tıbbi Bitki Kokteyli Üretimi — Bitkinin toplanması kurutulması ,parçalanması ve elenmesi (Yaş ağırlık)','100Kg',7181.81,'{"ihaleli_fiyat": 8402.72}'),
('4900.1','Malzeme Birim Fiyatları ( Özel orman fidanlık tesisinde kullanılacaktır.) — Ahır gübresi (Yanmış)','M³',430.22,null),
('4900.2','Malzeme Birim Fiyatları ( Özel orman fidanlık tesisinde kullanılacaktır.) — Kimyasal Gübre','Kg',9.63,null),
('4900.3','Malzeme Birim Fiyatları ( Özel orman fidanlık tesisinde kullanılacaktır.) — Humus','M³',430.22,null),
('4900.4','Malzeme Birim Fiyatları ( Özel orman fidanlık tesisinde kullanılacaktır.) — Turba (Yerli)','M³',645.35,null),
('4900.5','Malzeme Birim Fiyatları ( Özel orman fidanlık tesisinde kullanılacaktır.) — Mineral Toprak','M³',236.66,null),
('4900.6','Malzeme Birim Fiyatları ( Özel orman fidanlık tesisinde kullanılacaktır.) — Mil','M³',341.94,null),
('4900.7','Malzeme Birim Fiyatları ( Özel orman fidanlık tesisinde kullanılacaktır.) — Pomza','M³',537.83,null),
('4900.8','Malzeme Birim Fiyatları ( Özel orman fidanlık tesisinde kullanılacaktır.) — Perlit','M³',634.99,null),
('4900.9','Malzeme Birim Fiyatları ( Özel orman fidanlık tesisinde kullanılacaktır.) — Polietilen Tüp ve Torba','Kg',48.39,null),
('4900.10','Malzeme Birim Fiyatları ( Özel orman fidanlık tesisinde kullanılacaktır.) — Saksı (0,5 - 1 Lt)','Adet',1.49,null),
('4900.11','Malzeme Birim Fiyatları ( Özel orman fidanlık tesisinde kullanılacaktır.) — Saksı (1,1 - 2 Lt)','Adet',3.02,null),
('4900.12','Malzeme Birim Fiyatları ( Özel orman fidanlık tesisinde kullanılacaktır.) — Saksı (2,1 - 3 Lt)','Adet',3.22,null),
('4900.13','Malzeme Birim Fiyatları ( Özel orman fidanlık tesisinde kullanılacaktır.) — Saksı (3,1 - 4 Lt)','Adet',5.39,null),
('4900.14','Malzeme Birim Fiyatları ( Özel orman fidanlık tesisinde kullanılacaktır.) — Saksı (4,1 - 5 Lt)','Adet',5.94,null),
('4900.20','Malzeme Birim Fiyatları ( Özel orman fidanlık tesisinde kullanılacaktır.) — Sepet (10 - 15 lt)','Adet',12.96,null),
('4900.21','Malzeme Birim Fiyatları ( Özel orman fidanlık tesisinde kullanılacaktır.) — Sepet (30 - 40 lt)','Adet',25.86,null),
('4900.30','Malzeme Birim Fiyatları ( Özel orman fidanlık tesisinde kullanılacaktır.) — Damla Sulama (Malzeme)','Da',6561.2,null),
('4900.31','Malzeme Birim Fiyatları ( Özel orman fidanlık tesisinde kullanılacaktır.) — Damla Sulama (Montaj)','Da',1075.56,null),
('4900.32','Malzeme Birim Fiyatları ( Özel orman fidanlık tesisinde kullanılacaktır.) — Yağmurlama Sulama (Malzeme)','Da',6668.74,null),
('4900.33','Malzeme Birim Fiyatları ( Özel orman fidanlık tesisinde kullanılacaktır.) — Yağmurlama Sulama (Montaj)','Da',1075.56,null),
('4900.40','Malzeme Birim Fiyatları ( Özel orman fidanlık tesisinde kullanılacaktır.) — 500 m² ve daha büyük sera (Malzeme ve montajı dahil)','M2',419.61,null),
('4900.41','Malzeme Birim Fiyatları ( Özel orman fidanlık tesisinde kullanılacaktır.) — 500 m² ''den küçük sera (Malzeme ve montajı dahil)','M2',537.83,null),
('4900.50','Malzeme Birim Fiyatları ( Özel orman fidanlık tesisinde kullanılacaktır.) — Bambu (Uzunluk 105 cm, çapı 6 - 8 mm)','Adet',0.68,null),
('4900.51','Malzeme Birim Fiyatları ( Özel orman fidanlık tesisinde kullanılacaktır.) — Bambu (Uzunluk 150 cm, çapı 8 - 10 mm)','Adet',1.44,null),
('4900.52','Malzeme Birim Fiyatları ( Özel orman fidanlık tesisinde kullanılacaktır.) — Bambu (Uzunluk 150 cm, çapı 10 - 12 mm)','Adet',1.49,null),
('4900.53','Malzeme Birim Fiyatları ( Özel orman fidanlık tesisinde kullanılacaktır.) — Bambu (Uzunluk 210 cm, çapı 12 - 14 mm)','Adet',2.84,null),
('4900.54','Malzeme Birim Fiyatları ( Özel orman fidanlık tesisinde kullanılacaktır.) — Bambu (Uzunluk 210 cm, çapı 14 - 16 mm)','Adet',3.53,null),
('4900.55','Malzeme Birim Fiyatları ( Özel orman fidanlık tesisinde kullanılacaktır.) — Bambu (Uzunluk 210 cm, çapı 16 - 18 mm)','Adet',4.24,null),
('4900.56','Malzeme Birim Fiyatları ( Özel orman fidanlık tesisinde kullanılacaktır.) — Bambu (Uzunluk 250 cm, çapı 16 - 18 mm)','Adet',5.55,null),
('4900.57','Malzeme Birim Fiyatları ( Özel orman fidanlık tesisinde kullanılacaktır.) — Bambu (Uzunluk 250 cm, çapı 18 - 20 mm)','Adet',7.04,null),
('4900.58','Malzeme Birim Fiyatları ( Özel orman fidanlık tesisinde kullanılacaktır.) — Bambu (Uzunluk 300 cm, çapı 20 - 22 mm)','Adet',8.6,null),
('4900.59','Malzeme Birim Fiyatları ( Özel orman fidanlık tesisinde kullanılacaktır.) — Bambu (Uzunluk 300 cm, çapı 22 - 24 mm)','Adet',10.24,null),
('4900.60','Malzeme Birim Fiyatları ( Özel orman fidanlık tesisinde kullanılacaktır.) — Bambu (Uzunluk 300 cm, çapı 24 - 26 mm)','Adet',12.68,null),
('5000.1','Fidan Sayımları — Ekim Yastığında İbreli Fidan Sayımları (1+0,2+0 yaşlı)','Da',1000.0,'{"ihaleli_fiyat": 1170.0}'),
('5000.2','Fidan Sayımları — Ekim Yastığında Yapraklı Fidan Sayımları (1+0,2+0 yaşlı)','Da',909.09,'{"ihaleli_fiyat": 1063.64}'),
('5000.3','Fidan Sayımları — Araziye Repikajlı  İbreli Fidan Sayımları (Boy  sınıflamaları yapılarak)','1000 Adet',872.73,'{"ihaleli_fiyat": 1021.09}'),
('5000.4','Fidan Sayımları — Araziye Repikajlı  Yapraklı Fidan Sayımları (Çap sınıflamaları yapılarak)','1000 Adet',1163.64,'{"ihaleli_fiyat": 1361.45}')
) as v(poz_no,tanim,birim,fiyat,extra)
on conflict (source_id,poz_no,coalesce(birim,'')) do nothing;