-- Kültür 2026 part 4/10 (idempotent)
insert into bf_poz (source_id,poz_no,tanim,birim,fiyat,extra)
select 'c4283e74-55cd-4e4c-8394-65486dbbe9e3'::uuid, v.poz_no, v.tanim, v.birim, v.fiyat::numeric, v.extra::jsonb
from (values
('V.1257','Yonu Taşından 21-25 Cm. Arası Yükseklikte Silmeli Korniş Yapılması ve Yerine Konması İşçiliği','M',8503.21,null),
('V.1257/A','Puzolan Katkılı Horasan Harcı ile Yonu Taşından 21-25 Cm. Arası Yükseklikte Silmeli Korniş Yapılması ve Yerine Konması İşçiliği','M',8549.55,null),
('V.1257/B','500 Doz Hidrolik Kireç Harcı ile Yonu Taşından 21-25 Cm. Arası Yükseklikte Silmeli Korniş Yapılması ve Yerine Konması İşçiliği','M',8617.81,null),
('V.1258','Yonu Taşından 26-30 Cm. Arası Yükseklikte Düz Pahlı Korniş Yapılması ve Yerine Konması İşçiliği','M',7754.81,null),
('V.1258/A','Puzolan Katkılı Horasan Harcı ile Yonu Taşından 26-30 Cm. Arası Yükseklikte Düz Pahlı Korniş Yapılması ve Yerine Konması İşçiliği','M',7824.33,null),
('V.1258/B','500 Doz Hidrolik Kireç Harcı ile Yonu Taşından 26-30 Cm. Arası Yükseklikte Düz Pahlı Korniş Yapılması ve Yerine Konması İşçiliği -61-','M',7926.71,null),
('V.1259','Yonu Taşından 26-30 Cm. Arası Yükseklikte Silmeli Korniş Yapılması ve Yerine Konması İşçiliği','M',9279.81,null),
('V.1259/A','Puzolan Katkılı Horasan Harcı ileYonu Taşından 26-30 Cm. Arası Yükseklikte Silmeli Korniş Yapılması ve Yerine Konması İşçiliği','M',9349.33,null),
('V.1259/B','500 Doz Hidrolik Kireç Harcı ile Yonu Taşından 26-30 Cm. Arası Yükseklikte Silmeli Korniş Yapılması ve Yerine Konması İşçiliği','M',9451.71,null),
('V.1260','Yonu Taşından 31-35 Cm. Arası Yükseklikte Düz Pahlı Korniş Yapılması ve Yerine Konması İşçiliği','M',8517.31,null),
('V.1260/A','Puzolan Katkılı Horasan Harcı ile Yonu Taşından 31-35 Cm. Arası Yükseklikte Düz Pahlı Korniş Yapılması ve Yerine Konması İşçiliği','M',8586.83,null),
('V.1260/B','500 Doz Hidrolik Kireç Harcı ile Yonu Taşından 31-35 Cm. Arası Yükseklikte Düz Pahlı Korniş Yapılması ve Yerine Konması İşçiliği','M',8689.21,null),
('V.1261','Yonu Taşından 31-35 Cm. Arası Yükseklikte Silmeli Korniş Yapılması ve Yerine Konması İşçiliği','M',10042.31,null),
('V.1261/A','Puzolan Katkılı Horasan Harcı ile Yonu Taşından 31-35 Cm. Arası Yükseklikte Silmeli Korniş Yapılması ve Yerine Konması İşçiliği','M',10111.83,null),
('V.1261/B','500 Doz Hidrolik Kireç Harcı ile Yonu Taşından 31-35 Cm. Arası Yükseklikte Silmeli Korniş Yapılması ve Yerine Konması İşçiliği','M',10214.21,null),
('V.1262','Yonu Taşından 36-40 Cm. Arası Yükseklikte Düz Pahlı Korniş Yapılması ve Yerine Konması İşçiliği','M',9279.81,null),
('V.1262/A','Puzolan Katkılı Horasan Harcı ile Yonu Taşından 36-40 Cm. Arası Yükseklikte Düz Pahlı Korniş Yapılması ve Yerine Konması İşçiliği','M',9349.33,null),
('V.1262/B','500 Doz Hidrolik Kireç Harcı ile Yonu Taşından 36-40 Cm. Arası Yükseklikte Düz Pahlı Korniş Yapılması ve Yerine Konması İşçiliği','M',9451.71,null),
('V.1263','Yonu Taşından 36-40 Cm. Arası Yükseklikte Silmeli Korniş Yapılması ve Yerine Konması İşçiliği','M',10804.81,null),
('V.1263/A','Puzolan Katkılı Horasan Harcı ile Yonu Taşından 36-40 Cm. Arası Yükseklikte Silmeli Korniş Yapılması ve Yerine Konması İşçiliği','M',10874.33,null),
('V.1263/B','500 Doz Hidrolik Kireç Harcı ile Yonu Taşından 36-40 Cm. Arası Yükseklikte Silmeli Korniş Yapılması ve Yerine Konması İşçiliği','M',10976.71,null),
('V.1264','Yonu Taşından 41-45 Cm. Arası Yükseklikte Düz Pahlı Korniş Yapılması ve Yerine Konması İşçiliği','M',10042.31,null),
('V.1264/A','Puzolan Katkılı Horasan Harcı ile Yonu Taşından 41-45 Cm. Arası Yükseklikte Düz Pahlı Korniş Yapılması ve Yerine Konması İşçiliği','M',10111.83,null),
('V.1264/B','500 Doz Hidrolik Kireç Harcı ile Yonu Taşından 41-45 Cm. Arası Yükseklikte Düz Pahlı Korniş Yapılması ve Yerine Konması İşçiliği','M',10214.21,null),
('V.1265','Yonu Taşından 41-45 Cm. Arası Yükseklikte Silmeli Korniş Yapılması ve Yerine Konması İşçiliği','M',11567.31,null),
('V.1265/A','Puzolan Katkılı Horasan Harcı ile Yonu Taşından 41-45 Cm. Arası Yükseklikte Silmeli Korniş Yapılması ve Yerine Konması İşçiliği','M',11636.83,null),
('V.1265/B','500 Doz Hidrolik Kireç Harcı ile Yonu Taşından 41-45 Cm. Arası Yükseklikte Silmeli Korniş Yapılması ve Yerine Konması İşçiliği','M',11739.21,null),
('V.1266','Yonu Taşından 46-50 Cm. Arası Yükseklikte Düz Pahlı Korniş Yapılması ve Yerine Konması İşçiliği','M',10840.8,null),
('V.1266/A','Puzolan Katkılı Horasan Harcı ile Yonu Taşından 46-50 Cm. Arası Yükseklikte Düz Pahlı Korniş Yapılması ve Yerine Konması İşçiliği','M',10933.48,null),
('V.1266/B','500 Doz Hidrolik Kireç Harcı ile Yonu Taşından 46-50 Cm. Arası Yükseklikte Düz Pahlı Korniş Yapılması ve Yerine Konması İşçiliği','M',11070.0,null),
('V.1267','Yonu Taşından 46-50 Cm. Arası Yükseklikte Silmeli Korniş Yapılması ve Yerine Konması İşçiliği','M',12343.93,null),
('V.1267/A','Puzolan Katkılı Horasan Harcı ile Yonu Taşından 46-50 Cm. Arası Yükseklikte Silmeli Korniş Yapılması ve Yerine Konması İşçiliği','M',12436.6,null),
('V.1267/B','500 Doz Hidrolik Kireç Harcı ile Yonu Taşından 46-50 Cm. Arası Yükseklikte Silmeli Korniş Yapılması ve Yerine Konması İşçiliği','M',12573.13,null),
('V.1268','Yonu Taşından 51-55 Cm. Arası Yükseklikte Düz Pahlı Korniş Yapılması ve Yerine Konması İşçiliği -62-','M',12006.43,null),
('V.1268/A','Puzolan Katkılı Horasan Harcı ile Yonu Taşından 51-55 Cm. Arası Yükseklikte Düz Pahlı Korniş Yapılması ve Yerine Konması İşçiliği','M',12099.1,null),
('V.1268/B','500 Doz Hidrolik Kireç Harcı ile Yonu Taşından 51-55 Cm. Arası Yükseklikte Düz Pahlı Korniş Yapılması ve Yerine Konması İşçiliği','M',12235.63,null),
('V.1269','Yonu Taşından 51-55 Cm. Arası Yükseklikte Silmeli Korniş Yapılması ve Yerine Konması İşçiliği','M',13318.93,null),
('V.1269/A','Puzolan Katkılı Horasan Harcı ile Yonu Taşından 51-55 Cm. Arası Yükseklikte Silmeli Korniş Yapılması ve Yerine Konması İşçiliği','M',13411.6,null),
('V.1269/B','500 Doz Hidrolik Kireç Harcı ile Yonu Taşından 51-55 Cm. Arası Yükseklikte Silmeli Korniş Yapılması ve Yerine Konması İşçiliği','M',13548.13,null),
('V.1270','Yonu Taşından 56-60 Cm. Arası Yükseklikte Düz Pahlı Korniş Yapılması ve Yerine Konması İşçiliği','M',12768.93,null),
('V.1270/A','Puzolan Katkılı Horasan Harcı ile Yonu Taşından 56-60 Cm. Arası Yükseklikte Düz Pahlı Korniş Yapılması ve Yerine Konması İşçiliği','M',12861.6,null),
('V.1270/B','500 Doz Hidrolik Kireç Harcı ile Yonu Taşından 56-60 Cm. Arası Yükseklikte Düz Pahlı Korniş Yapılması ve Yerine Konması İşçiliği','M',12998.13,null),
('V.1271','Yonu Taşından 56-60 Cm. Arası Yükseklikte Silmeli Korniş Yapılması ve Yerine Konması İşçiliği','M',14718.93,null),
('V.1271/A','Puzolan Katkılı Horasan Harcı ile Yonu Taşından 56-60 Cm. Arası Yükseklikte Silmeli Korniş Yapılması ve Yerine Konması İşçiliği','M',14811.6,null),
('V.1271/B','500 Doz Hidrolik Kireç Harcı ile Yonu Taşından 56-60 Cm. Arası Yükseklikte Silmeli Korniş Yapılması ve Yerine Konması İşçiliği','M',14948.13,null),
('V.1272','Yonu Taşından 25 Cm. Yüksekliğe Kadar Mevcut Kornişin Islahı ve Yerine Konması İşçiliği','M',3418.84,null),
('V.1272/A','Puzolan Katkılı Horasan Harcı ile Yonu Taşından 25 Cm. Yüksekliğe Kadar Mevcut Kornişin Islahı ve Yerine Konması İşçiliği','M',3465.18,null),
('V.1272/B','500 Doz Hidrolik Kireç Harcı ile Yonu Taşından 25 Cm. Yüksekliğe Kadar Mevcut Kornişin Islahı ve Yerine Konması İşçiliği','M',3533.44,null),
('V.1273','Yonu Taşından 26-45 Cm. Arası Yükseklikte Mevcut Kornişin Islahı ve Yerine Konması İşçiliği','M',4111.06,null),
('V.1273/A','Puzolan Katkılı Horasan Harcı ile Yonu Taşından 26-45 Cm. Arası Yükseklikte Mevcut Kornişin Islahı ve Yerine Konması İşçiliği','M',4180.58,null),
('V.1273/B','500 Doz Hidrolik Kireç Harcı ile Yonu Taşından 26-45 Cm. Arası Yükseklikte Mevcut Kornişin Islahı ve Yerine Konması İşçiliği','M',4282.96,null),
('V.1274','Yonu Taşından 46-60 Cm. Arası Yükseklikte Mevcut Kornişin Islahı ve Yerine Konması İşçiliği','M',5481.43,null),
('V.1274/A','Puzolan Katkılı Horasan Harcı ile Yonu Taşından 46-60 Cm. Arası Yükseklikte Mevcut Kornişin Islahı ve Yerine Konması İşçiliği','M',5574.1,null),
('V.1274/B','500 Doz Hidrolik Kireç Harcı ile Yonu Taşından 46-60 Cm. Arası Yükseklikte Mevcut Kornişin Islahı ve Yerine Konması İşçiliği','M',5710.63,null),
('V.1275','Yonu Taşından 30 Cm.ye Kadar Yükseklikte Mevcut Kornişin Yerine Konması İşçiliği','M',2461.06,null),
('V.1275/A','Puzolan Katkılı Horasan Harcı ile Yonu Taşından 30 Cm.ye Kadar Yükseklikte Mevcut Kornişin Yerine Konması İşçiliği','M',2530.58,null),
('V.1275/B','500 Doz Hidrolik Kireç Harcı ile Yonu Taşından 30 Cm.ye Kadar Yükseklikte Mevcut Kornişin Yerine Konması İşçiliği','M',2632.96,null),
('V.1276','Yonu Taşından 60 Cm.ye Kadar Yükseklikte Mevcut Kornişin Yerine Konması İşçiliği','M',3267.31,null),
('V.1276/A','Puzolan Katkılı Horasan Harcı ile Yonu Taşından 60 Cm.ye Kadar Yükseklikte Mevcut Kornişin Yerine Konması İşçiliği','M',3336.83,null),
('V.1276/B','500 Doz Hidrolik Kireç Harcı ile Yonu Taşından 60 Cm.ye Kadar Yükseklikte Mevcut Kornişin Yerine Konması İşçiliği -63-','M',3439.21,null),
('V.1300','H- SÖVELER Yonu Taşından 15 Cm. Genişliğe Kadar Düz veya Pahlı Söve Yapılması ve Yerine Konması İşçiliği','M',5423.56,null),
('V.1300/A','Puzolan Katkılı Horasan Harcı ile Yonu Taşından 15 Cm. Genişliğe Kadar Düz veya Pahlı Söve Yapılması ve Yerine Konması İşçiliği','M',5493.45,null),
('V.1300/B','Hidrolik Kireç Harcı ile Yonu Taşından 15 Cm. Genişliğe Kadar Düz veya Pahlı Söve Yapılması ve Yerine Konması İşçiliği','M',5564.88,null),
('V.1301','Yonu Taşından 15 Cm. Genişliğe Kadar Silmeli Söve Yapılması ve Yerine Konması İşçiliği','M',6948.56,null),
('V.1301/A','Puzolan Katkılı Horasan Harcı ile Yonu Taşından 15 Cm. Genişliğe Kadar Silmeli Söve Yapılması ve Yerine Konması İşçiliği','M',7018.45,null),
('V.1301/B','Hidrolik Kireç Harcı ile Yonu Taşından 15 Cm. Genişliğe Kadar Silmeli Söve Yapılması ve Yerine Konması İşçiliği','M',7089.88,null),
('V.1302','Yonu Taşından 16-20 Cm. Arası Genişlikte Düz veya Pahlı Söve Yapılması ve Yerine Konması İşçiliği','M',6611.06,null),
('V.1302/A','Puzolan Katkılı Horasan Harcı ile Yonu Taşından 16-20 Cm. Arası Genişlikte Düz veya Pahlı Söve Yapılması ve Yerine Konması İşçiliği','M',6680.95,null),
('V.1302/B','Hidrolik Kireç Harcı ile Yonu Taşından 16-20 Cm. Arası Genişlikte Düz veya Pahlı Söve Yapılması ve Yerine Konması İşçiliği','M',6752.38,null),
('V.1303','Yonu Taşından 16-20 Cm. Arası Genişlikte Silmeli Söve Yapılması ve Yerine Konması İşçiliği','M',7711.06,null),
('V.1303/A','Puzolan Katkılı Horasan Harcı ile Yonu Taşından 16-20 Cm. Arası Genişlikte Silmeli Söve Yapılması ve Yerine Konması İşçiliği','M',7780.95,null),
('V.1303/B','Hidrolik Kireç Harcı ile Yonu Taşından 16-20 Cm. Arası Genişlikte Silmeli Söve Yapılması ve Yerine Konması','M',7852.38,null),
('V.1304','Yonu Taşından 21-25 Cm. Arası Genişlikte Düz veya Pahlı Söve Yapılması ve Yerine Konması İşçiliği','M',6992.31,null),
('V.1304/A','Puzolan Katkılı Horasan Harcı ile Yonu Taşından 21-25 Cm. Arası Genişlikte Düz veya Pahlı Söve Yapılması ve Yerine Konması İşçiliği','M',7062.2,null),
('V.1304/B','Hidrolik Kireç Harcı ile Yonu Taşından 21-25 Cm. Arası Genişlikte Düz veya Pahlı Söve Yapılması ve Yerine Konması İşçiliği','M',7133.63,null),
('V.1305','Yonu Taşından 21-25 Cm. Arası Genişlikte Silmeli Söve Yapılması ve Yerine Konması İşçiliği','M',8473.56,null),
('V.1305/A','Puzolan Katkılı Horasan Harcı ile Yonu Taşından 21-25 Cm. Arası Genişlikte Silmeli Söve Yapılması ve Yerine Konması İşçiliği','M',8543.45,null),
('V.1305/B','Hidrolik Kireç Harcı ile Yonu Taşından 21-25 Cm. Arası Genişlikte Silmeli Söve Yapılması ve Yerine Konması İşçiliği','M',8614.88,null),
('V.1306','Yonu Taşından 26-30 Cm. Arası Genişlikte Düz veya Pahlı Söve Yapılması ve Yerine Konması İşçiliği','M',8487.68,null),
('V.1306/A','Puzolan Katkılı Horasan Harcı ile Yonu Taşından 26-30 Cm. Arası Genişlikte Düz veya Pahlı Söve Yapılması ve Yerine Konması İşçiliği','M',8580.86,null),
('V.1306/B','Hidrolik Kireç Harcı ile Yonu Taşından 26-30 Cm. Arası Genişlikte Düz veya Pahlı Söve Yapılması ve Yerine Konması İşçiliği','M',8676.09,null),
('V.1307','Yonu Taşından 26-30 Cm. Arası Genişlikte Silmeli Söve Yapılması ve Yerine Konması İşçiliği','M',11668.93,null),
('V.1307/A','Puzolan Katkılı Horasan Harcı ile Yonu Taşından 26-30 Cm. Arası Genişlikte Silmeli Söve Yapılması ve Yerine Konması İşçiliği','M',11762.11,null),
('V.1307/B','Hidrolik Kireç Harcı ile Yonu Taşından 26-30 Cm. Arası Genişlikte Silmeli Söve Yapılması ve Yerine Konması İşçiliği','M',11857.34,null),
('V.1308','Yonu Taşından 31-35 Cm. Arası Genişlikte Düz veya Pahlı Söve Yapılması ve Yerine Konması İşçiliği','M',8934.55,null),
('V.1308/1','Puzolan Katkılı Horasan Harcı ile Yonu Taşından 31-35 Cm. Arası Genişlikte Düz veya Pahlı Söve Yapılması ve Yerine Konması İşçiliği','M',9027.74,null),
('V.1308/2','Hidrolik Kireç Harcı ile Yonu Taşından 31-35 Cm. Arası Genişlikte Düz veya Pahlı Söve Yapılması ve Yerine Konması İşçiliği','M',9122.96,null),
('V.1308/A','Yonu Taşından 35 Cm.den Yüksek Genişlikte Düz veya Pahlı Söve Yapılması ve Yerine Konması İşçiliği -64-','M',10906.43,null),
('V.1308/A1','Puzolan Katkılı Horasan Harcı ile Yonu Taşından 35 Cm.den Yüksek Genişlikte Düz veya Pahlı Söve Yapılması ve Yerine Konması İşçiliği','M',10999.61,null),
('V.1308/A2','Hidrolik Kireç Harcı ile Yonu Taşından 35 Cm.den Yüksek Genişlikte Düz veya Pahlı Söve Yapılması ve Yerine Konması İşçiliği','M',11094.84,null),
('V.1309','Yonu Taşından 31-35 Cm. Arası Genişlikte Silmeli Söve Yapılması ve Yerine Konması İşçiliği','M',10012.68,null),
('V.1309/1','Puzolan Katkılı Horasan Harcı ile Yonu Taşından 31-35 Cm. Arası Genişlikte Silmeli Söve Yapılması ve Yerine Konması İşçiliği','M',10105.86,null),
('V.1309/2','Hidrolik Kireç Harcı ile Yonu Taşından 31-35 Cm. Arası Genişlikte Silmeli Söve Yapılması ve Yerine Konması İşçiliği','M',10201.09,null),
('V.1309/A','Yonu Taşından 35 Cm.den Yüksek Genişlikte Silmeli Söve Yapılması ve Yerine Konması İşçiliği','M',13193.93,null),
('V.1309/A1','Puzolan Katkılı Horasan Harcı ile Yonu Taşından 35 Cm.den Yüksek Genişlikte Silmeli Söve Yapılması ve Yerine Konması İşçiliği','M',13287.11,null),
('V.1309/A2','Hidrolik Kireç Harcı ile Yonu Taşından 35 Cm.den Yüksek Genişlikte Silmeli Söve Yapılması ve Yerine Konması İşçiliği','M',13382.34,null),
('V.1310','Yonu Taşından Her Genişlikteki Mevcut Sövenin Islahı ve Yerine Konması İşçiliği','M',3179.81,null),
('V.1310/A','Puzolan Katkılı Horasan Harcı ile Yonu Taşından Her Genişlikteki Mevcut Sövenin Islahı ve Yerine Konması İşçiliği','M',3249.7,null),
('V.1310/B','Hidrolik Kireç Harcı ile Yonu Taşından Her Genişlikteki Mevcut Sövenin Islahı ve Yerine Konması İşçiliği','M',3321.13,null),
('V.1311','Yonu Taşından Her Genişlikteki Mevcut Sövenin Yerine Konması İşçiliği','M',1654.81,null),
('V.1311/A','Puzolan Katkılı Horasan Harcı ile Yonu Taşından Her Genişlikteki Mevcut Sövenin Yerine Konması İşçiliği','M',1724.7,null),
('V.1311/B','Hidrolik Kireç Harcı ile Yonu Taşından Her Genişlikteki Mevcut Sövenin Yerine Konması İşçiliği','M',1796.13,null),
('V.1312','Yonu Taşından Yığma Söve Yapılması İşçiliği Zammı','M',1650.0,null),
('V.1313','30 Cm. Genişliğe Kadar Yonu Taşı Silmeli Yığma Söve Yapılması İşçiliği Zammı','M',3300.0,null),
('V.1313/A','30 - 60 Cm. Arası Genişliğe Kadar ( 60 Cm. Dahil ) Yonu Taşı Silmeli Yığma Söve Yapılması İşçiliği Zammı','M',4950.0,null),
('V.1314','Yonu Taşından Pencere ve Kapıda Azami 25 Cm. Genişlikte Ara Lentosu Yapılması ve Yerine Konması İşçiliği','M',5437.68,null),
('V.1314/A','Puzolan Katkılı Horasan Harcı ile Yonu Taşından Pencere ve Kapıda Azami 25 Cm. Genişlikte Ara Lentosu Yapılması ve Yerine Konması İşçiliği','M',5530.86,null),
('V.1314/B','Hidrolik Kireç Harcı ile Yonu Taşından Pencere ve Kapıda Azami 25 Cm. Genişlikte Ara Lentosu Yapılması ve Yerine Konması İşçiliği','M',5626.09,null),
('V.1315/01','Yonu Taşı Sövede Parmaklık İçin Delik Açma İşçiliği','AD',182.66,null),
('V.1315/02','Ahşap Sövede Parmaklık İçin Delik Açma İşçiliği','AD',100.48,null),
('V.1315/03','Yonu Taşında Kenet İçin El İle Delik Açma İşçiliği','AD',77.0,null),
('V.1315/04','Yonu Taşında Zıvana İçin Delik Açma İşçiliği','AD',140.7,null),
('V.1315/05','Yonu Taşında Kurşun Dökülmesi İçin Kanal Açma İşçiliği','AD',82.5,null),
('V.1316/001','Her Türlü Taş ve Tuğla Duvarda, Betonda (Delik Çapı Ø25''e ve Derinliği 40cm'' ye kadar) Matkap İle Darbesiz ve Tahribatsız Delik Açılması İşçiliği',null,29.31,null),
('V.1316/002','Her Türlü Taş ve Tuğla Duvarda, Betonda Delik Çapı Ø25''e Kadar ve Derinliği 41-100cm (100cm dahil) arası Matkap İle Delik Açılması İşçiliği',null,58.61,null),
('V.1320/01','Çam Kerestesinden Ahşap Elemana (Delik Çapı Ø25''e Ve Derinliği 40cm'' Ye Kadar) Matkap İle Darbesiz Ve Tahribatsız Delik Açılması İşçiliği',null,29.31,null),
('V.1320/02','Meşe Kerestesinden Ahşap Elemana (Delik Çapı Ø25''e Ve Derinliği 40cm'' Ye Kadar) Matkap İle Darbesiz Ve Tahribatsız Delik Açılması İşçiliği -65-',null,43.54,null),
('V.1329','İ- HARPUŞTA, AYNA TAŞI, KÜLAH, TONOZ VE KUBBE İŞLERİ Yonu Taşı Tozu Ve Beyaz Çimento Harcı İle Pahlı Dişli Taraklı Ortalama 16 Cm Yüksekliğinde İmitasyon Harpuşta Yapılması','M²',6617.54,null),
('V.1329/001','Yonu Taşı Tozu Ve Beyaz Çimento Harcı İle Pahlı Dişli Taraklı Ortalama 25 Cm Yüksekliğinde İmitasyon Harpuşta Yapılması','M²',7693.6,null),
('V.1330','Yonu Taşından Basık, Masif Harpuşta Yapılması ve Yerine Konması İşçiliği','M²',12812.68,null),
('V.1330/01','Çimento Harcı İle Yonu Taşından Düz, Masif Harpuşta Yerine Konması İşçiliği','M²',7093.93,null),
('V.1330/02','Puzolan Katkılı Horasan Harcı ile Yonu Taşından Düz, Masif Harpuşta Yerine Konması İşçiliği','M²',7186.6,null),
('V.1330/03','Hidrolik Kireç Harcı ile Yonu Taşından Düz, Masif Harpuşta Yerine Konması İşçiliği','M²',7296.48,null),
('V.1330/A','Puzolan Katkılı Horasan Harcı ile Yonu Taşından Basık, Masif Harpuşta Yapılması ve Yerine Konması İşçiliği','M²',12905.35,null),
('V.1330/B','Hidrolik Kireç Harcı ile Yonu Taşından Basık, Masif Harpuşta Yapılması ve Yerine Konması İşçiliği','M²',13015.23,null),
('V.1331','Yonu Taşından Sivri, Masif Harpuşta Yapılması ve Yerine Konması İşçiliği (Ortalama Yüksekliği 20 Cm.den Yukarı)','M²',13956.43,null),
('V.1331/A','Puzolan Katkılı Horasan Harcı ile Yonu Taşından Sivri, Masif Harpuşta Yapılması ve Yerine Konması İşçiliği (Ortalama Yüksekliği 20 Cm.den Yukarı)','M²',14049.1,null),
('V.1331/B','Hidrolik Kireç Harcı ile Yonu Taşından Sivri, Masif Harpuşta Yapılması ve Yerine Konması İşçiliği (Ortalama Yüksekliği 20 Cm.den Yukarı)','M²',14158.98,null),
('V.1332','Yonu Taşından Hususi Öneme Haiz Masif, Barok Harpuşta Yapılması ve Yerine Konması İşçiliği','M²',18681.43,null),
('V.1332/A','Puzolan Katkılı Horasan Harcı ile Yonu Taşından Hususi Öneme Haiz Masif, Barok Harpuşta Yapılması ve Yerine Konması İşçiliği','M²',18774.1,null),
('V.1332/B','Hidrolik Kireç Harcı ile Yonu Taşından Hususi Öneme Haiz Masif, Barok Harpuşta Yapılması ve Yerine Konması İşçiliği','M²',18883.98,null),
('V.1333','Yonu Taşından Mevcut Barok Harpuştanın Islahı ve Yerine Konması İşçiliği','M²',8231.43,null),
('V.1333/1','Puzolan Katkılı Horasan Harcı ile Yonu Taşından Mevcut Barok Harpuştanın Islahı ve Yerine Konması İşçiliği','M²',8324.1,null),
('V.1333/2','Hidrolik Kireç Harcı ile Yonu Taşından Mevcut Barok Harpuştanın Islahı ve Yerine Konması İşçiliği','M²',8433.98,null),
('V.1333/A','Yonu Taşından Mevcut Basık ve Sivri Harpuştanın Islahı ve Yerine Konması İşçiliği','M²',5187.68,null),
('V.1333/A1','Puzolan Katkılı Horasan Harcı ile Yonu Taşından Mevcut Basık ve Sivri Harpuştanın Islahı ve Yerine Konması İşçiliği','M²',5280.35,null),
('V.1333/A2','Hidrolik Kireç Harcı ile Yonu Taşından Mevcut Basık ve Sivri Harpuştanın Islahı ve Yerine Konması İşçiliği','M²',5390.23,null),
('V.1334','Yonu Taşından Düz veya Pahlı Ayna Taşı Yapılması ve Yerine Konması İşçiliği','M²',11697.13,null),
('V.1334/A','Puzolan Katkılı Horasan Harcı ile Yonu Taşından Düz veya Pahlı Ayna Taşı Yapılması ve Yerine Konması İşçiliği','M²',11836.14,null),
('V.1334/B','Hidrolik Kireç Harcı ile Yonu Taşından Düz veya Pahlı Ayna Taşı Yapılması ve Yerine Konması İşçiliği','M²',12000.96,null),
('V.1335','Yonu Taşından Silmeli Ayna Taşı Yapılması ve Yerine Konması İşçiliği','M²',18090.88,null),
('V.1335/A','Puzolan Katkılı Horasan Harcı ile Yonu Taşından Silmeli Ayna Taşı Yapılması ve Yerine Konması İşçiliği','M²',18229.89,null),
('V.1335/B','Hidrolik Kireç Harcı ile Yonu Taşından Silmeli Ayna Taşı Yapılması ve Yerine Konması İşçiliği','M²',18394.71,null),
('V.1336','Yonu Taşından Mevcut Her Türlü Ayna Taşının Islahı ve Yerine Konması İşçiliği','M²',5509.63,null),
('V.1336/A','Puzolan Katkılı Horasan Harcı ile Yonu Taşından Mevcut Her Türlü Ayna Taşının Islahı ve Yerine Konması İşçiliği -66-','M²',5648.64,null),
('V.1336/B','Hidrolik Kireç Harcı ile Yonu Taşından Mevcut Her Türlü Ayna Taşının Islahı ve Yerine Konması İşçiliği','M²',5813.46,null),
('V.1337','Yonu Taşından Mevcut Ayna Taşının Yerine Konması İşçiliği','M²',3309.63,null),
('V.1337/A','Puzolan Katkılı Horasan Harcı ile Yonu Taşından Mevcut Ayna Taşının Yerine Konması İşçiliği','M²',3448.64,null),
('V.1337/B','Hidrolik Kireç Harcı ile Yonu Taşından Mevcut Ayna Taşının Yerine Konması İşçiliği','M²',3613.46,null),
('V.1338','Yonu Taşından Çimentolu Horasan Harç Dolgulu Geometrik Desenli Ayna Taşı Yapılması ve Yerine Konması İşçiliği','M²',31438.0,null),
('V.1338/1','Puzolan Katkılı Horasan Harcı ile Yonu Taşından Puzolan Katkılı Horasan Harç Dolgulu Geometrik Desenli Ayna Taşı Yapılması ve Yerine Konması İşçiliği','M²',31573.19,null),
('V.1338/2','Hidrolik Kireç Harcı ile Yonu Taşından Hidrolik Kireç Harç Dolgulu Geometrik Desenli Ayna Taşı Yapılması ve Yerine Konması İşçiliği','M²',31792.96,null),
('V.1338/A','Yonu Taşından Renklı Taş Dolgulu Geometrik Desenli Ayna Taşının Yapılması ve Yerine Konması İşçiliği','M²',39609.63,null),
('V.1338/A1','Puzolan Katkılı Horasan Harcı ile Yonu Taşından Renklı Taş Dolgulu Geometrik Desenli Ayna Taşının Yapılması ve Yerine Konması İşçiliği','M²',39748.64,null),
('V.1338/A2','Hidrolik Kireç Harcı ile Yonu Taşından Renklı Taş Dolgulu Geometrik Desenli Ayna Taşının Yapılması ve Yerine Konması İşçiliği','M²',39913.46,null),
('V.1339','Yonu Taşından, Çimentolu Horasan Harç Dolgulu, Yazı ve/veya Nebati Tezyinatlı Ayna Taşının Yapılması ve Yerine Konması İşçiliği','M²',38038.0,null),
('V.1339/1','Yonu Taşından, Puzolan Katkılı Horasan Harç Dolgulu, Yazı ve/veya Nebati Tezyinatlı Ayna Taşının Yapılması ve Yerine Konması İşçiliği','M²',38173.19,null),
('V.1339/2','Yonu Taşından, Hidrolik Kireç Harç Dolgulu, Yazı ve/veya Nebati Tezyinatlı Ayna Taşının Yapılması ve Yerine Konması İşçiliği','M²',38392.96,null),
('V.1339/A','Yonu Taşından Renkli Taş Dolgulu, Yazı ve/veya Nebati Tezyinatlı Ayna Taşının Yapılması ve Yerine Konması İşçiliği','M²',47309.63,null),
('V.1339/A1','Puzolan Katkılı Horasan Harcı ile Yonu Taşından Renkli Taş Dolgulu, Yazı ve/veya Nebati Tezyinatlı Ayna Taşının Yapılması ve Yerine Konması İşçiliği','M²',47448.64,null),
('V.1339/A2','Hidrolik Kireç Harcı ile Yonu Taşından Renkli Taş Dolgulu, Yazı ve/veya Nebati Tezyinatlı Ayna Taşının Yapılması ve Yerine Konması İşçiliği','M²',47613.46,null),
('V.1340','Yonu Taşından İçi ve Dişi İşlenmiş Tonoz Yapılması İşçiliği','M²',17694.26,null),
('V.1340/1','Puzolan Katkılı Horasan Harç ile Yonu Taşından İçi ve Dişı İşlenmiş Tonoz Yapılması İşçiliği','M²',17972.29,null),
('V.1340/2','Hidrolik Kiraç Harcı ile Yonu Taşından İçi ve Dişı İşlenmiş Tonoz Yapılması İşçiliği','M²',18301.94,null),
('V.1340/A','Yonu Taşı Tonoz Üst Kaplaması Yapılması ve Yerine Konulması İşçiliği','M²',14394.26,null),
('V.1340/A1','Puzolan Katkılı Horasan Harcı ile Yonu Taşı Tonoz Üst Kaplaması Yapılması ve Yerine Konulması İşçiliği','M²',14672.29,null),
('V.1340/A2','Hidrolik Kireç Harcı ile Yonu Taşı Tonoz Üst Kaplaması Yapılması ve Yerine Konulması İşçiliği','M²',15001.94,null),
('V.1341','Yonu Taşından İçi ve Dışı İşlenmiş Haçvari Tonoz Yapılması İşçiliği','M²',21469.26,null),
('V.1341/1','Puzolan Katkılı Horasan Harcı ile Yonu Taşından İçi ve Dışı İşlenmiş Haçvari Tonoz Yapılması İşçiliği','M²',21747.29,null),
('V.1341/2','Hidrolik Kireç Harcı ile Yonu Taşından İçi ve Dişi İşlenmiş Haçvari Tonoz Yapılması İşçiliği','M²',22076.94,null),
('V.1341/A','Yonu Taşından Yalnız İçi İşlenmiş Haçvari Tonoz Yapılması İşçiliği (Yonu Taşı Hariç)','M²',13019.26,null),
('V.1341/A1','Puzolan Katkılı Horasan Harcı ile Yonu Taşından Yalnız İçi İşlenmiş Haçvari Tonoz Yapılması İşçiliği (Yonu Taşı Hariç)','M²',13297.29,null),
('V.1341/A2','Hidrolik Kireç Harcı ile Yonu Taşından Yalnız İçi İşlenmiş Haçvari Tonoz Yapılması İşçiliği (Yonu Taşı Hariç)','M²',13626.94,null),
('V.1342','Yonu Taşından Yalnız İçi İşlenmiş Tonoz Yapılması İşçiliği -67-','M²',11369.26,null),
('V.1342/A','Puzolan Katkılı Horasan Harcı ile Yonu Taşından Yalnız İçi İşlenmiş Tonoz Yapılması İşçiliği','M²',11647.29,null),
('V.1342/B','Hidrolik Kireç Harcı ile Yonu Taşından Yalnız İçi İşlenmiş Tonoz Yapılması İşçiliği','M²',11976.94,null),
('V.1344','Yonu Taşından İçi ve Dışı İşlenmiş Demir Kenetli Köşeli Külah Yapılması İşçiliği','M²',29093.93,null),
('V.1344/A','Puzolan Katkılı Horasan Harcı ile Yonu Taşından İçi ve Dışı İşlenmiş Demir Kenetli Köşeli Külah Yapılması İşçiliği','M²',29186.6,null),
('V.1344/B','Hidrolik Kireç Harcı ile Yonu Taşından İçi ve Dışı İşlenmiş Demir Kenetli Köşeli Külah Yapılması İşçiliği','M²',29296.48,null),
('V.1345','Yonu Taşından Yalnız İçi İşlenmiş Demir Kenetli Köşeli Külah Yapılması İşçiliği','M²',18206.76,null),
('V.1345/A','Puzolan Katkılı Horasan Harcı ile Yonu Taşından Yalnız İçi İşlenmiş Demir Kenetli Köşeli Külah Yapılması İşçiliği','M²',18484.79,null),
('V.1345/B','Hidrolik Kiraç Harcı ileYonu Taşından Yalnız İçi İşlenmiş Demir Kenetli Köşeli Külah Yapılması İşçiliği','M²',18814.44,null),
('V.1346','Yonu Taşından İçi ve Dışı İşlenmiş Demir Kenetli Mahruti Külah Yapılması İşçiliği','M²',29643.93,null),
('V.1346/A','Puzolan Katkılı Horasan Harcı ile Yonu Taşından İçi ve Dışı İşlenmiş Demir Kenetli Mahruti Külah Yapılması İşçiliği','M²',29736.6,null),
('V.1346/B','Hidrolik Kireç Harcı ile Yonu Taşından İçi ve Dışı İşlenmiş Demir Kenetli Mahruti Külah Yapılması İşçiliği','M²',29846.48,null),
('V.1347','Yonu Taşından Yalnız İçi İşlenmiş Demir Kenetli Mahruti Külah Yapılması İşçiliği','M²',18756.76,null),
('V.1347/A','Puzolan Katkılı Horasan Harcı ile Yonu Taşından Yalnız İçi İşlenmiş Demir Kenetli Mahruti Külah Yapılması İşçiliği','M²',19034.79,null),
('V.1347/B','Hidrolik Kireç Harcı ile Yonu Taşından Yalnız İçi İşlenmiş Demir Kenetli Mahruti Külah Yapılması İşçiliği','M²',19364.44,null),
('V.1348','Yonu Taşından İçi ve Dışı İşlenmiş Kubbe Yapılması İşçiliği','M²',24400.18,null),
('V.1348/A','Puzolan Katkılı Horasan Harcı ile Yonu Taşından İçi ve Dışı İşlenmiş Kubbe Yapılması İşçiliği','M²',24492.85,null),
('V.1348/B','Hidrolik Kireç Harcı ile Yonu Taşından İçi ve Dışı İşlenmiş Kubbe Yapılması İşçiliği','M²',24602.73,null),
('V.1349','Yonu Taşından Yalnız İçi İşlenmiş Kubbe Yapılması İşçiliği','M²',14063.01,null),
('V.1349/1','Puzolan Katkılı Horasan Harcı ile Yonu Taşından Yalnız İçi İşlenmiş Kubbe Yapılması İşçiliği','M²',14341.04,null),
('V.1349/2','Hidrolik Kireç Harcı ile Yonu Taşından Yalnız İçi İşlenmiş Kubbe Yapılması İşçiliği','M²',14670.69,null),
('V.1349/A01','8-15 Cm Yonu Taşı Kubbe Üst Kaplaması Yapılması ve Yerine Konması İşçiliği','M²',10800.51,null),
('V.1349/A02','8-15 Cm Puzolan Katkılı Horasan Harcı ile Yonu Taşı Kubbe Üst Kaplaması Yapılması ve Yerine Konması İşçiliği','M²',15478.54,null),
('V.1349/A03','8-15 Cm Hidrolik Kireç Harcı ile Yonu Taşı Kubbe Üst Kaplaması Yapılması ve Yerine Konması İşçiliği J- MUHTELİF İMALATLAR','M²',15808.19,null),
('V.1375','Yonu Taşından Şerefe Altı ve Başlıktan Gayri Silme Tromp ve Kubbeler İle Benzeri Yerlerde, Demir Kenetli Stalâktit Yapılması İşçiliği','M²',74791.05,null),
('V.1375/A','Puzolan Katkılı Horasan Harcı ile Yonu Taşından Şerefe Altı ve Başlıktan Gayri Silme Tromp ve Kubbeler İle Benzeri Yerlerde, Demir Kenetli Stalâktit Yapılması İşçiliği','M²',75022.74,null),
('V.1375/B','Hidrolik Kireç Harcı ile Yonu Taşından Şerefe Altı ve Başlıktan Gayri Silme Tromp ve Kubbeler İle Benzeri Yerlerde, Demir Kenetli Stalâktit Yapılması İşçiliği','M²',75297.45,null),
('V.1376','Yonu Taşından Portalde Kurşunlu ve Kenetli Stalâktit Yapılması İşçiliği','M²',87403.55,null),
('V.1376/A','Puzolan Katkılı Horasan Harcı ile Yonu Taşından Portalde Kurşunlu ve Kenetli Stalâktit Yapılması İşçiliği -68-','M²',87635.24,null),
('V.1376/B','Hidrolik Kireç Harcı ile Yonu Taşından Portalde Kurşunlu ve Kenetli Stalâktit Yapılması İşçiliği','M²',87909.95,null),
('V.1377/1','Yonu Taşından 400 Doz Çimento Harcı İle Temizi 25-30 Cm. Arası(30 Cm.Dahil) Genişlikte, 15- 25cm Yüksekliğinde (25 Cm. Dahil) Bordür Yapılması Ve Yerine Konması İşçiliği','M',2708.11,null),
('V.1377/2','Yonu Taşından 400 Doz Çimento Harcı İle Temizi 25-30 Cm. Arası(30 Cm.Dahil) Genişlikte, 15- 25cm Yüksekliğinde (25 Cm. Dahil) Yekpare Masif Basamak Taşının Yapılması Ve Yerine Konması İşçiliği','M',4423.74,null),
('V.1377/A1','Puzolan Katkılı Horasan Harcı İle Yonu Taşından Temizi 25-30 Cm. Arası(30 Cm.Dahil) Genişlikte, 15- 25cm Yüksekliğinde (25 Cm. Dahil) Bordür Yapılması Ve Yerine Konması İşçiliği','M',2870.29,null),
('V.1377/A2','Puzolan Katkılı Horasan Harcı İle Yonu Taşından Temizi 25-30 Cm. Arası(30 Cm.Dahil) Genişlikte, 15- 25cm Yüksekliğinde (25 Cm. Dahil) Yekpare Masif Basamak Taşının Yapılması Ve Yerine Konması İşçiliği','M',4585.91,null),
('V.1377/B1','Hidrolik Kireç Harcı İle Yonu Taşından 25-30 Cm. Arası(30 Cm.Dahil) Genişlikte, 15- 25cm Yüksekliğinde (25 Cm. Dahil) Bordür Taşının Yapılması Ve Yerine Konması İşçiliği','M',3062.59,null),
('V.1377/B2','Hidrolik Kireç Harcı İle Yonu Taşından 25-30 Cm. Arası(30 Cm.Dahil) Genişlikte, 15- 25cm Yüksekliğinde (25 Cm. Dahil) Yekpare Masif Basamak Taşının Yapılması Ve Yerine Konması İşçiliği','M',4778.21,null),
('V.1378/1','400 Doz Çimento Harcı İle Yonu Taşından Temizi 10-15cm Genişliğinde 15- 25cm Yüksekliğinde (25 Cm. Dahil) Bordür Taşının Yapılması Ve Yerine Konması İşçiliği','M',1347.0,null),
('V.1378/2','Yonu Taşından Temizi 10-15cm Genişliğinde 15- 25cm Yüksekliğinde (25 Cm. Dahil) Yekpare Masif Basamak Taşının Yapılması Ve Yerine Konması İşçiliği','M',2268.88,null),
('V.1378/A1','Puzolan Katkılı Horasan Harcı İle Yonu Taşından Temizi 10-15cm (15 Cm Dahil) Genişliğinde 15- 25cm Yüksekliğinde (25 Cm. Dahil) Bordür Taşının Yapılması Ve Yerine Konması İşçiliği','M',1416.51,null),
('V.1378/A2','Puzolan Katkılı Horasan Harcı İle Yonu Taşından Temizi 10-15cm (15 Cm Dahil) Genişliğinde 15- 25cm Yüksekliğinde (25 Cm. Dahil) Yekpare Masif Basamak Taşının Yapılması Ve Yerine Konması İşçiliği','M',2338.39,null),
('V.1378/B1','Hidrolik Kireç Harcı İle Yonu Taşından Temizi 10-15cm Genişliğinde 15- 25cm Yüksekliğinde (25 Cm. Dahil) Bordür Taşının Yapılması Ve Yerine Konması İşçiliği','M',1498.93,null),
('V.1378/B2','Hidrolik Kireç Harcı İle Yonu Taşından Temizi 10-15cm Genişliğinde 15- 25cm Yüksekliğinde (25 Cm. Dahil) Yekpare Masif Basamak Taşının Yapılması Ve Yerine Konması İşçiliği','M',2420.8,null),
('V.1379/1','Yonu Taşından, Her Genişlikte, Mevcut Basamak Veya Bordür Taşının Islahı Ve Yerine Konması İşçiliği','M',2261.24,null),
('V.1379/A1','Puzolan Katkılı Kireç Harcı İle Yonu Taşından, Her Genişlikte, Mevcut Basamak Veya Bordür Taşının Islahı Ve Yerine Konması İşçiliği','M',2423.41,null),
('V.1379/B1','Hidrolik Kireç Harcı İle Yonu Taşından, Her Genişlikte, Mevcut Basamak Veya Bordür Taşının Islahı Ve Yerine Konması İşçiliği','M',2615.71,null),
('V.1380','Yonu Taşından 35x30x30 Cm. Ölçüsünde Kenarları Pahlı Prizmatik Abdest Alma Oturak Taşı Yapılması ve Yerine Konması İşçiliği','AD',9053.21,null),
('V.1380/A','Puzolan Katkılı Horasan Harcı ile Yonu Taşından 35x30x30 Cm. Ölçüsünde Kenarları Pahlı Prizmatik Abdest Alma Oturak Taşı Yapılması ve Yerine Konması İşçiliği','AD',9099.55,null),
('V.1380/B','Hidrolik Kireç Katkılı Horasan Harcı ile Yonu Taşından 35x30x30 Cm. Ölçüsünde Kenarları Pahlı Prizmatik Abdest Alma Oturak Taşı Yapılması ve Yerine Konması İşçiliği','AD',9154.49,null),
('V.1380/C','Yonu Taşından 30 cm''e Kadar Çapta ve 35 cm Yüksekliğe Kadar Ölçüde Silindirik Abdest Alma Oturak Taşı Yapılması ve Yerine Konması İşçiliği','AD',12103.21,null),
('V.1380/D','Puzolan Katkılı Horasan Harcı ile Yonu Taşından 30 cm''e Kadar Çapta ve 35 cm Yüksekliğe Kadar Ölçüde Silindirik Abdest Alma Oturak Taşı Yapılması ve Yerine Konması İşçiliği -69-','AD',12149.55,null),
('V.1380/E','Hidrolik Kireç Katkılı Horasan Harcı ile Yonu Taşından 30 cm''e Kadar Çapta ve 35 cm Yüksekliğe Kadar Ölçüde Silindirik Abdest Alma Oturak Taşı Yapılması ve Yerine Konması İşçiliği','AD',12204.49,null),
('V.1381','Yonu Taşından Azami 80x80 Cm. Dış Kesitinde Demirli ve Kenetli Baca ve Düz Baca Külahı Yapılması ve Yerine Konulması İşçiliği','M²',14425.18,null),
('V.1381/1','Puzolan Katkılı Horasan Harcı ile Yonu Taşından Azami 80x80 Cm. Dış Kesitinde Demirli ve Kenetli Baca ve Düz Baca Külahı Yapılması ve Yerine Konulması İşçiliği','M²',14517.85,null),
('V.1381/2','Hidrolik Kireç Katkılı Horasan Harcı ile Yonu Taşından Azami 80x80 Cm. Dış Kesitinde Demirli ve Kenetli Baca ve Düz Baca Külahı Yapılması ve Yerine Konulması İşçiliği','M²',14627.73,null),
('V.1381/A','Yonu Taşından Azami 80x80 Cm. den Daha Büyük Dış Kesitte En Çok Dört Parçalı, Demirli ve Kenetli Baca ve Düz Baca Külahı Yapılması ve Yerine Konulması İşçiliği','M²',15568.93,null),
('V.1381/A1','Puzolan Katkılı Horasan Harcı ile Yonu Taşından Azami 80x80 Cm. den Daha Büyük Dış Kesitte En Çok Dört Parçalı, Demirli ve Kenetli Baca ve Düz Baca Külahı Yapılması ve Yerine Konulması İşçiliği','M²',15661.6,null),
('V.1381/A2','Hidrolik Kireç Katkılı Horasan Harcı ile Yonu Taşından Azami 80x80 Cm. den Daha Büyük Dış Kesitte En Çok Dört Parçalı, Demirli ve Kenetli Baca ve Düz Baca Külahı Yapılması ve Yerine Konulması İşçiliği','M²',15771.48,null),
('V.1382','Yonu Taşı Bacalarda Yan Duman Deliği Açılması','AD',1174.5,null),
('V.1383','Düz Satıhlı İçi ve Dışı Temiz Tek veya Çift Parça Yonu Taşı Ocak Kemeri Yapılması ve Yerine Konulması İşçiliği','M²',11996.58,null),
('V.1383/A','Puzolan Katkılı Horasan Harcı ile Düz Satıhlı İçi ve Dışı Temiz Tek veya Çift Parça Yonu Taşı Ocak Kemeri Yapılması ve Yerine Konulması İşçiliği','M²',12001.2,null),
('V.1383/B','Hidrolik Kireç Katkılı Horasan Harcı ile Düz Satıhlı İçi ve Dışı Temiz Tek veya Çift Parça Yonu Taşı Ocak Kemeri Yapılması ve Yerine Konulması İşçiliği','M²',12006.7,null),
('V.1384','Farisi Köşeli İçi ve Dışı Temiz, İki veya Çok Parçalı Yonu Taşı Ocak Kemeri Yapılması ve Yerine Konması İşçiliği','M²',21671.58,null),
('V.1384/A','Puzolan Katkılı Horasan Harcı ile Farisi Köşeli İçi ve Dışı Temiz, İki veya Çok Parçalı Yonu Taşı Ocak Kemeri Yapılması ve Yerine Konması İşçiliği','M²',21676.2,null),
('V.1384/B','Hidrolik Kireç Katkılı Horasan Harcı ile Farisi Köşeli İçi ve Dışı Temiz, İki veya Çok Parçalı Yonu Taşı Ocak Kemeri Yapılması ve Yerine Konması İşçiliği','M²',21681.7,null),
('V.1385','Düz Satıhlı İçi ve Dışı Temiz, Tek veya Çok Parçalı, Kemerli, Profilli Yonu Taşı Ocak Kemeri Yapılması ve Yerine Konulması İşçiliği','M²',21927.83,null),
('V.1385/A','Puzolan Katkılı Horasan Harcı ile Düz Satıhlı İçi ve Dışı Temiz, Tek veya Çok Parçalı, Kemerli, Profilli Yonu Taşı Ocak Kemeri Yapılması ve Yerine Konulması İşçiliği','M²',21932.45,null),
('V.1385/B','Hidrolik Kireç Katkılı Horasan Harcı ile Düz Satıhlı İçi ve Dışı Temiz, Tek veya Çok Parçalı, Kemerli, Profilli Yonu Taşı Ocak Kemeri Yapılması ve Yerine Konulması İşçiliği','M²',21937.95,null),
('V.1386','Düz Satıhlı İçi ve Dışı Temiz, Tek veya Çift Parça Yonu Taşı Ocak Yaşmağı Yapılması ve Yerine Konulması İşçiliği','M²',14371.58,null),
('V.1386/A','Puzolan Katkılı Horasan Harcı ile Düz Satıhlı İçi ve Dışı Temiz, Tek veya Çift Parça Yonu Taşı Ocak Yaşmağı Yapılması ve Yerine Konulması İşçiliği -70-','M²',14376.2,null),
('V.1386/B','Hidrolik Kireç Katkılı Horasan Harcı ile Düz Satıhlı İçi ve Dışı Temiz, Tek veya Çift Parça Yonu Taşı Ocak Yaşmağı Yapılması ve Yerine Konulması İşçiliği','M²',14381.7,null),
('V.1387','Farisili Köşeli İçi ve Dışı Temiz, İki veya Çok Parçalı Yonu Taşı Ocak Yaşmağı Yapılması ve Yerine Konulması İşçiliği','M²',20090.33,null),
('V.1387/A','Puzolan Katkılı Horasan Harcı ile Farisili Köşeli İçi ve Dışı Temiz, İki veya Çok Parçalı Yonu Taşı Ocak Yaşmağı Yapılması ve Yerine Konulması İşçiliği','M²',20094.95,null),
('V.1387/B','Hidrolik Kireç Katkılı Horasan Harcı ile Farisili Köşeli İçi ve Dışı Temiz, İki veya Çok Parçalı Yonu Taşı Ocak Yaşmağı Yapılması ve Yerine Konulması İşçiliği','M²',20100.45,null),
('V.1400','K- SOM İMALATLAR Yonu Taşından Düz Ayak veya Benzeri Som İmalat Yapılması İşçiliği','M²',18265.88,null),
('V.1400/A','Puzolan Katkılı Horasan Harcı ile Yonu Taşından Düz Ayak veya Benzeri Som İmalat Yapılması İşçiliği','M²',18404.89,null),
('V.1400/B','Hidrolik Kireç Katkılı Horasan Harcı ile Yonu Taşından Düz Ayak veya Benzeri Som İmalat Yapılması İşçiliği','M²',18569.71,null),
('V.1401','Yonu Taşından Münhani veya Farisi Ayak veya Benzeri Som İmalat Yapılması İşçiliği','M²',20172.13,null),
('V.1401/A','Puzolan Katkılı Horasan Harcı ile Yonu Taşından Münhani veya Farisi Ayak veya Benzeri Som İmalat Yapılması İşçiliği','M²',20311.14,null),
('V.1401/B','Hidrolik Kireç Katkılı Horasan Harcı ile Yonu Taşından Münhani veya Farisi Ayak veya Benzeri Som İmalat Yapılması İşçiliği','M²',20475.96,null),
('V.1402','Yonu Taşından Basit Kurna Yapılması İşçiliği','AD',18112.5,null),
('V.1403','Yonu Taşından Klasik Kurna Yapılması İşçiliği','AD',28012.5,null),
('V.1415','L- YONU TAŞI ÜZERİNE İŞLEMELER Yonu Taşı Satıhlarda Her Genişlik ve Derinlikte Oluk Açılması İşçiliği','M²',5718.75,null),
('V.1416','Yonu Taşı Üzerine 3 Cm. Derinliğe Kadar Hendesi Tezyinat İşlenmesi','M²',33000.0,null),
('V.1417','Yonu Taşı Üzerine 3 Cm. Derinliğe Kadar Yazı Yazılması veya Nebati Tezyinat İşlenmesi İşçiliği','M²',44000.0,null),
('V.1418','Her Boydaki Yonu Taşı Kemer Taşlarında Diş Açılması','AD',550.0,null),
('V.1419','Her Boydaki Yonu Taşı Kemer Taşlarına veya Sövelerde İki Yan Dişleri İle Birlikte Makara Yapılması İşçiliği','AD',1650.0,null),
('V.1420','Her Nevi Yonu Taşı Satıhta 2-5 Cm. Genişlikte Tek Pah Açılması İşçiliği','M',825.0,null),
('V.1420/A','Her Nevi Yonu Taşı Satıhta 5-10 Cm. Genişlikte Tek Pah Açılması İşçiliği','M',1100.0,null),
('V.1420/B','Her Nevi Yonu Taşı Satıhta 2-5 Cm. Genişlikte Diş Açılması İşçiliği','M',1100.0,null),
('V.1420/C','Her Nevi Yonu Taşı Satıhta 5-10 Cm. Genişlikte Diş Açılması İşçiliği','M',1650.0,null),
('V.1420/D','Her Nevi Yonu Taşı Satıhta 10-15 Cm. Genişlikte Diş Açılması İşçiliği','M',2200.0,null),
('V.1421','Her Nevi Yonu Taşı Satıhta 4-8 Cm. Yükseklikte ve Her Genişlikte Yuvarlak Üçgen veya Çok Kenarlı Kabartma Fitil Yapılması İşçiliği -71-','M',6600.0,null),
('V.1430/01','16- MERMER İŞLERİ A- MERMER KAPLAMALAR Mermerden Çimento Harçlı 30-40-50cmxserbest boy 5-8 Cm. Kalınlıkta Duvar Kaplaması Yapılması İşçiliği','M²',2097.19,null),
('V.1430/02','Mermerden Çimento Harçlı 30-40cmxserbest boy 9-12 Cm. Kalınlıkta Duvar Kaplaması Yapılması İşçiliği','M²',3306.56,null),
('V.1430/03','Mermerden Çimento Harçlı 50cmxserbest boy 9-12 Cm. Kalınlıkta Duvar Kaplaması Yapılması İşçiliği','M²',3911.25,null),
('V.1430/04','Çimento Harcı İle Düz Satıhta Çürütülen Yerlerde Mermer Kaplaması Yapılması İşçiliği','M²',5000.63,null),
('V.1430/B01','500 Doz Hidrolik Kireç Harcı ile 30-40-50cmxserbest boy Mermerden 5-8Cm. Kalınlıkta Duvar Kaplaması Yapılması İşçiliği','M²',2440.29,null),
('V.1430/B02','500 Doz Hidrolik Kireç Harcı ile 30-40cmxserbest boy Mermerden 9-12Cm. Kalınlıkta Duvar Kaplaması Yapılması İşçiliği','M²',3649.66,null),
('V.1430/B03','500 Doz Hidrolik Kireç Harcı ile 50cmxserbest boy Mermerden 9-12Cm. Kalınlıkta Duvar Kaplaması Yapılması İşçiliği','M²',4254.35,null),
('V.1430/B04','500 Doz Hidrolik Kireç Harcı ile Düz Satıhta Çürütülen Yerlerde Mermer Kaplaması Yapılması İşçiliği','M²',5686.83,null),
('V.1431/001','Çimento Harcı İle 2 Cm. Kalınlıkta 40CmX80Cm Beyaz Mermer Plakalarla Hamamda Duvar Kaplaması Yapılması İşçiliği','M²',3514.66,null),
('V.1431/B001','500 Doz Hidrolik Kireç Harcı ile 2 Cm. Kalınlıkta 40CmX80Cm Beyaz Mermer Plakalarla Hamamda Duvar Kaplaması Yapılması İşçiliği','M²',3985.89,null),
('V.1432/001','Çimento Harcı İle 3 Cm. Kalınlıkta 40CmX80Cm Beyaz Mermer Plakalarla Hamamda Döşeme Yapılması İşçiliği','M²',3978.79,null),
('V.1432/B001','500 Doz Hidrolik Kireç Harcı ile 3 Cm. Kalınlıkta 40CmX80Cm Beyaz Mermer Plakalarla Hamamda Döşeme Yapılması İşçiliği','M²',4321.89,null),
('V.1433/001','Çimento Harcı İle 4 Cm. Kalınlıkta 40CmX80Cm Beyaz Mermer Plakalarla Hamamda Döşeme Yapılması İşçiliği','M²',4225.19,null),
('V.1433/B001','500 Doz Hidrolik Kireç Harcı ile 4 Cm. Kalınlıkta 40CmX80Cm Beyaz Mermer Plakalarla Hamamda Döşeme Yapılması İşçiliği','M²',4568.29,null),
('V.1435','B- MERMER KORKULUKLAR Mermerden Kurşunlu ve Kenetli Kavisli İki Yüzü Düz Korkuluk Yapılması ve Yerine Konması İşçiliği','M²',26330.44,null),
('V.1435/1','500 Doz Hidrolik Kireç Harcı ile Mermerden Kurşunlu ve Kenetli Kavisli İki Yüzü Düz Korkuluk Yapılması ve Yerine Konması İşçiliği','M²',26353.31,null),
('V.1435/A','Mermerden Düz Korkuluk Yapılması ve Yerine Konması İşçiliği','M²',33436.69,null),
('V.1435/A1','500 Doz Hidrolik Kireç Harcı ile Mermerden Düz Korkuluk Yapılması ve Yerine Konması İşçiliği','M²',33459.56,null),
('V.1436','Mermerden Tek Yüzü Profilli, Kurşunlu ve Kenetli Düz Korkuluk Yapılması ve Yerine Konması İşçiliği','M²',32380.44,null),
('V.1436/A','500 Doz Hidrolik Kireç Harcı ile Mermerden Tek Yüzü Profilli, Kurşunlu ve Kenetli Düz Korkuluk Yapılması ve Yerine Konması İşçiliği','M²',32403.31,null),
('V.1437','Mermerden İki Yüzü Profilli, Kurşunlu ve Kenetli Düz Korkuluk Yapılması ve Yerine Konması İşçiliği','M²',42830.44,null),
('V.1437/A','500 Doz Hidrolik Kireç Harcı ile Mermerden İki Yüzü Profilli, Kurşunlu ve Kenetli Düz Korkuluk Yapılması ve Yerine Konması İşçiliği','M²',42853.31,null),
('V.1438','Mermerden Kurşunlu ve Kenetli, Tek Yüzü Profilli ve Oymalı Korkuluk Yapılması ve Yerine Konması İşçiliği','M²',52730.44,null),
('V.1438/A','500 Doz Hidrolik Kireç Harcı ile Mermerden Kurşunlu ve Kenetli, Tek Yüzü Profilli ve Oymalı Korkuluk Yapılması ve Yerine Konması İşçiliği','M²',52753.31,null),
('V.1439','Mermerden Kurşunlu ve Kenetli, İki Yüzü Profilli ve Oymalı Korkuluk Yapılması ve Yerine Konması İşçiliği','M²',100580.44,null),
('V.1439/A','500 Doz Hidrolik Kireç Harcı ile Mermerden Kurşunlu ve Kenetli, İki Yüzü Profilli ve Oymalı Korkuluk Yapılması ve Yerine Konması İşçiliği','M²',100603.31,null),
('V.1440','Mermerden Tek Yüzü Profilli ve Oymalı, Kurşunlu ve Kenetli Şebekeli Korkuluk Yapılması ve Yerine Konması İşçiliği -72-','M²',98930.44,null),
('V.1440/A','500 Doz Hidrolik Kireç Harcı ile Mermerden Tek Yüzü Profilli ve Oymalı, Kurşunlu ve Kenetli Şebekeli Korkuluk Yapılması ve Yerine Konması İşçiliği','M²',98953.31,null),
('V.1441','Mermerden İki Yüzü Profilli ve Pahlı, Kurşunlu ve Kenetli Şebekeli Korkuluk Yapılması ve Yerine Konması İşçiliği','M²',143480.44,null),
('V.1441/A','500 Doz Hidrolik Kireç Harcı ile Mermerden İki Yüzü Profilli ve Pahlı, Kurşunlu ve Kenetli Şebekeli Korkuluk Yapılması ve Yerine Konması İşçiliği','M²',143503.31,null),
('V.1442','Mermerden Mevcut Her Türlü Korkuluğun Alıştırılıp Kurşunlu ve Kenetli Olarak Yerine Konması İşçiliği','M²',16942.94,null),
('V.1442/A','500 Doz Hidrolik Kireç Harcı ile Mermerden Mevcut Her Türlü Korkuluğun Alıştırılıp Kurşunlu ve Kenetli Olarak Yerine Konması İşçiliği','M²',16965.81,null),
('V.1460','C- MERMERDEN BAŞLIK VE SÜTUNLAR Mermerden 40 Cm.Yüksekliğe Kadar (40 Cm. Dahil) Kurşunlu ve Kenetli Stalâktitli Başlık Yapılması ve Yerine Konması İşçiliği','AD',118431.25,null),
('V.1461','Mermerden 40 Cm. Yüksekliğe Kadar(40 Cm. Dahil) Kurşunlu ve Kenetli Baklavalı Başlık Yapılması ve Yerine Konması İşçiliği','AD',57931.25,null),
('V.1462','Mermerden 40 Cm.Yüksekliğe Kadar (40 Cm. Dahil) Kurşunlu ve Kenetli Düz Başlık Yapılması ve Yerine Konması İşçiliği','AD',28781.25,null),
('V.1463','Mermerden 40 Cm. Yüksekliğe Kadar(40 Cm. Dahil) Kurşunlu Kenetli Profilli Sütun Kaidesi Yapılması ve Yerine Konması İşçiliği','AD',40112.5,null),
('V.1464','Mermerden 40 Cm. Yüksekliğe Kadar (40 Cm. Dahil) Kurşunlu ve Kenetli Basit Sütun Kaidesi Yapılması ve Yerine Konması İşçiliği','AD',24712.5,null),
('V.1465','Mermerden 41-60 Cm. Arası Yükseklikte Kurşunlu ve Kenetli Stalâktitli Başlık Yapılması ve Yerine Konması İşçiliği','AD',148387.5,null),
('V.1466','Mermerden 41-60 Cm. Arası Yükseklikte Kurşunlu Kenetli ve Baklavalı Başlık Yapılması ve Yerine Konması İşçiliği','AD',74137.5,null),
('V.1467','Mermerden 41- 60 Cm.Arası Yükseklikte Kurşunlu ve Kenetli Düz Başlık Yapılması ve Yerine Konması İşçiliği','AD',37837.5,null),
('V.1468','Mermerden 41-60 Cm. Arası Yükseklikte Kurşunlu ve Kenetli Profilli Sütun Kaidesi Yapılması ve Yerine Konması İşçiliği','AD',54375.0,null),
('V.1469','Mermerden 41- 60 Cm.Arası Yükseklikte Kurşunlu ve Kenetli Basit Sütun Kaidesi Yapılması ve Yerine Konması İşçiliği','AD',30468.75,null),
('V.1470','Mermerden 61-80 Cm. Arası Yükseklikte Kurşunlu ve Kenetli Stalâktitli Başlık Yapılması ve Yerine Konması İşçiliği','AD',230593.75,null),
('V.1471','Mermerden 61- 80 Cm. Arası Yükseklikte Kurşunlu ve Kenetli Baklavalı Başlık Yapılması ve Yerine Konması İşçiliği','AD',109043.75,null),
('V.1472','Mermerden 61- 80 Cm. Arası Yükseklikte Kurşunlu ve Kenetli Düz Başlık Yapılması ve Yerine Konması İşçiliği','AD',51843.75,null),
('V.1473','Mermerden 61-80 Cm. Arası Yükseklikte Kurşunlu ve Kenetli Profilli Sütun Kaidesi Yapılması ve Yerine Konması İşçiliği','AD',76337.5,null),
('V.1474','Mermerden 61-80 Cm. Arası Yükseklikte Kurşunlu ve Kenetli Basit Sütun Kaidesi Yapılması ve Yerine Konması İşçiliği','AD',41137.5,null),
('V.1478','Mermerden 0.50-3.00 Mt. Yüksekliğe Kadar Her Boy ve Çapta Yekpare veya En Çok İki Parçadan Yuvarlak Sütun veya Sütunce Hazırlanması ve Yerine Konması İşçiliği','M²',43812.5,null),
('V.1478/A','Mermerden Her Çapta ve 3.00 Mt.den Yüksek Yekpare Yuvarlak Sütun veya Sütunce Hazırlanması ve Yerine Konması İşçiliği -73-','M²',46562.5,null),
('V.1479','Mermerden 0.50-3.00 Mt. Yüksekliğe Kadar Her Boyda ve Genişlikte Yekpare veya En Çok İki Parçadan Köşeli Sütun veya Sütunce Hazırlanması ve Yerine Konması İşçiliği','M²',30062.5,null),
('V.1479/A','Mermerden Her Çapta ve 3.00 Mt.den Yüksek Yekpare Köşeli Sütun veya Sütunce Hazırlanması ve Yerine Konması İşçiliği','M²',35562.5,null),
('V.1480','Üstü Boş Yerlerde Her Boyda ve Çapta, Mevcut Yuvarlak veya Köşeli Sütunun, Kurşunlu ve Kenetli Olarak Yerine Konması İşçiliği','M²',7256.25,null),
('V.1481','Üstü Askıya Alınmış Yerlerde, Her Boy ve Genişlikte Mevcut Yuvarlak veya Köşeli Sütunun Kurşunlu ve Kenetli Olarak Yerine Konması İşçiliği D- MERMER ÇÖRTEN VE KEMERLER','M²',19062.5,null),
('V.1500','Mermerden Her Boy ve Kesitte Düz Çörten Yapılması ve Yerine Konması İşçiliği','M²',22281.56,null),
('V.1500/A','500 Doz Hidrolik Kireç Harcı ile Mermerden Her Boy ve Kesitte Düz Çörten Yapılması ve Yerine Konması İşçiliği','M²',22624.66,null),
('V.1500/A01','500 Doz Hidrolik Kireç Harcı ile Mermerden Her Boy ve Kesitte Mevcut Düz Çörtenin Islahı ve Yerine Konması İşçiliği','M²',6802.79,null),
('V.1501','Mermerden Her Boyda ve Kesitte Basit Profilli ve Desenli Çörten Yapılması ve Yerine Konması İşçiliği','M²',37994.06,null),
('V.1501/A','500 Doz Hidrolik Kireç Harcı ile Mermerden Her Boyda ve Kesitte Basit Profilli ve Desenli Çörten Yapılması ve Yerine Konması İşçiliği','M²',38337.16,null),
('V.1502','Mermerden Her Boyda ve Kesitte, Nebati ve Hayvani Tezyinatlı Çörten Yapılması ve Yerine Konması İşçiliği','M²',44594.06,null),
('V.1502/A','500 Doz Hidrolik Kireç Harcı ile Mermerden Her Boyda ve Kesitte, Nebati ve Hayvani Tezyinatlı Çörten Yapılması ve Yerine Konması İşçiliği','M²',44937.16,null),
('V.1503','Mermerden, Bir Taşın Görünen Yüzü Toplamı 0.20 M2.den Büyük Kemer Taşı Yapılması ve Yerine Konması İşçiliği','M²',21721.25,null),
('V.1503/A','500 Doz Hidrolik Kireç Harcı ile Mermerden, Bir Taşın Görünen Yüzü Toplamı 0.20 M2.den Büyük Kemer Taşı Yapılması ve Yerine Konması İşçiliği','M²',22178.71,null),
('V.1504','Mermerden, Bir Taşın Görünen Yüzü Toplamı 0.20 M2.den Küçük Kemer Taşı Yapılması ve Yerine Konması İşçiliği','M²',27821.25,null),
('V.1504/A','500 Doz Hidrolik Kireç Harcı ile Mermerden, Bir Taşın Görünen Yüzü Toplamı 0.20 M2.den Küçük Kemer Taşı Yapılması ve Yerine Konması İşçiliği','M²',28278.71,null),
('V.1505','Mermerden, Bir Taşın Görünen Yüzü Toplamı 0.20 M2.den Büyük Mevcut Kemer Taşının Islahı ve Yerine Konması İşçiliği','M²',9896.25,null),
('V.1505/A','500 Doz Hidrolik Kireç Harcı ile Mermerden, Bir Taşın Görünen Yüzü Toplamı 0.20 M2.den Büyük Mevcut Kemer Taşının Islahı ve Yerine Konması İşçiliği','M²',10353.71,null),
('V.1506','Mermerden, Bir Taşın Görünen Yüzü Toplamı 0.20 M2.den Küçük Mevcut Kemer Taşının Islahı ve Yerine Konması İşçiliği','M²',12646.25,null),
('V.1506/A','500 Doz Hidrolik Kireç Harcı ile Mermerden, Bir Taşın Görünen Yüzü Toplamı 0.20 M2.den Küçük Mevcut Kemer Taşının Islahı ve Yerine Konması İşçiliği','M²',13103.71,null),
('V.1507','Mermerden Koçbaşı Düz Konsol Yapılması ve Yerine Konması İşçiliği','AD',6616.88,null),
('V.1507/A','500 Doz Hidrolik Kireç Harcı ile Mermerden Koçbaşı Düz Konsol Yapılması ve Yerine Konması İşçiliği','AD',6845.61,null),
('V.1508','Mermerden, Koçbaşı Basit Profilli veya Silmeli Konsol Yapılması ve Yerine Konması İşçiliği','AD',8266.88,null),
('V.1508/A','500 Doz Hidrolik Kireç Harcı ile Mermerden, Koçbaşı Basit Profilli veya Silmeli Konsol Yapılması ve Yerine Konması İşçiliği','AD',8495.61,null),
('V.1509','Mermerden, Koçbaşı Hayvani Profilli, Nebati veya Geometrik Tezyinatlı Konsol Yapılması ve Yerine Konması İşçiliği','AD',11566.88,null),
('V.1509/A','500 Doz Hidrolik Kireç Harcı ile Mermerden, Koçbaşı Hayvani Profilli, Nebati veya Geometrik Tezyinatlı Konsol Yapılması ve Yerine Konması İşçiliği -74-','AD',11795.61,null),
('V.1530','E- MERMER KORNİŞLER Mermerden 10 Cm. Yüksekliğe Kadar Düz Pahlı Korniş Yapılması ve Yerine Konması İşçiliği','M',6214.69,null),
('V.1530/A','500 Doz Hidrolik Kireç Harcı ile Mermerden 10 Cm. Yüksekliğe Kadar Düz Pahlı Korniş Yapılması ve Yerine Konması İşçiliği','M',6329.05,null),
('V.1531','Mermerden 10 Cm. Yüksekliğe Kadar Silmeli Korniş Yapılması ve Yerine Konması İşçiliği','M',8458.44,null),
('V.1531/A','500 Doz Hidrolik Kireç Harcı ile Mermerden 10 Cm. Yüksekliğe Kadar Silmeli Korniş Yapılması ve Yerine Konması İşçiliği','M',8572.8,null),
('V.1532','Mermerden 11-15 Cm.Arası Yükseklikte (15 Cm. Dahil) Düz Pahlı Korniş Yapılması ve Yerine Konması İşçiliği','M',6977.19,null),
('V.1532/A','500 Doz Hidrolik Kireç Harcı ile Mermerden 11-15 Cm.Arası Yükseklikte (15 Cm. Dahil) Düz Pahlı Korniş Yapılması ve Yerine Konması İşçiliği','M',7091.55,null),
('V.1533','Mermerden, 11-15 Cm.Arası Yükseklikte (15 Cm. Dahil) Silmeli Korniş Yapılması ve Yerine Konması İşçiliği','M',10408.44,null),
('V.1533/A','500 Doz Hidrolik Kireç Harcı ile Mermerden, 11-15 Cm.Arası Yükseklikte (15 Cm. Dahil) Silmeli Korniş Yapılması ve Yerine Konması İşçiliği','M',10522.8,null),
('V.1534','Mermerden, 16-20 Cm.Arası Yükseklikte (20 Cm. Dahil) Düz Pahlı Korniş Yapılması ve Yerine Konması İşçiliği','M',8883.44,null),
('V.1534/A','500 Doz Hidrolik Kireç Harcı ile Mermerden, 16-20 Cm.Arası Yükseklikte (20 Cm. Dahil) Düz Pahlı Korniş Yapılması ve Yerine Konması İşçiliği','M',8997.8,null),
('V.1535','Mermerden, 16-20 Cm.Arası Yükseklikte (20 Cm. Dahil) Silmeli Korniş Yapılması ve Yerine Konması İşçiliği','M',11552.19,null),
('V.1535/A','500 Doz Hidrolik Kireç Harcı ile Mermerden, 16-20 Cm.Arası Yükseklikte (20 Cm. Dahil) Silmeli Korniş Yapılması ve Yerine Konması İşçiliği','M',11666.55,null),
('V.1536','Mermerden, 21-25 Cm.Arası Yükseklikte (25 Cm. Dahil) Düz Pahlı Korniş Yapılması ve Yerine Konması İşçiliği','M',10027.19,null),
('V.1536/A','500 Doz Hidrolik Kireç Harcı ile Mermerden, 21-25 Cm.Arası Yükseklikte (25 Cm. Dahil) Düz Pahlı Korniş Yapılması ve Yerine Konması İşçiliği','M',10141.55,null),
('V.1537','Mermerden, 21-25 Cm.Arası Yükseklikte (25 Cm. Dahil) Silmeli Korniş Yapılması ve Yerine Konması İşçiliği','M',12314.69,null),
('V.1537/A','500 Doz Hidrolik Kireç Harcı ile Mermerden, 21-25 Cm.Arası Yükseklikte (25 Cm. Dahil) Silmeli Korniş Yapılması ve Yerine Konması İşçiliği','M',12429.05,null),
('V.1538','Mermerden, 26-30 Cm.Arası Yükseklikte (30 Cm. Dahil) Düz Pahlı Korniş Yapılması ve Yerine Konması İşçiliği','M',11609.54,null),
('V.1538/A','500 Doz Hidrolik Kireç Harcı ile Mermerden, 26-30 Cm.Arası Yükseklikte (30 Cm. Dahil) Düz Pahlı Korniş Yapılması ve Yerine Konması İşçiliği','M',11781.09,null),
('V.1539','Mermerden, 26-30 Cm.Arası Yükseklikte (30 Cm. Dahil) Silmeli Korniş Yapılması ve Yerine Konması İşçiliği','M',13897.04,null),
('V.1539/A','500 Doz Hidrolik Kireç Harcı ile Mermerden, 26-30 Cm.Arası Yükseklikte (30 Cm. Dahil) Silmeli Korniş Yapılması ve Yerine Konması İşçiliği','M',14068.59,null),
('V.1540','Mermerden, 31-35 Cm.Arası Yükseklikte (35 Cm. Dahil) Düz Pahlı Korniş Yapılması ve Yerine Konması İşçiliği','M',12753.29,null)
) as v(poz_no,tanim,birim,fiyat,extra)
on conflict (source_id,poz_no,coalesce(birim,'')) do nothing;