-- Kültür 2026 part 2/10 (idempotent)
insert into bf_poz (source_id,poz_no,tanim,birim,fiyat,extra)
select 'c4283e74-55cd-4e4c-8394-65486dbbe9e3'::uuid, v.poz_no, v.tanim, v.birim, v.fiyat::numeric, v.extra::jsonb
from (values
('V.0401/01F1','Özgün Olmayan Horasan, Hidrolik, Puzolanik veya Kireç Harçlı veya Takviyeli Harç İle Sıvanmış Kesme Taş Yüzeylerin Zemin Bozulmayacak ve Raspa Sonrası Artık Kalmayacak Şekilde İtinalı Sıva Raspası Yapılması (5-10cm)','M²',598.56,null),
('V.0401/01G','Çimento Harcı İle Sıvanmış Kubbe, Tonoz,Kemer, Minare vb. Taş Yüzeylerin Zemin Bozulmayacak ve Raspa Sonrası Artık Kalmayacak Şekilde İtinalı Sıva Raspası Yapılması (0-5cm)','M²',1328.98,null),
('V.0401/01G1','Özgün Olmayan Horasan, Hidrolik, Puzolanik veya Kireç Harçlı veya Takviyeli Harç İle Sıvanmış Kubbe, Tonoz,Kemer, Minare vb. Taş Yüzeylerin Zemin Bozulmayacak ve Raspa Sonrası Artık Kalmayacak Şekilde İtinalı Sıva Raspası Yapılması (0-5cm)','M²',795.88,null),
('V.0401/01H','Çimento Harcı İle Sıvanmış Kubbe, Tonoz,Kemer, Minare vb. Taş Yüzeylerin Zemin Bozulmayacak ve Raspa Sonrası Artık Kalmayacak Şekilde İtinalı Sıva Raspası Yapılması (5-10cm) -29-','M²',1614.91,null),
('V.0401/01H1','Özgün Olmayan Horasan, Hidrolik, Puzolanik veya Kireç Harçlı veya Takviyeli Harç İle Sıvanmış Kubbe, Tonoz,Kemer, Minare vb. Taş Yüzeylerin Zemin Bozulmayacak ve Raspa Sonrası Artık Kalmayacak Şekilde İtinalı Sıva Raspası Yapılması (5-10cm)','M²',940.75,null),
('V.0401/01J','Çimento Harcı İle Sıvanmış Kubbe, Tonoz,Kemer, Minare vb. Tuğla Yüzeylerin Zemin Bozulmayacak ve Raspa Sonrası Artık Kalmayacak Şekilde İtinalı Sıva Raspası Yapılması (0-5cm)','M²',1372.81,null),
('V.0401/01J1','Özgün Olmayan Horasan, Hidrolik, Puzolanik veya Kireç Harçlı veya Takviyeli Harç İle Sıvanmış Kubbe, Tonoz,Kemer, Minare vb. Tuğla Yüzeylerin Zemin Bozulmayacak ve Raspa Sonrası Artık Kalmayacak Şekilde İtinalı Sıva Raspası Yapılması (0-5cm)','M²',826.38,null),
('V.0401/01K','Çimento Harcı İle Sıvanmış Kubbe, Tonoz,Kemer, Minare vb. Tuğla Yüzeylerin Zemin Bozulmayacak ve Raspa Sonrası Artık Kalmayacak Şekilde İtinalı Sıva Raspası Yapılması (5-10cm)','M²',1658.75,null),
('V.0401/01K1','Özgün Olmayan Horasan, Hidrolik, Puzolanik veya Kireç Harçlı veya Takviyeli Harç İle Sıvanmış Kubbe, Tonoz,Kemer, Minare vb. Tuğla Yüzeylerin Zemin Bozulmayacak ve Raspa Sonrası Artık Kalmayacak Şekilde İtinalı Sıva','M²',971.25,null),
('V.0401/01L','Raspası Yapılması (5-10cm) Çimento Harcı İle Sıvanmış Kerpiç Yüzeylerin Zemin Bozulmayacak Şekilde İtinalı Sıva Raspası Yapılması (0-5cm)','M²',520.31,null),
('V.0401/01L1','Özgün Olmayan Horasan, Hidrolik, Puzolanik veya Kireç Harçlı veya Takviyeli Harç İle Sıvanmış Kerpiç Yüzeylerin Zemin Bozulmayacak Şekilde İtinalı Sıva Raspası Yapılması (0-5cm)','M²',263.63,null),
('V.0401/01M','Çimento Harç İle Sıvanmış Bağdadi Yüzeylerin Zemin Bozulmayacak ve Raspa Sonrası Artık Kalmayacak Şekilde İtinalı Sıva Raspası Yapılması (0-5cm)','M²',1612.5,null),
('V.0401/01M1','Özgün Olmayan Horasan, Hidrolik, Puzolanik veya Kireç Harçlı veya Takviyeli Harç İle Sıvanmış Bağdadi Yüzeylerin Zemin Bozulmayacak ve Raspa Sonrası Artık Kalmayacak Şekilde İtinalı Sıva Raspası Yapılması (0-5cm)','M²',1153.13,null),
('V.0401/01N','Çimento Harcı İle Sıvanmış Taş Tuğla Karışık Yüzeylerin Zemin Bozulmayacak ve Raspa Sonrası Artık Kalmayacak Şekilde İtinalı Sıva Raspası Yapılması (0- 5cm)','M²',949.38,null),
('V.0401/01N1','Çimento Harcı İle Sıvanmış Taş Tuğla Karışık Yüzeylerin Zemin Bozulmayacak ve Raspa Sonrası Artık Kalmayacak Şekilde İtinalı Sıva Raspası Yapılması (5-10cm)','M²',1101.88,null),
('V.0401/01O','Özgün Olmayan Horasan, Hidrolik, Puzolanik veya Kireç Harçlı veya Takviyeli Harç İle Sıvanmış Taş Tuğla Karışık Yüzeylerin Zemin Bozulmayacak ve Raspa Sonrası Artık Kalmayacak Şekilde İtinalı Sıva Raspası Yapılması (0-5cm)','M²',587.73,null),
('V.0401/01O1','Özgün Olmayan Horasan, Hidrolik, Puzolanik veya Kireç Harçlı veya Takviyeli Harç İle Sıvanmış Taş Tuğla Karışık Yüzeylerin Zemin Bozulmayacak ve Raspa Sonrası Artık Kalmayacak Şekilde İtinalı Sıva Raspası Yapılması (5- 10cm) -30-','M²',663.98,null),
('V.0401/C01','B- KALEM İŞİ SIVA RASPALARI Düz Yüzeylerde Kalem İşi ve Diğer Tezyinatın Araştırılması ve Ortaya Çıkarılması İçin Çok İtinalı Alçı Sıva Raspası Yapılması','M²',2156.94,null),
('V.0401/C02','Düz Yüzeylerde Kalem İşi ve Diğer Tezyinatın Araştırılması ve Ortaya Çıkarılması İçin Çok İtinalı Horasan Sıva Raspası Yapılması','M²',2256.94,null),
('V.0401/C03','Düz Yüzeylerde Kalem İşi ve Diğer Tezyinatın Araştırılması ve Ortaya Çıkarılması İçin Çok İtinalı Çimento Sıva Raspası Yapılması','M²',3788.19,null),
('V.0401/C04','Düz Yüzeylerde Kalem İşi ve Diğer Tezyinatın Araştırılması ve Ortaya Çıkarılması İçin Çok İtinalı Yağlı Macun Raspası Yapılması','M²',6144.44,null),
('V.0401/D01','Kubbe, Tonoz, Kemer vb. Kavisli Yüzeylerde Kalem İşi ve Diğer Tezyinatın Araştırılması ve Ortaya Çıkarılması İçin Çok İtinalı Alçı Sıva Raspası Yapılması','M²',2531.94,null),
('V.0401/D02','Kubbe, Tonoz, Kemer vb. Kavisli Yüzeylerde Kalem İşi ve Diğer Tezyinatın Araştırılması ve Ortaya Çıkarılması İçin Çok İtinalı Horasan Raspası Yapılması','M²',3356.94,null),
('V.0401/D03','Kubbe, Tonoz, Kemer vb. Kavisli Yüzeylerde Kalem İşi ve Diğer Tezyinatın Araştırılması ve Ortaya Çıkarılması İçin Çok İtinalı Çimento Raspası Yapılması','M²',5658.19,null),
('V.0401/D04','Kubbe, Tonoz, Kemer vb. Kavisli Yüzeylerde Kalem İşi ve Diğer Tezyinatın Araştırılması ve Ortaya Çıkarılması İçin Çok İtinalı Yağlı Macun Raspası Yapılması','M²',9251.94,null),
('V.0401/E01','Düz Yüzeylerde Kalem İşi Bulunmayan Özgün Sıva Yüzeylerinin Ortaya Çıkarılması İçin Çok İtinalı Alçı Sıva Raspası Yapılması','M²',1138.19,null),
('V.0401/E02','Düz Yüzeylerde Kalem İşi Bulunmayan Özgün Sıva Yüzeylerinin Ortaya Çıkarılması İçin Çok İtinalı Horasan Sıva Raspası Yapılması','M²',1306.94,null),
('V.0401/E03','Düz Yüzeylerde Kalem İşi Bulunmayan Özgün Sıva Yüzeylerinin Ortaya Çıkarılması İçin Çok İtinalı Çimento Sıva Raspası Yapılması','M²',2256.94,null),
('V.0401/E04','Düz Yüzeylerde Kalem İşi Bulunmayan Özgün Sıva Yüzeylerinin Ortaya Çıkarılması İçin Çok İtinalı Yağlı Macun Raspası Yapılması','M²',3710.06,null),
('V.0401/F01','Kubbe, Tonoz, Kemer vb. Kavisli Yüzeylerde Kalem İşi Bulunmayan Özgün Sıva Yüzeylerinin Ortaya Çıkarılması İçin Çok İtinalı Alçı Sıva Raspası Yapılması','M²',1688.19,null),
('V.0401/F02','Kubbe, Tonoz, Kemer vb. Kavisli Yüzeylerde Kalem İşi Bulunmayan Özgün Sıva Yüzeylerinin Ortaya Çıkarılması İçin Çok İtinalı Horasan Raspası Yapılması','M²',1856.94,null),
('V.0401/F03','Kubbe, Tonoz, Kemer vb. Kavisli Yüzeylerde Kalem İşi Bulunmayan Özgün Sıva Yüzeylerinin Ortaya Çıkarılması İçin Çok İtinalı Çimento Raspası Yapılması','M²',3356.94,null),
('V.0401/F04','Kubbe, Tonoz, Kemer vb. Kavisli Yüzeylerde Kalem İşi Bulunmayan Özgün Sıva Yüzeylerinin Ortaya Çıkarılması İçin Çok İtinalı Yağlı Macun Raspası Yapılması -31-','M²',5635.06,null),
('V.0402/01','C- BETON, MOZAİK VE TAŞ TAKLİDİ TABAKA RASPALARI Tuğla Minare Gövde ve Peteğinde Bulunan Özgün Yapı Yüzeyi İle Aderans Sağlamış İmitasyon Beton, Mozaik ve Taş Taklidi Tabakanın İtinalı Olarak Raspası Yapılması (0-5cm)','M²',3312.5,null),
('V.0402/02','Tuğla Minare Gövde ve Peteğinde Bulunan Özgün Yapı Yüzeyi İle Aderans Sağlamış İmitasyon Beton, Mozaik ve Taş Taklidi Tabakanın İtinalı Olarak Raspası Yapılması (5-10cm)','M²',4968.75,null),
('V.0402/03','Tuğla Minare Kirpi Şerefe Altında Bulunan Özgün Yapı Yüzeyi İle Aderans Sağlamış İmitasyon Beton, Mozaik ve Taş Taklidi Tabakanın İtinalı Olarak Raspası Yapılması (0-10cm)','M²',6875.0,null),
('V.0402/04','Tuğla Satıhlar Üzerinde Bulunan Özgün Yapı Yüzeyi İle Aderans Sağlamış İmitasyon Beton, Mozaik ve Taş Taklidi Tabakanın İtinalı Olarak Raspası Yapılması (0-5cm)','M²',1909.38,null),
('V.0402/05','Tuğla Satıhlar Üzerinde Bulunan Özgün Yapı Yüzeyi İle Aderans Sağlamış İmitasyon Beton, Mozaik ve Taş Taklidi Tabakanın İtinalı Olarak Raspası Yapılması (5-10cm)','M²',2671.88,null),
('V.0402/06','Yonu Taşı veya Moloz Taşı Satıhlar Üzerinde Bulunan Özgün Yapı Yüzeyi İle Aderans Sağlamış İmitasyon Beton, Mozaik ve Taş Taklidi Tabakanın İtinalı Olarak Raspası Yapılması (0-5cm)','M²',1528.13,null),
('V.0402/07','Yonu Taşı veya Moloz Taşı Satıhlar Üzerinde Bulunan Özgün Yapı Yüzeyi İle Aderans Sağlamış İmitasyon Beton, Mozaik ve Taş Taklidi Tabakanın İtinalı Olarak Raspası Yapılması (5-10cm)','M²',2100.0,null),
('V.0402/10','Kubbe, Tonoz, Kemer, Minare vb. Yüzeylerinde Bulunan Özgün Yapı İle Aderans Sağlamış İmitasyon Beton, Mozaik ve Taş Taklidi Tabakanın İtinalı Olarak Raspası Yapılması (0-5cm)','M²',2037.5,null),
('V.0402/11','Kubbe, Tonoz, Kemer, Minare vb. Yüzeylerinde Bulunan Özgün Yapı İle Aderans Sağlamış İmitasyon Beton, Mozaik ve Taş Taklidi Tabakanın İtinalı Olarak Raspası Yapılması (5-10cm)','M²',2800.0,null),
('V.0402/12','Duvar Yüzeylerinde Bulunan Özgün Yapı İle Aderans Sağlamış Kemikleşmiş Harç Kalıntılarının, Çimento Esaslı Lokal Dolguların, Cephe Üzerine Akmış Çimento Şerbetlerinin Küçük El Aletleri İle (Bistürü Vb.) Duvar Yüzeyine Zarar Vermeden İtinalı Olarak Raspa Yapılması','M²',2847.56,null),
('V.0402/13','Kubbe, Tonoz, Kemer, Minare vb. Yüzeylerinde Bulunan Özgün Yapı İle Aderans Sağlamış Kemikleşmiş Harç Kalıntılarının, Çimento Esaslı Lokal Dolguların, Cephe Üzerine Akmış Çimento Şerbetlerinin Küçük El Aletleri İle (Bistürü Vb.) Yüzeye Zarar Vermeden İtinalı Olarak Raspa Yapılması','M²',3881.94,null),
('V.0403/A01','D- KALEM İŞİ ARAŞTIRMA RASPALARI Düz Yüzeylerde Kalemişi ve Diğer Tezyinatın Araştırılması ve Ortaya Çıkarılması Bedeli','M²',4431.94,null),
('V.0403/B01','Kubbe, Tonoz, Kemer vb. Kavisli Yüzeylerde, Kurul Tarafından Korunmasına Karar Verilen Kalemişi ve Diğer Tezyinatın Araştırılması ve Ortaya Çıkarılması Bedeli','M²',6922.56,null),
('V.0403/C01','Ahşap Üstü Edirnekâri (Altın Varak Kabartmalı) Tezyinat Üzerinde Araştırma Raspası Yapılması','M²',11450.3,null),
('V.0404/A01','E- KALEM İŞİ BADANA RASPALARI Düz Yüzeylerde Kalem İşi ve Diğer Tezyinatın Ortaya Çıkarılması İçin Çok İtinalı İnce Badana Raspası Yapılması','M²',5056.94,null),
('V.0404/A02','Düz Yüzeylerde Kalem İşi Bulunmayan Özgün Sıva Yüzeylerinin Ortaya Çıkarılması İçin Çok İtinalı İnce Badana Raspası Yapılması','M²',3172.56,null),
('V.0404/B01','Kubbe, Tonoz, Kemer vb. Kavisli Yüzeylerde Kalem İşi ve Diğer Tezyinatın Ortaya Çıkarılması İçin Çok İtinalı İnce Badana Raspası Yapılması','M²',7531.94,null),
('V.0404/B02','Kubbe, Tonoz, Kemer vb. Kavisli Yüzeylerde Kalem İşi Bulunmayan Özgün Sıva Yüzeylerinin Ortaya Çıkarılması İçin Çok İtinalı İnce Badana Raspası Yapılması','M²',4822.56,null),
('V.0405','Kaba Badana Raspası Yapılması -32-','M²',255.0,null),
('V.0406','F- AHŞAP, TAŞ VB. DİĞER RASPA İŞLERİ Oymalı Satıhlardan Başka Her Çeşit Klasik Tuğla, Mermer ve Yonu Taşı Satıhlarında Tel Fırça İle Badana Raspası Yapılması','M²',586.25,null),
('V.0407','Yonu Taşı Yüzünde, Dişli El Tarağı İle Badana veya Yağlı Boya Raspası Yapılması','M²',1730.0,null),
('V.0407/1','Her Nevi Düz Yonu Taşı Üzerindeki En Fazla 3 Kat Yağlı Boya veya Zift vb. nin Boya Sökücü veya Bistrü İle Temizlenmesi','M²',1394.38,null),
('V.0407/2','Her Nevi Kavisli ve Münhani Yonu Taşı Satıhlar Üzerindeki En Fazla 3 Kat Yağlı Boya veya Zift vb. nin Boya Sökücü veya Bistrü İle Temizlenmesi','M²',1630.63,null),
('V.0407/A','Kemer, Tonoz, Sutün ve Benzeri Yerlerde Dişli El Tarağı İle Badana ve Yağlı Boya Raspası Yapılması','M²',3636.25,null),
('V.0407/A2','Profilli ve Basit Tezyinatlı vb. Yonu Taşı Satıhlarda En Fazla 3 kat Yağlı Boya veya Zift vb.''nin Boya Sökücü veya Bistüri İle Temizlenmesi','M²',3724.38,null),
('V.0408/1','Oymalı, Tezyinatlı Yonu Taşı Yüzeylerde Bulunan En Fazla 3 kat Yağlı Boya veya Zift vb.''nin Boya Sökücü veya Bistüri İle Temizlenmesi','M²',6470.0,null),
('V.0409/1','Her Nevi Ahşap Profilli ve Basit Tezyinatlı Satıhlar Üzerindeki En Fazla 3 kat Yağlı Boyanın Boya Sökücü İle Temizlenmesi','M²',2066.88,null),
('V.0410/01','Düz Veya Kavisli Ahşap Yüzeylerde Bulunan Boya, Cila, Macun ve Sülyen Katmanlarının Temizlenmesi','M²',4748.19,null),
('V.0410/02','Her Nevi Profilli ve Basit Tezyinatlı vb. Ahşap Yüzeylerde Bulunan Boya, Cila, Macun ve Sülyen Katmanlarının Temizlenmesi','M²',6382.33,null),
('V.0410/1','Her Nevi Düz ve Kavisli Ahşap Satıhlar Üzerindeki En Fazla 3 kat Yağlı Boyanın Boya Sökücü İle Temizlenmesi','M²',1490.94,null),
('V.0410/A','Biyolojik Müdahale Yapılacak Olan Ahşapların Uygulama Öncesi Temizliği 6- DERZ AÇMALAR','M²',768.46,null),
('V.0411/01','Çimento Harçlı veya Çimento Takviyeli Harçlı Moloz Taş Duvarda Derz Açılması','M²',890.63,null),
('V.0411/01A','Çimento Harçlı veya Çimento Takviyeli Harçlı Kubbe, Tonoz,Kemer vb. Moloz Taş Yüzeylerde Derz Açılması','M²',890.63,null),
('V.0411/02','Horasan, Hidrolik, Puzolanik veya Kireç Harçlı veya Takviyeli Moloz Taş Duvarda Derz Açılması','M²',700.0,null),
('V.0411/02A','Horasan, Hidrolik, Puzolanik, Kireç Harçlı veya Takviyeli Harçlı Kubbe, Tonoz,Kemer vb. Moloz Taş Yüzeylerde Derz Açılması','M²',700.0,null),
('V.0411/03','Çimento Harçlı veya Çimento Takviyeli Harçlı Taş Tuğla Karışık Cephede Derz Açılması','M²',1271.88,null),
('V.0411/04','Horasan, Hidrolik, Puzolanik veya Kireç Harçlı veya Takviyeli Taş Tuğla Karışık Cephede Derz Açılması','M²',985.94,null),
('V.0411/05','Çimento Harçlı veya Çimento Takviyeli Harçlı Klasik Tuğla Cephede Derz Açılması','M²',1653.13,null),
('V.0411/05A','Çimento Harçlı veya Çimento Takviyeli Harçlı Kubbe, Tonoz,Kemer vb. Yüzeylerde Klasik Tuğla Yüzeylerde Derz Açılması','M²',1653.13,null),
('V.0411/06','Horasan, Hidrolik, Puzolanik veya Kireç Harçlı veya Takviyeli Klasik Tuğla Cephede Derz Açılması','M²',1271.88,null),
('V.0411/06A','Horasan, Hidrolik, Puzolanik, Kireç Harçlı veya Takviyeli Harçlı Kubbe, Tonoz,Kemer vb. Yüzeylerde Klasik Tuğla Yüzeylerde Derz Açılması','M²',1271.88,null),
('V.0411/07','Çimento Harçlı veya Çimento Takviyeli Harçlı Taslak Yonu Taş Duvarda Derz Açılması','M²',604.69,null),
('V.0411/08','Horasan, Hidrolik, Puzolanik veya Kireç Harçlı veya Takviyeli Taslak Yonu Taş Duvarda Derz Açılması','M²',509.38,null),
('V.0411/09','Çimento Harçlı veya Çimento Takviyeli Harçlı Yonu Taşı Duvarda Derz Açılması','M²',483.75,null),
('V.0411/09A','Çimento Harçlı veya Çimento Takviyeli Harçlı Kubbe, Tonoz,Kemer vb. Yonu Taşı Yüzeylerde Derz Açılması -33-','M²',483.75,null),
('V.0411/10','Horasan, Hidrolik, Puzolanik veya Kireç Harçlı veya Takviyeli Yonu Taşı Duvarda Derz Açılması','M²',388.44,null),
('V.0411/10A','Horasan, Hidrolik, Puzolanik, Kireç Harçlı veya Takviyeli Harçlı Kubbe, Tonoz,Kemer vb. Yonu Taşı Yüzeylerde Derz Açılması','M²',388.44,null),
('V.0411/11A','Çimento Harçlı veya Çimento Takviyeli Harçlı Mermere (Kapı Kenarları, Söveler ve Kornişlere) Derz Açılması','M',127.5,null),
('V.0411/12','Çimento Harçlı veya Çimento Takviyeli Harçlı Mermer Veya Yonu Taşı Döşemede Derz Açılması','M²',254.69,null),
('V.0411/13','Çimento Harçlı veya Çimento Takviyeli Harçlı Mermer Duvarda Derz Açılması','M²',318.44,null),
('V.0411/14','Çimento Harçlı veya Çimento Takviyeli Harçlı Profilli veya Münhani Satıhlı Yonu Taşı veya Mermer Yüzeylerde Derz Açılması','M²',636.88,null),
('V.0411/15','Çimento Harçlı veya Çimento Takviyeli Harçlı Portal, Mihrap vb. Müzeyyen Satıhlı Yonu Taşı veya Mermer Yüzeylerde Derz Açılması','M²',1070.0,null),
('V.0417','Düz Satıhlarda AB57 İle Mermer Temizliği Yapılması','M²',1615.69,null),
('V.0418','Profilli ve Oymalı Satıhlarda AB57 İle Mermer Temizliği Yapılması','M²',3402.56,null),
('V.0418/A1','Düz ve Kavisli Küfeki Yonu Taşı,Moloz Taş ve Almaşık Yüzeylerin Küfeki Tozu İle Düşük Basınçlı Hassas Cephe Temizliği','M²',925.76,null),
('V.0418/A2','Profilli Ve Oymalı Küfeki Yonu Taşı,Moloz Taş ve Almaşık Yüzeylerin Küfeki Tozu İle Düşük Basınçlı Hassas Cephe Temizliği','M²',2713.9,null),
('V.0418/B1','Düz ve Kavisli Volkanik Yonu Taşı,Moloz Taş ve Almaşık Yüzeylerin Volkanik Taş Tozu İle Düşük Basınçlı Hassas Cephe Temizliği','M²',898.8,null),
('V.0418/B2','Profilli Ve Oymalı Volkanik Yonu Taşı,Moloz Taş ve Almaşık Yüzeylerin Volkanik Taş Tozu İle Düşük Basınçlı Hassas Cephe Temizliği','M²',2659.95,null),
('V.0418/C1','Düz ve Kavisli Bazalt Yonu Taşı,Moloz Taş ve Almaşık Yüzeylerin Bazalt Taş Tozu İle Düşük Basınçlı Hassas Cephe Temizliği','M²',919.69,null),
('V.0418/C2','Profilli Ve Oymalı Bazalt Yonu Taşı,Moloz Taş ve Almaşık Yüzeylerin Bazalt Taş Tozu İle Düşük Basınçlı Hassas Cephe Temizliği','M²',2701.73,null),
('V.0418/D1','Düz ve Kavisli Andezit Yonu Taşı,Moloz Taş ve Almaşık Yüzeylerin Andezit Taş Tozu İle Düşük Basınçlı Hassas Cephe Temizliği','M²',926.71,null),
('V.0418/D2','Profilli Ve Oymalı Andezit Yonu Taşı,Moloz Taş ve Almaşık Yüzeylerin Andezit Taş Tozu İle Düşük Basınçlı Hassas Cephe Temizliği','M²',2715.8,null),
('V.0418/E1','Düz ve Kavisli Traverten Yonu Taşı,Moloz Taş ve Almaşık Yüzeylerin Traverten Taş Tozu İle Düşük Basınçlı Hassas Cephe Temizliği','M²',936.83,null),
('V.0418/E2','Profilli Ve Oymalı Traverten Yonu Taşı,Moloz Taş ve Almaşık Yüzeylerin Traverten Taş Tozu İle Düşük Basınçlı Hassas Cephe Temizliği','M²',2736.01,null),
('V.0418/F1','Düz Ve Kavisli Taş, Tuğla Vb. Yüzeylerde Kaba Temizlik Yapılması','M²',337.46,null),
('V.0420','Mermer ve Yonu Taşı Cephelerin Kompresör İle Sıcak Su Püskürtülerek Temizlenmesi','M²',629.35,null),
('V.0424/01A','Sönmüş Kireç Harcı ile Çatlakların Enjeksiyona hazır hale getirilmesi','M',382.56,null),
('V.0425/01A','Puzolan Bağlayıcılı Sönmüş Kireç ile Çatlakların Enjeksiyona hazır hale getirilmesi','M',389.54,null),
('V.0426/01A','Hidrolik Bağlayıcılı Kireç harcı ile Çatlakların Enjeksiyona hazır hale getirilmesi','M',432.58,null),
('V.0427/01A','Puzolan Bağlayıcılı Hidrolik Kireç ile Çatlakların Enjeksiyona hazır hale getirilmesi Sönmüş kireç ile 100 cm kalınlığa kadar olan duvar, tonoz ve kubbelerdeki','M',549.19,null),
('V.0428/01A','çatlakların ve/veya boşlukların doldurulması için yüzeylerin enjeksiyona hazır hale getirilmesi (101-130 cm arasında kalınlığı olan duvarlarda duvar kalınlık çarpanı 1.15, 131 cm ve daha üzeri kalınlıklarda ise duvar kalınlık çarpanı 1.25 olarak alınacaktır) -34-','M²',1519.89,null),
('V.0429/01A','Puzolan katkılı kireç ile 100 cm kalınlığa kadar olan duvar, tonoz ve kubbelerdeki çatlakların ve/veya boşlukların doldurulması için yüzeylerin enjeksiyona hazır hale getirilmesi (101-130 cm arasında kalınlığı olan duvarlarda duvar kalınlık çarpanı 1.15, 131 cm ve daha üzeri kalınlıklarda ise duvar kalınlık çarpanı 1.25 olarak alınacaktır)','M²',1531.05,null),
('V.0430/01A','NHL 3.5 sınıfı hidrolik kireç ile 100 cm kalınlığa kadar olan duvar, tonoz ve kubbelerdeki çatlakların ve/veya boşlukların doldurulması için yüzeylerin enjeksiyona hazır hale getirilmesi (101-130 cm arasında kalınlığı olan duvarlarda duvar kalınlık çarpanı 1.15, 131 cm ve daha üzeri kalınlıklarda ise duvar kalınlık çarpanı 1.25 olarak alınacaktır)','M²',1599.91,null),
('V.0431/01A','Mermer tozlu ve pirinçli NHL 3.5 sınıfı hidrolik kireç ile 100 cm kalınlığa kadar olan duvar, tonoz ve kubbelerdeki çatlakların ve/veya boşlukların doldurulması için yüzeylerin enjeksiyona hazır hale getirilmesi (101-130 cm arasında kalınlığı olan duvarlarda duvar kalınlık çarpanı 1.15, 131 cm ve daha üzeri kalınlıklarda ise duvar kalınlık çarpanı 1.25 olarak alınacaktır)','M²',1598.95,null),
('V.0432/A1','Enjeksiyona Hazır Hale Getirilen Yüzeylerde Sönmüş Kireç Enjeksiyonu İle Çatlakların Ve/Veya Boşlukların Doldurulması ( 5 Tona Kadar)','KG',134.51,null),
('V.0432/A2','Enjeksiyona Hazır Hale Getirilen Yüzeylerde Sönmüş Kireç Enjeksiyonu İle Çatlakların Ve/Veya Boşlukların Doldurulması ( 5 Ton Dahil Ve Üstü)','KG',110.76,null),
('V.0433/A1','Enjeksiyona Hazır Hale Getirilen Yüzeylerde Puzolan Bağlayıcılı Sönmüş Kireç Enjeksiyonu İle Çatlakların Ve/Veya Boşlukların Doldurulması ( 5 Tona Kadar)','KG',135.0,null),
('V.0433/A2','Enjeksiyona Hazır Hale Getirilen Yüzeylerde Puzolan Bağlayıcılı Sönmüş Kireç Enjeksiyonu İle Çatlakların Ve/Veya Boşlukların Doldurulması ( 5 Ton Dahil Ve Üstü)','KG',111.25,null),
('V.0434/A1','Enjeksiyona Hazır Hale Getirilen Yüzeylerde Hidrolik Bağlayıcılı Kireç Enjeksiyonu İle Çatlakların Ve/Veya Boşlukların Doldurulması ( 5 Tona Kadar)','KG',138.88,null),
('V.0434/A2','Enjeksiyona Hazır Hale Getirilen Yüzeylerde Hidrolik Bağlayıcılı Kireç Enjeksiyonu İle Çatlakların Ve/Veya Boşlukların Doldurulması ( 5 Ton Dahil Ve Üstü)','KG',115.13,null),
('V.0435/A1','Enjeksiyona Hazır Hale Getirilen Yüzeylerde Puzolan Bağlayıcılı Hidrolik Kireç Enjeksiyonu İle Çatlakların Ve/Veya Boşlukların Doldurulması ( 5 Tona Kadar)','KG',139.34,null),
('V.0435/A2','Enjeksiyona Hazır Hale Getirilen Yüzeylerde Puzolan Bağlayıcılı Hidrolik Kireç Enjeksiyonu İle Çatlakların Ve/Veya Boşlukların Doldurulması( 5 Ton Dahil Ve Üstü)','KG',115.59,null),
('V.0435/B1','Enjeksiyona Hazır Hale Getirilen Yüzeylerde Doğal Hidrolik Kireç Esaslı Hazır Enjeksiyon Harcı İle Çatlakların Ve/Veya Boşlukların Doldurulması ( 5 Tona Kadar)','KG',118.61,null),
('V.0435/B2','Enjeksiyona Hazır Hale Getirilen Yüzeylerde Doğal Hidrolik Kireç Esaslı Hazır Enjeksiyon Harcı İle Çatlakların Ve/Veya Boşlukların Doldurulması( 5 Ton Dahil Ve Üstü)','KG',100.81,null),
('V.0436/001','Üzerinde Kalem İşi Bulunan Korunması Gerekli Özgün Duvar Sıva Yüzeylerinin Mikroenjeksiyon Yöntemi ile Sağlamlaştırılması','M²',7712.18,null),
('V.0436/002','Üzerinde Kalem İşi Bulunan Korunması Gerekli Özgün Kubbe, Tonoz vb. (Bağdadi Hariç) Sıva Yüzeylerinin Mikroenjeksiyon Yöntemi ile Sağlamlaştırılması','M²',9998.74,null),
('V.0437/001','Mevcut Kalemişi Tezyinatlı Sıva Yüzeylerinin İtinalı Bir Şekilde Yerinden Alınması ve Sağlamlaştırılması','M²',13365.9,null),
('V.0437/002','Koruma Altına Alınan Tezyinatlı Sıvaların İtinalı Bir Şekilde Yerlerine Montajı','M²',5441.63,null),
('V.0437/003','Yerinden Sökülen Çini ve Tezyinatlı Sıvalar İçin Geçici Raf Hazırlanması -35-','M²',2654.1,null),
('V.0501','7- TAHKİM İŞLERİ Blokaj Yapılması İşçiliği','M³',1787.5,null),
('V.0502','Elenmesi Gerekmeyen İnce Agrega Serilmesi','M³',478.75,null),
('V.0502/001','Sergi Alanı Yapılacak Alanlara çapı 6-10 cm arası Dolomit (Dekoratif Taş) Malzeme Serilmesi','M³',10625.0,null),
('V.0502/A','Eski Eserde Yıkıntı Moloz Toprak Karışımı Hafriyat Yapılması','M³',1025.0,null),
('V.0505','Üstü Kapalı Hamam Cehennemliği Temizlenmesi','M²',4868.75,null),
('V.0505/A','Üstü Açık Hamam Cehennemliği Temizlenmesi','M²',1281.25,null),
('V.0506','İmitasyon Tuğla ve/veya Moloz Taşı Kubbe, Tonoz ve Benzeri Yerlerde Dikiş Yapılması İşçiliği','M',3024.38,null),
('V.0506/A','Hidrolik Kireç ve Puzolan Katkılı Enjeksiyon Harcı ile Klasik Tuğla ve/veya Moloz Taşı Kubbe, Tonoz ve Benzeri Yerlerde Dikiş Yapılması İşçiliği','M',3526.45,null),
('V.0506/B','Hidrolik Kireçli Enjeksiyon Harcı ile Klasik Tuğla ve/veya Moloz Taşı Kubbe, Tonoz ve Benzeri Yerlerde Dikiş Yapılması İşçiliği','M',3521.35,null),
('V.0506/C','İmitasyon Tuğla ve/veya Moloz Taşı Duvarlarda Dikiş Yapılması İşçiliği','M',2577.5,null),
('V.0506/D','Hidrolik Kireç ve Puzolan Katkılı Enjeksiyon Harcı ile Klasik Tuğla ve/veya Moloz Taşı Duvarlarda Dikiş Yapılması İşçiliği','M',3079.58,null),
('V.0506/E','Hidrolik Kireçli Enjeksiyon Harcı ile Klasik Tuğla ve/veya Moloz Taşı Duvarlarda Dikiş Yapılması İşçiliği','M',3074.48,null),
('V.0507','Yonu Taşı, Kubbe, Tonoz ve Benzeri Yerlerde Dikiş Yapılması İşçiliği','M',3421.25,null),
('V.0507/A','Hidrolik Kireç ve Puzolan Katkılı Enjeksiyon Harcı ile Yonu Taşı, Kubbe, Tonoz ve Benzeri Yerlerde Dikiş Yapılması İşçiliği','M',3923.33,null),
('V.0507/B','Hidrolik Kireçli Enjeksiyon Harcı ile Yonu Taşı, Kubbe, Tonoz ve Benzeri Yerlerde Dikiş Yapılması İşçiliği','M',3918.23,null),
('V.0507/C','Yonu Taşı Duvarlarda Dikiş Yapılması İşçiliği','M',2974.38,null),
('V.0507/D','Hidrolik Kireç ve Puzolan Katkılı Enjeksiyon Harcı ile Yonu Taşı Duvarlarda Dikiş Yapılması İşçiliği','M',3476.45,null),
('V.0507/E','Hidrolik Kireçli Enjeksiyon Harcı ile Yonu Taşı Duvarlarda Dikiş Yapılması İşçiliği','M',3471.35,null),
('V.0508','Hamamlarda Tüteklik Açılması','M',3187.5,null),
('V.0509/001','Tüteklik Yapılması -36-','M',3896.56,null),
('V.0510/01','8- KAZILAR (Kazı ve Dolgu İşleri Şartnamesindeki şartlar uygulanır.) Sit Alanı Olan veya Olmayan Alanda Kültür Katmanı Bulununcaya Kadar Yumuşak Toprak Zeminde Serbest Kazı Yapılması (Drenaj, Tretuar, Bahçe Duvarı Temeli, Şadırvan Temeli, Avlu İçi Tesisat Kazıları vb.)','M³',2550.0,null),
('V.0510/02','Sit Alanı Olan veya Olmayan Alanda Kültür Katmanı Bulununcaya Kadar Sert Toprak Zeminde Serbest Kazı Yapılması (Drenaj, Tretuar, Bahçe Duvarı Temeli, Şadırvan Temeli, Avlu İçi Tesisat Kazıları vb.)','M³',3315.0,null),
('V.0511/01','Eski Eser Yapı Özgün Beden Duvarları Sınırı İçerisinde Yumuşak Toprak Zeminde Kazı Yapılması','M³',3537.5,null),
('V.0511/02','Eski Eser Yapı Özgün Beden Duvarları Sınırı İçerisinde Sert Toprak Zeminde Kazı Yapılması','M³',4598.75,null),
('V.0512/01','Müze Yönetiminde, Koruma Kurulu Kararı Doğrultusunda Yapımına Karar Verilen Bilimsel Amaçlı Yumuşak Toprak Zeminde İtinalı Kazısı Yapılması','M³',4925.0,null),
('V.0512/02','Müze Yönetiminde, Koruma Kurulu Kararı Doğrultusunda Yapımına Karar Verilen Bilimsel Amaçlı Sert Toprak Zeminde İtinalı Kazısı Yapılması','M³',6402.5,null),
('V.0514','Bodrum, Çatı ve Döşeme Arası Moloz ve Pisliklerin (Kir, Toz, Toprak Katmanı) Temizlenmesi ve Atılması','M³',11375.0,null),
('V.0514/1','Kubbe Üzerinde Bulunan Moloz Ve Toprak Dolgunun Alınması','M³',3268.75,null),
('V.0514/1A','Üstü Açılmış Çatı ve Döşeme Arası Moloz ve Pisliklerin (Kir, Toz, Toprak Katmanı) Temizlenmesi ve Atılması','M³',5687.5,null),
('V.0515','Bahçe Toprağının Elenmesi , Serilip Düzeltilmesi Ve Sıkıştırılması 9- KALIP VE İSKELE İŞLERİ','M³',1875.0,null),
('V.0602/01','Çatı Arası Vb. Girilmesi Zor Olan Yerlerde Askıya Alma Karkası Yapılması İşçiliği','M³',2026.66,null),
('V.0602/1','Kemer, Kubbe, Tonoz, Tavan ve Benzeri İşlerde 13.50 Mt''ye kadar Askıya Alma Karkası Yapılması İşçiliği','M³',699.76,null),
('V.0603','Cephe İş İskelesi Yapılması İşçiliği','M²',177.46,null),
('V.0603/1','İş İskelesi Yapılması İşçiliği (13.50 MT Yükseklğe Kadar)','M³',234.04,null),
('V.0605/B','Kubbe ve Tonoz İskelesi (13.50Mt''ye kadar) Yapılması İşçiliği','M³',403.94,null),
('V.0606','Minarede İş İskelesi Yapılması İşçiliği (Her Yükseklikte)','M³',209.86,null),
('V.0608/1','Haçvarı veya Yıldız Tonozlar İçin Ahşap Kalıp Yapılması','M²',2795.31,null),
('V.0609/1','Ahşaptan düz yüzeyli beton ve betonarme kalıbı yapılması','M²',1029.08,null),
('V.0609/2','Küresel Yüzeyli Kargir Kemer, Kubbe ve Tonozlar İçin Ahşap Kalıp Yapılması','M²',2153.13,null),
('V.0610','Çalışma Platformu ve Korkuluğunun Yapılması','M²',1069.69,null),
('V.0611','Kubbe ve Tonozlarda Çelik Borudan Tam Güvenlikli İş İskelesi Yapılması (0,00- 51,50m arası)','M³',379.91,null),
('V.0612','Minare ve Şerefede (Her Yükseklikte) Çelik Borudan Tam Güvenlikli İş İskelesi Yapılması (0-20.00 MT Arası)','M³',386.35,null),
('V.0612/1','Minare ve Şerefede (Her Yükseklikte) Çelik Borudan Tam Güvenlikli İş İskelesi Yapılması (20-60.00 MT Arası)','M³',577.6,null),
('V.0613/1','Şantiye Çevresinin Galvanizli Sac İle Çevrilmesi','M²',759.5,null),
('V.0613/A01','Ahşap Veya Demir Karkas Üzerine Her Renkte Oluklu Bitümlü Levhalarla Geçici Çatı Örtüsü Yapılması (Kategori R>=1400 N/M2) (Yangın Sınıfı Broof) (Ahşap veya Demir Karkas Hariç)','M²',510.0,null),
('V.0613/A02','II. Kalite Norm Çam Kereste İle Geçici Ahşap Karkası/Takviye Karkası Yapılması','M³',20903.13,null),
('V.0613/A03','II. Kalite Norm Olmayan Çam Kereste İle Geçici Ahşap Karkası/Takviye Karkası Yapılması','M³',23503.13,null),
('V.0613/B01','Ahşap Veya Demir Karkas Üzerine 10mm Polikarbonat Levhalarla Geçici Çatı Örtüsü Yapılması (Ahşap veya Demir Karkas Hariç) -37-','M²',549.06,null),
('V.0614','Özgün Elemanların ( Mihrap, Minber, Kürsü, Hünkar Mahfili vb.) Koruma altına alınması','M²',1915.28,null),
('V.0615','Çelik borudan Tam Güvenlikli Cephe İskelesi Yapılması','M²',146.89,null),
('V.0616/01','Çelik Borudan Tam Güvenlikli İş İskelesi Yapılması','M³',314.79,null),
('V.0617/001','Profil Demirinden Demir Platformlu Askıya Alma Karkası Yapılması-Montajı - Sökülmesi','KG',196.68,null),
('V.0617/002','Profil Demirinden Platformsuz Askıya Alma Karkası/Takviye Karkası Yapılması -Montajı -Sökülmesi','KG',187.1,null),
('V.0618/001','Münferit Demirinden Demir Platformlu Askıya Alma Karkası Yapılması- Montajı -Sökülmesi','TON',112376.75,null),
('V.0701/01','10- DEMİR İŞLERİ Kapı ve Kepenk Üzerine Soğuk Dövme Saç Kaplama Yapılması, Yerine Konulması, Kabara Çakılması','KG',351.76,null),
('V.0702/001','Lama Demirinden Klasik Lokmalı Parmaklık Çerçevesi Yapılması ve Yerine Montajı','kg',284.13,null),
('V.0702/002','Çerçevesiz ve Lokması Sertleştırılmış Kurşundan, Küçük Lokmalı (Lokmaları Kurşun) Klasik Demir Parmaklık Yapılması ve Yerine Konması','KG',820.5,null),
('V.0702/003A','Çerçevesiz ve Küçük Lokmalı (Lokmaları Demir) Klasik Demir Parmaklık Yapılması ve Yerine Konması','KG',523.45,null),
('V.0702/004','Çerçevesiz ve Lokması Sertleştırılmış Kurşundan Büyük Lokmalı (Lokmaları Kurşun) Klasik Demir Parmaklık Yapılması ve Yerine Konması','KG',747.23,null),
('V.0702/005A','Çerçevesiz ve Büyük Lokmalı (Lokmaları Demir) Klasik Demir Parmaklık Yapılması ve Yerine Konması','KG',633.99,null),
('V.0703','Mevcut Basit Demir Parmaklığın İtinalı Şekilde Sökülmesi, Numaralandırılması Ve Yerine Konması İşçiliği','KG',120.94,null),
('V.0705','Mevcut Klasik Demir Parmaklığın İtinalı Şekilde Sökülmesi, Numaralandırılması Ve Yerine Konması İşçiliği','KG',406.88,null),
('V.0706','Gergi Demiri Yapılması ve Yerine Konması','KG',290.68,null),
('V.0706/A','Mevcut Gergi Demirinin Yerine Konması İşçiliği','KG',159.38,null),
('V.0707','Basit Bronz Bilezik veya Parmaklık Yapılması ve Yerine Konması','KG',2391.45,null),
('V.0708','Müzeyyen Bronz Bilezik veya Parmaklık Yapılması ve Yerine Konması','KG',3058.33,null),
('V.0710','Klasik Geçmeli Dövme Demir Parmaklık Yapılması ve Yerine Konması','KG',1197.18,null),
('V.0710/1','Özgün Klasik Demir Parmaklıkların Boya Sökücü İle Temizlenerek Boyaya Hazır Hale Getirilmesi','M²',3598.75,null),
('V.0710/2','Klasik Demir Parmaklıkların 2 Kat Antipas ve 2 kat Sentetik Boya İle Boyanması','M²',425.0,null),
('V.0710/3','Özgün Gergi Demiri ve Putrellerin Mekanik Yöntem İle Temizlenerek Boyaya Hazır Hale Getirilmesi','M²',1573.75,null),
('V.0710/4','Özgün Gergi Demiri ve Putrellerin 2 Kat Antipas ve 2 kat Sentetik Boya İle Boyanması','M²',619.38,null),
('V.0710/5','Demir Yüzeylere İki Kat ( Farklı Renkte) Antipas Sürülmesi','M²',251.88,null),
('V.0711','İşlenerek dekore edilmiş her çeşit demirden parmaklık, korkuluk v.b.dekoratif (perforje) imalat yapılması ve yerine konulması (her çeşit demirlerden merdiven, balkon, köprü korkulukları çeşitli parmaklıklar, kaplamalar, bölmeler ve benzeri)','KG',513.44,null),
('V.0712/2A','Güçlendirme Amaçlı Paslanmaz Çelik İmalat Yapılması (Kubbe - Kasnak Çekme Elemanları, Bağlayıcı Kiriş Sistemi, Sütun Kuşaklama Vb Özellikli Paslanmaz Çelik İmalatlar Vb.)','KG',911.05,null),
('V.0712/2B','Güçlendirme Amaçlı Sıcak Galvanize Daldırılmış Çelik İmalat Yapılması (Kubbe - Kasnak Çekme Elemanları, Bağlayıcı Kiriş Sistemi, Sütun Kuşaklama Vb Özellikli Çelik İmalatlar Vb.) -38-','KG',621.96,null),
('V.0712/5A','Güçlendirme Amaçlı Duvar İçi, Paslanmaz Çelik Mil Yapılması ve Yerine Konması (Diş Açma Hariç) ( Zayiatı Dahil) (Karot İle Delik Delinmesi Hariç)','KG',882.99,null),
('V.0712/5B','Güçlendirme Amaçlı Duvar İçi, Ön Germeli Yuvarlak Kesitli Paslanmaz Çelik Flanş Yapılması ve Yerine Konması (Diş Açma Ve Zayiatı Dahil) (Karot İle Delik Delinmesi Hariç)','KG',1193.76,null),
('V.0712/5C','Güçlendirme Amaçlı Duvar İçi, Paslanmaz Çelik Manşon-Somun-Pul Yapılması ve Yerine Konması (Diş Açma Ve Zayiatı Dahil) (Karot İle Delik Delinmesi Hariç)','KG',1484.23,null),
('V.0712/5D1','Güçlendirme Amaçlı Duvar İçi, Paslanmaz Çelik Mile Diş Açılması','m',2919.43,null),
('V.0712/5E','Güçlendirme Amaçlı Sıcak Galvanize Daldırılmış Duvar İçi, Ön Germeli Dikdörtgen veya Yuvarlak Kesitli Çelik Gergi Çubuğu Yapılması (Karot İle Delik Delinmesi Hariç)','KG',731.29,null),
('V.0712/6','Güçlendirme Amaçlı Tuğla Duvarda Karot Makinesi Kullanılarak 35mm çapında tek seferde 3m''ye kadar( 3m dahil) Darbesiz ve Tahribatsız Delik Delinmesi İşçiliği (ÖRNEK)','M',3833.5,null),
('V.0712/7','Güçlendirme Amaçlı Tuğla Duvarda Karot Makinesi Kullanılarak 35mm çapında Tek seferde 3m Üzeri Derinlikler İçin (3m hariç) Darbesiz ve Tahribatsız Delik Delinmesi İşçiliği (ÖRNEK)','M',4383.5,null),
('V.0712/8','Güçlendirme Amaçlı Kesme Taş Duvarda Karot Makinesi Kullanılarak 82mm çapında Tek seferde 8m Derinlik İçin Darbesiz ve Tahribatsız Delik Delinmesi İşçiliği (ÖRNEK)','M',11786.5,null),
('V.0713/01','Kenet, Zıvana Bağlantı Yuvalarına Eritilmiş Kurşun Dökülmesi','KG',159.56,null),
('V.0714/001','Paslanmazdan Basit İmalat Yapılması (Küpeşte, Korkuluk boruları , abdest alma ayağı boruları Vb.)','KG',752.84,null),
('V.0714/002','Paslanmazdan Aksesuarlı İmalat Yapılması (Küpeşte, korkuluk aksesuarları, abdest alma ayakları aksesuarıı Vb.)','KG',1126.75,null),
('V.0715/001','Paslanmazdan Kenet Yapılması ve Yerine Montajı ( Delik Açılması Dahil)','KG',965.2,null),
('V.0715/002','Galvaniz İşlenmiş Demirden Kenet Yapılması ve Yerine Montajı ( Delik Açılması Dahil)','KG',898.9,null),
('V.0716/001','Paslanmazdan Zıvana Yapılması ve Yerine Montajı ( Delik Açılması Dahil)','KG',1270.49,null),
('V.0716/002','Galvaniz İşlenmiş Demirden Zıvana Yapılması ve Yerine Montajı ( Delik Açılması Dahil)','KG',1190.01,null),
('V.0717/001','Tuğla, Yonu Taşı, Moloz Taş Yüzeylere Paslanmaz Dişli Tij İle Dikiş Yapılması (Delik Açılması Dahil)','KG',1218.26,null),
('V.0717/002','Tuğla, Yonu Taşı, Moloz Taş Yüzeylere Galvaniz İşlenmiş Demirden Dişli Tij İle Dikiş Yapılması','KG',1137.79,null),
('V.0720','Demir İmalata Sıcak Daldırma Galvaniz Kaplama Yapılması','kg',59.86,null),
('V.0721/A01','Düz Sac Levhalarla Ahşap Bağlantı Elemanı Yapılması Ve Yerine Monte Edilmesi','kg',447.95,null),
('V.0721/A02','Paslanmazdan Ahşap Bağlantı Elemanı Yapılması Ve Yerine Monte Edilmesi -39-','KG',533.01,null),
('V.0801/A01','11- KLASİK TUĞLA, YONU TAŞI VE MERMER DÖŞEMELER A- KLASİK TUĞLA DÖŞEMELER Horasan Harçlı Klasik Tuğla İle Döşeme Yapılması İşçiliği','M²',1112.34,null),
('V.0802','Çok Köşeli Klasik Tuğla İle Döşeme Yapılması İşçiliği','M²',1704.26,null),
('V.0802/001','Horasan Harçlı Çok Köşeli Klasik Döşeme Tuğlasının Islah Edilerek Yerine Konulması','M²',3343.59,null),
('V.0802/A01','Horasan Harçlı Çok Köşeli Klasik Tuğla İle Döşeme Yapılması İşçiliği B- YONU TAŞI VE MERMER DÖŞEMELER','M²',1749.84,null),
('V.0805','Yonu Taşı Silmeli Şerefe Döşemesi Yapılması İşçiliği','M²',14853.55,null),
('V.0805/A','Puzolan Katkılı Kireç Harcı ile Yonu Taşı Silmeli Şerefe Döşemesi Yapılması İşçiliği','M²',14972.65,null),
('V.0805/B','Hidrolik Kireç Harcı ile Yonu Taşı Silmeli Şerefe Döşemesi Yapılması İşçiliği','M²',15426.55,null),
('V.0806','Yonu Taşı Mevcut, Silmeli Şerefe Döşemesi Islahı ve Yerine Konması İşçiliği','M²',3441.05,null),
('V.0806/A','Puzolan Katkılı Kireç Harcı ileYonu Taşı Mevcut, Silmeli Şerefe Döşemesi Islahı ve Yerine Konması İşçiliği','M²',3560.15,null),
('V.0806/B','Hidrolik Kireç Harcı ileYonu Taşı Mevcut, Silmeli Şerefe Döşemesi Islahı ve Yerine Konması İşçiliği','M²',4014.05,null),
('V.0810','Mevcut Döşemelik Yonu Taşının Kenarlarının Düzeltilmesi İşçiliği','M²',1906.25,null),
('V.0811','Mevcut Döşemelik Mermerin Kenarlarının Düzeltilmesi İşçiliği','M²',3431.25,null),
('V.0813/01','Yonu Taşından (Bazalt)250 Doz Çimento Harcı İle 10X10, 10x20, 15x30 cm vb. Parke Taşı İle Döşeme Yapılması (ÖRNEK)','M²',2717.81,null),
('V.0814','Mevcut Mermer, Yonu Taşı veya İmitasyon Taşla Kum Üzerine Döşeme Yapılması İşçiliği ÇİMENTO HARÇLI YONU TAŞI DÖŞEME İŞLERİ','M²',981.94,null),
('V.0817/001','Mevcut 5-8 Cm (8 Cm Dahil) Kalınlıkta 30-40-50cmxserbest boy Yonu Taşı İle Çimento Harçlı Düz veya Kavisli 1-2 Cm. Genişlikte Derzli Döşeme Yapılması İşçiliği (Taş Sertliği 1,5 dan küçük)','M²',1117.26,null),
('V.0817/002','Mevcut 5-8 Cm (8 Cm Dahil) Kalınlıkta 30-40-50cmxserbest boy Yonu Taşı İle Çimento Harçlı Düz veya Kavisli 1-2 Cm. Genişlikte Derzli Döşeme Yapılması İşçiliği (Taş Sertliği 1,5 ve 1,5 dan büyük)','M²',1373.51,null),
('V.0817/003','Mevcut 9-12 Cm (12 Cm Dahil) Kalınlıkta 30-40cmxserbest boy Yonu Taşı İle Çimento Harçlı Düz veya Kavisli 1-2 Cm. Genişlikte Derzli Döşeme Yapılması İşçiliği (Taş Sertliği 1,5 dan küçük)','M²',1448.33,null),
('V.0817/004','Mevcut 9-12 Cm (12 Cm Dahil) Kalınlıkta 50cmxserbest boy Yonu Taşı İle Çimento Harçlı Düz veya Kavisli 1-2 Cm. Genişlikte Derzli Döşeme Yapılması İşçiliği (Taş Sertliği 1,5 dan küçük)','M²',1832.7,null),
('V.0817/005','Mevcut 9-12 Cm (12 Cm Dahil) Kalınlıkta 30-40cmxserbest boy Yonu Taşı İle Çimento Harçlı Düz veya Kavisli 1-2 Cm. Genişlikte Derzli Döşeme Yapılması İşçiliği (Taş Sertliği 1,5 ve 1,5 dan büyük)','M²',1832.7,null),
('V.0817/006','Mevcut 9-12 Cm (12 Cm Dahil) Kalınlıkta 50cmxserbest boy Yonu Taşı İle Çimento Harçlı Düz veya Kavisli 1-2 Cm. Genişlikte Derzli Döşeme Yapılması İşçiliği (Taş Sertliği 1,5 ve 1,5 dan büyük) -40-','M²',2470.2,null),
('V.0817/007','Mevcut Döşemelik Yonu Yaşı İle 13-15Cm (15 Cm Dahil) 30-40 cmxserbest boy Çimento Harçlı Düz veya Kavisli 1-2 Cm. Genişlikte Derzli Döşeme Yapılması İşçiliği (Taş Sertliği 1,5 dan küçük)','M²',1779.39,null),
('V.0817/008','Mevcut Döşemelik Yonu Yaşı İle 13-15Cm (15 Cm Dahil) 50cmxserbest boy Çimento Harçlı Düz veya Kavisli 1-2 Cm. Genişlikte Derzli Döşeme Yapılması İşçiliği (Taş Sertliği 1,5 dan küçük)','M²',2291.89,null),
('V.0817/009','Mevcut Döşemelik Yonu Yaşı İle 13-15Cm (15 Cm Dahil) 30-40xserbest boy Çimento Harçlı Düz veya Kavisli 1-2 Cm. Genişlikte Derzli Döşeme Yapılması İşçiliği (Taş Sertliği 1,5 ve 1,5 dan büyük)','M²',2291.89,null),
('V.0817/010','Mevcut Döşemelik Yonu Yaşı İle 13-15Cm (15 Cm Dahil) 50cmxserbest boy Çimento Harçlı Düz veya Kavisli 1-2 Cm. Genişlikte Derzli Döşeme Yapılması İşçiliği (Taş Sertliği 1,5 ve 1,5 dan büyük) PUZOLAN KATKILI HARÇLI YONU TAŞI DÖŞEME İŞLERİ','M²',2673.14,null),
('V.0817/A001','Puzolan Katkılı Kireç Harcı ile Mevcut 5-8 Cm (8 Cm Dahil) Kalınlıkta 30-40- 50cmxserbest boy Yonu Taşı İle Düz veya Kavisli 1-2 Cm. Genişlikte Derzli Döşeme Yapılması İşçiliği (Taş Sertliği 1,5 dan küçük)','M²',1226.86,null),
('V.0817/A002','Puzolan Katkılı Kireç Harcı ile Mevcut 5-8 Cm (8 Cm Dahil) Kalınlıkta 30-40- 50cmxserbest boy Yonu Taşı İle Düz veya Kavisli 1-2 Cm. Genişlikte Derzli Döşeme Yapılması İşçiliği(Taş Sertliği 1,5 ve 1,5 dan büyük)','M²',1483.11,null),
('V.0817/A003','Puzolan Katkılı Kireç Harcı ile Mevcut 9-12 Cm (12 Cm Dahil) Kalınlıkta 30- 40xserbest boy Yonu Taşı İle Düz veya Kavisli 1-2 Cm. Genişlikte Derzli Döşeme Yapılması İşçiliği (Taş Sertliği 1,5 dan küçük)','M²',1571.63,null),
('V.0817/A004','Puzolan Katkılı Kireç Harcı ile Mevcut 9-12 Cm (12 Cm Dahil) Kalınlıkta 50cmxserbest boy Yonu Taşı İle Düz veya Kavisli 1-2 Cm. Genişlikte Derzli Döşeme Yapılması İşçiliği (Taş Sertliği 1,5 dan küçük)','M²',1956.0,null),
('V.0817/A005','Puzolan Katkılı Kireç Harcı ile Mevcut 9-12 Cm (12 Cm Dahil) Kalınlıkta 30- 40xserbest boy Yonu Taşı İle Düz veya Kavisli 1-2 Cm. Genişlikte Derzli Döşeme Yapılması İşçiliği(Taş Sertliği 1,5 ve 1,5 dan büyük)','M²',1956.0,null),
('V.0817/A006','Puzolan Katkılı Kireç Harcı ile Mevcut 9-12 Cm (12 Cm Dahil) Kalınlıkta 50cmxserbest boy Yonu Taşı İle Düz veya Kavisli 1-2 Cm. Genişlikte Derzli Döşeme Yapılması İşçiliği(Taş Sertliği 1,5 ve 1,5 dan büyük)','M²',2593.5,null),
('V.0817/A007','Mevcut Döşemelik Yonu Yaşı İle 13-15Cm (15 Cm Dahil) 30-40cmxserbest boy Puzolan Katkılı Kireç Harçlı Düz veya Kavisli 1-2 Cm. Genişlikte Derzli Döşeme Yapılması İşçiliği (Taş Sertliği 1,5 dan küçük)','M²',1916.4,null),
('V.0817/A008','Mevcut Döşemelik Yonu Yaşı İle 13-15Cm (15 Cm Dahil) 50cmxserbest boy Puzolan Katkılı Kireç Harçlı Düz veya Kavisli 1-2 Cm. Genişlikte Derzli Döşeme Yapılması İşçiliği (Taş Sertliği 1,5 dan küçük)','M²',2428.9,null),
('V.0817/A009','Mevcut Döşemelik Yonu Yaşı İle 13-15Cm (15 Cm Dahil) 30-40xserbest boy Puzolan Katkılı Kireç Harçlı Düz veya Kavisli 1-2 Cm. Genişlikte Derzli Döşeme Yapılması İşçiliği (Taş Sertliği 1,5 ve 1,5 dan büyük)','M²',2428.9,null),
('V.0817/A010','Mevcut Döşemelik Yonu Yaşı İle 13-15Cm (15 Cm Dahil) 50cmxserbest boy Puzolan Katkılı Kireç Harçlı Düz veya Kavisli 1-2 Cm. Genişlikte Derzli Döşeme Yapılması İşçiliği (Taş Sertliği 1,5 ve 1,5 dan büyük) -41-','M²',2810.15,null),
('V.0817/B001','HİDROLİK KİREÇ HARÇLI YONU TAŞI DÖŞEME İŞLERİ Hidrolik Kireç Harcı ile Mevcut 5-8 Cm (8 Cm Dahil) Kalınlıkta 30-40- 50cmxserbest boy Yonu Taşı İle Düz veya Kavisli 1-2 Cm. Genişlikte Derzli Döşeme Yapılması İşçiliği (Taş Sertliği 1,5 dan küçük)','M²',1589.99,null),
('V.0817/B002','Hidrolik Kireç Harcı ile Mevcut 5-8 Cm (8 Cm Dahil) Kalınlıkta 30-40- 50cmxserbest boy Yonu Taşı İle Düz veya Kavisli 1-2 Cm. Genişlikte Derzli Döşeme Yapılması İşçiliği (Taş Sertliği 1,5 ve 1,5''dan büyük)','M²',1846.24,null),
('V.0817/B003','Hidrolik Kireç Harcı ile Mevcut 9-12 Cm (12 Cm Dahil) Kalınlıkta 30- 40cmxserbest boy Yonu Taşı İle Düz veya Kavisli 1-2 Cm. Genişlikte Derzli Döşeme Yapılması İşçiliği (Taş Sertliği 1,5 dan küçük)','M²',1980.15,null),
('V.0817/B004','Hidrolik Kireç Harcı ile Mevcut 9-12 Cm (12 Cm Dahil) Kalınlıkta 50cmxserbest boy Yonu Taşı İle Düz veya Kavisli 1-2 Cm. Genişlikte Derzli Döşeme Yapılması İşçiliği (Taş Sertliği 1,5 dan küçük)','M²',2364.53,null),
('V.0817/B005','Hidrolik Kireç Harcı ile Mevcut 9-12 Cm (12 Cm Dahil) Kalınlıkta 30- 40cmxserbest boy Yonu Taşı İle Düz veya Kavisli 1-2 Cm. Genişlikte Derzli Döşeme Yapılması İşçiliği (Taş Sertliği 1,5 ve 1,5''dan büyük)','M²',2364.53,null),
('V.0817/B006','Hidrolik Kireç Harcı ile Mevcut 9-12 Cm (12 Cm Dahil) Kalınlıkta 50cmxserbest boy Yonu Taşı İle Düz veya Kavisli 1-2 Cm. Genişlikte Derzli Döşeme Yapılması İşçiliği (Taş Sertliği 1,5 ve 1,5''dan büyük)','M²',3002.03,null),
('V.0817/B007','Mevcut Döşemelik Yonu Yaşı İle 13-15Cm (15 Cm Dahil) 30-40cmxserbest boy Hidrolik Kireç Harçlı Düz veya Kavisli 1-2 Cm. Genişlikte Derzli Döşeme Yapılması İşçiliği (Taş Sertliği 1,5 dan küçük)','M²',2370.3,null),
('V.0817/B008','Mevcut Döşemelik Yonu Yaşı İle 13-15Cm (15 Cm Dahil) 50cmxserbest boy Hidrolik Kireç Harçlı Düz veya Kavisli 1-2 Cm. Genişlikte Derzli Döşeme Yapılması İşçiliği (Taş Sertliği 1,5 dan küçük)','M²',2882.8,null),
('V.0817/B009','Mevcut Döşemelik Yonu Yaşı İle 13-15Cm (15 Cm Dahil) 30-40cmxserbest boy Hidrolik Kireç Harçlı Düz veya Kavisli 1-2 Cm. Genişlikte Derzli Döşeme Yapılması İşçiliği (Taş Sertliği 1,5 ve 1,5''dan büyük)','M²',2882.8,null),
('V.0817/B010','Mevcut Döşemelik Yonu Yaşı İle 13-15Cm (15 Cm Dahil) 50cmxserbest boy Hidrolik Kireç Harçlı Düz veya Kavisli 1-2 Cm. Genişlikte Derzli Döşeme Yapılması İşçiliği (Taş Sertliği 1,5 ve 1,5''dan büyük)','M²',3264.05,null),
('V.0818/A001','PUZOLAN KATKILI HARÇLI MERMER DÖŞEME İŞLERİ Puzolan Katkılı Kireç Harcı İle 5-8 Cm (8 Cm Dahil) Kalınlıkta 30-40- 50cmxserbest boy Mevcut Mermer Döşeme Taşı İle Düz ve/veya Kavisli 1-2 Cm. Genişlikte Derzli Döşeme Yapılması İşçiliği','M²',1864.36,null),
('V.0818/A002','Puzolan Katkılı Kireç Harcı İle 9-12 Cm (12 cm dahi) Kalınlıkta 30- 40cmxserbest boy Mevcut Mermer Döşeme Taşı İle Düz ve/veya Kavisli 1-2 Cm. Genişlikte Derzli Döşeme Yapılması İşçiliği','M²',2337.25,null),
('V.0818/A003','Puzolan Katkılı Kireç Harcı İle 9-12 Cm (12 cm dahi) Kalınlıkta 50cmxserbest boy Mevcut Mermer Döşeme Taşı İle Düz ve/veya Kavisli 1-2 Cm. Genişlikte Derzli Döşeme Yapılması İşçiliği -42-','M²',2784.13,null),
('V.0818/B001','MERMER TOZLU HİDROLİK KİREÇ HARÇLI MERMER DÖŞEME İŞLERİ Mermer Tozlu 500 Doz Hidrolik Kireç Harcı ile 5-8 Cm (8 Cm Dahil) Kalınlıkta 30-40-50cmxserbest boy Mevcut Mermer Döşeme Taşı İle Düz ve/veya Kavisli 1-2 Cm. Genişlikte Derzli Döşeme Yapılması İşçiliği','M²',2222.46,null),
('V.0818/B002','Mermer Tozlu 500 Doz Hidrolik Kireç Harcı ile 9-12 Cm (12 cm dahi) Kalınlıkta 30-40cmxserbest boy Mevcut Mermer Döşeme Taşı İle Düz ve/veya Kavisli 1-2 Cm. Genişlikte Derzli Döşeme Yapılması İşçiliği','M²',2740.13,null),
('V.0818/B003','Mermer Tozlu 500 Doz Hidrolik Kireç Harcı ile 9-12 Cm (12 cm dahi) Kalınlıkta 50cmxserbest boy Mevcut Mermer Döşeme Taşı İle Düz ve/veya Kavisli 1-2 Cm. Genişlikte Derzli Döşeme Yapılması İşçiliği','M²',3187.0,null),
('V.0818/B004','Mevcut Mermer Döşeme Taşı İle 13-15Cm (15 Cm Dahil) 30-40xserbest boy Puzolan Katkılı Kireç Harçlı Düz ve/veya Kavisli 1-2 Cm. Genişlikte Derzli Döşeme Yapılması İşçiliği (Taş Sertliği 1,5 dan küçük)','M²',2553.9,null),
('V.0818/B005','Mevcut Mermer Döşeme Taşı İle 13-15Cm (15 Cm Dahil) 50cmxserbest boy Puzolan Katkılı Kireç Harçlı Düz ve/veya Kavisli 1-2 Cm. Genişlikte Derzli Döşeme Yapılması İşçiliği (Taş Sertliği 1,5 dan küçük)','M²',3000.78,null),
('V.0818/B006','Mevcut Mermer Döşeme Taşı İle 13-15Cm (15 Cm Dahil) 30-40cmxserbest boy Mermer Tozlu 500 Doz Hidrolik Kireç Harçlı Düz ve/veya Kavisli 1-2 Cm. Genişlikte Derzli Döşeme Yapılması İşçiliği','M²',3001.53,null),
('V.0818/B007','Mevcut Mermer Döşeme Taşı İle 13-15Cm (15 Cm Dahil) 50cmxserbest boy Mermer Tozlu 500 Doz Hidrolik Kireç Harçlı Düz ve/veya Kavisli 1-2 Cm. Genişlikte Derzli Döşeme Yapılması İşçiliği','M²',3448.4,null),
('V.0819','Hamamdan Sökülmüş Büyük Boy, Döşeme Taşının Islahı ve Yerine Konması İşçiliği','M²',2827.19,null),
('V.0819/A','Puzolan Katkılı Horasan Harç ile Hamamdan Sökülmüş Büyük Boy, Döşeme Taşının Islahı ve Yerine Konması İşçiliği','M²',2874.55,null),
('V.0819/B','500 Doz Hidrolik Kireçli Harç ile Hamamdan Sökülmüş Büyük Boy, Döşeme Taşının Islahı ve Yerine Konması İşçiliği','M²',2942.81,null),
('V.0820','Cehennemlik ve Benzeri Kanallar Üzerine En Çok 10 Cm. Kalınlıkta Saltaşı Döşeme Yapılması İşçiliği','M²',4352.19,null),
('V.0820/A','Puzolan Katkılı Harç ile Cehennemlik ve Benzeri Kanallar Üzerine En Çok 10 Cm. Kalınlıkta Saltaşı Döşeme Yapılması İşçiliği','M²',4377.03,null),
('V.0820/B','500 Doz Hidrolik Kireçli Harç ile Cehennemlik ve Benzeri Kanallar Üzerine En Çok 10 Cm. Kalınlıkta Saltaşı Döşeme Yapılması İşçiliği','M²',4467.81,null),
('V.0821','Zemin Üzerine Değişik Geometrik Şekilli Taşlarla (Kayrak) Harçlı Ve Derzli Döşeme Yapılması İşçiliği','M²',1350.43,null),
('V.0822','Yonu Taşından 8-10cm Genişliğinde Süpürgelik Yapılması (ÖRNEK) -43-','M',367.13,null),
('V.0850','12- YÜZEYSEL İŞLEMLER Mevcut Veya Yere Döşenmiş Sert Yonu Taşının El ile Mucartalanması İşçiliği (Taş Sertliği 1,5 ve 1,5 dan büyük)','M²',1100.0,null),
('V.0850/1','Mevcut Veya Yere Döşenmiş Yumuşak Yonu Taşının El ile Taraklanması İşçiliği (Taş Sertliği 1,5 dan küçük)','M²',550.0,null),
('V.0850/2','Sert veya Yumuşak Yonu Taşının Fabrikada Mucartalanması İşçiliği Karşilığı','M²',275.0,null),
('V.0851','Mevcut veya Döşenmiş Sert veya Yumuşak Yonu Taşının Makine ile Mucartalanması işçiliği','M²',302.5,null),
('V.0852/1','Duvarda ve Kemerde bulunan Yumuşak Yonu Taşının El ile Taraklanması İşçiliği','M²',687.5,null),
('V.0852/2','Duvarda ve Kemerde bulunan Sert Yonu Taşının El ile Mucartalanması İşçiliği','M²',1375.0,null),
('V.0852/3','Silmede bulunan Yumuşak Yonu Taşının El ile Taraklanması işçiliği','M²',825.0,null),
('V.0852/4','Silmede bulunan Sert Yonu Taşının El ile Mucartalanması işçiliği','M²',1375.0,null),
('V.0852/5','Silmeli Kornişte bulunan Yumuşak Yonu Taşının El ile Taraklanması işçiliği','M²',962.5,null),
('V.0852/6','Silmeli Kornişte bulunan Sert Yonu Taşının El ile Mucartalanması işçiliği','M²',1650.0,null),
('V.0901','13- MOLOZ VE TUĞLA DUVAR İŞLERİ Kireç Harç İle Harman veya Delikli Tuğla Duvar Yapılması İşçiliği','M³',5802.88,null),
('V.0901/A','Puzolan Katkılı Kireç Harcı İle Harman veya Delikli tuğla Tuğla Duvar Yapılması İşçiliği','M³',6281.98,null),
('V.0901/B','500 Doz Hidrolik Kireç Harcı İle Harman veya Delikli Tuğla Duvar Yapılması İşçiliği','M³',8551.5,null),
('V.0902/01','225 Doz Çimento Takviyeli Kireç Harçla Moloz Taş Duvar Yapılması İşçiliği','M³',7658.69,null),
('V.0902/A01','Puzolan Katkılı Kireç Harcı ile Moloz Taş Duvar Yapılması İşçiliği','M³',8398.38,null),
('V.0902/B01','Horasan Harcı İle Moloz Taş Duvar Yapılması İşçiliği','M³',8446.93,null),
('V.0902/B02','500 Doz Hidrolik Kireç Harcı ile Moloz Taş Duvar Yapılması İşçiliği','M³',11121.8,null),
('V.0902/C01','225 Doz Çimento Takviyeli Kireç Harçla Çürütülen Yerlere Ortalama 25 cm Kalınlıkta Moloz Taş Kaplama Yapılması İşçiliği','M²',2465.86,null),
('V.0902/C02','Puzolan Katkılı Kireç Harcı ile Çürütülen Yerlere Ortalama 25 cm Kalınlıkta Moloz Taş Kaplama Yapılması İşçiliği','M²',2663.11,null),
('V.0902/C03','Horasan Harcı İle ile Çürütülen Yerlere Ortalama 25 cm Kalınlıkta Moloz Taş Kaplama Yapılması İşçiliği','M²',2676.05,null),
('V.0902/C04','500 Doz Hidrolik Kireç Harcı ile Çürütülen Yerlere Ortalama 25 cm Kalınlıkta Moloz Taş Kaplama Yapılması İşçiliği','M²',3389.35,null),
('V.0903/001','225 Doz Çimento Takviyeli Kireç Harçla Sıralı Moloz Taş Duvar Yapılması İşçiliği','M³',9446.19,null),
('V.0903/A01','Puzolan Katkılı Horasan Harcı ile Sıralı Moloz Taş Duvar Yapılması İşçiliği','M³',10861.41,null),
('V.0903/B01','500 Doz Hidrolik Kireç Harcı ile Sıralı Moloz Taş Duvar Yapılması İşçiliği','M³',12909.3,null),
('V.0903/C01','225 Doz Çimento Takviyeli Kireç Harçla Çürütülen Yerlere Ortalama 25 cm Kalınlıkta Sıralı Moloz Taş Kaplama Yapılması İşçiliği','M²',3159.61,null),
('V.0903/C02','Puzolan Katkılı Horasan Harcı ile Çürütülen Yerlere Ortalama 25 cm Kalınlıkta Sıralı Moloz Taş Kaplama Yapılması İşçiliği','M²',3356.86,null),
('V.0903/C03','500 Doz Hidrolik Kireç Harcı ile Çürütülen Yerlere Ortalama 25 cm Kalınlıkta Sıralı Moloz Taş Kaplama Yapılması İşçiliği','M²',4083.1,null),
('V.0904','225 Doz Çimento Takviyeli Kireç Harçla Sıralı Moloz Taş İle Kubbe ve Tonoz Yapılması İşçiliği','M³',8835.59,null),
('V.0904/A','Puzolan Katkılı Horasan Harcı ile Sıralı Moloz Taş İle Kubbe ve Tonoz Yapılması İşçiliği -44-','M³',9543.2,null),
('V.0904/B','500 Doz Hidrolik Kireç Harcı ile Sıralı Moloz Taş İle Kubbe ve Tonoz Yapılması İşçiliği','M³',10567.15,null),
('V.0905/001','250 Doz Çimento Harçlı Moloz Taş Dolgu Yapılması İşçiliği','M³',3289.81,null),
('V.0905/A01','Puzolan Katkılı Kireçli Harç ile Moloz Taş Dolgu Yapılması İşçiliği','M³',3837.51,null),
('V.0905/B01','Hidrolik Kireçli Harç ile Moloz Taş Dolgu Yapılması İşçiliği','M³',6472.18,null),
('V.0906/001','Ocak Taşı İle 250 Doz Çimento Harçlı Dolgu Yapılması','M³',4702.23,null),
('V.0906/A01','Ocak Taşı İle Puzolan Katkılı Kireç Harcı ile Dolgu Yapılması','M³',4312.43,null),
('V.0906/B01','Ocak Taşı İle Hidrolik Kireç Harcı ile Dolgu Yapılması','M³',6947.09,null),
('V.0907','Çamur Harcı İle Taşıyıcı Kerpiç Yapılması ve Örülmesi İşçiliği','M³',14686.8,null),
('V.0908/1','Pomza Taşı İle Harçsız Moloz Dolgu Yapılması','M³',7307.18,null),
('V.0908/A','Pomza Taşı İle Puzolan Katkılı Kireç Harçlı Moloz Dolgu Yapılması','M³',8260.03,null),
('V.0908/B','Pomza Taşı İle 500 Doz Hidrolik Kireç Harçlı Moloz Dolgu Yapılması 14- TABİİ VE İMİTASYON TUĞLA İŞLERİ','M³',10983.45,null),
('V.1001/A','Klasik Tuğla İle Puzolan Katkılı Kireç Harçlı Duvar Yapılması İşçiliği','M³',8986.6,null),
('V.1001/B','Klasik Tuğla İle 500 Doz Hidrolik Kireç Harçlı Duvar Yapılması İşçiliği','M³',13979.55,null),
('V.1001/C','Klasik Tuğla İle Puzolan Katkılı Horasan Harçlı Duvar Yapılması İşçiliği','M³',10225.08,null),
('V.1002/A','Klasik Tuğla İle Puzolan Katkılı Horasan Harçla Kubbe, Tonoz veya Kemer Yapılması İşçiliği','M³',11750.08,null),
('V.1002/B','Klasik Tuğla İle 500 Doz Hidrolik Kireç Harçla Kubbe, Tonoz veya Kemer Yapılması İşçiliği','M³',15504.55,null),
('V.1003/A','Klasik Tuğla İle Puzolan Katkılı Kireç Harçla Üç Sıralı Kirpi Saçak Yapılması İşçiliği','M',3056.05,null),
('V.1003/B','Klasik Tuğla İle 500 Doz Hidrolik Kireç Harçla Üç Sıralı Kirpi Saçak Yapılması İşçiliği','M',3382.86,null),
('V.1004/1','Klasik Tuğla İle Puzolan Katkılı Kireç Harçlı Beş Sıralı Kirpi Saçak Yapılması İşçiliği','M',5119.44,null),
('V.1004/2','Klasik Tuğla İle 500 Doz Hidrolik Kireç Harçlı Beş Sıralı Kirpi Saçak Yapılması İşçiliği','M',5709.51,null),
('V.1004/A1','Klasik Tuğla İle Puzolan Katkılı Kireç Harçlı Yedi Sıralı Kirpi Saçak Yapılması İşçiliği','M',7188.03,null),
('V.1004/A2','Klasik Tuğla İle 500 Doz Hidrolik Kireç Harçlı Yedi Sıralı Kirpi Saçak Yapılması İşçiliği','M',8050.45,null),
('V.1005/001','Düz Satıhta, Çimento Harç İle Tuğla Hatıllı Sıralı Moloz Taş Duvar Yapılması İşçiliği','M³',10852.31,null),
('V.1005/A01','Puzolan Katkılı Horasan Harcı ile Düz Satıhta, Tuğla Hatıllı Sıralı Moloz Taş Duvar Yapılması İşçiliği','M³',12386.41,null),
('V.1005/B01','500 Doz Hidrolik Kireç Harcı ile Düz Satıhta, Tuğla Hatıllı Sıralı Moloz Taş Duvar Yapılması İşçiliği','M³',14434.3,null),
('V.1006/01','Kavisli Satıhta, Çimento Harç İle Tuğla Hatıllı Sıralı Moloz Taş Duvar Yapılması İşçiliği','M³',12764.81,null),
('V.1006/A01','Puzolan Katkılı Horasan Harcı ile Kavisli Satıhta, Tuğla Hatıllı Sıralı Moloz Taş Duvar Yapılması İşçiliği','M³',14298.91,null),
('V.1006/B01','500 Doz Hidrolik Kireç Harcı ile Kavisli Satıhta, Tuğla Hatıllı Sıralı Moloz Taş Duvar Yapılması İşçiliği','M³',16346.8,null),
('V.1007/A','Puzolan Katkılı Horasan Harcı ile Düz Satıhta Bir Sıra Taslak Yonu Taşı, Bir veya Daha Çok Sıralı Tabii veya Presli Klasik Tuğla İle Kaplama Yapılması İşçiliği','M²',4510.74,null),
('V.1007/B','Hidrolik Kireç Harcı ile Düz Satıhta Bir Sıra Taslak Yonu Taşı, Bir veya Daha Çok Sıralı Tabii veya Presli Klasik Tuğla İle Kaplama Yapılması İşçiliği','M²',4939.28,null),
('V.1008/A','Puzolan Katkılı Horasan Harcı ile Kavisli Satıhta Bir Sıra Taslak Yonu Taşı, Bir veya Daha Çok Sıralı Tabii veya Presli Klasik Tuğla İle Kaplama Yapılması İşçiliği -45-','M²',5654.49,null),
('V.1008/B','Hidrolik Kireç Harcı ile Kavisli Satıhta Bir Sıra Taslak Yonu Taşı, Bir veya Daha Çok Sıralı Tabii veya Presli Klasik Tuğla İle Kaplama Yapılması İşçiliği','M²',6083.03,null),
('V.1009/A','Puzolan Katkılı Horasan Harcı ile Düz Satıhta Bir Sıra Yonu Taşı, Bir veya Daha Çok Sıralı Tabii veya Presli Klasik Tuğla İle Kaplama Yapılması İşçiliği','M²',6495.4,null),
('V.1009/B','Hidrolik Kireç Harcı ile Düz Satıhta Bir Sıra Yonu Taşı, Bir veya Daha Çok Sıralı Tabii veya Presli Klasik Tuğla İle Kaplama Yapılması İşçiliği','M²',6852.51,null),
('V.1010/A','Puzolan Katkılı Horasan Harcı ile Kavisli Satıhta Bir Sıra Yonu Taşı, Bir veya Daha Çok Sıralı Tabii veya Presli Klasik Tuğla İle Kaplama Yapılması İşçiliği','M²',8401.65,null),
('V.1010/B','Hidrolik Kireç Harcı ile Kavisli Satıhta Bir Sıra Yonu Taşı, Bir veya Daha Çok Sıralı Tabii veya Presli Klasik Tuğla İle Kaplama Yapılması İşçiliği','M²',8758.76,null),
('V.1011/A','Puzolan Katkılı Horasan Harcı ile Tabii veya Klasik Tuğla ile Minare Gövdesi ve Peteği Yapılması İşçiliği','M³',18631.33,null),
('V.1011/B','500 Doz Hidrolik Kireç Harcı ile Tabii veya Klasik Tuğla ile Minare Gövdesi ve Peteği Yapılması İşçiliği','M³',22385.8,null),
('V.1012/A','Puzolan Katkılı Horasan Harcı ile Tabii veya Klasik Tuğla ile Minarede (7/8) Küp Yapılması İşçiliği','M³',22784.14,null),
('V.1012/B','500 Doz Hidrolik Kireç Harcı ile Tabii veya Klasik Tuğla ile Minarede (7/8) Küp Yapılması İşçiliği','M³',25173.35,null),
('V.1013/A','Puzolan Katkılı Horasan Harç ile Tabii veya Klasik Tuğla İle Minarede Profilli veya Kirpi Şerefe Altı Yapılması İşçiliği','M³',27025.08,null),
('V.1013/B','500 Doz Hidrolik Kireç Harç ile Tabii veya Klasik Tuğla İle Minarede Profilli veya Kirpi Şerefe Altı Yapılması İşçiliği','M³',30779.55,null),
('V.1015/A','Puzolan Katkılı Horasan Harcı ile Tabii veya Klasik Tuğla ile Minarede Stalâktitli Şerefe Altı Yapılması İşçiliği','M³',33950.08,null),
('V.1015/B','500 Doz Hidrolik Kireç Harcı ile Tabii veya Klasik Tuğla ile Minarede Stalâktitli Şerefe Altı Yapılması İşçiliği','M³',37704.55,null),
('V.1016/A','Puzolan Katkılı Horasan Harcı ile Düz Satıhta Tabii veya Presli Klasik Tuğla ile Yarım Tuğla Kalınlıkta Çıtalı Düz Kaplama Yapılması İşçiliği','M²',2552.15,null),
('V.1016/B','Hidrolik Kireç Harcı ile Düz Satıhta Tabii veya Presli Klasik Tuğla ile Yarım Tuğla Kalınlıkta Çıtalı Düz Kaplama Yapılması İşçiliği','M²',2790.23,null),
('V.1017/A','Puzolan Katkılı Horasan Harcı ile Düz Satıhta Tabii veya Klasik Tuğla ile Yarım Tuğla Kalınlıkta Çıtalı Dik ve Yatay Desenli Kaplama Yapılması İşçiliği','M²',5260.55,null),
('V.1017/B','Hidrolik Kireç Harcı ile Düz Satıhta Tabii veya Klasik Tuğla ile Yarım Tuğla Kalınlıkta Çıtalı Dik ve Yatay Desenli Kaplama Yapılması İşçiliği','M²',5524.6,null),
('V.1018/1','Puzolan Katkılı Horasan Harcı ile Düz Satıhta Tabii veya Klasik Tuğla İle Yarım Tuğla Kalınlıkta Çıtalı veya Her Çeşit Geometrik Desenli Kaplama Yapılması İşçiliği','M²',6873.05,null),
('V.1018/2','Hidrolik Kireç Harcı ile Düz Satıhta Tabii veya Klasik Tuğla İle Yarım Tuğla Kalınlıkta Çıtalı veya Her Çeşit Geometrik Desenli Kaplama Yapılması İşçiliği','M²',7137.1,null),
('V.1018/A1','Puzolan Katkılı Horasan Harcı ile Tabii veya Klasik Tuğla ile Yarım Tuğla Kalınlıkta ve Ahşap Karkas İçinde Geometrik Desenli,Çıtalı Duvar Kaplaması Yapılması İşçiliği','M²',9291.8,null),
('V.1018/A2','Hidrolik Kireç Harcı ile Tabii veya Klasik Tuğla ile Yarım Tuğla Kalınlıkta ve Ahşap Karkas İçinde Geometrik Desenli,Çıtalı Duvar Kaplaması Yapılması İşçiliği','M²',9555.85,null)
) as v(poz_no,tanim,birim,fiyat,extra)
on conflict (source_id,poz_no,coalesce(birim,'')) do nothing;