-- Kültür 2026 part 3/10 (idempotent)
insert into bf_poz (source_id,poz_no,tanim,birim,fiyat,extra)
select 'c4283e74-55cd-4e4c-8394-65486dbbe9e3'::uuid, v.poz_no, v.tanim, v.birim, v.fiyat::numeric, v.extra::jsonb
from (values
('V.1019/A','Puzolan Katkılı Horasan Harcı ile Kavisli Satıhta,Tabii veya Presli Klasik Tuğla İle Yarım Tuğla Kalınlıkta Çıtalı Düz Kaplama Yapılması İşçiliği','M²',3610.55,null),
('V.1019/B','Hidrolik Kireç Harcı ile Kavisli Satıhta,Tabii veya Presli Klasik Tuğla İle Yarım Tuğla Kalınlıkta Çıtalı Düz Kaplama Yapılması İşçiliği','M²',3874.6,null),
('V.1020/A','Puzolan Katkılı Horasan Harcı ile Kavisli Satıhta Tabii veya Klasik Tuğla İle Yarım Tuğla Kalınlıkta Dik ve Yatay Desenli Çıtalı Kaplama Yapılması İşçiliği -46-','M²',6873.05,null),
('V.1020/B','Hidrolik Kireç Harcı ile Kavisli Satıhta Tabii veya Klasik Tuğla İle Yarım Tuğla Kalınlıkta Dik ve Yatay Desenli Çıtalı Kaplama Yapılması İşçiliği','M²',7137.1,null),
('V.1021/A','Puzolan Katkılı Horasan Harcı ile Kavisli Satıhta Tabii veya Muhtelif Boyda Kesilmiş veya Kalıplanmış Klasik Tuğla İle Yarım Tuğla Kalınlıkta Çıtalı ve Her Çeşit Geometrik Desenli Kaplama Yapılması İşçiliği','M²',8082.43,null),
('V.1021/B','Hidrolik Kireç Harcı ile Kavisli Satıhta Tabii veya Muhtelif Boyda Kesilmiş veya Kalıplanmış Klasik Tuğla İle Yarım Tuğla Kalınlıkta Çıtalı ve Her Çeşit Geometrik Desenli Kaplama Yapılması İşçiliği','M²',8346.48,null),
('V.1022/A','Puzolan Katkılı Horasan Harcı ile (7/ 8) Küp veya Benzeri Satıhlarda Tabii veya Klasik Tuğla ile Yarım Tuğla Kalınlıkta Çıtalı Dik ve Yatay Desenli Kaplama Yapılması İşçiliği','M²',12516.8,null),
('V.1022/B','Hidrolik Kireç Harcı ile (7/ 8) Küp veya Benzeri Satıhlarda Tabii veya Klasik Tuğla ile Yarım Tuğla Kalınlıkta Çıtalı Dik ve Yatay Desenli Kaplama Yapılması İşçiliği','M²',12780.85,null),
('V.1023/A','Çürütülen Yerlere Hidrolik Kireç Harcı ile Düz Satıhta Tabii veya Presli Klasik ve İmitasyon Tuğla ile Yarım Tuğla Kalınlıkta Çıtalı Kaplama Yapılması İşçiliği','MT',1314.23,null),
('V.1023/B','Çürütülen Yerlere Hidrolik Kireç Harcı ile Kavisli Satıhta,Tabii veya Presli Klasik ve İmitasyon Tuğla İle Yarım Tuğla Kalınlıkta Çıtalı Kaplama Yapılması İşçiliği','MT',2076.73,null),
('V.1024/A','Çürütülen Yerlere Puzolan Katlılı Horasan Harcı ile Düz Satıhta Tabii veya Presli Klasik ve İmitasyon Tuğla ile Yarım Tuğla Kalınlıkta Çıtalı Kaplama Yapılması İşçiliği','MT',1298.39,null),
('V.1024/B','Çürütülen Yerlere Puzolan Katlılı Horasan Harcı ile Kavisli Satıhta,Tabii veya Presli Klasik ve İmitasyon Tuğla İle Yarım Tuğla Kalınlıkta Çıtalı Kaplama Yapılması İşçiliği 15- YONU TAŞI İŞLERİ','MT',2060.89,null),
('V.1101/01','A-KAPLAMALAR Çimento Harcı İle Yonu Taşından 30x40cmxserbest Boy Ortalama 20-25 Cm. Derinlikte Yatay Ve Dikey Derzli, Kaba Yonu Taşı İle Düz Kaplama Yapılması İşçiliği','M²',6485.14,null),
('V.1101/02','Çimento Harcı İle Yonu Taşından 50xserbest Boy Ortalama 20-25 Cm. Derinlikte Yatay Ve Dikey Derzli, Kaba Yonu Taşı İle Düz Kaplama Yapılması İşçiliği','M²',8042.95,null),
('V.1101/03','Çimento Harcı İle Yonu Taşından 30x40xserbest Boy Ortalama 30-35 Cm. Derinlikte Yatay Ve Dikey Derzli, Kaba Yonu Taşı İle Düz Kaplama Yapılması İşçiliği','M²',9685.4,null),
('V.1101/A01','Puzolan Katkılı Horasan Harcı İle Yonu Taşından 30x40cmxserbest Boy Ortalama 20-25 Cm. Derinlikte Yatay Ve Dikey Derzli, Kaba Yonu Taşı İle Düz Kaplama Yapılması İşçiliği','M²',7002.35,null),
('V.1101/A02','Puzolan Katkılı Horasan Harcı İle Yonu Taşından 50xserbest Boy Ortalama 20- 25 Cm. Derinlikte Yatay Ve Dikey Derzli, Kaba Yonu Taşı İle Düz Kaplama Yapılması İşçiliği','M²',8655.48,null),
('V.1101/A03','Puzolan Katkılı Horasan Harcı İle Yonu Taşından 30x40xserbest Boy Ortalama 30-35 Cm. Derinlikte Yatay Ve Dikey Derzli, Kaba Yonu Taşı İle Düz Kaplama Yapılması İşçiliği','M²',10375.01,null),
('V.1101/B01','Hidrolik Kireç Harcı İle Yonu Taşından 30x40cmxserbest Boy Ortalama 20-25 Cm. Derinlikte Yatay Ve Dikey Derzli, Kaba Yonu Taşı İle Düz Kaplama Yapılması İşçiliği','M²',7333.03,null),
('V.1101/B02','Hidrolik Kireç Harcı İle Yonu Taşından 50xserbest Boy Ortalama 20-25 Cm. Derinlikte Yatay Ve Dikey Derzli, Kaba Yonu Taşı İle Düz Kaplama Yapılması İşçiliği','M²',8986.15,null),
('V.1101/B03','Hidrolik Kireç Harcı İle Yonu Taşından 30x40xserbest Boy Ortalama 30-35 Cm. Derinlikte Yatay Ve Dikey Derzli, Kaba Yonu Taşı İle Düz Kaplama Yapılması İşçiliği -47-','M²',10815.9,null),
('V.1102/A01','Puzolan Katkılı Horasan Harcı İle Yonu Taşından 30x40cmxserbest Boy Ortalama 20-25 Cm. Derinlikte Yatay Ve Dikey Derzli, Kaba Yonu Taşı İle Kavisli Kaplama Yapılması İşçiliği','M²',7628.89,null),
('V.1102/A03','Puzolan Katkılı Horasan Harcı İle Yonu Taşından 30x40xserbest Boy Ortalama 30-35 Cm. Derinlikte Yatay Ve Dikey Derzli Kaba Yonu Taşı İle Kavisli Kaplama Yapılması İşçiliği','M²',11735.74,null),
('V.1102/B01','Hidrolik Kireç Harcı İle Yonu Taşından 30x40cmxserbest Boy Ortalama 20-25 Cm. Derinlikte Yatay Ve Dikey Derzli Kaba Yonu Taşı İle Kavisli Kaplama Yapılması İşçiliği','M²',8476.78,null),
('V.1102/B02','Hidrolik Kireç Harcı İleyonu Taşından 50xserbest Boy Ortalama 20-25 Cm. Derinlikte Yatay Ve Dikey Derzli Kaba Yonu Taşı İle Kavisli Kaplama Yapılması İşçiliği','M²',10320.53,null),
('V.1102/B03','Hidrolik Kireç Harcı İle Yonu Taşından 30x40xserbest Boy Ortalama 30-35 Cm. Derinlikte Yatay Ve Dikey Derzli Kaba Yonu Taşı İle Kavisli Kaplama Yapılması İşçiliği','M²',12531.53,null),
('V.1103','Ortalama 25 Cm. Derinlikte Yatay ve Dikey Derzli, Murç ile Yonu Taşından Düz Kaplama Yapılması İşçiliği','M²',5341.39,null),
('V.1103/A','Puzolan Katkılı Horasan Harcı ile Ortalama 25 Cm. Derinlikte Yatay ve Dikey Derzli, Murç ile Yonu Taşından Düz Kaplama Yapılması İşçiliği','M²',5760.74,null),
('V.1103/B','Hidrolik Kireç Harcı ile Ortalama 25 Cm. Derinlikte Yatay ve Dikey Derzli, Murç ile Yonu Taşından Düz Kaplama Yapılması İşçiliği','M²',6189.28,null),
('V.1104/001','ÇİMENTO HARÇLI YONU TAŞI KAPLAMA İŞLERİ Çimento Harcı ile Yonu Taşından 30-40-50cmxserbest boy Ortalama 5-8Cm (8Cm dahil) Derinlikte Düz Kaplama Yapılması İşçiliği','M²',1402.84,null),
('V.1104/002','Çimento Harcı ile Yonu Taşından 30-40cmxserbest boy Ortalama 9-12Cm (12Cm dahil) Derinlikte Düz Kaplama Yapılması İşçiliği','M²',2061.95,null),
('V.1104/003','Çimento Harcı ile Yonu Taşından 50cmxserbest boy Ortalama 9-12Cm (12Cm dahil) Derinlikte Düz Kaplama Yapılması İşçiliği','M²',2545.7,null),
('V.1104/004','Çimento Harcı ile Yonu Taşından 30-40cmxserbest boy Ortalama 12-15Cm (15Cm dahil) Derinlikte Düz Kaplama Yapılması İşçiliği','M²',2559.8,null),
('V.1104/005','Çimento Harcı ile Yonu Taşından 50cmxserbest boy Ortalama 12-15Cm (15Cm dahil) Derinlikte Düz Kaplama Yapılması İşçiliği','M²',3164.49,null),
('V.1104/006','Çimento Harcı ile Yonu Taşından 30-40cmxserbest boy Ortalama 20-25Cm (25Cm dahil) Derinlikte Düz Kaplama Yapılması İşçiliği','M²',11019.26,null),
('V.1104/007','Çimento Harcı ile Yonu Taşından 50cmxserbest boy Ortalama 20-25Cm (25Cm dahil) Derinlikte Düz Kaplama Yapılması İşçiliği','M²',13731.76,null),
('V.1104/008','Çimento Harcı ile Yonu Taşından 30-40cmxserbest boy Ortalama 30-35Cm (35Cm dahil) Derinlikte Düz Kaplama Yapılması İşçiliği -48-','M²',16500.68,null),
('V.1104/A001','PUZOLAN KATKILI HORASAN HARÇLI YONU TAŞI KAPLAMA İŞLERİ Puzolan Katkılı Horasan Harcı İle Yonu Taşından 30-40-50cmxserbest boy Ortalama 5-8Cm (8Cm dahil) Derinlikte Düz Kaplama Yapılması İşçiliği','M²',1589.21,null),
('V.1104/A002','Puzolan Katkılı Horasan Harcı İle Yonu Taşından 30-40cmxserbest boy Ortalama 9-12Cm (12Cm dahil) Derinlikte Düz Kaplama Yapılması İşçiliği','M²',2271.61,null),
('V.1104/A003','Puzolan Katkılı Horasan Harcı İle Yonu Taşından 50cmxserbest boy Ortalama 9- 12Cm (12Cm dahil) Derinlikte Düz Kaplama Yapılması İşçiliği','M²',2755.36,null),
('V.1104/A004','Puzolan Katkılı Horasan Harcı İle Yonu Taşından 30-40cmxserbest boy Ortalama 12-15Cm (15Cm dahil) Derinlikte Düz Kaplama Yapılması İşçiliği','M²',2792.78,null),
('V.1104/A005','Puzolan Katkılı Horasan Harcı İle Yonu Taşından 50cmxserbest boy Ortalama 12-15Cm (15Cm dahil) Derinlikte Düz Kaplama Yapılması İşçiliği','M²',3397.46,null),
('V.1104/A006','Puzolan Katkılı Horasan Harcı İle Yonu Taşından 30-40cmxserbest boy Ortalama 20-25Cm (25Cm dahil) Derinlikte Düz Kaplama Yapılması İşçiliği','M²',11298.83,null),
('V.1104/A007','Puzolan Katkılı Horasan Harcı İle Yonu Taşından 50cmxserbest boy Ortalama 20-25Cm (25Cm dahil) Derinlikte Düz Kaplama Yapılması İşçiliği','M²',14011.33,null),
('V.1104/A008','Puzolan Katkılı Horasan Harcı İle Yonu Taşından 30-40cmxserbest boy Ortalama 30-35Cm (35Cm dahil) Derinlikte Düz Kaplama Yapılması İşçiliği','M²',16873.44,null),
('V.1104/B001','HİDROLİK KİREÇ HARÇLI YONU TAŞI KAPLAMA İŞLERİ Hidrolik Kireç Harcı ile Yonu Taşından 30-40-50cmxserbest boy Ortalama 5- 8Cm (8Cm dahil) Derinlikte Düz Kaplama Yapılması İşçiliği','M²',1779.68,null),
('V.1104/B002','Hidrolik Kireç Harcı ile Yonu Taşından 30-40cmxserbest boy Ortalama 9-12Cm (12Cm dahil) Derinlikte Düz Kaplama Yapılması İşçiliği','M²',2485.89,null),
('V.1104/B003','Hidrolik Kireç Harcı ile Yonu Taşından 50cmxserbest boy Ortalama 9-12Cm (12Cm dahil) Derinlikte Düz Kaplama Yapılması İşçiliği','M²',2969.64,null),
('V.1104/B004','Hidrolik Kireç Harcı ile Yonu Taşından 30-40cmxserbest boy Ortalama 12- 15Cm (15Cm dahil) Derinlikte Düz Kaplama Yapılması İşçiliği','M²',3030.85,null),
('V.1104/B005','Hidrolik Kireç Harcı ile Yonu Taşından 50cmxserbest boy Ortalama 12-15Cm (15Cm dahil) Derinlikte Düz Kaplama Yapılması İşçiliği','M²',3635.54,null),
('V.1104/B006','Hidrolik Kireç Harcı ile Yonu Taşından 30-40cmxserbest boy Ortalama 20- 25Cm (25Cm dahil) Derinlikte Düz Kaplama Yapılması İşçiliği','M²',11584.51,null),
('V.1104/B007','Hidrolik Kireç Harcı ile Yonu Taşından 50cmxserbest boy Ortalama 20-25Cm (25Cm dahil) Derinlikte Düz Kaplama Yapılması İşçiliği','M²',14297.01,null),
('V.1104/B008','Hidrolik Kireç Harcı ile Yonu Taşından 50cmxserbest boy Ortalama 30-35Cm (35Cm dahil) Derinlikte Düz Kaplama Yapılması İşçiliği','M²',17254.35,null),
('V.1106','Mevcut veya İdare Malı Bir Yıkımdan Çıkmış Yonu Taşının Islah Edilerek Ortalama 25 Cm. Derinlikte Düz Kaplama Yapılması İşçiliği','M²',5169.26,null),
('V.1106/A','Puzolan Katkılı Horasan Harcı ile Mevcut veya İdare Malı Bir Yıkımdan Çıkmış Yonu Taşının Islah Edilerek Ortalama 25 Cm. Derinlikte Düz Kaplama Yapılması İşçiliği','M²',5448.83,null),
('V.1106/B','Hidrolik Kireç Harcı ile Mevcut veya İdare Malı Bir Yıkımdan Çıkmış Yonu Taşının Islah Edilerek Ortalama 25 Cm. Derinlikte Düz Kaplama Yapılması İşçiliği','M²',5734.51,null),
('V.1107','Çimento Harcı ile Yonu Taşından Ortalama 25 Cm. Kalınlıkta (Derinlikte) Kavisli Kaplama Yapılması İşçiliği','M²',11525.51,null),
('V.1107/A','Puzolan Katkılı Horasan Harcı ile Yonu Taşından Ortalama 25 Cm. Kalınlıkta(Derinlikte) Kavisli Kaplama Yapılması İşçiliği','M²',11805.08,null),
('V.1107/B','Hidrolik Kireç Harcı ile Yonu Taşından Ortalama 25 Cm. Kalınlıkta(Derinlikte) Kavisli Kaplama Yapılması İşçiliği -49-','M²',12090.76,null),
('V.1108','Mevcut veya İdare Malı Bir Yıkımdan Çıkmış Yonu Taşının Islah Edilerek Ortalama 25 Cm. Derinlikte Kavisli veya Farisili Kaplama Yapılması İşçiliği','M²',5806.76,null),
('V.1108/A','Puzolan Katkılı Horasan Harcı ile Mevcut veya İdare Malı Bir Yıkımdan Çıkmış Yonu Taşının Islah Edilerek Ortalama 25 Cm. Derinlikte Kavisli veya Farisili Kaplama Yapılması İşçiliği','M²',6086.33,null),
('V.1108/B','Hidrolik Kireç Harcı ile Mevcut veya İdare Malı Bir Yıkımdan Çıkmış Yonu Taşının Islah Edilerek Ortalama 25 Cm. Derinlikte Kavisli veya Farisili Kaplama Yapılması İşçiliği','M²',6372.01,null),
('V.1109','Yonu Taşından Ortalama 25 Cm. Kalınlıkta ve 20-35 Cm Genişlikte Farisili Kaplama Yapılması İşçiliği','M²',14688.01,null),
('V.1109/A','Puzolan Katkılı Horasan Harcı ile Yonu Taşından Ortalama 25 Cm. Kalınlıkta ve 20-35 Cm Genişlikte Farisili Kaplama Yapılması İşçiliği','M²',14967.58,null),
('V.1109/B','Hidrolik Kireç Harcı ile Yonu Taşından Ortalama 25 Cm. Kalınlıkta ve 20-35 Cm Genişlikte Farisili Kaplama Yapılması İşçiliği','M²',15253.26,null),
('V.1111','Yonu Taşından Ortalama 25 Cm. Kalınlıkta ve 36-50 Cm Genişlikte Farisili Kaplama Yapılması İşçiliği','M²',14138.01,null),
('V.1111/A','Puzolan Katkılı Horasan Harcı ile Yonu Taşından Ortalama 25 Cm. Kalınlıkta ve 36-50 Cm Genişlikte Farisili Kaplama Yapılması İşçiliği','M²',14417.58,null),
('V.1111/B','Hidrolik Kireç Harcı ile Yonu Taşından Ortalama 25 Cm. Kalınlıkta ve 36-50 Cm Genişlikte Farisili Kaplama Yapılması İşçiliği','M²',14703.26,null),
('V.1112','Yonu Taşından Ortalama 25 Cm. Kalınlıkta ve 51 Cm.den Daha Geniş Farisili Kaplama Yapılması İşçiliği','M²',13588.01,null),
('V.1112/A','Puzolan Katkılı Horasan Harcı ile Yonu Taşından Ortalama 25 Cm. Kalınlıkta ve 51 Cm.den Daha Geniş Farisili Kaplama Yapılması İşçiliği','M²',13867.58,null),
('V.1112/B','Hidrolik Kireç Harcı ile Yonu Taşından Ortalama 25 Cm. Kalınlıkta ve 51 Cm.den Daha Geniş Farisili Kaplama Yapılması İşçiliği','M²',14153.26,null),
('V.1113','Yonu Taşından Farisili, Köşeli Türbe Külahı Yapılması İşçiliği','M²',15788.01,null),
('V.1113/A','Puzolan Katkılı Horasan Harcı ile Yonu Taşından Farisili, Köşeli Türbe Külahı Yapılması İşçiliği','M²',16067.58,null),
('V.1113/B','Hidrolik Kireç Harcı ile Yonu Taşından Farisili, Köşeli Türbe Külahı Yapılması İşçiliği','M²',16221.55,null),
('V.1114','Yonu Taşından Dilimli Külah Kaplaması Yapılması İşçiliği','M²',27006.76,null),
('V.1114/A','Puzolan Katkılı Horasan Harcı ile Yonu Taşından Dilimli Külah Kaplaması Yapılması İşçiliği','M²',27286.33,null),
('V.1114/B','Hidrolik Kireç Harcı ile Yonu Taşından Dilimli Külah Kaplaması Yapılması İşçiliği','M²',27440.3,null),
('V.1115','Yonu Taşından Mahruti ve Geçmeli Külah Kaplaması Yapılması İşçiliği','M²',22056.76,null),
('V.1115/A','Puzolan Katkılı Horasan Harcı ile Yonu Taşından Mahruti ve Geçmeli Külah Kaplaması Yapılması İşçiliği','M²',22336.33,null),
('V.1115/B','Hidrolik Kireç Harcı ile Yonu Taşından Mahruti ve Geçmeli Külah Kaplaması Yapılması İşçiliği','M²',22664.44,null),
('V.1116','Mevcut Yonu Taşından Mahruti ve Geçmeli Külah Kaplamasının Islahı ve Yerine Konması İşçiliği','M²',9956.76,null),
('V.1116/A','Puzolan Katkılı Horasan Harcı ile Mevcut Yonu Taşından Mahruti ve Geçmeli Külah Kaplamasının Islahı ve Yerine Konması İşçiliği','M²',10236.33,null),
('V.1116/B','Hidrolik Kireç Harcı ile Mevcut Yonu Taşından Mahruti ve Geçmeli Külah Kaplamasının Islahı ve Yerine Konması İşçiliği','M²',10390.3,null),
('V.1117','Mevcut Yonu Taşından Dilimli Külah Kaplamasının Islahı ve Yerine Konması','M²',13256.76,null),
('V.1117/A','Puzolan Katkılı Horasan Harcı ile Mevcut Yonu Taşından Dilimli Külah Kaplamasının Islahı ve Yerine Konması','M²',13536.33,null),
('V.1117/B','Hidrolik Kireç Harcı ile Mevcut Yonu Taşından Dilimli Külah Kaplamasının Islahı ve Yerine Konması','M²',13690.3,null),
('V.1125','Yonu Taşı Çift Kat İçi ve Dışı İşlenmiş Temiz Tonoz Yapılması İşçiliği -50-','M²',18794.26,null),
('V.1125/A','Puzolan Katkılı Horasan Harcı ile Yonu Taşı Çift Kat İçi ve Dışı İşlenmiş Temiz Tonoz Yapılması İşçiliği','M²',19073.83,null),
('V.1125/B','Hidrolik Kireç Harcı ile Yonu Taşı Çift Kat İçi ve Dışı İşlenmiş Temiz Tonoz Yapılması İşçiliği','M²',19401.94,null),
('V.1126','Mevcut Yonu Taşından Tonoz Kaplaması Islahı ve Yerine Konması İşçiliği','M²',9444.26,null),
('V.1126/A','Puzolan Katkılı Horasan Harcı ile Mevcut Yonu Taşından Tonoz Kaplaması Islahı ve Yerine Konması İşçiliği','M²',9723.83,null),
('V.1126/B','Hidrolik Kireç Harcı ile Mevcut Yonu Taşından Tonoz Kaplaması Islahı ve Yerine Konması İşçiliği','M²',10051.94,null),
('V.1127','Yonu Taşından Çift Kat İçi ve Dışı İşlenmiş Temiz Kubbe Yapılması İşçiliği','M²',25319.26,null),
('V.1127/A','Puzolan Katkılı Horasan Harcı ile Yonu Taşından Çift Kat İçi ve Dışı İşlenmiş Temiz Kubbe Yapılması İşçiliği','M²',25598.83,null),
('V.1127/B','Hidrolik Kireç Harcı ile Yonu Taşından Çift Kat İçi ve Dışı İşlenmiş Temiz Kubbe Yapılması İşçiliği','M²',25926.94,null),
('V.1128','Yonu Taşından Dilimli Kubbe Yapılması İşçiliği','M²',36244.26,null),
('V.1128/A','Puzolan Katkılı Horasan Harcı ile Yonu Taşından Dilimli Kubbe Yapılması İşçiliği','M²',36523.83,null),
('V.1128/B','Hidrolik Kireç Harcı ile Yonu Taşından Dilimli Kubbe Yapılması İşçiliği','M²',36851.94,null),
('V.1129','Mevcut Yonu Taşının Islah Edilerek Tek Sıralı Kubbe Yapılması İşçiliği','M²',13219.26,null),
('V.1129/A','Puzolan Katkılı Horasan Harcı ile Mevcut Yonu Taşının Islah Edilerek Tek Sıralı Kubbe Yapılması İşçiliği','M²',13498.83,null),
('V.1129/B','Hidrolik Kireç Harcı ile Mevcut Yonu Taşının Islah Edilerek Tek Sıralı Kubbe Yapılması İşçiliği','M²',13826.94,null),
('V.1130','Mevcut Yonu Taşının Islah Edilerek Dilimli Kubbe Yapılması İşçiliği','M²',16994.26,null),
('V.1130/A','Puzolan Katkılı Horasan Harcı ile Mevcut Yonu Taşının Islah Edilerek Dilimli Kubbe Yapılması İşçiliği','M²',17273.83,null),
('V.1130/B','Hidrolik Kireç Harcı ile Mevcut Yonu Taşının Islah Edilerek Dilimli Kubbe Yapılması İşçiliği','M²',17601.94,null),
('V.1131','B- ÇÜRÜTÜLEN YERLERE KAPLAMA (MİNARE DAHİL ) Çürütülen Yerlere Ortalama 25 Cm. Kalınlıkta Düz Yonu Taşı Kaplama Yapılması İşçiliği','M²',13219.26,null),
('V.1131/A','Puzolan Katkılı Horasan Harcı ile Çürütülen Yerlere Ortalama 25 Cm. Kalınlıkta Düz Yonu Taşı Kaplama Yapılması İşçiliği','M²',13498.83,null),
('V.1131/B','Hidrolik Kireç Harcı ile Çürütülen Yerlere Ortalama 25 Cm. Kalınlıkta Düz Yonu Taşı Kaplama Yapılması İşçiliği','M²',13826.94,null),
('V.1132','Çürütülen Yerlere Ortalama 25 Cm. Kalınlıkta Kavisli Yonu Taşı Kaplama Yapılması İşçiliği','M²',15081.76,null),
('V.1132/A','Puzolan Katkılı Horasan Harcı İle Çürütülen Yerlere Ortalama 25 Cm. Kalınlıkta Kavisli Yonu Taşı Kaplama Yapılması İşçiliği','M²',15361.33,null),
('V.1132/B','Hidrolik Kireç Harcı ile Çürütülen Yerlere Ortalama 25 Cm. Kalınlıkta Kavisli Yonu Taşı Kaplama Yapılması İşçiliği','M²',15689.44,null),
('V.1133','Çürütülen Yerlere Ortalama 25 Cm. Kalınlıkta ve 20-35 Cm. Genişlikte Yonu Taşı Farisili Kaplama Yapılması İşçiliği','M²',13981.76,null),
('V.1133/A','Puzolan Katkılı Kireç Harcı ile Çürütülen Yerlere Ortalama 25 Cm. Kalınlıkta ve 20-35 Cm. Genişlikte Yonu Taşı Farisili Kaplama Yapılması İşçiliği','M²',14261.33,null),
('V.1133/B','Hidrolik Kireç Harcı ile Çürütülen Yerlere Ortalama 25 Cm. Kalınlıkta ve 20-35 Cm. Genişlikte Yonu Taşı Farisili Kaplama Yapılması İşçiliği','M²',14589.44,null),
('V.1134','Çürütülen Yerlere Ortalama 25 Cm. Kalınlıkta ve 36-50 Cm Genişlikte Yonu Taşı Farisili Kaplama Yapılması İşçiliği','M²',13600.51,null),
('V.1134/1','Puzolan Katkılı Horasan Harcı ile Çürütülen Yerlere Ortalama 25 Cm Kalınlıkta ve 36-50 Cm Genişlikte Yonu Taşı Farisili Kaplama Yapılması İşçiliği -51-','M²',13880.08,null),
('V.1134/2','Hidrolik Kireç Harcı ile Çürütülen Yerlere Ortalama 25 Cm. Kalınlıkta ve 36-50 Cm Genişlikte Yonu Taşı Farisili Kaplama Yapılması İşçiliği','M²',14208.19,null),
('V.1134/A','Çürütülen Yerlere Ortalama 51 Cm. ve Daha Geniş Yonu Taşı Farisili Kaplama Yapılması İşçiliği','M²',13219.26,null),
('V.1134/A1','Puzolan Katkılı Horasan Harcı ile Çürütülen Yerlere Ortalama 51 Cm. ve Daha Geniş Yonu Taşı Farisili Kaplama Yapılması İşçiliği','M²',13498.83,null),
('V.1134/A2','Hidrolik Kireç Harcı ile Çürütülen Yerlere Ortalama 51 Cm. ve Daha Geniş Yonu Taşı Farisili Kaplama','M²',13826.94,null),
('V.1135','İçi ve Dışı Düz, Minare Gövde ve Peteğinde Çürütülen Yerlere, Yapılan Çürütmenin Derinliğinde Yonu Taşı Kaplama Yapılması İşçiliği','M²',17315.88,null),
('V.1135/A','Puzolan Katkılı Horasan Harcı ile İçi ve Dışı Düz, Minare Gövde ve Peteğinde Çürütülen Yerlere, Yapılan Çürütmenin Derinliğinde Yonu Taşı Kaplama Yapılması İşçiliği','M²',17455.66,null),
('V.1135/B','Hidrolik Kireç Harcı ile İçi ve Dışı Düz, Minare Gövde ve Peteğinde Çürütülen Yerlere, Yapılan Çürütmenin Derinliğinde Yonu Taşı Kaplama Yapılması İşçiliği','M²',17619.71,null),
('V.1136','Yuvarlak Minare Gövde ve Peteğinde Çürütülen Yerlere, Yapılan Çürütmenin Derinliğinde Yonu Taşı Kaplama Yapılması İşçiliği','M²',25015.88,null),
('V.1136/A','Puzolan Katkılı Horasan Harcı ile Yuvarlak Minare Gövde ve Peteğinde Çürütülen Yerlere, Minare Gövde ve Peteğinde Çürütülen Yerlere, Yapılan Çürütmenin Derinliğinde Yonu Taşı Kaplama Yapılması İşçiliği','M²',25155.66,null),
('V.1136/B','Hidrolik Kireç Harcı ile Yuvarlak Minare Gövde ve Peteğinde Çürütülen Yerlere, Yapılan Çürütmenin Derinliğinde Yonu Taşı Kaplama Yapılması İşçiliği','M²',25319.71,null),
('V.1137','20-35 Cm. Genişliğe Kadar Farisili Minare Gövde ve Peteğinde Çürütülen Yerlere Yapılan Çürütmenin Derinliğinde Yonu Taşı Kaplama Yapılması İşçiliği','M²',27178.38,null),
('V.1137/A','Puzolan Katkılı Horasan Harcı ile 20-35 Cm. Genişliğe Kadar Farisili Minare Gövde ve Peteğinde Çürütülen Yerlere Yapılan Çürütmenin Derinliğinde Yonu Taşı Kaplama Yapılması İşçiliği','M²',27318.16,null),
('V.1137/B','Hidrolik Kireç Harcı ile 20-35 Cm. Genişliğe Kadar Farisili Minare Gövde ve Peteğinde Çürütülen Yerlere Yapılan Çürütmenin Derinliğinde Yonu Taşı Kaplama Yapılması İşçiliği','M²',27482.21,null),
('V.1138','36-50 Cm. Genişlikte Farisili Minare Gövde ve Peteğinde Çürütülen Yerlere Yapılan Çürütmenin Derinliğinde Yonu Taşı Kaplama Yapılması İşçiliği','M²',26078.38,null),
('V.1138/A','Puzolan Katkılı Horasan Harcı ile 36-50 Cm. Genişlikte Farisili Minare Gövde ve Peteğinde Çürütülen Yerlere Yapılan Çürütmenin Derinliğinde Yonu Taşı Kaplama Yapılması İşçiliği','M²',26218.16,null),
('V.1138/B','Hidrolik Kireç Harcı ile 36-50 Cm. Genişlikte Farisili Minare Gövde ve Peteğinde Çürütülen Yerlere Yapılan Çürütmenin Derinliğinde Yonu Taşı Kaplama Yapılması İşçiliği','M²',26382.21,null),
('V.1139','Farisili ve Kavallı Minare Gövde, Peteğinde ve Diğer Benzeri Çürütülen Yerlerde Yapılan Çürütmenin Derinliğinde Yonu Taşı Kaplama Yapılması İşçiliği','M²',38728.38,null),
('V.1139/A','Puzolan Katkılı Horasan Harcı ile Farisili ve Kavallı Minare Gövde, Peteğinde ve Diğer Benzeri Çürütülen Yerlerde Yapılan Çürütmenin Derinliğinde Yonu Taşı Kaplama Yapılması İşçiliği','M²',38868.16,null),
('V.1139/B','Hidrolik Kireç Harcı ile Farisili ve Kavallı Minare Gövde, Peteğinde ve Diğer Benzeri Çürütülen Yerlerde Yapılan Çürütmenin Derinliğinde Yonu Taşı Kaplama Yapılması İşçiliği -52-','M²',39032.21,null),
('V.1140','C- MİNARE İŞLERİ Yonu Taşından Kurşunlu Kenetli Düz Minare Gövde ve Peteği Yapılması İşçiliği (Gömlek Hariç)','M²',16509.63,null),
('V.1140/A','Puzolan Katkılı Horasan Harcı ile Yonu Taşından Kurşunlu Kenetli Düz Minare Gövde ve Peteği Yapılması İşçiliği (Gömlek Hariç)','M²',16648.64,null),
('V.1140/B','Hidrolik Kireç Harcı ile Yonu Taşından Kurşunlu Kenetli Düz Minare Gövde ve Peteği Yapılması İşçiliği (Gömlek Hariç)','M²',16813.46,null),
('V.1141','Yonu Taşından Kurşunlu Kenetli Minare Kaidesi Yapılması İşçiliği (Gömlek Hariç)','M²',13209.63,null),
('V.1141/A','Puzolan Katkılı Horasan Harcı ile Yonu Taşından Kurşunlu Kenetli Minare Kaidesi Yapılması İşçiliği (Gömlek Hariç)','M²',13348.64,null),
('V.1141/B','Hidrolik Kıreç Harcı ile Yonu Taşından Kurşunlu Kenetli Minare Kaidesi Yapılması İşçiliği (Gömlek Hariç)','M²',13513.46,null),
('V.1142','Mevcut Yonu Taşından Minare Kaidesinin Islahı ve Kurşunlu Kenetli Olarak Yerine Konması','M²',5428.38,null),
('V.1142/A','Puzolan Katkılı Horasan Harcı ile Mevcut Yonu Taşından Minare Kaidesinin Islahı ve Kurşunlu Kenetli Olarak Yerine Konması','M²',5567.39,null),
('V.1142/B','Hidrolik Kireç Harcı ile Mevcut Yonu Taşından Minare Kaidesinin Islahı ve Kurşunlu Kenetli Olarak Yerine Konması','M²',5732.21,null),
('V.1143','Minarede Yonu Taşından Baklavalı Tipte, Kurşunlu Kenetli (7/ 8) Küp Yapılması İşçiliği (Gömlek Hariç)','M²',35834.98,null),
('V.1143/1','Puzolan Katkılı Horasan Harcı ile Minarede Yonu Taşından Baklavalı Tipte, Kurşunlu Kenetli (7/ 8) Küp Yapılması İşçiliği (Gömlek Hariç)','M²',36159.33,null),
('V.1143/2','Hidrolik Kireç Harcı ile Minarede Yonu Taşından Baklavalı Tipte, Kurşunlu Kenetli (7/ 8) Küp Yapılması İşçiliği (Gömlek Hariç)','M²',36543.93,null),
('V.1143/A','Minarede Kurşunlu Kenetli Yonu Taşı Basit Tipte (7/8) Küp Yapılması İşçiliği (Gömlek Hariç)','M²',23734.98,null),
('V.1143/A1','Puzolan Katkılı Horasan Harcı ile Minarede Kurşunlu Kenetli Yonu Taşı Basit Tipte (7/8) Küp Yapılması İşçiliği (Gömlek Hariç)','M²',24059.33,null),
('V.1143/A2','Hidrolik Kireç Harcı ile Minarede Kurşunlu Kenetli Yonu Taşı Basit Tipte (7/8) Küp Yapılması İşçiliği (Gömlek','M²',24443.93,null),
('V.1144','Yonu Taşından Kurşunlu Kenetli Tek Parça Yuvarlak Minare Gövde ve Peteği Yapılması İşçiliği','M²',24722.13,null),
('V.1144/A','Puzolan Katkılı Horasan Harcı ile Yonu Taşından Kurşunlu Kenetli Tek Parça Yuvarlak Minare Gövde ve Peteği Yapılması İşçiliği','M²',24861.14,null),
('V.1144/B','Hidrolik Kireç Harcı ile Yonu Taşından Kurşunlu Kenetli Tek Parça Yuvarlak Minare Gövde ve Peteği Yapılması İşçiliği','M²',25025.96,null),
('V.1145','Yonu Taşından Tek Parça 50 Cm. Genişliğe Kadar Farisili Kurşunlu Kenetli Minare Gövde ve Peteği Yapılması İşçiliği','M²',26372.13,null),
('V.1145/A','Puzolan Katkılı Horasan Harcı ile Yonu Taşından Tek Parça 50 Cm. Genişliğe Kadar Farisili Kurşunlu Kenetli Minare Gövde ve Peteği Yapılması İşçiliği','M²',26511.14,null),
('V.1145/B','Hidrolik Kireç Harcı ile Yonu Taşından Tek Parça 50 Cm. Genişliğe Kadar Farisili Kurşunlu Kenetli Minare Gövde ve Peteği Yapılması İşçiliği','M²',26675.96,null),
('V.1146','Yonu Taşından Tek Parça 50 Cm.den Büyük Genişlikte Farisili, Kurşunlu Kenetli Minare Gövde ve Peteği Yapılması İşçiliği','M²',25272.13,null),
('V.1146/A','Puzolan Katkılı Horasan Harcı ile Yonu Taşından Tek Parça 50 Cm.den Büyük Genişlikte Farisili, Kurşunlu Kenetli Minare Gövde ve Peteği Yapılması İşçiliği','M²',25411.14,null),
('V.1146/B','Hidrolik Kireç Harcı ile Yonu Taşından Tek Parça 50 Cm.den Büyük Genişlikte Farisili, Kurşunlu Kenetli Minare Gövde ve Peteği Yapılması İşçiliği','M²',25575.96,null),
('V.1147','Yonu Taşından Tek Parça Farisili ve Kavallı Kurşunlu Kenetli Minare Gövde ve Peteği Yapılması İşçiliği','M²',37922.13,null),
('V.1147/A','Puzolan Katkılı Horasan Harcı ile Yonu Taşından Tek Parça Farisili ve Kavallı Kurşunlu Kenetli Minare Gövde ve Peteği Yapılması İşçiliği -53-','M²',38061.14,null),
('V.1147/B','Hidrolik Kireç Harcı ile Yonu Taşından Tek Parça Farisili ve Kavallı Kurşunlu Kenetli Minare Gövde ve Peteği Yapılması İşçiliği','M²',38225.96,null),
('V.1149','Islah Edilecek Mevcut Taşlarla Tek Parçalı Yuvarlak veya Farisili Kurşunlu Kenetli Minare Gövde ve Peteği Yapılması İşçiliği','M²',13722.13,null),
('V.1149/A','Puzolan Katkılı Horasan Harcı ile Islah Edilecek Mevcut Taşlarla Tek Parçalı Yuvarlak veya Farisili Kurşunlu Kenetli Minare Gövde ve Peteği Yapılması İşçiliği','M²',13861.14,null),
('V.1149/B','Hidrolik Kireç Harcı ile Islah Edilecek Mevcut Taşlarla Tek Parçalı Yuvarlak veya Farisili Kurşunlu Kenetli Minare Gövde ve Peteği Yapılması İşçiliği','M²',14025.96,null),
('V.1151','Yonu Taşından Kurşunlu Kenetli, Yuvarlak ve İçi Gömlekli Minare Gövde ve Peteği Yapılması İşçiliği (Gömlek Hariç)','M²',20378.55,null),
('V.1151/A','Puzolan Katkılı Horasan Harcı ile Yonu Taşından Kurşunlu Kenetli, Yuvarlak ve İçi Gömlekli Minare Gövde ve Peteği Yapılması İşçiliği (Gömlek Hariç)','M²',20610.24,null),
('V.1151/B','Hidrolik Kireç Harcı ile Yonu Taşından Kurşunlu Kenetli, Yuvarlak ve İçi Gömlekli Minare Gövde ve Peteği Yapılması İşçiliği (Gömlek Hariç)','M²',20884.95,null),
('V.1152','Yonu Taşından Kurşunlu Kenetli 50 Cm. Genşliğe Kadar Farisili ve İçi Gömlekli Minare Gövde ve Peteği Yapılması İşçiliği (Gömlek Hariç)','M²',21478.55,null),
('V.1152/A','Puzolan Katkılı Horasan Harcı ile Yonu Taşından Kurşunlu Kenetli 50 Cm. Genşliğe Kadar Farisili ve İçi Gömlekli Minare Gövde ve Peteği Yapılması İşçiliği (Gömlek Hariç)','M²',21710.24,null),
('V.1152/B','Hidrolik Kireç Harcı ile Yonu Taşından Kurşunlu Kenetli 50 Cm. Genşliğe Kadar Farisili ve İçi Gömlekli Minare Gövde ve Peteği Yapılması İşçiliği (Gömlek Hariç)','M²',21984.95,null),
('V.1153','Yonu Taşından Kurşunlu Kenetli 50 Cm''den Büyük Genişlikte Farisili ve İçi Gömlekli Minare Gövde ve Peteği Yapılması İşçiliği (Gömlek Hariç)','M²',20378.55,null),
('V.1153/A','Puzolan Katkılı Horasan Harcı ile Yonu Taşından Kurşunlu Kenetli 50 Cm''den Büyük Genişlikte Farisili ve İçi Gömlekli Minare Gövde ve Peteği Yapılması İşçiliği (Gömlek Hariç)','M²',20610.24,null),
('V.1153/B','Hidrolik Kireç Harcı ile Yonu Taşından Kurşunlu Kenetli 50 Cm''den Büyük Genişlikte Farisili ve İçi Gömlekli Minare Gövde ve Peteği Yapılması İşçiliği (Gömlek Hariç)','M²',20884.95,null),
('V.1154','Yonu Taşından Kurşunlu Kenetli Farisili ve Kavallı İçi Gömlekli Minare Gövde ve Peteği Yapılması İşçiliği (Gömlek Hariç)','M²',30278.55,null),
('V.1154/A','Puzolan Katkılı Horasan Harcı ile Yonu Taşından Kurşunlu Kenetli Farisili ve Kavallı İçi Gömlekli Minare Gövde ve Peteği Yapılması İşçiliği (Gömlek Hariç)','M²',30510.24,null),
('V.1154/B','Hidrolik Kireç Harcı ile Yonu Taşından Kurşunlu Kenetli Farisili ve Kavallı İçi Gömlekli Minare Gövde ve Peteği Yapılması İşçiliği (Gömlek Hariç)','M²',30784.95,null),
('V.1155','Islah Edilecek Mevcut Taşlarla Kurşunlu Kenetli Farisili ve Kavallı İçi Gömlekli Minare Gövde ve Peteği Yapılması İşçiliği','M²',8278.55,null),
('V.1155/A','Puzolan Katkılı Horasan Harcı ile Islah Edilecek Mevcut Taşlarla Kurşunlu Kenetli Farisili ve Kavallı İçi Gömlekli Minare Gövde ve Peteği Yapılması İşçiliği','M²',8510.24,null),
('V.1155/B','Hidrolik Kireç Harcı ile Islah Edilecek Mevcut Taşlarla Kurşunlu Kenetli Farisili ve Kavallı İçi Gömlekli Minare Gövde ve Peteği Yapılması İşçiliği','M²',8784.95,null),
('V.1156','Yonu Taşından Kurşunlu Kenetli Minare Gömleği Yapılması İşçiliği','M²',13722.13,null),
('V.1156/A','Puzolan Katkılı Horasan Harcı ile Yonu Taşından Kurşunlu Kenetli Minare Gömleği Yapılması İşçiliği','M²',13861.14,null),
('V.1156/B','Hidrolik Kireç Harcı ile Yonu Taşından Kurşunlu Kenetli Minare Gömleği Yapılması İşçiliği','M²',14025.96,null),
('V.1157','Mevcut Yonu Taşının Islah Edilerek Kurşunlu Kenetli Minare Gömleği Yapılması İşçiliği','M²',7728.55,null),
('V.1157/A','Puzolan Katkılı Horasan Harcı ile Mevcut Yonu Taşının Islah Edilerek Kurşunlu Kenetli Minare Gömleği Yapılması İşçiliği -54-','M²',7960.24,null),
('V.1157/B','Hidrolik Kireç Harcı ile Mevcut Yonu Taşının Islah Edilerek Kurşunlu Kenetli Minare Gömleği Yapılması İşçiliği','M²',8234.95,null),
('V.1158','Minare Gövde ve Peteğinde Yonu Taşından 15-25 Cm. Yükseklikte Kurşunlu Kenetli Simit veya Korniş Yapılması İşçiliği','M',7946.96,null),
('V.1158/A','Puzolan Katkılı Horasan Harcı ile Minare Gövde ve Peteğinde Yonu Taşından 15-25 Cm. Yükseklikte Kurşunlu Kenetli Simit veya Korniş Yapılması İşçiliği','M',7993.3,null),
('V.1158/B','Hidrolik Kireç Harcı ile Minare Gövde ve Peteğinde Yonu Taşından 15-25 Cm. Yükseklikte Kurşunlu Kenetli Simit veya Korniş Yapılması İşçiliği','M',8048.24,null),
('V.1159','Yonu Taşından Mevcut Minare Simit ve Kornişinin Islahı ve Yerine Konması İşçiliği','M',3546.96,null),
('V.1159/A','Puzolan Katkılı Horasan Harcı ile Yonu Taşından Mevcut Minare Simit ve Kornişinin Islahı ve Yerine Konması İşçiliği','M',3593.3,null),
('V.1159/B','Hidrolik Kireç Harcı ile Yonu Taşından Mevcut Minare Simit ve Kornişinin Islahı ve Yerine Konması İşçiliği','M',3648.24,null),
('V.1160','Minarede Yonu Taşından Stalâktitli Kurşunlu ve Kenetli Şerefe Altı Yapılması İşçiliği','M²',77428.55,null),
('V.1160/1','Puzolan Katkılı Horasan Harcı ile Minarede Yonu Taşından Stalâktitli Kurşunlu ve Kenetli Şerefe Altı Yapılması İşçiliği','M²',77660.24,null),
('V.1160/2','Hidrolik Kireç Harcı ile Minarede Yonu Taşından Stalâktitli Kurşunlu ve Kenetli Şerefe Altı Yapılması İşçiliği','M²',77934.95,null),
('V.1160/A','Minarede ve Her Yerde Yonu Taşından Müzeyyen Stalâktit Yapılması İşçiliği','M²',156328.55,null),
('V.1160/A1','Puzolan Katkılı Horasan Harcı ile Minarede ve Her Yerde Yonu Taşından Müzeyyen Stalâktit Yapılması İşçiliği','M²',156560.24,null),
('V.1160/A2','Hidrolik Kireç Harcı ile Minarede ve Her Yerde Yonu Taşından Müzeyyen Stalâktit Yapılması İşçiliği','M²',156834.95,null),
('V.1161','Minarede Yonu Taşından Kurşunlu Kenetli Müzeyyen Barok Şerfe Altı Yapılması İşçiliği','M²',60928.55,null),
('V.1161/A','Puzolan Katkılı Horasan Harcı ile Minarede Yonu Taşından Kurşunlu Kenetli Müzeyyen Barok Şerfe Altı Yapılması İşçiliği','M²',61160.24,null),
('V.1161/B','Hidrolik Kireç Harcı ile Minarede Yonu Taşından Kurşunlu Kenetli Müzeyyen Barok Şerfe Altı Yapılması İşçiliği','M²',61434.95,null),
('V.1162','Minarede Yonu Taşından Kurşunlu ve Kenetli Barok Şerfe Altı Yapılması İşçiliği','M²',48828.55,null),
('V.1162/1','Puzolan Katkılı Horasan Harcı ile Minarede Yonu Taşından Kurşunlu ve Kenetli Barok Şerfe Altı Yapılması İşçiliği','M²',49060.24,null),
('V.1162/2','Hidrolik Kireç Harcı ile Minarede Yonu Taşından Kurşunlu ve Kenetli Barok Şerfe Altı Yapılması İşçiliği','M²',49334.95,null),
('V.1162/A','Minarede Yonu Taşından Kurşunlu ve Kenetli Basit Barok Şerfe Altı Yapılması İşçiliği','M²',33428.55,null),
('V.1162/A1','Puzolan Katkılı Horasan Harcı ile Minarede Yonu Taşından Kurşunlu ve Kenetli Basit Barok Şerfe Altı Yapılması İşçiliği','M²',33660.24,null),
('V.1162/A2','Hidrolik Kireç Harcı ile Minarede Yonu Taşından Kurşunlu ve Kenetli Basit Barok Şerefe Altı Yapılması İşçiliği','M²',33934.95,null),
('V.1163','Minarede Mevcut Yonu Taşından Her Türlü Şerefe Altının Islahı ve Kurşunlu ve Kenetli Olarak Yerine Konması İşçiliği','M²',25728.55,null),
('V.1163/A','Puzolan Katkılı Kireç Harcı ile Minarede Mevcut Yonu Taşından Her Türlü Şerefe Altının Islahı ve Kurşunlu ve Kenetli Olarak Yerine Konması İşçiliği','M²',25960.24,null),
('V.1163/B','Hidrolik Kireç Harcı ile Minarede Mevcut Yonu Taşından Her Türlü Şerefe Altının Islahı ve Kurşunlu ve Kenetli Olarak Yerine Konması İşçiliği','M²',26234.95,null),
('V.1164','Minarede Yonu Taşından Kurşunlu ve Kenetli Yedek veya Çekirdeksiz Minare Basamağı Yapılması ve Yerine Konması İşçiliği','M',14276.6,null),
('V.1164/A','Puzolan Katkılı Horasan Harcı ile Minarede Yonu Taşından Kurşunlu ve Kenetli Yedek veya Çekirdeksiz Minare Basamağı Yapılması ve Yerine Konması İşçiliği -55-','M',14299.78,null),
('V.1164/B','Hidrolik Kireç Harcı ile Minarede Yonu Taşından Kurşunlu ve Kenetli Yedek veya Kurşunlu ve Kenetli Yedek veya Çekirdeksiz Minare Basamağı Yapılması ve Yerine Konması İşçiliği','M',14327.25,null),
('V.1165','Yonu Taşından Kurşunlu Kenetli, Yedek veya Çekirdekli Minare Basamağı Yapılması ve Yerine Konması İşçiliği','M',17282.85,null),
('V.1165/A','Puzolan Katkılı Kireç Harcı ile Yonu Taşından Kurşunlu Kenetli, Yedek veya Çekirdekli Minare Basamağı Yapılması ve Yerine Konması İşçiliği','M',17306.03,null),
('V.1165/B','Hidrolik Kireç Harcı ile Yonu Taşından Kurşunlu Kenetli, Yedek veya Yedek veya Çekirdekli Minare Basamağı Yapılması ve Yerine Konması İşçiliği','M',17333.5,null),
('V.1166','Yonu Taşı Minare Çekirdeği Değiştirilmesi İşçiliği','M',17282.85,null),
('V.1166/A','Puzolan Katkılı Horasan Harcı ile Yonu Taşı Minare Çekirdeği Değiştirilmesi İşçiliği','M',17306.03,null),
('V.1166/B','Hidrolik Kireç Harcı ile Yonu Taşı Minare Çekirdeği Değiştirilmesi İşçiliği','M',17333.5,null),
('V.1167','Yonu Taşından Çekirdeksiz Minare Basamak ve Yedeğinin Değiştirilmesi İşçiliği','M',16439.1,null),
('V.1167/A','Puzolan Katkılı Horasan Harcı ile Yonu Taşından Çekirdeksiz Minare Basamak ve Yedeğinin Değiştirilmesi İşçiliği','M',16462.28,null),
('V.1167/B','Hidrolik Kireç Harcı ile Yonu Taşından Çekirdeksiz Minare Basamak ve Yedeğinin Değiştirilmesi İşçiliği','M',16489.75,null),
('V.1168','Yonu Taşından Çekirdekli Minare Basamak ve Yedeğinin Değiştirilmesi İşçiliği','M',19445.35,null),
('V.1168/A','Puzolan Katkılı Horasan Harcı ile Yonu Taşından Çekirdekli Minare Basamak ve Yedeğinin Değiştirilmesi İşçiliği','M',19468.53,null),
('V.1168/B','Hidrolik Kireç Harcı ile Yonu Taşından Çekirdekli Minare Basamak ve Yedeğinin Değiştirilmesi İşçiliği','M',19496.0,null),
('V.1169','Çekirdekli veya Çekirdeksiz Mevcut Minare Basamak ve Yedeğinin Islahı ve Kurşunlu ve Kenetli Olarak Yerine Konması İşçiliği','M',9326.6,null),
('V.1169/A','Puzolan Katkılı Horasan Kireç Harcı ile Çekirdekli veya Çekirdeksiz Mevcut Minare Basamak ve Yedeğinin Islahı ve Kurşunlu ve Kenetli Olarak Yerine Konması İşçiliği','M',9349.78,null),
('V.1169/B','Hidrolik Kireç Harcı ile Çekirdekli veya Çekirdeksiz Mevcut Minare Basamak ve Yedeğinin Islahı ve Kurşunlu ve Kenetli Olarak Yerine Konması İşçiliği','M',9377.25,null),
('V.1170','Yonu Taşından İçi ve Dışı İşlenmiş Kurşunlu Kenetli, Köşeli ve/veya Mahruti Minare Külahı Yapılması İşçiliği','M²',36653.55,null),
('V.1170/A','Puzolan Katkılı Horasan Harcı ile Yonu Taşından İçi ve Dışı İşlenmiş Kurşunlu Kenetli, Köşeli ve/veya Mahruti Minare Külahı Yapılması İşçiliği','M²',36885.24,null),
('V.1170/B','Hidrolik Kireç Harcı ile Yonu Taşından İçi ve Dışı İşlenmiş Kurşunlu Kenetli, Köşeli ve/veya Mahruti Minare Külahı Yapılması İşçiliği','M²',37159.95,null),
('V.1171','Yonu Taşından İçi ve Dışı İşlenmiş Kurşunlu ve Kenetli Barok veya Ampir Minare Külahı Yapılması İşçiliği','M²',47653.55,null),
('V.1171/A','Puzolan Katkılı Horasan Harcı ile Yonu Taşından İçi ve Dışı İşlenmiş Kurşunlu ve Kenetli Barok veya Ampir Minare Külahı Yapılması İşçiliği','M²',47885.24,null),
('V.1171/B','Hidrolik Kireç Harcı ile Yonu Taşından İçi ve Dışı İşlenmiş Kurşunlu ve Kenetli Barok veya Ampir Minare Külahı Yapılması İşçiliği','M²',48159.95,null),
('V.1172','Yonu Taşından, İçi ve Dışı İşlenmiş Kurşunlu ve Kenetli Müzeyyen Barok veya Ampir Minare Külahı Yapılması ve Yerine Konması İşçiliği','M²',66716.05,null),
('V.1172/A','Puzolan Katkılı Horasan Harcı ile Yonu Taşından, İçi ve Dışı İşlenmiş Kurşunlu ve Kenetli Müzeyyen Barok veya Ampir Minare Külahı Yapılması ve Yerine Konması İşçiliği','M²',66947.74,null),
('V.1172/B','Hidrolik Kireç Harcı ile Yonu Taşından, İçi ve Dışı İşlenmiş Kurşunlu ve Kenetli Müzeyyen Barok veya Ampir Minare Külahı Yapılması ve Yerine Konması İşçiliği','M²',67222.45,null),
('V.1173','Mevcut Her Türlü Yonu Taşı Minare Külahının Islahı ve Kurşunlu ve Kenetli Olarak Yerine Konması İşçiliği -56-','M²',26753.55,null),
('V.1173/A','Puzolan Katkılı Horasan Harcı ile Mevcut Her Türlü Yonu Taşı Minare Külahının Islahı ve Kurşunlu ve Kenetli Olarak Yerine Konması İşçiliği','M²',26985.24,null),
('V.1173/B','Hidrolik Kireç Harcı ile Mevcut Her Türlü Yonu Taşı Minare Külahının Islahı ve Kurşunlu ve Kenetli Olarak Yerine Konması İşçiliği','M²',27259.95,null),
('V.1174/A','Puzolan Katkılı Horasan Harcı ile Her Boyda Yonu Taşı Klasik Alem Yapılması ve Yerine Konması İşçiliği','M',17380.8,null),
('V.1174/B','Hidrolik Kireç Harcı ile Her Boyda Yonu Taşı Klasik Alem Yapılması ve Yerine Konması İşçiliği','M',17435.74,null),
('V.1175','Her Boyda Yonu Taşı Basit Barok veya Ampir Alem Yapılması ve Yerine Konması İşçiliği','M',22834.46,null),
('V.1175/A','Puzolan Katkılı Horasan Harcı ile Her Boyda Yonu Taşı Basit Barok veya Ampir Alem Yapılması ve Yerine Konması İşçiliği','M',22880.8,null),
('V.1175/B','Hidrolik Kireç Harcı ile Her Boyda Yonu Taşı Basit Barok veya Ampir Alem Yapılması ve Yerine Konması İşçiliği','M',22935.74,null),
('V.1176','D- KORKULUKLAR Yonu Taşından Kurşunlu ve Kenetli Kavisli veya İki Yüzü Düz Korkuluk Yapılması ve Yerine Konması İşçiliği','M²',18630.64,null),
('V.1176/1','Pozolan Katkılı Horasan Harç ile Yonu Taşından Kurşunlu ve Kenetli Kavisli veya İki Yüzü Düz Korkuluk Yapılması ve Yerine Konması İşçiliği','M²',18639.91,null),
('V.1176/2','Hidrolik Kireç Harç ile Yonu Taşından Kurşunlu ve Kenetli Kavisli veya İki Yüzü Düz Korkuluk Yapılması ve Yerine Konması İşçiliği','M²',18650.9,null),
('V.1176/A','Yonu Taşından Düz Korkuluk Yapılması ve Yerine Konması İşçiliği','M²',16430.64,null),
('V.1176/A1','Pozolan Katkılı Horasan Harcı ile Yonu Taşından Düz Korkuluk Yapılması ve Yerine Konması İşçiliği','M²',16439.91,null),
('V.1176/A2','Hidrolik Kireç Harcı ile Yonu Taşından Düz Korkuluk Yapılması ve Yerine Konması İşçiliği','M²',16450.9,null),
('V.1177','Yonu Taşından Kurşunlu ve Kenetli ve Tek Yüzü Profilli Korkuluk Yapılması ve Yerine Konması İşçiliği','M²',24130.64,null),
('V.1177/A','Puzolan Katkılı Horasan Harcı ile Yonu Taşından Kurşunlu ve Kenetli ve Tek Yüzü Profilli Korkuluk Yapılması ve Yerine Konması İşçiliği','M²',24139.91,null),
('V.1177/B','Hidrolik Kireç Harcı ile Yonu Taşından Kurşunlu ve Kenetli ve Tek Yüzü Profilli Korkuluk Yapılması ve Yerine Konması İşçiliği','M²',24150.9,null),
('V.1178','Yonu Taşından Kurşunlu ve Kenetli ve İki Yüzü Profilli Korkuluk Yapılması ve Yerine Konması İşçiliği','M²',29630.64,null),
('V.1178/A','Puzolan Katkılı Horasan Harcı ile Yonu Taşından Kurşunlu ve Kenetli ve İki Yüzü Profilli Korkuluk Yapılması ve Yerine Konması İşçiliği','M²',29639.91,null),
('V.1178/B','Hidrolik Kireç Harcı ile Yonu Taşından Kurşunlu ve Kenetli ve İki Yüzü Profilli Korkuluk Yapılması ve Yerine Konması İşçiliği','M²',29650.9,null),
('V.1179','Yonu Taşından Kurşunlu ve Kenetli Tek Yüzü Profilli ve Oymalı Korkuluk Yapılması ve Yerine Konması İşçiliği','M²',37330.64,null),
('V.1179/A','Puzolan Katkılı Horasan Harcı ile Yonu Taşından Kurşunlu ve Kenetli Tek Yüzü Profilli ve Oymalı Korkuluk Yapılması ve Yerine Konması İşçiliği','M²',37339.91,null),
('V.1179/B','Hidrolik Kireç Harcı ile Yonu Taşından Kurşunlu ve Kenetli Tek Yüzü Profilli ve Oymalı Korkuluk Yapılması ve Yerine Konması İşçiliği','M²',37350.9,null),
('V.1180','Yonu Taşından Kurşunlu ve Kenetli İki Yüzü Profilli ve Oymalı Korkuluk Yapılması ve Yerine Konması İşçiliği','M²',70330.64,null),
('V.1180/A','Puzolan Katkılı Horasan Harcı ile Yonu Taşından Kurşunlu ve Kenetli İki Yüzü Profilli ve Oymalı Korkuluk Yapılması ve Yerine Konması İşçiliği','M²',70339.91,null),
('V.1180/B','Hidrolik Kireç Harcı ile Yonu Taşından Kurşunlu ve Kenetli İki Yüzü Profilli ve Oymalı Korkuluk Yapılması ve Yerine Konması İşçiliği','M²',70350.9,null),
('V.1181','Yonu Taşından Kurşunlu Kenetli Tek Yüzü Profilli ve Pahlı Şebekeli Korkuluk Yapılması ve Yerine Konması','M²',54380.64,null),
('V.1181/A','Puzolan Katkılı Horasan Harcı ile Yonu Taşından Kurşunlu Kenetli Tek Yüzü Profilli ve Pahlı Şebekeli Korkuluk Yapılması ve Yerine Konması İşçiliği -57-','M²',54389.91,null),
('V.1181/B','Hidrolik Kireç Harcı ile Yonu Taşından Kurşunlu Kenetli Tek Yüzü Profilli ve Pahlı Şebekeli Korkuluk Yapılması ve Yerine Konması İşçiliği','M²',54400.9,null),
('V.1182','Yonu Taşından, Kurşunlu ve Kenetli İki Yüzü Profilli ve Pahlı Şebekeli Korkuluk Yapılması ve Yerine Konması İşçiliği','M²',84080.64,null),
('V.1182/A','Puzolan Katkılı Horasan Harcı ile Yonu Taşından, Kurşunlu ve Kenetli İki Yüzü Profilli ve Pahlı Şebekeli Korkuluk Yapılması ve Yerine Konması İşçiliği','M²',84089.91,null),
('V.1182/B','Hidrolik Kireç Harcı ile Yonu Taşından, Kurşunlu ve Kenetli İki Yüzü Profilli ve Pahlı Şebekeli Korkuluk Yapılması ve Yerine Konması İşçiliği','M²',84100.9,null),
('V.1183','Yonu Taşından, Mevcut Her Türlü Korkuluk Islahı ve Alıştırılıp Kurşunlu ve Kenetli Olarak Yerine Konması İşçiliği','M²',12030.64,null),
('V.1183/1','Puzolan Katkılı Horasan Harcı ile Yonu Taşından, Mevcut Her Türlü Korkuluk Islahı ve Alıştırılıp Kurşunlu ve Kenetli Olarak Yerine Konması İşçiliği','M²',12039.91,null),
('V.1183/2','Hidrolik Kireç Harçlı Yonu Taşından, Mevcut Her Türlü Korkuluk Islahı ve Alıştırılıp Kurşunlu ve Kenetli Olarak Yerine Konması İşçiliği','M²',12050.9,null),
('V.1183/A','Yerde Yapılmış Her Türlü Yonu Taşı Korkuluğun Minare Şerefesine Çekilmesi İşçiliği','M²',2681.25,null),
('V.1183/B','Yerde Yapılmış Veya Onarımları Tamamlanmış Beton Dışlık Veya Alçı İçlik Pencerelerin 20 Mt''den Yükseğe Çekilmesi (100kg''dan Fazla)','M²',4868.75,null),
('V.1183/C','Yerde Yapılmış Veya Onarımları Tamamlanmış Beton Dışlık Veya Alçı İçlik Pencerelerin 10-20 Mt Arası Yüksekliğe Çekilmesi (100kg''dan Fazla) E- BAŞLIKLAR VE SÜTUNLAR','M²',3562.5,null),
('V.1184','Yonu Taşından 40 Cm.Yüksekliğe Kadar (40 Cm. Dahil) Kurşunlu ve Kenetli Stalâktitli Başlık Yapılması ve Yerine Konması İşçiliği','AD',79381.25,null),
('V.1184/A','Yonu Taşından 41-50 Cm. Arası Yükseklikte Kurşunlu ve Kenetli Stalâktitli Başlık Yapılması ve Yerine Konması İşçiliği','AD',94231.25,null),
('V.1185','Yonu Taşından 40 Cm. Yüksekliğe Kadar(40 Cm. Dahil) Kurşunlu ve Kenetli Baklavalı Başlık Yapılması ve Yerine Konması İşçiliği','AD',39781.25,null),
('V.1185/A','Yonu Taşından 41-50 Cm. Arası Yükseklikte Kurşunlu ve Kenetli Baklavalı Başlık Yapılması ve Yerine Konması İşçiliği','AD',45281.25,null),
('V.1186','Yonu Taşından 40 Cm. Yüksekliğe Kadar (40 Cm. Dahil) Kurşunlu ve Kenetli Düz Başlık Yapılması ve Yerine Konması İşçiliği','AD',17781.25,null),
('V.1186/A','Yonu Taşından 41-50 Cm.Arası Yükseklikte Kurşunlu ve Kenetli Düz Başlık Yapılması ve Yerine Konması İşçiliği','AD',23281.25,null),
('V.1187','Yonu Taşından 40 Cm. Yüksekliğe Kadar(40 Cm. Dahil) Kurşunlu ve Kenetli Profilli Sütun Kaidesi Yapılması ve Yerine Konması İşçiliği','AD',23318.75,null),
('V.1188','Yonu Taşından 40 Cm. Yüksekliğe Kadar (40 Cm.Dahil) Kurşunlu ve Kenetli Basit Sütun Kaidesi Yapılması ve Yerine Konması İşçiliği','AD',14812.5,null),
('V.1189','Yonu Taşından 51-60 Cm. Arası Yükseklikte Kurşunlu ve Kenetli Stalâktitli Başlık Yapılması ve Yerine Konması İşçiliği','AD',108237.5,null),
('V.1190','Yonu Taşından 51-60 Cm. Arası Yükseklikte Kurşunlu ve Kenetli Baklavalı Başlık Yapılması ve Yerine Konması İşçiliği','AD',51587.5,null),
('V.1191','Yonu Taşından 51-60 Cm.Arası Yükseklikte Kurşunlu ve Kenetli Düz Başlık Yapılması ve Yerine Konması İşçiliği','AD',22731.25,null),
('V.1192','Yonu Taşından 41-60 Cm. Arası Yükseklikte Kurşunlu ve Kenetli Profilli Sütun Kaidesi Yapılması ve Yerine Konması İşçiliği','AD',36225.0,null),
('V.1193','Yonu Taşından 41-60 Cm. Arası Yükseklikte Kurşunlu ve Kenetli Basit Sütun Kaidesi Yapılması ve Yerine Konması İşçiliği','AD',19725.0,null),
('V.1194','Yonu Taşından 61-70 Cm. Arası Yükseklikte Kurşunlu ve Kenetli Stalâktitli Başlık Yapılması ve Yerine Konması İşçiliği','AD',133793.75,null),
('V.1194/A','Yonu Taşından 71-80 Cm. Arası Yükseklikte Kurşunlu ve Kenetli Stalâktitli Başlık Yapılması ve Yerine Konması İşçiliği','AD',161293.75,null),
('V.1195','Yonu Taşından 61-70 Cm. Arası Yükseklikte Kurşunlu ve Kenetli Baklavalı Başlık Yapılması ve Yerine Konması İşçiliği','AD',63687.5,null),
('V.1195/A','Yonu Taşından 71-80 Cm. Arası Yükseklikte Kurşunlu ve Kenetli Baklavalı Başlık Yapılması ve Yerine Konması İşçiliği -58-','AD',65593.75,null),
('V.1196','Yonu Taşından 61-70 Cm. Arası Yükseklikte Kurşunlu ve Kenetli Düz Başlık Yapılması ve Yerine Konması İşçiliği','AD',31237.5,null),
('V.1196/A','Yonu Taşından 71-80 Cm.Arası Yükseklikte Kurşunlu ve Kenetli Düz Başlık Yapılması ve Yerine Konması İşçiliği','AD',33437.5,null),
('V.1197','Yonu Taşından 61-80 Cm. Arası Yükseklikte Kurşunlu Kenetli ve Profilli Sütun Kaidesi Yapılması ve Yerine Konması İşçiliği','AD',48837.5,null),
('V.1198','Yonu Taşından 61-80 Cm. Arası Yükseklikte Kurşunlu ve Kenetli Basit Sütun Kaidesi Yapılması ve Yerine Konması İşçiliği','AD',26031.25,null),
('V.1202','Yonu Taşından Her Çapta ve 3.00 Mt.den Yüksek ve En Çok İki Parçalı Yuvarlak Sütun veya Sütunce Yapılması ve Yerine Konması İşçiliği','M²',24562.5,null),
('V.1202/A','Yonu Taşından Her Çapta ve 0.50-3.00 Mt. Yüksekliğe Kadar Yekpare Yuvarlak Sütun veya Sütunce Yapılması ve Yerine Konması İşçiliği','M²',19062.5,null),
('V.1203','Yonu Taşından Her Ölçüdeki Kesitte ve 3 Mt.den Yüksek Yekpare veya En Çok İki Parçalı Dört veya Çok Köşeli Sütun veya Sütunce Yapılması ve Yerine Konması İşçiliği','M²',30062.5,null),
('V.1203/A','Yonu Taşından Her Ölçüdeki Kesitte ve 0.50-3.00 Mt. Yüksekliğe Kadar Yekpare Çok Köşeli Sütun veya Sütunce Yapılması ve Yerine Konması İşçiliği','M²',24562.5,null),
('V.1203/B','Yonu Taşından Her Boyda Dört Köşeli Sütun veya Sütunce Yapılması ve Yerine Konması İşçiliği','M²',13562.5,null),
('V.1204','Üstü Boş Yerlerde Her Boyda Mevcut Başlığın Kurşunlu ve Kenetli Olarak Yerine Konması İşçiliği','AD',4837.5,null),
('V.1205','Üstü Askıya Alınmış Yerlerde Her Boyda Mevcut Başlığın Kurşunlu ve Kenetli Olarak Yerine Konması İşçiliği','AD',13562.5,null),
('V.1206','Yekpare veya Parçalı Mevcut Yonu Taşı Yuvarlak veya Köşeli Sütun veya Sütuncenin Kurşunlu ve Kenetli Olarak Yerine Konması İşçiliği F- KEMER VE ÇÖRTENLER','M²',10812.5,null),
('V.1225','Yonu Taşından Bir Taşın Görünen Yüzü Toplamı 0.20 M2''den Büyük Kemer Taşı Yapılması ve Yerine Konması İşçiliği','M²',16387.84,null),
('V.1225/A','Puzolan Katkılı Horasan Harcı ile Yonu Taşından Bir Taşın Görünen Yüzü Toplamı 0.20 M2''den Büyük Kemer Taşı Yapılması ve Yerine Konması İşçiliği','M²',16573.19,null),
('V.1225/B','500 Doz Hidrolik Kireç Harcı ile Yonu Taşından Bir Taşın Görünen Yüzü Toplamı 0.20 M2''den Büyük Kemer Taşı Yapılması ve Yerine Konması İşçiliği','M²',16846.24,null),
('V.1226','Yonu Taşından Bir Taşın Görünen Yüzü Toplamı 0.20 M2''den Küçük Kemer Taşı Yapılması ve Yerine Konması İşçiliği','M²',20200.34,null),
('V.1226/A','Puzolan Katkılı Horasan Harcı ile Yonu Taşından Bir Taşın Görünen Yüzü Toplamı 0.20 M2''den Küçük Kemer Taşı Yapılması ve Yerine Konması İşçiliği','M²',20385.69,null),
('V.1226/B','500 Doz Hidrolik Kireç Harcı ile Yonu Taşından Bir Taşın Görünen Yüzü Toplamı 0.20 M2''den Küçük Kemer Taşı Yapılması ve Yerine Konması İşçiliği','M²',20658.74,null),
('V.1227','Yonu Taşından Bir Taşın Görünen Yüzü Toplamı 0.20 M2''den Büyük Mevcut Kemer Taşının Islah Edilerek Yerine Konması İşçiliği','M²',7150.34,null),
('V.1227/A','Puzolan Katkılı Horasan Harcı ile Yonu Taşından Bir Taşın Görünen Yüzü Toplamı 0.20 M2''den Büyük Mevcut Kemer Taşının Islah Edilerek Yerine Konması İşçiliği','M²',7335.69,null),
('V.1227/B','500 Doz Hidrolik Kireç Harcı ile Yonu Taşından Bir Taşın Görünen Yüzü Toplamı 0.20 M2''den Büyük Mevcut Kemer Taşının Islah Edilerek Yerine Konması İşçiliği','M²',7608.74,null),
('V.1228','Yonu Taşından Bir Taşın Görünen Yüzü Toplamı 0.20 M2''den Küçük Mevcut Kemer Taşının Islah Edilerek Yerine Konması İşçiliği','M²',8250.34,null),
('V.1228/1','Puzolan Katkılı Horasan Harcı ile Yonu Taşından Bir Taşın Görünen Yüzü Toplamı 0.20 M2''den Küçük Mevcut Kemer Taşının Islah Edilerek Yerine Konması İşçiliği -59-','M²',8435.69,null),
('V.1228/2','500 Doz Hidrolik Kireç Harcı ile Yonu Taşından Bir Taşın Görünen Yüzü Toplamı 0.20 M2''den Küçük Mevcut Kemer Taşının Islah Edilerek Yerine Konması İşçiliği','M²',8708.74,null),
('V.1228/A','Her Türlü Kaplama da ( Yonu Taşı, Moloz Taşı, Tuğla, Almaşık ) Kemer İç ve Dış Yüzlerine İsabet Eden Kısmına İşçilik Zammı','M',825.0,null),
('V.1229','Yonu Taşından Her Kesitte ve Boyda Düz Çörten Yapılması ve Yerine Konması İşçiliği','M²',15597.13,null),
('V.1229/A','Puzolan Katkılı Horasan Harcı ile Yonu Taşından Her Kesitte ve Boyda Düz Çörten Yapılması ve Yerine Konması İşçiliği','M²',15736.14,null),
('V.1229/A01','Puzolan Katkılı Horasan Harcı ile Yonu Taşından Her Kesitte ve Boyda Mevcut Düz Çörtenin Islahı ve Yerine Konması İşçiliği','M²',5061.14,null),
('V.1229/B','500 Doz Hidrolik Kireç Harcı ile Yonu Taşından Her Kesitte ve Boyda Düz Çörten Yapılması ve Yerine Konması İşçiliği','M²',15940.93,null),
('V.1229/B01','500 Doz Hidrolik Kireç Harcı ile Yonu Taşından Her Kesitte ve Boyda Mevcut Düz Çörtenin Islahı ve Yerine Konması İşçiliği','M²',5265.93,null),
('V.1230','Yonu Taşından Her Kesitte ve Boyda Basit Profilli ve Desenli Çörten Yapılması ve Yerine Konması İşçiliği','M²',24797.13,null),
('V.1230/A','Puzolan Katkılı Horasan Harcı ile Yonu Taşından Her Kesitte ve Boyda Basit Profilli ve Desenli Çörten Yapılması ve Yerine Konması İşçiliği','M²',24936.14,null),
('V.1230/B','500 Doz Hidrolik Kireç Harcı ileYonu Taşından Her Kesitte ve Boyda Basit Profilli ve Desenli Çörten Yapılması ve Yerine Konması İşçiliği','M²',25140.93,null),
('V.1231','Yonu Taşından Her Kesitte ve Boyda Nebati veya Hayvani Tezyinatlı Çörten Yapılması ve Yerine Konması İşçiliği','M²',30809.63,null),
('V.1231/A','Puzolan Katkılı Horasan Harcı ile Yonu Taşından Her Kesitte ve Boyda Nebati veya Hayvani Tezyinatlı Çörten Yapılması ve Yerine Konması İşçiliği','M²',30948.64,null),
('V.1231/B','500 Doz Hidrolik Kireç Harcı ile Yonu Taşından Her Kesitte ve Boyda Nebati veya Hayvani Tezyinatlı Çörten Yapılması ve Yerine Konması İşçiliği','M²',31153.43,null),
('V.1232','Yonu Taşından Koç Başı Düz Konsol Yapılması ve Yerine Konması İşçiliği','AD',4968.93,null),
('V.1232/A','Puzolan Katkılı Horasan Harcı ile Yonu Taşından Koç Başı Düz Konsol Yapılması ve Yerine Konması İşçiliği','AD',5061.6,null),
('V.1232/B','500 Doz Hidrolik Kireç Harcı ileYonu Taşından Koç Başı Düz Konsol Yapılması ve Yerine Konması İşçiliği','AD',5198.13,null),
('V.1233','Yonu Taşından, Koç Başı Basit Profilli veya Silmeli Konsol Yapılması ve Yerine Konması İşçiliği','AD',6068.93,null),
('V.1233/A','Puzolan Katkılı Horasan Harcı ile Yonu Taşından, Koç Başı Basit Profilli veya Silmeli Konsol Yapılması ve Yerine Konması İşçiliği','AD',6161.6,null),
('V.1233/B','500 Doz Hidrolik Kireç Harcı ile Yonu Taşından, Koç Başı Basit Profilli veya Silmeli Konsol Yapılması ve Yerine Konması İşçiliği','AD',6298.13,null),
('V.1234','Yonu Taşından Koç Başı, Hayvani Profilli Nebati veya Geometrik Tezyinatli Konsol Yapılması ve Yerine Konması İşçiliği','AD',8268.93,null),
('V.1234/A','Puzolan Katkılı Horasan Harcı ile Yonu Taşından Koç Başı, Hayvani Profilli Nebati veya Geometrik Tezyinatli Konsol Yapılması ve Yerine Konması İşçiliği','AD',8361.6,null),
('V.1234/B','500 Doz Hidrolik Kireç Harcı ile Yonu Taşından Koç Başı, Hayvani Profilli Nebati veya Geometrik Tezyinatli Konsol Yapılması ve Yerine Konması İşçiliği','AD',8498.13,null),
('V.1235','Yonu Taşından ( L) Başlı Çengelli Düz Konsol Yapılması ve Yerine Konması İşçiliği','AD',5518.93,null),
('V.1235/A','Puzolan Katkılı Horasan Harcı ile Yonu Taşından ( L) Başlı Çengelli Düz Konsol Yapılması ve Yerine Konması İşçiliği','AD',5611.6,null),
('V.1235/B','500 Doz Hidrolik Kireç Harcı ile Yonu Taşından ( L) Başlı Çengelli Düz Konsol Yapılması ve Yerine Konması İşçiliği -60-','AD',5748.13,null),
('V.1250','G- KORNİŞLER Yonu Taşından 10 Cm. Yüksekliğe Kadar (10 Cm. Dahil) Düz Pahlı Korniş Yapılması ve Yerine Konması İşçiliği','M',4265.71,null),
('V.1250/A','Puzolan Katkılı Horasan Harcı ile Yonu Taşından 10 Cm. Yüksekliğe Kadar (10 Cm. Dahil) Düz Pahlı KornişYapılması ve Yerine Konması İşçiliği','M',4312.05,null),
('V.1250/B','500 Doz Hidrolik Kireç Harcı ile Yonu Taşından 10 Cm. Yüksekliğe Kadar (10 Cm. Dahil) Düz Pahlı Korniş Yapılması ve Yerine Konması İşçiliği','M',4380.31,null),
('V.1251','Yonu Taşından 10 Cm.Yüksekliğe Kadar (10 Cm. Dahil) Silmeli Korniş Yapılması ve Yerine Konması İşçiliği','M',5790.71,null),
('V.1251/A','Puzolan Katkılı Horasan Harcı ile Yonu Taşından 10 Cm. Yüksekliğe Kadar (10 Cm. Dahil) Silmeli Korniş Yapılması ve Yerine Konması İşçiliği','M',5837.05,null),
('V.1251/B','500 Doz Hidrolik Kireç Harcı ile Yonu Taşından 10 Cm. Yüksekliğe Kadar (10 Cm. Dahil) Silmeli Korniş Yapılması ve Yerine Konması İşçiliği','M',5905.31,null),
('V.1252','Yonu Taşından 11-15 Cm. Arası Yükseklikte Düz Pahlı Korniş Yapılması ve Yerine Konması İşçiliği','M',5028.21,null),
('V.1252/A','Puzolan Katkılı Horasan Harcı ile Yonu Taşından 11-15 Cm. Arası Yükseklikte Düz Pahlı Korniş Yapılması ve Yerine Konması İşçiliği','M',5074.55,null),
('V.1252/B','500 Doz Hidrolik Kireç Harcı ile Yonu Taşından 11-15 Cm. Arası Yükseklikte Düz Pahlı Korniş Yapılması ve Yerine Konması İşçiliği','M',5142.81,null),
('V.1253','Yonu Taşından 11-15 Cm. Arası Yükseklikte Silmeli Korniş Yapılması ve Yerine Konması İşçiliği','M',6553.21,null),
('V.1253/A','Puzolan Katkılı Horasan Harcı ileYonu Taşından 11-15 Cm. Arası Yükseklikte Silmeli Korniş Yapılması ve Yerine Konması İşçiliği','M',6599.55,null),
('V.1253/B','500 Doz Hidrolik Kireç Harcı ileYonu Taşından 11-15 Cm. Arası Yükseklikte Silmeli Korniş Yapılması ve Yerine Konması İşçiliği','M',6667.81,null),
('V.1254','Yonu Taşından 16-20 Cm. Arası Yükseklikte Düz Pahlı Korniş Yapılması ve Yerine Konması İşçiliği','M',5812.59,null),
('V.1254/A','Puzolan Katkılı Horasan Harcı ileYonu Taşından 16-20 Cm. Arası Yükseklikte Düz Pahlı Korniş Yapılması ve Yerine Konması İşçiliği','M',5858.93,null),
('V.1254/B','500 Doz Hidrolik Kireç Harcı ileYonu Taşından 16-20 Cm. Arası Yükseklikte Düz Pahlı Korniş Yapılması ve Yerine Konması İşçiliği','M',5927.19,null),
('V.1255','Yonu Taşından 16-20 Cm. Arası Yükseklikte Silmeli Korniş Yapılması ve Yerine Konması İşçiliği','M',7337.59,null),
('V.1255/A','Puzolan Katkılı Horasan Harcı ileYonu Taşından 16-20 Cm. Arası Yükseklikte Silmeli Korniş Yapılması ve Yerine Konması İşçiliği','M',7383.93,null),
('V.1255/B','500 Doz Hidrolik Kireç Harcı ile Yonu Taşından 16-20 Cm. Arası Yükseklikte Silmeli Korniş Yapılması ve Yerine Konması İşçiliği','M',7452.19,null),
('V.1256','Yonu Taşından 21-25 Cm. Arası Yükseklikte Düz Pahlı Korniş Yapılması ve Yerine Konması İşçiliği','M',6575.09,null),
('V.1256/A','Puzolan Katkılı Horasan Harcı ile Yonu Taşından 21-25 Cm. Arası Yükseklikte Düz Pahlı Korniş Yapılması ve Yerine Konması İşçiliği','M',6621.43,null),
('V.1256/B','500 Doz Hidrolik Kireç Harcı ileYonu Taşından 21-25 Cm. Arası Yükseklikte Düz Pahlı Korniş Yapılması ve Yerine Konması İşçiliği','M',6689.69,null)
) as v(poz_no,tanim,birim,fiyat,extra)
on conflict (source_id,poz_no,coalesce(birim,'')) do nothing;